// Code generated by cleanproto. DO NOT EDIT.

import {
  decodeLibrarySnapshot,
  encodeAddAuthorRequest,
  encodeAddBookRequest,
  encodeAddGenreRequest,
} from './model.js';

/** @typedef {() => Object.<string, string>} HeaderProvider */
/** @typedef {(response: Response) => Promise<never>} ErrorHandler */
/** @typedef {BodyInit|Uint8Array} RequestBody */

export class Capi {
  /**
   * @param {string} [baseURL='']
   * @param {HeaderProvider | null} [headerProvider=null]
   * @param {ErrorHandler | null} [errorHandler=null]
   */
  constructor(baseURL = '', headerProvider = null, errorHandler = null) {
    this.baseURL = baseURL;
    this.headerProvider = headerProvider == null ? () => ({}) : headerProvider;
    this.errorHandler = errorHandler == null ? async (response) => { throw new Error(`HTTP ${response.status}`); } : errorHandler;
  }

  /**
   * @param {string} path
   * @param {{ method?: string, body?: RequestBody, signal?: AbortSignal, contentType?: string, duplex?: 'half' }} [options={}]
   * @returns {Promise<Response>}
   */
  async #request(path, { method = 'GET', body, signal, contentType, duplex } = {}) {
    const headers = this.headerProvider() || {};
    headers['Accept'] = 'application/x-protobuf';
    if (body !== undefined) {
      headers['Content-Type'] = contentType || 'application/x-protobuf';
    }
    const init = { method, headers, body, signal, credentials: 'include' };
    if (duplex) { init.duplex = duplex; }
    return fetch(`${this.baseURL}${path}`, init);
  }

  /**
   * @returns {Promise<void>}
   */
  async getV1Healthz() {
    const response = await this.#request("/v1/healthz", { method: 'GET' });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    await response.arrayBuffer();
  }

  /**
   * @returns {Promise<LibrarySnapshot>}
   */
  async getV1Library() {
    const response = await this.#request("/v1/library", { method: 'GET' });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeLibrarySnapshot(await response.arrayBuffer());
  }

  /**
   * @param {AddAuthorRequest} payload
   * @returns {Promise<LibrarySnapshot>}
   */
  async postV1Author(payload) {
    const response = await this.#request("/v1/author", { method: 'POST', body: encodeAddAuthorRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeLibrarySnapshot(await response.arrayBuffer());
  }

  /**
   * @param {AddGenreRequest} payload
   * @returns {Promise<LibrarySnapshot>}
   */
  async postV1Genre(payload) {
    const response = await this.#request("/v1/genre", { method: 'POST', body: encodeAddGenreRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeLibrarySnapshot(await response.arrayBuffer());
  }

  /**
   * @param {AddBookRequest} payload
   * @returns {Promise<LibrarySnapshot>}
   */
  async postV1Book(payload) {
    const response = await this.#request("/v1/book", { method: 'POST', body: encodeAddBookRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeLibrarySnapshot(await response.arrayBuffer());
  }

  /**
   * @returns {Promise<LibrarySnapshot>}
   */
  async postV1LibraryRandom() {
    const response = await this.#request("/v1/library/random", { method: 'POST' });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeLibrarySnapshot(await response.arrayBuffer());
  }

}
