// Code generated by cleanproto. DO NOT EDIT.
/**
 * @typedef {Object} Author
 * @property {number} id
 * @property {string} name
 */
/**
 * @typedef {Object} Genre
 * @property {number} id
 * @property {string} name
 */
/**
 * @typedef {Object} Book
 * @property {number} id
 * @property {string} title
 * @property {number} authorId
 * @property {string} authorName
 * @property {number} genreId
 * @property {string} genreName
 * @property {number} publicationYear
 */
/**
 * @typedef {Object} LibrarySnapshot
 * @property {Author[]} authors
 * @property {Genre[]} genres
 * @property {Book[]} books
 */
/**
 * @typedef {Object} AddAuthorRequest
 * @property {string} name
 */
/**
 * @typedef {Object} AddGenreRequest
 * @property {string} name
 */
/**
 * @typedef {Object} AddBookRequest
 * @property {string} title
 * @property {number} authorId
 * @property {number} genreId
 * @property {number} publicationYear
 */
/**
 * @typedef {Object} AccessPolicy
 * @property {number} policyType
 * @property {string[]} scopes
 */
/**
 * @typedef {Object} ApiErr
 * @property {number} code
 * @property {string} displayErr
 * @property {string} internalErr
 */
import { Reader, Writer } from './runtime.js';

const WIRE = {
    VARINT: 0,
    FIXED64: 1,
    LDELIM: 2,
    FIXED32: 5
};

const tag = (field, wire) => (field << 3) | wire;


/**
 * @param {Author} message
 * @param {Writer} writer
 */
export function writeAuthor(message, writer) {
    if (message.id !== undefined && message.id !== null && message.id !== 0) {
        writer.uint32(tag(1, WIRE.VARINT)).int64(message.id);
    }
    if (message.name !== undefined && message.name !== null && message.name !== "") {
        writer.uint32(tag(2, WIRE.LDELIM)).string(message.name);
    }
}


/**
 * @param {Author} message
 * @returns {Uint8Array}
 */
export function encodeAuthor(message) {
    const writer = Writer.create();
    writeAuthor(message, writer);
    return writer.finish();
}


/**
 * @param {Reader} reader
 * @param {number} [length]
 * @returns {Author}
 */
function decodeAuthorMessage(reader, length) {
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = {id: 0, name: "" };
    while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
            case 1: {
                message.id = readInt64(reader, "int64");
                break;
            }
            case 2: {
                message.name = reader.string();
                break;
            }
            default:
                reader.skipType(tag & 7);
        }
    }
    return message;
}


/**
 * @param {ArrayBuffer} buffer
 * @returns {Author}
 */
export function decodeAuthor(buffer) {
    const reader = Reader.create(new Uint8Array(buffer));
    return decodeAuthorMessage(reader);
}



/**
 * @param {Genre} message
 * @param {Writer} writer
 */
export function writeGenre(message, writer) {
    if (message.id !== undefined && message.id !== null && message.id !== 0) {
        writer.uint32(tag(1, WIRE.VARINT)).int64(message.id);
    }
    if (message.name !== undefined && message.name !== null && message.name !== "") {
        writer.uint32(tag(2, WIRE.LDELIM)).string(message.name);
    }
}


/**
 * @param {Genre} message
 * @returns {Uint8Array}
 */
export function encodeGenre(message) {
    const writer = Writer.create();
    writeGenre(message, writer);
    return writer.finish();
}


/**
 * @param {Reader} reader
 * @param {number} [length]
 * @returns {Genre}
 */
function decodeGenreMessage(reader, length) {
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = {id: 0, name: "" };
    while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
            case 1: {
                message.id = readInt64(reader, "int64");
                break;
            }
            case 2: {
                message.name = reader.string();
                break;
            }
            default:
                reader.skipType(tag & 7);
        }
    }
    return message;
}


/**
 * @param {ArrayBuffer} buffer
 * @returns {Genre}
 */
export function decodeGenre(buffer) {
    const reader = Reader.create(new Uint8Array(buffer));
    return decodeGenreMessage(reader);
}



/**
 * @param {Book} message
 * @param {Writer} writer
 */
export function writeBook(message, writer) {
    if (message.id !== undefined && message.id !== null && message.id !== 0) {
        writer.uint32(tag(1, WIRE.VARINT)).int64(message.id);
    }
    if (message.title !== undefined && message.title !== null && message.title !== "") {
        writer.uint32(tag(2, WIRE.LDELIM)).string(message.title);
    }
    if (message.authorId !== undefined && message.authorId !== null && message.authorId !== 0) {
        writer.uint32(tag(3, WIRE.VARINT)).int64(message.authorId);
    }
    if (message.authorName !== undefined && message.authorName !== null && message.authorName !== "") {
        writer.uint32(tag(4, WIRE.LDELIM)).string(message.authorName);
    }
    if (message.genreId !== undefined && message.genreId !== null && message.genreId !== 0) {
        writer.uint32(tag(5, WIRE.VARINT)).int64(message.genreId);
    }
    if (message.genreName !== undefined && message.genreName !== null && message.genreName !== "") {
        writer.uint32(tag(6, WIRE.LDELIM)).string(message.genreName);
    }
    if (message.publicationYear !== undefined && message.publicationYear !== null && message.publicationYear !== 0) {
        writer.uint32(tag(7, WIRE.VARINT)).int32(message.publicationYear);
    }
}


/**
 * @param {Book} message
 * @returns {Uint8Array}
 */
export function encodeBook(message) {
    const writer = Writer.create();
    writeBook(message, writer);
    return writer.finish();
}


/**
 * @param {Reader} reader
 * @param {number} [length]
 * @returns {Book}
 */
function decodeBookMessage(reader, length) {
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = {id: 0, title: "", authorId: 0, authorName: "", genreId: 0, genreName: "", publicationYear: 0 };
    while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
            case 1: {
                message.id = readInt64(reader, "int64");
                break;
            }
            case 2: {
                message.title = reader.string();
                break;
            }
            case 3: {
                message.authorId = readInt64(reader, "int64");
                break;
            }
            case 4: {
                message.authorName = reader.string();
                break;
            }
            case 5: {
                message.genreId = readInt64(reader, "int64");
                break;
            }
            case 6: {
                message.genreName = reader.string();
                break;
            }
            case 7: {
                message.publicationYear = reader.int32();
                break;
            }
            default:
                reader.skipType(tag & 7);
        }
    }
    return message;
}


/**
 * @param {ArrayBuffer} buffer
 * @returns {Book}
 */
export function decodeBook(buffer) {
    const reader = Reader.create(new Uint8Array(buffer));
    return decodeBookMessage(reader);
}



/**
 * @param {LibrarySnapshot} message
 * @param {Writer} writer
 */
export function writeLibrarySnapshot(message, writer) {
    if (message.authors && message.authors.length > 0) {
        for (const item of message.authors) {
            writer.uint32(tag(1, WIRE.LDELIM)).fork();
            writeAuthor(item, writer);
            writer.ldelim();
        }
    }
    if (message.genres && message.genres.length > 0) {
        for (const item of message.genres) {
            writer.uint32(tag(2, WIRE.LDELIM)).fork();
            writeGenre(item, writer);
            writer.ldelim();
        }
    }
    if (message.books && message.books.length > 0) {
        for (const item of message.books) {
            writer.uint32(tag(3, WIRE.LDELIM)).fork();
            writeBook(item, writer);
            writer.ldelim();
        }
    }
}


/**
 * @param {LibrarySnapshot} message
 * @returns {Uint8Array}
 */
export function encodeLibrarySnapshot(message) {
    const writer = Writer.create();
    writeLibrarySnapshot(message, writer);
    return writer.finish();
}


/**
 * @param {Reader} reader
 * @param {number} [length]
 * @returns {LibrarySnapshot}
 */
function decodeLibrarySnapshotMessage(reader, length) {
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = {authors: [], genres: [], books: [] };
    while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
            case 1: {
                message.authors.push(decodeAuthorMessage(reader, reader.uint32()));
                break;
            }
            case 2: {
                message.genres.push(decodeGenreMessage(reader, reader.uint32()));
                break;
            }
            case 3: {
                message.books.push(decodeBookMessage(reader, reader.uint32()));
                break;
            }
            default:
                reader.skipType(tag & 7);
        }
    }
    return message;
}


/**
 * @param {ArrayBuffer} buffer
 * @returns {LibrarySnapshot}
 */
export function decodeLibrarySnapshot(buffer) {
    const reader = Reader.create(new Uint8Array(buffer));
    return decodeLibrarySnapshotMessage(reader);
}



/**
 * @param {AddAuthorRequest} message
 * @param {Writer} writer
 */
export function writeAddAuthorRequest(message, writer) {
    if (message.name !== undefined && message.name !== null && message.name !== "") {
        writer.uint32(tag(1, WIRE.LDELIM)).string(message.name);
    }
}


/**
 * @param {AddAuthorRequest} message
 * @returns {Uint8Array}
 */
export function encodeAddAuthorRequest(message) {
    const writer = Writer.create();
    writeAddAuthorRequest(message, writer);
    return writer.finish();
}


/**
 * @param {Reader} reader
 * @param {number} [length]
 * @returns {AddAuthorRequest}
 */
function decodeAddAuthorRequestMessage(reader, length) {
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = {name: "" };
    while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
            case 1: {
                message.name = reader.string();
                break;
            }
            default:
                reader.skipType(tag & 7);
        }
    }
    return message;
}


/**
 * @param {ArrayBuffer} buffer
 * @returns {AddAuthorRequest}
 */
export function decodeAddAuthorRequest(buffer) {
    const reader = Reader.create(new Uint8Array(buffer));
    return decodeAddAuthorRequestMessage(reader);
}



/**
 * @param {AddGenreRequest} message
 * @param {Writer} writer
 */
export function writeAddGenreRequest(message, writer) {
    if (message.name !== undefined && message.name !== null && message.name !== "") {
        writer.uint32(tag(1, WIRE.LDELIM)).string(message.name);
    }
}


/**
 * @param {AddGenreRequest} message
 * @returns {Uint8Array}
 */
export function encodeAddGenreRequest(message) {
    const writer = Writer.create();
    writeAddGenreRequest(message, writer);
    return writer.finish();
}


/**
 * @param {Reader} reader
 * @param {number} [length]
 * @returns {AddGenreRequest}
 */
function decodeAddGenreRequestMessage(reader, length) {
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = {name: "" };
    while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
            case 1: {
                message.name = reader.string();
                break;
            }
            default:
                reader.skipType(tag & 7);
        }
    }
    return message;
}


/**
 * @param {ArrayBuffer} buffer
 * @returns {AddGenreRequest}
 */
export function decodeAddGenreRequest(buffer) {
    const reader = Reader.create(new Uint8Array(buffer));
    return decodeAddGenreRequestMessage(reader);
}



/**
 * @param {AddBookRequest} message
 * @param {Writer} writer
 */
export function writeAddBookRequest(message, writer) {
    if (message.title !== undefined && message.title !== null && message.title !== "") {
        writer.uint32(tag(1, WIRE.LDELIM)).string(message.title);
    }
    if (message.authorId !== undefined && message.authorId !== null && message.authorId !== 0) {
        writer.uint32(tag(2, WIRE.VARINT)).int64(message.authorId);
    }
    if (message.genreId !== undefined && message.genreId !== null && message.genreId !== 0) {
        writer.uint32(tag(3, WIRE.VARINT)).int64(message.genreId);
    }
    if (message.publicationYear !== undefined && message.publicationYear !== null && message.publicationYear !== 0) {
        writer.uint32(tag(4, WIRE.VARINT)).int32(message.publicationYear);
    }
}


/**
 * @param {AddBookRequest} message
 * @returns {Uint8Array}
 */
export function encodeAddBookRequest(message) {
    const writer = Writer.create();
    writeAddBookRequest(message, writer);
    return writer.finish();
}


/**
 * @param {Reader} reader
 * @param {number} [length]
 * @returns {AddBookRequest}
 */
function decodeAddBookRequestMessage(reader, length) {
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = {title: "", authorId: 0, genreId: 0, publicationYear: 0 };
    while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
            case 1: {
                message.title = reader.string();
                break;
            }
            case 2: {
                message.authorId = readInt64(reader, "int64");
                break;
            }
            case 3: {
                message.genreId = readInt64(reader, "int64");
                break;
            }
            case 4: {
                message.publicationYear = reader.int32();
                break;
            }
            default:
                reader.skipType(tag & 7);
        }
    }
    return message;
}


/**
 * @param {ArrayBuffer} buffer
 * @returns {AddBookRequest}
 */
export function decodeAddBookRequest(buffer) {
    const reader = Reader.create(new Uint8Array(buffer));
    return decodeAddBookRequestMessage(reader);
}



/**
 * @param {AccessPolicy} message
 * @param {Writer} writer
 */
export function writeAccessPolicy(message, writer) {
    if (message.policyType !== undefined && message.policyType !== null && message.policyType !== 0) {
        writer.uint32(tag(1, WIRE.VARINT)).int32(message.policyType);
    }
    if (message.scopes && message.scopes.length > 0) {
        for (const item of message.scopes) {
            writer.uint32(tag(2, WIRE.LDELIM)).string(item);
        }
    }
}


/**
 * @param {AccessPolicy} message
 * @returns {Uint8Array}
 */
export function encodeAccessPolicy(message) {
    const writer = Writer.create();
    writeAccessPolicy(message, writer);
    return writer.finish();
}


/**
 * @param {Reader} reader
 * @param {number} [length]
 * @returns {AccessPolicy}
 */
function decodeAccessPolicyMessage(reader, length) {
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = {policyType: 0, scopes: [] };
    while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
            case 1: {
                message.policyType = reader.int32();
                break;
            }
            case 2: {
                message.scopes.push(reader.string());
                break;
            }
            default:
                reader.skipType(tag & 7);
        }
    }
    return message;
}


/**
 * @param {ArrayBuffer} buffer
 * @returns {AccessPolicy}
 */
export function decodeAccessPolicy(buffer) {
    const reader = Reader.create(new Uint8Array(buffer));
    return decodeAccessPolicyMessage(reader);
}



/**
 * @param {ApiErr} message
 * @param {Writer} writer
 */
export function writeApiErr(message, writer) {
    if (message.code !== undefined && message.code !== null && message.code !== 0) {
        writer.uint32(tag(1, WIRE.VARINT)).int32(message.code);
    }
    if (message.displayErr !== undefined && message.displayErr !== null && message.displayErr !== "") {
        writer.uint32(tag(2, WIRE.LDELIM)).string(message.displayErr);
    }
    if (message.internalErr !== undefined && message.internalErr !== null && message.internalErr !== "") {
        writer.uint32(tag(3, WIRE.LDELIM)).string(message.internalErr);
    }
}


/**
 * @param {ApiErr} message
 * @returns {Uint8Array}
 */
export function encodeApiErr(message) {
    const writer = Writer.create();
    writeApiErr(message, writer);
    return writer.finish();
}


/**
 * @param {Reader} reader
 * @param {number} [length]
 * @returns {ApiErr}
 */
function decodeApiErrMessage(reader, length) {
    const end = length === undefined ? reader.len : reader.pos + length;
    const message = {code: 0, displayErr: "", internalErr: "" };
    while (reader.pos < end) {
        const tag = reader.uint32();
        switch (tag >>> 3) {
            case 1: {
                message.code = reader.int32();
                break;
            }
            case 2: {
                message.displayErr = reader.string();
                break;
            }
            case 3: {
                message.internalErr = reader.string();
                break;
            }
            default:
                reader.skipType(tag & 7);
        }
    }
    return message;
}


/**
 * @param {ArrayBuffer} buffer
 * @returns {ApiErr}
 */
export function decodeApiErr(buffer) {
    const reader = Reader.create(new Uint8Array(buffer));
    return decodeApiErrMessage(reader);
}



function readInt64(reader, method) {
    const value = reader[method]();
    if (typeof value === "number") {
        return value;
    }
    if (typeof value === "bigint") {
        return Number(value);
    }
    return value.toNumber();
}
