// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package pq

import (
	"database/sql"
)

type AgentSession struct {
	ID                string
	UserID            int64
	CreatedAt         int64
	ExpiresAt         int64
	TokenHash         []byte
	TokenPrefix       string
	RevokedAt         int64
	Scopes            string
	Status            int64
	RequestingAddress string
	ApprovalCode      string
	ApprovedAt        int64
}

type Asset struct {
	ID               int64
	SpaceID          int64
	Key              string
	AssetDirectoryID int64
	CreatedAt        int64
	CreatedBy        int64
}

type AssetDirectory struct {
	ID        int64
	SpaceID   int64
	Key       string
	ParentID  int64
	CreatedAt int64
	CreatedBy int64
}

type AssetMigration struct {
	ID                 int64
	OldConfigVersionID int64
	NewConfigVersionID int64
	Status             string
	LastError          string
	CreatedAt          int64
	StartedAt          int64
	LastAttemptAt      int64
	FinishedAt         int64
}

type AssetStore struct {
	ID           string
	Sha256       string
	SizeBytes    int64
	InlineBlob   []byte
	LocalStatus  int64
	RemoteStatus int64
	CreatedAt    int64
}

type AssetVersion struct {
	ID        int64
	AssetID   int64
	Version   int64
	CreatedAt int64
	CreatedBy int64
	SizeBytes int64
	Sha256    string
}

type AuthzGrant struct {
	ID         int64
	UserID     int64
	TemplateID int64
	Deleted    int64
	CreatedBy  int64
	CreatedAt  int64
	DataBlob   []byte
}

type AuthzRuleTemplate struct {
	ID      int64
	Name    string
	Builtin int64
	Deleted int64
}

type AuthzRuleTemplateVersion struct {
	ID         int64
	TemplateID int64
	Version    int64
	CreatedAt  int64
	CreatedBy  int64
	DataBlob   []byte
}

type Config struct {
	ID               int64
	Name             string
	SpaceID          int64
	ValueDirectoryID int64
	CreatedAt        int64
	CreatedBy        int64
}

type ConfigVersion struct {
	ID        int64
	ConfigID  int64
	Version   int64
	Value     string
	CreatedAt int64
	CreatedBy int64
}

type DeploymentConfig struct {
	DeploymentID int64
	NodeID       int64
	SpaceID      int64
	Name         string
	Deleted      int64
}

type DeploymentVersion struct {
	ID           int64
	DeploymentID int64
	Version      int64
	CreatedAt    int64
	CreatedBy    int64
	SpecBlob     []byte
}

type EnrollmentRequest struct {
	ID                  int64
	CreatedAt           int64
	UpdatedAt           int64
	RequestingIpAddress string
	RequestingMachineID string
	OpendeployVersion   string
	UnderlayAddress     string
	Status              string
}

type GlobalAccessRule struct {
	ID        int64
	Name      string
	CreatedBy int64
	CreatedAt int64
	DataBlob  []byte
}

type LocalKv struct {
	Key   string
	Value []byte
}

type NodeRow struct {
	ID            int64
	EnrollmentID  sql.NullInt64
	EnrolledAt    int64
	Name          string
	Identifier    string
	Roles         string
	Addresses     string
	WgPublicKey   string
	AllowedSpaces string
}

type NodeStatus struct {
	ID              int64
	NodeID          int64
	LastConnectedAt int64
	IsConnected     int64
}

type PublicKey struct {
	Kid      string
	KeyBytes []byte
}

type ScheduledInstance struct {
	ID                int64
	DeploymentID      int64
	DeploymentVersion int64
	NodeID            int64
	InstanceOrdinal   int64
}

type ScheduledInstanceStatus struct {
	ScheduledInstanceID   int64
	UpdatedAt             int64
	DeploymentID          int64
	PreparerConfigVersion sql.NullInt64
	PreparerArtifact      sql.NullString
	PreparerInputsStatus  int64
	PreparerImageStatus   int64
	RunnerConfigVersion   sql.NullInt64
	RunnerPid             sql.NullInt64
	RunnerArtifact        sql.NullString
	RunnerStatus          sql.NullInt64
	RunnerNumRestarts     sql.NullInt64
	RunnerLastRestartAt   sql.NullInt64
	RunnerExtraBlob       []byte
}

type ScheduledInstanceVersion struct {
	ID                  int64
	ScheduledInstanceID int64
	Version             int64
	CreatedAt           int64
	State               int64
}

type Secret struct {
	ID               int64
	Name             string
	SpaceID          int64
	ValueDirectoryID int64
	CreatedAt        int64
	CreatedBy        int64
}

type SecretKeyslot struct {
	Slot       string
	SmkVersion int64
	WrappedSmk []byte
	Nonce      []byte
	KdfSalt    []byte
	CreatedAt  int64
}

type SecretVersion struct {
	ID         int64
	SecretID   int64
	Version    int64
	SmkVersion int64
	Ciphertext []byte
	Nonce      []byte
	CreatedAt  int64
	CreatedBy  int64
}

type Space struct {
	ID   int64
	Name string
}

type SystemConfigRevision struct {
	ID         int64
	UpdatedAt  int64
	ConfigBlob []byte
}

type SystemSecret struct {
	Name       string
	SmkVersion int64
	Ciphertext []byte
	Nonce      []byte
	CreatedAt  int64
	UpdatedAt  int64
}

type User struct {
	ID          int64
	Name        string
	DataBlob    []byte
	CreatedAt   int64
	LastLoginAt int64
}

type ValueDirectory struct {
	ID        int64
	SpaceID   int64
	Name      string
	ParentID  int64
	CreatedAt int64
	CreatedBy int64
}
