// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package pq

import (
	"context"
	"database/sql"
)

const appendAuthzRuleTemplateVersion = `-- name: AppendAuthzRuleTemplateVersion :exec
INSERT INTO authz_rule_template_versions (template_id, version, created_at, author, data_blob)
SELECT ?1, COALESCE(MAX(version), 0) + 1, ?2, ?3, ?4
FROM authz_rule_template_versions
WHERE template_id = ?1
`

type AppendAuthzRuleTemplateVersionParams struct {
	TemplateID int64
	CreatedAt  int64
	Author     int64
	DataBlob   []byte
}

func (q *Queries) AppendAuthzRuleTemplateVersion(ctx context.Context, arg AppendAuthzRuleTemplateVersionParams) error {
	_, err := q.db.ExecContext(ctx, appendAuthzRuleTemplateVersion,
		arg.TemplateID,
		arg.CreatedAt,
		arg.Author,
		arg.DataBlob,
	)
	return err
}

const appendScheduledInstanceVersion = `-- name: AppendScheduledInstanceVersion :exec
INSERT INTO scheduled_instance_versions (scheduled_instance_id, version, created_at, state)
SELECT ?1, COALESCE(MAX(version), 0) + 1, ?2, ?3
FROM scheduled_instance_versions
WHERE scheduled_instance_id = ?1
`

type AppendScheduledInstanceVersionParams struct {
	ScheduledInstanceID int64
	CreatedAt           int64
	State               int64
}

func (q *Queries) AppendScheduledInstanceVersion(ctx context.Context, arg AppendScheduledInstanceVersionParams) error {
	_, err := q.db.ExecContext(ctx, appendScheduledInstanceVersion, arg.ScheduledInstanceID, arg.CreatedAt, arg.State)
	return err
}

const approveAgentSession = `-- name: ApproveAgentSession :execrows
UPDATE agent_sessions SET status = 2, approved_at = ?, scopes = ?
WHERE id = ? AND user_id = ? AND status = 1
`

type ApproveAgentSessionParams struct {
	ApprovedAt int64
	Scopes     string
	ID         string
	UserID     int64
}

// ApproveAgentSession records the approver's scopes and the approval together,
// and only from PENDING, so two operators racing on the same request cannot
// both approve it and the second one's scopes cannot overwrite the first's.
func (q *Queries) ApproveAgentSession(ctx context.Context, arg ApproveAgentSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, approveAgentSession,
		arg.ApprovedAt,
		arg.Scopes,
		arg.ID,
		arg.UserID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const claimAgentSessionToken = `-- name: ClaimAgentSessionToken :execrows
UPDATE agent_sessions SET token_hash = ?, token_prefix = ?, expires_at = ?, scopes = ?
WHERE id = ? AND status = 2 AND length(token_hash) = 0
`

type ClaimAgentSessionTokenParams struct {
	TokenHash   []byte
	TokenPrefix string
	ExpiresAt   int64
	Scopes      string
	ID          string
}

// ClaimAgentSessionToken mints a session's token exactly once. The empty
// token_hash in the WHERE clause is the guard: two concurrent pickups race here
// and only the one that finds the row unclaimed reports a row affected, so a
// session can never hand out two working tokens.
func (q *Queries) ClaimAgentSessionToken(ctx context.Context, arg ClaimAgentSessionTokenParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, claimAgentSessionToken,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.ExpiresAt,
		arg.Scopes,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const completeAssetStoreRow = `-- name: CompleteAssetStoreRow :exec
UPDATE asset_store SET sha256 = ?, local_status = ?, remote_status = ? WHERE id = ?
`

type CompleteAssetStoreRowParams struct {
	Sha256       string
	LocalStatus  int64
	RemoteStatus int64
	ID           string
}

func (q *Queries) CompleteAssetStoreRow(ctx context.Context, arg CompleteAssetStoreRowParams) error {
	_, err := q.db.ExecContext(ctx, completeAssetStoreRow,
		arg.Sha256,
		arg.LocalStatus,
		arg.RemoteStatus,
		arg.ID,
	)
	return err
}

const countAssetVersionsBySha = `-- name: CountAssetVersionsBySha :one
SELECT COUNT(*) FROM asset_versions WHERE sha256 = ?
`

func (q *Queries) CountAssetVersionsBySha(ctx context.Context, sha256 string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAssetVersionsBySha, sha256)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAssetsInDirectory = `-- name: CountAssetsInDirectory :one
SELECT COUNT(*) FROM assets WHERE asset_directory_id = ? AND deleted_at = 0
`

func (q *Queries) CountAssetsInDirectory(ctx context.Context, assetDirectoryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAssetsInDirectory, assetDirectoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChildAssetDirectories = `-- name: CountChildAssetDirectories :one
SELECT COUNT(*) FROM asset_directories WHERE parent_id = ?
`

func (q *Queries) CountChildAssetDirectories(ctx context.Context, parentID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChildAssetDirectories, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countChildValueDirectories = `-- name: CountChildValueDirectories :one
SELECT COUNT(*) FROM value_directories WHERE parent_id = ?
`

func (q *Queries) CountChildValueDirectories(ctx context.Context, parentID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countChildValueDirectories, parentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countConfigsInDirectory = `-- name: CountConfigsInDirectory :one
SELECT COUNT(*) FROM configs WHERE value_directory_id = ? AND deleted_at = 0
`

func (q *Queries) CountConfigsInDirectory(ctx context.Context, valueDirectoryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countConfigsInDirectory, valueDirectoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDeploymentsForSpace = `-- name: CountDeploymentsForSpace :one
SELECT COUNT(*) FROM deployment_configs d
WHERE d.deleted_at = 0
  AND (SELECT sp.space_id FROM deployment_space_versions sp
       WHERE sp.deployment_id = d.deployment_id
       ORDER BY sp.version DESC LIMIT 1) = ?
`

func (q *Queries) CountDeploymentsForSpace(ctx context.Context, spaceID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDeploymentsForSpace, spaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countDirectorySiblingsWithKey = `-- name: CountDirectorySiblingsWithKey :one


SELECT COUNT(*) FROM asset_directories
WHERE space_id = ? AND parent_id = ? AND key = ? AND id != ?
`

type CountDirectorySiblingsWithKeyParams struct {
	SpaceID  int64
	ParentID int64
	Key      string
	ID       int64
}

// === assets ===
// Container reads are hand-written in assets.go: the current space is the
// newest asset_spaces row and reads exclude soft-deleted assets.
func (q *Queries) CountDirectorySiblingsWithKey(ctx context.Context, arg CountDirectorySiblingsWithKeyParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countDirectorySiblingsWithKey,
		arg.SpaceID,
		arg.ParentID,
		arg.Key,
		arg.ID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countSecretsInDirectory = `-- name: CountSecretsInDirectory :one
SELECT COUNT(*) FROM secrets WHERE value_directory_id = ? AND deleted_at = 0
`

func (q *Queries) CountSecretsInDirectory(ctx context.Context, valueDirectoryID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, countSecretsInDirectory, valueDirectoryID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countValueDirectorySiblingsWithName = `-- name: CountValueDirectorySiblingsWithName :one

SELECT COUNT(*) FROM value_directories
WHERE space_id = ? AND parent_id = ? AND name = ? AND id != ?
`

type CountValueDirectorySiblingsWithNameParams struct {
	SpaceID  int64
	ParentID int64
	Name     string
	ID       int64
}

// === value directories (shared by secrets and configs) ===
func (q *Queries) CountValueDirectorySiblingsWithName(ctx context.Context, arg CountValueDirectorySiblingsWithNameParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countValueDirectorySiblingsWithName,
		arg.SpaceID,
		arg.ParentID,
		arg.Name,
		arg.ID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuthzRuleTemplate = `-- name: CreateAuthzRuleTemplate :one


INSERT INTO authz_rule_templates (name, builtin, deleted_at)
VALUES (?, 0, 0) RETURNING id
`

// === authz ===
// The template list read is hand-written in authz.go: a template row is its
// identity joined with the version log for created_at/author (v1 row) and
// current content (latest row). Creation appends the v1 version row in the
// same tx; content updates are pure appends.
func (q *Queries) CreateAuthzRuleTemplate(ctx context.Context, name string) (int64, error) {
	row := q.db.QueryRowContext(ctx, createAuthzRuleTemplate, name)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createDeploymentConfig = `-- name: CreateDeploymentConfig :one

INSERT INTO deployment_configs (node_id, name, deleted_at)
VALUES (?, ?, 0)
RETURNING deployment_id
`

type CreateDeploymentConfigParams struct {
	NodeID int64
	Name   string
}

// === deployment_configs ===
// CreateDeploymentConfig inserts a new stable deployment identity and
// auto-allocates its deployment_id. Deleted deployments do not reserve their
// former identity tuple. The caller inserts the v1 version row in the same tx.
func (q *Queries) CreateDeploymentConfig(ctx context.Context, arg CreateDeploymentConfigParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, createDeploymentConfig, arg.NodeID, arg.Name)
	var deployment_id int64
	err := row.Scan(&deployment_id)
	return deployment_id, err
}

const createSpace = `-- name: CreateSpace :one
INSERT INTO spaces (name) VALUES (?)
RETURNING id, name
`

func (q *Queries) CreateSpace(ctx context.Context, name string) (Space, error) {
	row := q.db.QueryRowContext(ctx, createSpace, name)
	var i Space
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const deleteAssetDirectory = `-- name: DeleteAssetDirectory :exec
DELETE FROM asset_directories WHERE id = ?
`

func (q *Queries) DeleteAssetDirectory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteAssetDirectory, id)
	return err
}

const deleteAssetStoreRow = `-- name: DeleteAssetStoreRow :exec
DELETE FROM asset_store WHERE id = ?
`

func (q *Queries) DeleteAssetStoreRow(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAssetStoreRow, id)
	return err
}

const deleteGlobalAccessRuleRow = `-- name: DeleteGlobalAccessRuleRow :exec
DELETE FROM global_access_rules WHERE id = ?
`

func (q *Queries) DeleteGlobalAccessRuleRow(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteGlobalAccessRuleRow, id)
	return err
}

const deleteSpace = `-- name: DeleteSpace :exec
DELETE FROM spaces WHERE id = ?
`

func (q *Queries) DeleteSpace(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteSpace, id)
	return err
}

const deleteValueDirectory = `-- name: DeleteValueDirectory :exec
DELETE FROM value_directories WHERE id = ?
`

func (q *Queries) DeleteValueDirectory(ctx context.Context, id int64) error {
	_, err := q.db.ExecContext(ctx, deleteValueDirectory, id)
	return err
}

const finishAssetMigration = `-- name: FinishAssetMigration :one
UPDATE asset_migrations
SET status = 'finished', last_error = '', finished_at = ?
WHERE id = ?
RETURNING id, old_config_version_id, new_config_version_id, status, last_error,
          created_at, started_at, last_attempt_at, finished_at
`

type FinishAssetMigrationParams struct {
	FinishedAt int64
	ID         int64
}

func (q *Queries) FinishAssetMigration(ctx context.Context, arg FinishAssetMigrationParams) (AssetMigration, error) {
	row := q.db.QueryRowContext(ctx, finishAssetMigration, arg.FinishedAt, arg.ID)
	var i AssetMigration
	err := row.Scan(
		&i.ID,
		&i.OldConfigVersionID,
		&i.NewConfigVersionID,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.StartedAt,
		&i.LastAttemptAt,
		&i.FinishedAt,
	)
	return i, err
}

const getAgentSession = `-- name: GetAgentSession :one
SELECT id, user_id, created_at, expires_at, token_hash, token_prefix, revoked_at, scopes,
       status, requesting_address, approval_code, approved_at
FROM agent_sessions WHERE id = ?
`

func (q *Queries) GetAgentSession(ctx context.Context, id string) (AgentSession, error) {
	row := q.db.QueryRowContext(ctx, getAgentSession, id)
	var i AgentSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.TokenHash,
		&i.TokenPrefix,
		&i.RevokedAt,
		&i.Scopes,
		&i.Status,
		&i.RequestingAddress,
		&i.ApprovalCode,
		&i.ApprovedAt,
	)
	return i, err
}

const getAssetDirectoryByID = `-- name: GetAssetDirectoryByID :one
SELECT id, space_id, key, parent_id, created_at, author
FROM asset_directories
WHERE id = ?
`

func (q *Queries) GetAssetDirectoryByID(ctx context.Context, id int64) (AssetDirectory, error) {
	row := q.db.QueryRowContext(ctx, getAssetDirectoryByID, id)
	var i AssetDirectory
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Key,
		&i.ParentID,
		&i.CreatedAt,
		&i.Author,
	)
	return i, err
}

const getAssetStoreRowByID = `-- name: GetAssetStoreRowByID :one
SELECT id, sha256, size_bytes, inline_blob, local_status, remote_status, created_at
FROM asset_store
WHERE id = ?
`

func (q *Queries) GetAssetStoreRowByID(ctx context.Context, id string) (AssetStore, error) {
	row := q.db.QueryRowContext(ctx, getAssetStoreRowByID, id)
	var i AssetStore
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.SizeBytes,
		&i.InlineBlob,
		&i.LocalStatus,
		&i.RemoteStatus,
		&i.CreatedAt,
	)
	return i, err
}

const getAssetStoreRowBySha = `-- name: GetAssetStoreRowBySha :one
SELECT id, sha256, size_bytes, inline_blob, local_status, remote_status, created_at
FROM asset_store
WHERE sha256 = ? AND sha256 != ''
`

func (q *Queries) GetAssetStoreRowBySha(ctx context.Context, sha256 string) (AssetStore, error) {
	row := q.db.QueryRowContext(ctx, getAssetStoreRowBySha, sha256)
	var i AssetStore
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.SizeBytes,
		&i.InlineBlob,
		&i.LocalStatus,
		&i.RemoteStatus,
		&i.CreatedAt,
	)
	return i, err
}

const getConfigByID = `-- name: GetConfigByID :one
SELECT id, updated_at, config_blob FROM system_config_revisions WHERE id = ?
`

func (q *Queries) GetConfigByID(ctx context.Context, id int64) (SystemConfigRevision, error) {
	row := q.db.QueryRowContext(ctx, getConfigByID, id)
	var i SystemConfigRevision
	err := row.Scan(&i.ID, &i.UpdatedAt, &i.ConfigBlob)
	return i, err
}

const getDeploymentVersion = `-- name: GetDeploymentVersion :one
SELECT id, deployment_id, version, created_at, author, spec_blob
FROM deployment_versions
WHERE deployment_id = ? AND version = ?
`

type GetDeploymentVersionParams struct {
	DeploymentID int64
	Version      int64
}

func (q *Queries) GetDeploymentVersion(ctx context.Context, arg GetDeploymentVersionParams) (DeploymentVersion, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentVersion, arg.DeploymentID, arg.Version)
	var i DeploymentVersion
	err := row.Scan(
		&i.ID,
		&i.DeploymentID,
		&i.Version,
		&i.CreatedAt,
		&i.Author,
		&i.SpecBlob,
	)
	return i, err
}

const getLatestAuthzRuleTemplateVersionBlob = `-- name: GetLatestAuthzRuleTemplateVersionBlob :one
SELECT data_blob FROM authz_rule_template_versions
WHERE template_id = ? ORDER BY id DESC LIMIT 1
`

func (q *Queries) GetLatestAuthzRuleTemplateVersionBlob(ctx context.Context, templateID int64) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getLatestAuthzRuleTemplateVersionBlob, templateID)
	var data_blob []byte
	err := row.Scan(&data_blob)
	return data_blob, err
}

const getLatestConfig = `-- name: GetLatestConfig :one
select id, updated_at, config_blob from system_config_revisions order by id desc limit 1
`

func (q *Queries) GetLatestConfig(ctx context.Context) (SystemConfigRevision, error) {
	row := q.db.QueryRowContext(ctx, getLatestConfig)
	var i SystemConfigRevision
	err := row.Scan(&i.ID, &i.UpdatedAt, &i.ConfigBlob)
	return i, err
}

const getLocalKV = `-- name: GetLocalKV :one

SELECT value FROM local_kv WHERE key = ?
`

// === local_kv ===
func (q *Queries) GetLocalKV(ctx context.Context, key string) ([]byte, error) {
	row := q.db.QueryRowContext(ctx, getLocalKV, key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const getNextAssetVersionNumber = `-- name: GetNextAssetVersionNumber :one
SELECT COALESCE(MAX(version), 0) + 1
FROM asset_versions
WHERE asset_id = ?
`

func (q *Queries) GetNextAssetVersionNumber(ctx context.Context, assetID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextAssetVersionNumber, assetID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getNextConfigVersionNumber = `-- name: GetNextConfigVersionNumber :one
SELECT COALESCE(MAX(version), 0) + 1
FROM config_versions
WHERE config_id = ?
`

func (q *Queries) GetNextConfigVersionNumber(ctx context.Context, configID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextConfigVersionNumber, configID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getNextSecretVersionNumber = `-- name: GetNextSecretVersionNumber :one
SELECT COALESCE(MAX(version), 0) + 1
FROM secret_versions
WHERE secret_id = ?
`

func (q *Queries) GetNextSecretVersionNumber(ctx context.Context, secretID int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, getNextSecretVersionNumber, secretID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const getPersonalSession = `-- name: GetPersonalSession :one
SELECT id, user_id, created_at, expires_at, token_hash, revoked_at,
       requesting_address, user_agent, last_active_at
FROM personal_sessions WHERE id = ?
`

func (q *Queries) GetPersonalSession(ctx context.Context, id string) (PersonalSession, error) {
	row := q.db.QueryRowContext(ctx, getPersonalSession, id)
	var i PersonalSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.TokenHash,
		&i.RevokedAt,
		&i.RequestingAddress,
		&i.UserAgent,
		&i.LastActiveAt,
	)
	return i, err
}

const getPublicKey = `-- name: GetPublicKey :one

SELECT kid, key_bytes FROM public_keys WHERE kid = ?
`

// === public_keys ===
func (q *Queries) GetPublicKey(ctx context.Context, kid string) (PublicKey, error) {
	row := q.db.QueryRowContext(ctx, getPublicKey, kid)
	var i PublicKey
	err := row.Scan(&i.Kid, &i.KeyBytes)
	return i, err
}

const getSystemSecret = `-- name: GetSystemSecret :one

SELECT name, smk_version, ciphertext, nonce, created_at, updated_at
FROM system_secrets
WHERE name = ?
`

// === system_secrets ===
func (q *Queries) GetSystemSecret(ctx context.Context, name string) (SystemSecret, error) {
	row := q.db.QueryRowContext(ctx, getSystemSecret, name)
	var i SystemSecret
	err := row.Scan(
		&i.Name,
		&i.SmkVersion,
		&i.Ciphertext,
		&i.Nonce,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUnfinishedAssetMigration = `-- name: GetUnfinishedAssetMigration :one

SELECT id, old_config_version_id, new_config_version_id, status, last_error,
       created_at, started_at, last_attempt_at, finished_at
FROM asset_migrations
WHERE status != 'finished'
ORDER BY id
LIMIT 1
`

// === asset_migrations ===
func (q *Queries) GetUnfinishedAssetMigration(ctx context.Context) (AssetMigration, error) {
	row := q.db.QueryRowContext(ctx, getUnfinishedAssetMigration)
	var i AssetMigration
	err := row.Scan(
		&i.ID,
		&i.OldConfigVersionID,
		&i.NewConfigVersionID,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.StartedAt,
		&i.LastAttemptAt,
		&i.FinishedAt,
	)
	return i, err
}

const getUser = `-- name: GetUser :one

SELECT id, name, data_blob, created_at, last_login_at FROM users WHERE id = ?
`

// === users ===
func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.DataBlob,
		&i.CreatedAt,
		&i.LastLoginAt,
	)
	return i, err
}

const getValueDirectoryByID = `-- name: GetValueDirectoryByID :one
SELECT id, space_id, name, parent_id, created_at, author
FROM value_directories
WHERE id = ?
`

func (q *Queries) GetValueDirectoryByID(ctx context.Context, id int64) (ValueDirectory, error) {
	row := q.db.QueryRowContext(ctx, getValueDirectoryByID, id)
	var i ValueDirectory
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.Author,
	)
	return i, err
}

const insertAgentSession = `-- name: InsertAgentSession :exec

INSERT INTO agent_sessions (id, user_id, created_at, expires_at, token_hash, token_prefix, revoked_at, scopes,
                            status, requesting_address, approval_code, approved_at)
VALUES (?, ?, ?, ?, ?, ?, 0, ?, ?, ?, ?, ?)
`

type InsertAgentSessionParams struct {
	ID                string
	UserID            int64
	CreatedAt         int64
	ExpiresAt         int64
	TokenHash         []byte
	TokenPrefix       string
	Scopes            string
	Status            int64
	RequestingAddress string
	ApprovalCode      string
	ApprovedAt        int64
}

// === agent_sessions ===
func (q *Queries) InsertAgentSession(ctx context.Context, arg InsertAgentSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertAgentSession,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.TokenHash,
		arg.TokenPrefix,
		arg.Scopes,
		arg.Status,
		arg.RequestingAddress,
		arg.ApprovalCode,
		arg.ApprovedAt,
	)
	return err
}

const insertAssetDirectory = `-- name: InsertAssetDirectory :one
INSERT INTO asset_directories (space_id, key, parent_id, created_at, author)
VALUES (?, ?, ?, ?, ?)
RETURNING id, space_id, key, parent_id, created_at, author
`

type InsertAssetDirectoryParams struct {
	SpaceID   int64
	Key       string
	ParentID  int64
	CreatedAt int64
	Author    int64
}

func (q *Queries) InsertAssetDirectory(ctx context.Context, arg InsertAssetDirectoryParams) (AssetDirectory, error) {
	row := q.db.QueryRowContext(ctx, insertAssetDirectory,
		arg.SpaceID,
		arg.Key,
		arg.ParentID,
		arg.CreatedAt,
		arg.Author,
	)
	var i AssetDirectory
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Key,
		&i.ParentID,
		&i.CreatedAt,
		&i.Author,
	)
	return i, err
}

const insertAssetMigration = `-- name: InsertAssetMigration :one
INSERT INTO asset_migrations (
    old_config_version_id, new_config_version_id, status, created_at
) VALUES (?, ?, 'pending', ?)
RETURNING id, old_config_version_id, new_config_version_id, status, last_error,
          created_at, started_at, last_attempt_at, finished_at
`

type InsertAssetMigrationParams struct {
	OldConfigVersionID int64
	NewConfigVersionID int64
	CreatedAt          int64
}

func (q *Queries) InsertAssetMigration(ctx context.Context, arg InsertAssetMigrationParams) (AssetMigration, error) {
	row := q.db.QueryRowContext(ctx, insertAssetMigration, arg.OldConfigVersionID, arg.NewConfigVersionID, arg.CreatedAt)
	var i AssetMigration
	err := row.Scan(
		&i.ID,
		&i.OldConfigVersionID,
		&i.NewConfigVersionID,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.StartedAt,
		&i.LastAttemptAt,
		&i.FinishedAt,
	)
	return i, err
}

const insertAssetRow = `-- name: InsertAssetRow :one
INSERT INTO assets (key, asset_directory_id, created_at)
VALUES (?, ?, ?)
RETURNING id
`

type InsertAssetRowParams struct {
	Key              string
	AssetDirectoryID int64
	CreatedAt        int64
}

func (q *Queries) InsertAssetRow(ctx context.Context, arg InsertAssetRowParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertAssetRow, arg.Key, arg.AssetDirectoryID, arg.CreatedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertAssetSpaceRow = `-- name: InsertAssetSpaceRow :exec
INSERT INTO asset_spaces (asset_id, author, created_at, space_id)
VALUES (?, ?, ?, ?)
`

type InsertAssetSpaceRowParams struct {
	AssetID   int64
	Author    int64
	CreatedAt int64
	SpaceID   int64
}

func (q *Queries) InsertAssetSpaceRow(ctx context.Context, arg InsertAssetSpaceRowParams) error {
	_, err := q.db.ExecContext(ctx, insertAssetSpaceRow,
		arg.AssetID,
		arg.Author,
		arg.CreatedAt,
		arg.SpaceID,
	)
	return err
}

const insertAssetStoreRow = `-- name: InsertAssetStoreRow :one

INSERT INTO asset_store (id, sha256, size_bytes, inline_blob, local_status, remote_status, created_at)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, sha256, size_bytes, inline_blob, local_status, remote_status, created_at
`

type InsertAssetStoreRowParams struct {
	ID           string
	Sha256       string
	SizeBytes    int64
	InlineBlob   []byte
	LocalStatus  int64
	RemoteStatus int64
	CreatedAt    int64
}

// === asset_store ===
func (q *Queries) InsertAssetStoreRow(ctx context.Context, arg InsertAssetStoreRowParams) (AssetStore, error) {
	row := q.db.QueryRowContext(ctx, insertAssetStoreRow,
		arg.ID,
		arg.Sha256,
		arg.SizeBytes,
		arg.InlineBlob,
		arg.LocalStatus,
		arg.RemoteStatus,
		arg.CreatedAt,
	)
	var i AssetStore
	err := row.Scan(
		&i.ID,
		&i.Sha256,
		&i.SizeBytes,
		&i.InlineBlob,
		&i.LocalStatus,
		&i.RemoteStatus,
		&i.CreatedAt,
	)
	return i, err
}

const insertAssetVersion = `-- name: InsertAssetVersion :one
INSERT INTO asset_versions (asset_id, version, created_at, author, size_bytes, sha256)
VALUES (?, ?, ?, ?, ?, ?)
RETURNING id, asset_id, version, created_at, author, size_bytes, sha256
`

type InsertAssetVersionParams struct {
	AssetID   int64
	Version   int64
	CreatedAt int64
	Author    int64
	SizeBytes int64
	Sha256    string
}

func (q *Queries) InsertAssetVersion(ctx context.Context, arg InsertAssetVersionParams) (AssetVersion, error) {
	row := q.db.QueryRowContext(ctx, insertAssetVersion,
		arg.AssetID,
		arg.Version,
		arg.CreatedAt,
		arg.Author,
		arg.SizeBytes,
		arg.Sha256,
	)
	var i AssetVersion
	err := row.Scan(
		&i.ID,
		&i.AssetID,
		&i.Version,
		&i.CreatedAt,
		&i.Author,
		&i.SizeBytes,
		&i.Sha256,
	)
	return i, err
}

const insertAuthzGrantRow = `-- name: InsertAuthzGrantRow :one
INSERT INTO authz_grants (user_id, template_id, author, created_at, data_blob)
VALUES (?, ?, ?, ?, ?) RETURNING id
`

type InsertAuthzGrantRowParams struct {
	UserID     int64
	TemplateID int64
	Author     int64
	CreatedAt  int64
	DataBlob   []byte
}

func (q *Queries) InsertAuthzGrantRow(ctx context.Context, arg InsertAuthzGrantRowParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertAuthzGrantRow,
		arg.UserID,
		arg.TemplateID,
		arg.Author,
		arg.CreatedAt,
		arg.DataBlob,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertConfigRow = `-- name: InsertConfigRow :one


INSERT INTO configs (name, value_directory_id, created_at)
VALUES (?, ?, ?)
RETURNING id
`

type InsertConfigRowParams struct {
	Name             string
	ValueDirectoryID int64
	CreatedAt        int64
}

// === configs ===
// Container reads are hand-written in values.go: the current space is the
// newest config_spaces row and reads exclude soft-deleted configs.
func (q *Queries) InsertConfigRow(ctx context.Context, arg InsertConfigRowParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertConfigRow, arg.Name, arg.ValueDirectoryID, arg.CreatedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertConfigSpaceRow = `-- name: InsertConfigSpaceRow :exec
INSERT INTO config_spaces (config_id, author, created_at, space_id)
VALUES (?, ?, ?, ?)
`

type InsertConfigSpaceRowParams struct {
	ConfigID  int64
	Author    int64
	CreatedAt int64
	SpaceID   int64
}

func (q *Queries) InsertConfigSpaceRow(ctx context.Context, arg InsertConfigSpaceRowParams) error {
	_, err := q.db.ExecContext(ctx, insertConfigSpaceRow,
		arg.ConfigID,
		arg.Author,
		arg.CreatedAt,
		arg.SpaceID,
	)
	return err
}

const insertConfigVersion = `-- name: InsertConfigVersion :one
INSERT INTO config_versions (config_id, version, value, created_at, author)
VALUES (?, ?, ?, ?, ?)
RETURNING id, config_id, version, value, created_at, author
`

type InsertConfigVersionParams struct {
	ConfigID  int64
	Version   int64
	Value     string
	CreatedAt int64
	Author    int64
}

func (q *Queries) InsertConfigVersion(ctx context.Context, arg InsertConfigVersionParams) (ConfigVersion, error) {
	row := q.db.QueryRowContext(ctx, insertConfigVersion,
		arg.ConfigID,
		arg.Version,
		arg.Value,
		arg.CreatedAt,
		arg.Author,
	)
	var i ConfigVersion
	err := row.Scan(
		&i.ID,
		&i.ConfigID,
		&i.Version,
		&i.Value,
		&i.CreatedAt,
		&i.Author,
	)
	return i, err
}

const insertDeploymentSpaceVersion = `-- name: InsertDeploymentSpaceVersion :one
INSERT INTO deployment_space_versions (deployment_id, version, author, created_at, space_id)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type InsertDeploymentSpaceVersionParams struct {
	DeploymentID int64
	Version      int64
	Author       int64
	CreatedAt    int64
	SpaceID      int64
}

func (q *Queries) InsertDeploymentSpaceVersion(ctx context.Context, arg InsertDeploymentSpaceVersionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertDeploymentSpaceVersion,
		arg.DeploymentID,
		arg.Version,
		arg.Author,
		arg.CreatedAt,
		arg.SpaceID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertDeploymentVersion = `-- name: InsertDeploymentVersion :exec

INSERT INTO deployment_versions (deployment_id, version, created_at, author, spec_blob)
VALUES (?, ?, ?, ?, ?)
`

type InsertDeploymentVersionParams struct {
	DeploymentID int64
	Version      int64
	CreatedAt    int64
	Author       int64
	SpecBlob     []byte
}

// === deployment_versions ===
func (q *Queries) InsertDeploymentVersion(ctx context.Context, arg InsertDeploymentVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertDeploymentVersion,
		arg.DeploymentID,
		arg.Version,
		arg.CreatedAt,
		arg.Author,
		arg.SpecBlob,
	)
	return err
}

const insertGlobalAccessRuleRow = `-- name: InsertGlobalAccessRuleRow :one
INSERT INTO global_access_rules (name, author, created_at, data_blob)
VALUES (?, ?, ?, ?) RETURNING id
`

type InsertGlobalAccessRuleRowParams struct {
	Name      string
	Author    int64
	CreatedAt int64
	DataBlob  []byte
}

func (q *Queries) InsertGlobalAccessRuleRow(ctx context.Context, arg InsertGlobalAccessRuleRowParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertGlobalAccessRuleRow,
		arg.Name,
		arg.Author,
		arg.CreatedAt,
		arg.DataBlob,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPersonalSession = `-- name: InsertPersonalSession :exec

INSERT INTO personal_sessions (id, user_id, created_at, expires_at, token_hash, revoked_at,
                               requesting_address, user_agent, last_active_at)
VALUES (?, ?, ?, ?, ?, 0, ?, ?, ?)
`

type InsertPersonalSessionParams struct {
	ID                string
	UserID            int64
	CreatedAt         int64
	ExpiresAt         int64
	TokenHash         []byte
	RequestingAddress string
	UserAgent         string
	LastActiveAt      int64
}

// === personal_sessions ===
func (q *Queries) InsertPersonalSession(ctx context.Context, arg InsertPersonalSessionParams) error {
	_, err := q.db.ExecContext(ctx, insertPersonalSession,
		arg.ID,
		arg.UserID,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.TokenHash,
		arg.RequestingAddress,
		arg.UserAgent,
		arg.LastActiveAt,
	)
	return err
}

const insertScheduledInstance = `-- name: InsertScheduledInstance :one


INSERT INTO scheduled_instances (deployment_id, deployment_version, node_id, instance_ordinal, deployment_space_version_id)
VALUES (?, ?, ?, ?, ?)
RETURNING id
`

type InsertScheduledInstanceParams struct {
	DeploymentID             int64
	DeploymentVersion        int64
	NodeID                   int64
	InstanceOrdinal          int64
	DeploymentSpaceVersionID int64
}

// === scheduled_instances ===
// Reads are hand-written in scheduled_instances.go: an instance row is its
// identity joined with the version log for creation time and current state.
// Creation appends the v1 version row in the same tx; state transitions are
// pure appends.
func (q *Queries) InsertScheduledInstance(ctx context.Context, arg InsertScheduledInstanceParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertScheduledInstance,
		arg.DeploymentID,
		arg.DeploymentVersion,
		arg.NodeID,
		arg.InstanceOrdinal,
		arg.DeploymentSpaceVersionID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertScheduledInstanceStatus = `-- name: InsertScheduledInstanceStatus :exec

INSERT INTO scheduled_instance_status (
    scheduled_instance_id, updated_at, deployment_id,
    preparer_config_version, preparer_artifact,
    preparer_inputs_status, preparer_image_status,
    runner_config_version, runner_pid, runner_artifact, runner_status,
    runner_num_restarts, runner_last_restart_at, runner_extra_blob
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(scheduled_instance_id, updated_at) DO UPDATE SET
    deployment_id = excluded.deployment_id,
    preparer_config_version = excluded.preparer_config_version,
    preparer_artifact = excluded.preparer_artifact,
    preparer_inputs_status = excluded.preparer_inputs_status,
    preparer_image_status = excluded.preparer_image_status,
    runner_config_version = excluded.runner_config_version,
    runner_pid = excluded.runner_pid,
    runner_artifact = excluded.runner_artifact,
    runner_status = excluded.runner_status,
    runner_num_restarts = excluded.runner_num_restarts,
    runner_last_restart_at = excluded.runner_last_restart_at,
    runner_extra_blob = excluded.runner_extra_blob
`

type InsertScheduledInstanceStatusParams struct {
	ScheduledInstanceID   int64
	UpdatedAt             int64
	DeploymentID          int64
	PreparerConfigVersion sql.NullInt64
	PreparerArtifact      sql.NullString
	PreparerInputsStatus  int64
	PreparerImageStatus   int64
	RunnerConfigVersion   sql.NullInt64
	RunnerPid             sql.NullInt64
	RunnerArtifact        sql.NullString
	RunnerStatus          sql.NullInt64
	RunnerNumRestarts     sql.NullInt64
	RunnerLastRestartAt   sql.NullInt64
	RunnerExtraBlob       []byte
}

// === scheduled_instance_status ===
func (q *Queries) InsertScheduledInstanceStatus(ctx context.Context, arg InsertScheduledInstanceStatusParams) error {
	_, err := q.db.ExecContext(ctx, insertScheduledInstanceStatus,
		arg.ScheduledInstanceID,
		arg.UpdatedAt,
		arg.DeploymentID,
		arg.PreparerConfigVersion,
		arg.PreparerArtifact,
		arg.PreparerInputsStatus,
		arg.PreparerImageStatus,
		arg.RunnerConfigVersion,
		arg.RunnerPid,
		arg.RunnerArtifact,
		arg.RunnerStatus,
		arg.RunnerNumRestarts,
		arg.RunnerLastRestartAt,
		arg.RunnerExtraBlob,
	)
	return err
}

const insertSecretRow = `-- name: InsertSecretRow :one


INSERT INTO secrets (name, value_directory_id, created_at)
VALUES (?, ?, ?)
RETURNING id
`

type InsertSecretRowParams struct {
	Name             string
	ValueDirectoryID int64
	CreatedAt        int64
}

// === secrets ===
// Container reads and the version-record list are hand-written in values.go:
// the current space is the newest secret_spaces row and reads exclude
// soft-deleted secrets.
func (q *Queries) InsertSecretRow(ctx context.Context, arg InsertSecretRowParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, insertSecretRow, arg.Name, arg.ValueDirectoryID, arg.CreatedAt)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertSecretSpaceRow = `-- name: InsertSecretSpaceRow :exec
INSERT INTO secret_spaces (secret_id, author, created_at, space_id)
VALUES (?, ?, ?, ?)
`

type InsertSecretSpaceRowParams struct {
	SecretID  int64
	Author    int64
	CreatedAt int64
	SpaceID   int64
}

func (q *Queries) InsertSecretSpaceRow(ctx context.Context, arg InsertSecretSpaceRowParams) error {
	_, err := q.db.ExecContext(ctx, insertSecretSpaceRow,
		arg.SecretID,
		arg.Author,
		arg.CreatedAt,
		arg.SpaceID,
	)
	return err
}

const insertSecretVersion = `-- name: InsertSecretVersion :one
INSERT INTO secret_versions (secret_id, version, smk_version, ciphertext, nonce, created_at, author)
VALUES (?, ?, ?, ?, ?, ?, ?)
RETURNING id, secret_id, version, smk_version, ciphertext, nonce, created_at, author
`

type InsertSecretVersionParams struct {
	SecretID   int64
	Version    int64
	SmkVersion int64
	Ciphertext []byte
	Nonce      []byte
	CreatedAt  int64
	Author     int64
}

func (q *Queries) InsertSecretVersion(ctx context.Context, arg InsertSecretVersionParams) (SecretVersion, error) {
	row := q.db.QueryRowContext(ctx, insertSecretVersion,
		arg.SecretID,
		arg.Version,
		arg.SmkVersion,
		arg.Ciphertext,
		arg.Nonce,
		arg.CreatedAt,
		arg.Author,
	)
	var i SecretVersion
	err := row.Scan(
		&i.ID,
		&i.SecretID,
		&i.Version,
		&i.SmkVersion,
		&i.Ciphertext,
		&i.Nonce,
		&i.CreatedAt,
		&i.Author,
	)
	return i, err
}

const insertValueDirectory = `-- name: InsertValueDirectory :one
INSERT INTO value_directories (space_id, name, parent_id, created_at, author)
VALUES (?, ?, ?, ?, ?)
RETURNING id, space_id, name, parent_id, created_at, author
`

type InsertValueDirectoryParams struct {
	SpaceID   int64
	Name      string
	ParentID  int64
	CreatedAt int64
	Author    int64
}

func (q *Queries) InsertValueDirectory(ctx context.Context, arg InsertValueDirectoryParams) (ValueDirectory, error) {
	row := q.db.QueryRowContext(ctx, insertValueDirectory,
		arg.SpaceID,
		arg.Name,
		arg.ParentID,
		arg.CreatedAt,
		arg.Author,
	)
	var i ValueDirectory
	err := row.Scan(
		&i.ID,
		&i.SpaceID,
		&i.Name,
		&i.ParentID,
		&i.CreatedAt,
		&i.Author,
	)
	return i, err
}

const listAgentSessionsForUser = `-- name: ListAgentSessionsForUser :many
SELECT id, user_id, created_at, expires_at, token_hash, token_prefix, revoked_at, scopes,
       status, requesting_address, approval_code, approved_at
FROM agent_sessions WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListAgentSessionsForUser(ctx context.Context, userID int64) ([]AgentSession, error) {
	rows, err := q.db.QueryContext(ctx, listAgentSessionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentSession
	for rows.Next() {
		var i AgentSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.RevokedAt,
			&i.Scopes,
			&i.Status,
			&i.RequestingAddress,
			&i.ApprovalCode,
			&i.ApprovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetDirectories = `-- name: ListAssetDirectories :many
SELECT id, space_id, key, parent_id, created_at, author
FROM asset_directories
ORDER BY space_id, parent_id, key
`

func (q *Queries) ListAssetDirectories(ctx context.Context) ([]AssetDirectory, error) {
	rows, err := q.db.QueryContext(ctx, listAssetDirectories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetDirectory
	for rows.Next() {
		var i AssetDirectory
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.Key,
			&i.ParentID,
			&i.CreatedAt,
			&i.Author,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetIDsBySha = `-- name: ListAssetIDsBySha :many
SELECT DISTINCT asset_id FROM asset_versions WHERE sha256 = ?
`

func (q *Queries) ListAssetIDsBySha(ctx context.Context, sha256 string) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listAssetIDsBySha, sha256)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var asset_id int64
		if err := rows.Scan(&asset_id); err != nil {
			return nil, err
		}
		items = append(items, asset_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetSpaceRowsByAssetID = `-- name: ListAssetSpaceRowsByAssetID :many
SELECT id, asset_id, author, created_at, space_id
FROM asset_spaces WHERE asset_id = ?
ORDER BY id ASC
`

func (q *Queries) ListAssetSpaceRowsByAssetID(ctx context.Context, assetID int64) ([]AssetSpace, error) {
	rows, err := q.db.QueryContext(ctx, listAssetSpaceRowsByAssetID, assetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AssetSpace
	for rows.Next() {
		var i AssetSpace
		if err := rows.Scan(
			&i.ID,
			&i.AssetID,
			&i.Author,
			&i.CreatedAt,
			&i.SpaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssetStoreRowMetas = `-- name: ListAssetStoreRowMetas :many
SELECT id, sha256, size_bytes, CAST(LENGTH(inline_blob) AS INTEGER) AS inline_size, local_status, remote_status, created_at
FROM asset_store
`

type ListAssetStoreRowMetasRow struct {
	ID           string
	Sha256       string
	SizeBytes    int64
	InlineSize   int64
	LocalStatus  int64
	RemoteStatus int64
	CreatedAt    int64
}

func (q *Queries) ListAssetStoreRowMetas(ctx context.Context) ([]ListAssetStoreRowMetasRow, error) {
	rows, err := q.db.QueryContext(ctx, listAssetStoreRowMetas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetStoreRowMetasRow
	for rows.Next() {
		var i ListAssetStoreRowMetasRow
		if err := rows.Scan(
			&i.ID,
			&i.Sha256,
			&i.SizeBytes,
			&i.InlineSize,
			&i.LocalStatus,
			&i.RemoteStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuthzGrantRows = `-- name: ListAuthzGrantRows :many
SELECT id, user_id, template_id, author, created_at, data_blob FROM authz_grants
WHERE deleted_at = 0
`

type ListAuthzGrantRowsRow struct {
	ID         int64
	UserID     int64
	TemplateID int64
	Author     int64
	CreatedAt  int64
	DataBlob   []byte
}

func (q *Queries) ListAuthzGrantRows(ctx context.Context) ([]ListAuthzGrantRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuthzGrantRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthzGrantRowsRow
	for rows.Next() {
		var i ListAuthzGrantRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.TemplateID,
			&i.Author,
			&i.CreatedAt,
			&i.DataBlob,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfigSpaceRowsByConfigID = `-- name: ListConfigSpaceRowsByConfigID :many
SELECT id, config_id, author, created_at, space_id
FROM config_spaces WHERE config_id = ?
ORDER BY id ASC
`

func (q *Queries) ListConfigSpaceRowsByConfigID(ctx context.Context, configID int64) ([]ConfigSpace, error) {
	rows, err := q.db.QueryContext(ctx, listConfigSpaceRowsByConfigID, configID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfigSpace
	for rows.Next() {
		var i ConfigSpace
		if err := rows.Scan(
			&i.ID,
			&i.ConfigID,
			&i.Author,
			&i.CreatedAt,
			&i.SpaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfigVersionIDsByConfigID = `-- name: ListConfigVersionIDsByConfigID :many
SELECT id FROM config_versions WHERE config_id = ? ORDER BY version
`

func (q *Queries) ListConfigVersionIDsByConfigID(ctx context.Context, configID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listConfigVersionIDsByConfigID, configID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfigVersionRows = `-- name: ListConfigVersionRows :many
SELECT id, config_id, version, value, created_at, author
FROM config_versions
ORDER BY config_id, version
`

func (q *Queries) ListConfigVersionRows(ctx context.Context) ([]ConfigVersion, error) {
	rows, err := q.db.QueryContext(ctx, listConfigVersionRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfigVersion
	for rows.Next() {
		var i ConfigVersion
		if err := rows.Scan(
			&i.ID,
			&i.ConfigID,
			&i.Version,
			&i.Value,
			&i.CreatedAt,
			&i.Author,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listConfigVersionsByConfigID = `-- name: ListConfigVersionsByConfigID :many
SELECT id, config_id, version, value, created_at, author
FROM config_versions WHERE config_id = ?
ORDER BY version ASC
`

func (q *Queries) ListConfigVersionsByConfigID(ctx context.Context, configID int64) ([]ConfigVersion, error) {
	rows, err := q.db.QueryContext(ctx, listConfigVersionsByConfigID, configID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfigVersion
	for rows.Next() {
		var i ConfigVersion
		if err := rows.Scan(
			&i.ID,
			&i.ConfigID,
			&i.Version,
			&i.Value,
			&i.CreatedAt,
			&i.Author,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentDeploymentSpaceVersions = `-- name: ListCurrentDeploymentSpaceVersions :many
SELECT sp.id, sp.deployment_id, sp.version, sp.author, sp.created_at, sp.space_id
FROM deployment_space_versions sp
JOIN (SELECT deployment_id, MAX(version) AS version
      FROM deployment_space_versions GROUP BY deployment_id) latest
  ON latest.deployment_id = sp.deployment_id AND latest.version = sp.version
`

func (q *Queries) ListCurrentDeploymentSpaceVersions(ctx context.Context) ([]DeploymentSpaceVersion, error) {
	rows, err := q.db.QueryContext(ctx, listCurrentDeploymentSpaceVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentSpaceVersion
	for rows.Next() {
		var i DeploymentSpaceVersion
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Version,
			&i.Author,
			&i.CreatedAt,
			&i.SpaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentSpaceVersionsByDeploymentID = `-- name: ListDeploymentSpaceVersionsByDeploymentID :many
SELECT id, deployment_id, version, author, created_at, space_id
FROM deployment_space_versions
WHERE deployment_id = ?
ORDER BY version ASC
`

func (q *Queries) ListDeploymentSpaceVersionsByDeploymentID(ctx context.Context, deploymentID int64) ([]DeploymentSpaceVersion, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentSpaceVersionsByDeploymentID, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentSpaceVersion
	for rows.Next() {
		var i DeploymentSpaceVersion
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Version,
			&i.Author,
			&i.CreatedAt,
			&i.SpaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentVersions = `-- name: ListDeploymentVersions :many
SELECT id, deployment_id, version, created_at, author, spec_blob
FROM deployment_versions
WHERE deployment_id = ?
ORDER BY version ASC
`

func (q *Queries) ListDeploymentVersions(ctx context.Context, deploymentID int64) ([]DeploymentVersion, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentVersions, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentVersion
	for rows.Next() {
		var i DeploymentVersion
		if err := rows.Scan(
			&i.ID,
			&i.DeploymentID,
			&i.Version,
			&i.CreatedAt,
			&i.Author,
			&i.SpecBlob,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGlobalAccessRuleRows = `-- name: ListGlobalAccessRuleRows :many
SELECT id, name, author, created_at, data_blob FROM global_access_rules
`

func (q *Queries) ListGlobalAccessRuleRows(ctx context.Context) ([]GlobalAccessRule, error) {
	rows, err := q.db.QueryContext(ctx, listGlobalAccessRuleRows)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GlobalAccessRule
	for rows.Next() {
		var i GlobalAccessRule
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Author,
			&i.CreatedAt,
			&i.DataBlob,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestScheduledInstanceStatuses = `-- name: ListLatestScheduledInstanceStatuses :many
SELECT s.scheduled_instance_id, s.updated_at, s.deployment_id,
       s.preparer_config_version, s.preparer_artifact,
       s.preparer_inputs_status, s.preparer_image_status,
       s.runner_config_version, s.runner_pid, s.runner_artifact, s.runner_status,
       s.runner_num_restarts, s.runner_last_restart_at, s.runner_extra_blob
FROM scheduled_instance_status s
JOIN (
    SELECT scheduled_instance_id, MAX(updated_at) AS updated_at
    FROM scheduled_instance_status
    GROUP BY scheduled_instance_id
) latest ON latest.scheduled_instance_id = s.scheduled_instance_id AND latest.updated_at = s.updated_at
`

func (q *Queries) ListLatestScheduledInstanceStatuses(ctx context.Context) ([]ScheduledInstanceStatus, error) {
	rows, err := q.db.QueryContext(ctx, listLatestScheduledInstanceStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledInstanceStatus
	for rows.Next() {
		var i ScheduledInstanceStatus
		if err := rows.Scan(
			&i.ScheduledInstanceID,
			&i.UpdatedAt,
			&i.DeploymentID,
			&i.PreparerConfigVersion,
			&i.PreparerArtifact,
			&i.PreparerInputsStatus,
			&i.PreparerImageStatus,
			&i.RunnerConfigVersion,
			&i.RunnerPid,
			&i.RunnerArtifact,
			&i.RunnerStatus,
			&i.RunnerNumRestarts,
			&i.RunnerLastRestartAt,
			&i.RunnerExtraBlob,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingAgentSessionsForUser = `-- name: ListPendingAgentSessionsForUser :many
SELECT id, user_id, created_at, expires_at, token_hash, token_prefix, revoked_at, scopes,
       status, requesting_address, approval_code, approved_at
FROM agent_sessions WHERE user_id = ? AND status = 1 ORDER BY created_at DESC
`

func (q *Queries) ListPendingAgentSessionsForUser(ctx context.Context, userID int64) ([]AgentSession, error) {
	rows, err := q.db.QueryContext(ctx, listPendingAgentSessionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AgentSession
	for rows.Next() {
		var i AgentSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.TokenHash,
			&i.TokenPrefix,
			&i.RevokedAt,
			&i.Scopes,
			&i.Status,
			&i.RequestingAddress,
			&i.ApprovalCode,
			&i.ApprovedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPersonalSessionsForUser = `-- name: ListPersonalSessionsForUser :many
SELECT id, user_id, created_at, expires_at, token_hash, revoked_at,
       requesting_address, user_agent, last_active_at
FROM personal_sessions WHERE user_id = ? ORDER BY created_at DESC
`

func (q *Queries) ListPersonalSessionsForUser(ctx context.Context, userID int64) ([]PersonalSession, error) {
	rows, err := q.db.QueryContext(ctx, listPersonalSessionsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PersonalSession
	for rows.Next() {
		var i PersonalSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.TokenHash,
			&i.RevokedAt,
			&i.RequestingAddress,
			&i.UserAgent,
			&i.LastActiveAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledInstanceStatusHistoryForDeployment = `-- name: ListScheduledInstanceStatusHistoryForDeployment :many
SELECT scheduled_instance_id, updated_at, deployment_id,
       preparer_config_version, preparer_artifact,
       preparer_inputs_status, preparer_image_status,
       runner_config_version, runner_pid, runner_artifact, runner_status,
       runner_num_restarts, runner_last_restart_at, runner_extra_blob
FROM scheduled_instance_status
WHERE deployment_id = ?
ORDER BY updated_at ASC
`

func (q *Queries) ListScheduledInstanceStatusHistoryForDeployment(ctx context.Context, deploymentID int64) ([]ScheduledInstanceStatus, error) {
	rows, err := q.db.QueryContext(ctx, listScheduledInstanceStatusHistoryForDeployment, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledInstanceStatus
	for rows.Next() {
		var i ScheduledInstanceStatus
		if err := rows.Scan(
			&i.ScheduledInstanceID,
			&i.UpdatedAt,
			&i.DeploymentID,
			&i.PreparerConfigVersion,
			&i.PreparerArtifact,
			&i.PreparerInputsStatus,
			&i.PreparerImageStatus,
			&i.RunnerConfigVersion,
			&i.RunnerPid,
			&i.RunnerArtifact,
			&i.RunnerStatus,
			&i.RunnerNumRestarts,
			&i.RunnerLastRestartAt,
			&i.RunnerExtraBlob,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScheduledInstanceStatusHistorySince = `-- name: ListScheduledInstanceStatusHistorySince :many
SELECT scheduled_instance_id, updated_at, deployment_id,
       preparer_config_version, preparer_artifact,
       preparer_inputs_status, preparer_image_status,
       runner_config_version, runner_pid, runner_artifact, runner_status,
       runner_num_restarts, runner_last_restart_at, runner_extra_blob
FROM scheduled_instance_status
WHERE scheduled_instance_id = ? AND updated_at > ?
ORDER BY updated_at ASC
`

type ListScheduledInstanceStatusHistorySinceParams struct {
	ScheduledInstanceID int64
	UpdatedAt           int64
}

func (q *Queries) ListScheduledInstanceStatusHistorySince(ctx context.Context, arg ListScheduledInstanceStatusHistorySinceParams) ([]ScheduledInstanceStatus, error) {
	rows, err := q.db.QueryContext(ctx, listScheduledInstanceStatusHistorySince, arg.ScheduledInstanceID, arg.UpdatedAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScheduledInstanceStatus
	for rows.Next() {
		var i ScheduledInstanceStatus
		if err := rows.Scan(
			&i.ScheduledInstanceID,
			&i.UpdatedAt,
			&i.DeploymentID,
			&i.PreparerConfigVersion,
			&i.PreparerArtifact,
			&i.PreparerInputsStatus,
			&i.PreparerImageStatus,
			&i.RunnerConfigVersion,
			&i.RunnerPid,
			&i.RunnerArtifact,
			&i.RunnerStatus,
			&i.RunnerNumRestarts,
			&i.RunnerLastRestartAt,
			&i.RunnerExtraBlob,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretKeyslots = `-- name: ListSecretKeyslots :many

SELECT slot, smk_version, wrapped_smk, nonce, kdf_salt, created_at
FROM secret_keyslots ORDER BY slot
`

// === secret_keyslots ===
func (q *Queries) ListSecretKeyslots(ctx context.Context) ([]SecretKeyslot, error) {
	rows, err := q.db.QueryContext(ctx, listSecretKeyslots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SecretKeyslot
	for rows.Next() {
		var i SecretKeyslot
		if err := rows.Scan(
			&i.Slot,
			&i.SmkVersion,
			&i.WrappedSmk,
			&i.Nonce,
			&i.KdfSalt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretSpaceRowsBySecretID = `-- name: ListSecretSpaceRowsBySecretID :many
SELECT id, secret_id, author, created_at, space_id
FROM secret_spaces WHERE secret_id = ?
ORDER BY id ASC
`

func (q *Queries) ListSecretSpaceRowsBySecretID(ctx context.Context, secretID int64) ([]SecretSpace, error) {
	rows, err := q.db.QueryContext(ctx, listSecretSpaceRowsBySecretID, secretID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SecretSpace
	for rows.Next() {
		var i SecretSpace
		if err := rows.Scan(
			&i.ID,
			&i.SecretID,
			&i.Author,
			&i.CreatedAt,
			&i.SpaceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretVersionIDsBySecretID = `-- name: ListSecretVersionIDsBySecretID :many
SELECT id FROM secret_versions WHERE secret_id = ? ORDER BY version
`

func (q *Queries) ListSecretVersionIDsBySecretID(ctx context.Context, secretID int64) ([]int64, error) {
	rows, err := q.db.QueryContext(ctx, listSecretVersionIDsBySecretID, secretID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []int64
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretVersionMetas = `-- name: ListSecretVersionMetas :many
SELECT id, secret_id, version, created_at, author
FROM secret_versions
ORDER BY secret_id, version
`

type ListSecretVersionMetasRow struct {
	ID        int64
	SecretID  int64
	Version   int64
	CreatedAt int64
	Author    int64
}

func (q *Queries) ListSecretVersionMetas(ctx context.Context) ([]ListSecretVersionMetasRow, error) {
	rows, err := q.db.QueryContext(ctx, listSecretVersionMetas)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSecretVersionMetasRow
	for rows.Next() {
		var i ListSecretVersionMetasRow
		if err := rows.Scan(
			&i.ID,
			&i.SecretID,
			&i.Version,
			&i.CreatedAt,
			&i.Author,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSecretVersionsBySecretID = `-- name: ListSecretVersionsBySecretID :many
SELECT id, secret_id, version, created_at, author
FROM secret_versions WHERE secret_id = ?
ORDER BY version ASC
`

type ListSecretVersionsBySecretIDRow struct {
	ID        int64
	SecretID  int64
	Version   int64
	CreatedAt int64
	Author    int64
}

func (q *Queries) ListSecretVersionsBySecretID(ctx context.Context, secretID int64) ([]ListSecretVersionsBySecretIDRow, error) {
	rows, err := q.db.QueryContext(ctx, listSecretVersionsBySecretID, secretID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSecretVersionsBySecretIDRow
	for rows.Next() {
		var i ListSecretVersionsBySecretIDRow
		if err := rows.Scan(
			&i.ID,
			&i.SecretID,
			&i.Version,
			&i.CreatedAt,
			&i.Author,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpaces = `-- name: ListSpaces :many

SELECT id, name FROM spaces ORDER BY id
`

// === spaces ===
func (q *Queries) ListSpaces(ctx context.Context) ([]Space, error) {
	rows, err := q.db.QueryContext(ctx, listSpaces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Space
	for rows.Next() {
		var i Space
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnreferencedAssetStoreRows = `-- name: ListUnreferencedAssetStoreRows :many
SELECT s.id, s.sha256, s.size_bytes, CAST(LENGTH(s.inline_blob) AS INTEGER) AS inline_size, s.local_status, s.remote_status, s.created_at
FROM asset_store s
WHERE s.created_at < ? AND NOT EXISTS (SELECT 1 FROM asset_versions v WHERE v.sha256 = s.sha256)
`

type ListUnreferencedAssetStoreRowsRow struct {
	ID           string
	Sha256       string
	SizeBytes    int64
	InlineSize   int64
	LocalStatus  int64
	RemoteStatus int64
	CreatedAt    int64
}

func (q *Queries) ListUnreferencedAssetStoreRows(ctx context.Context, createdAt int64) ([]ListUnreferencedAssetStoreRowsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUnreferencedAssetStoreRows, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUnreferencedAssetStoreRowsRow
	for rows.Next() {
		var i ListUnreferencedAssetStoreRowsRow
		if err := rows.Scan(
			&i.ID,
			&i.Sha256,
			&i.SizeBytes,
			&i.InlineSize,
			&i.LocalStatus,
			&i.RemoteStatus,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, data_blob, created_at, last_login_at FROM users ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DataBlob,
			&i.CreatedAt,
			&i.LastLoginAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listValueDirectories = `-- name: ListValueDirectories :many
SELECT id, space_id, name, parent_id, created_at, author
FROM value_directories
ORDER BY space_id, parent_id, name
`

func (q *Queries) ListValueDirectories(ctx context.Context) ([]ValueDirectory, error) {
	rows, err := q.db.QueryContext(ctx, listValueDirectories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ValueDirectory
	for rows.Next() {
		var i ValueDirectory
		if err := rows.Scan(
			&i.ID,
			&i.SpaceID,
			&i.Name,
			&i.ParentID,
			&i.CreatedAt,
			&i.Author,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAssetMigrationError = `-- name: RecordAssetMigrationError :one
UPDATE asset_migrations
SET status = 'running', last_attempt_at = ?, last_error = ?
WHERE id = ?
RETURNING id, old_config_version_id, new_config_version_id, status, last_error,
          created_at, started_at, last_attempt_at, finished_at
`

type RecordAssetMigrationErrorParams struct {
	LastAttemptAt int64
	LastError     string
	ID            int64
}

func (q *Queries) RecordAssetMigrationError(ctx context.Context, arg RecordAssetMigrationErrorParams) (AssetMigration, error) {
	row := q.db.QueryRowContext(ctx, recordAssetMigrationError, arg.LastAttemptAt, arg.LastError, arg.ID)
	var i AssetMigration
	err := row.Scan(
		&i.ID,
		&i.OldConfigVersionID,
		&i.NewConfigVersionID,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.StartedAt,
		&i.LastAttemptAt,
		&i.FinishedAt,
	)
	return i, err
}

const renameAssetKey = `-- name: RenameAssetKey :exec
UPDATE assets SET key = ? WHERE id = ?
`

type RenameAssetKeyParams struct {
	Key string
	ID  int64
}

func (q *Queries) RenameAssetKey(ctx context.Context, arg RenameAssetKeyParams) error {
	_, err := q.db.ExecContext(ctx, renameAssetKey, arg.Key, arg.ID)
	return err
}

const renameConfigRow = `-- name: RenameConfigRow :exec
UPDATE configs SET name = ? WHERE id = ?
`

type RenameConfigRowParams struct {
	Name string
	ID   int64
}

func (q *Queries) RenameConfigRow(ctx context.Context, arg RenameConfigRowParams) error {
	_, err := q.db.ExecContext(ctx, renameConfigRow, arg.Name, arg.ID)
	return err
}

const renameSecretRow = `-- name: RenameSecretRow :exec
UPDATE secrets SET name = ? WHERE id = ?
`

type RenameSecretRowParams struct {
	Name string
	ID   int64
}

func (q *Queries) RenameSecretRow(ctx context.Context, arg RenameSecretRowParams) error {
	_, err := q.db.ExecContext(ctx, renameSecretRow, arg.Name, arg.ID)
	return err
}

const revokeAgentSession = `-- name: RevokeAgentSession :exec
UPDATE agent_sessions SET revoked_at = ?, status = ?
WHERE id = ? AND user_id = ? AND revoked_at = 0
`

type RevokeAgentSessionParams struct {
	RevokedAt int64
	Status    int64
	ID        string
	UserID    int64
}

func (q *Queries) RevokeAgentSession(ctx context.Context, arg RevokeAgentSessionParams) error {
	_, err := q.db.ExecContext(ctx, revokeAgentSession,
		arg.RevokedAt,
		arg.Status,
		arg.ID,
		arg.UserID,
	)
	return err
}

const revokePersonalSession = `-- name: RevokePersonalSession :execrows
UPDATE personal_sessions SET revoked_at = ?
WHERE id = ? AND user_id = ? AND revoked_at = 0
`

type RevokePersonalSessionParams struct {
	RevokedAt int64
	ID        string
	UserID    int64
}

func (q *Queries) RevokePersonalSession(ctx context.Context, arg RevokePersonalSessionParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, revokePersonalSession, arg.RevokedAt, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const setAgentSessionStatus = `-- name: SetAgentSessionStatus :exec
UPDATE agent_sessions SET status = ?, approved_at = ?, revoked_at = ?
WHERE id = ?
`

type SetAgentSessionStatusParams struct {
	Status     int64
	ApprovedAt int64
	RevokedAt  int64
	ID         string
}

func (q *Queries) SetAgentSessionStatus(ctx context.Context, arg SetAgentSessionStatusParams) error {
	_, err := q.db.ExecContext(ctx, setAgentSessionStatus,
		arg.Status,
		arg.ApprovedAt,
		arg.RevokedAt,
		arg.ID,
	)
	return err
}

const setAssetDirectoryID = `-- name: SetAssetDirectoryID :exec
UPDATE assets SET asset_directory_id = ? WHERE id = ?
`

type SetAssetDirectoryIDParams struct {
	AssetDirectoryID int64
	ID               int64
}

func (q *Queries) SetAssetDirectoryID(ctx context.Context, arg SetAssetDirectoryIDParams) error {
	_, err := q.db.ExecContext(ctx, setAssetDirectoryID, arg.AssetDirectoryID, arg.ID)
	return err
}

const setAssetDirectoryKey = `-- name: SetAssetDirectoryKey :exec
UPDATE asset_directories SET key = ? WHERE id = ?
`

type SetAssetDirectoryKeyParams struct {
	Key string
	ID  int64
}

func (q *Queries) SetAssetDirectoryKey(ctx context.Context, arg SetAssetDirectoryKeyParams) error {
	_, err := q.db.ExecContext(ctx, setAssetDirectoryKey, arg.Key, arg.ID)
	return err
}

const setAssetDirectoryParent = `-- name: SetAssetDirectoryParent :exec
UPDATE asset_directories SET parent_id = ? WHERE id = ?
`

type SetAssetDirectoryParentParams struct {
	ParentID int64
	ID       int64
}

func (q *Queries) SetAssetDirectoryParent(ctx context.Context, arg SetAssetDirectoryParentParams) error {
	_, err := q.db.ExecContext(ctx, setAssetDirectoryParent, arg.ParentID, arg.ID)
	return err
}

const setAssetStoreLocalStatus = `-- name: SetAssetStoreLocalStatus :exec
UPDATE asset_store SET local_status = ? WHERE id = ?
`

type SetAssetStoreLocalStatusParams struct {
	LocalStatus int64
	ID          string
}

func (q *Queries) SetAssetStoreLocalStatus(ctx context.Context, arg SetAssetStoreLocalStatusParams) error {
	_, err := q.db.ExecContext(ctx, setAssetStoreLocalStatus, arg.LocalStatus, arg.ID)
	return err
}

const setAssetStoreRemoteStatus = `-- name: SetAssetStoreRemoteStatus :exec
UPDATE asset_store SET remote_status = ? WHERE id = ?
`

type SetAssetStoreRemoteStatusParams struct {
	RemoteStatus int64
	ID           string
}

func (q *Queries) SetAssetStoreRemoteStatus(ctx context.Context, arg SetAssetStoreRemoteStatusParams) error {
	_, err := q.db.ExecContext(ctx, setAssetStoreRemoteStatus, arg.RemoteStatus, arg.ID)
	return err
}

const setAuthzGrantDeletedAt = `-- name: SetAuthzGrantDeletedAt :exec
UPDATE authz_grants SET deleted_at = ? WHERE id = ?
`

type SetAuthzGrantDeletedAtParams struct {
	DeletedAt int64
	ID        int64
}

func (q *Queries) SetAuthzGrantDeletedAt(ctx context.Context, arg SetAuthzGrantDeletedAtParams) error {
	_, err := q.db.ExecContext(ctx, setAuthzGrantDeletedAt, arg.DeletedAt, arg.ID)
	return err
}

const setAuthzRuleTemplateDeletedAt = `-- name: SetAuthzRuleTemplateDeletedAt :exec
UPDATE authz_rule_templates SET deleted_at = ? WHERE id = ?
`

type SetAuthzRuleTemplateDeletedAtParams struct {
	DeletedAt int64
	ID        int64
}

func (q *Queries) SetAuthzRuleTemplateDeletedAt(ctx context.Context, arg SetAuthzRuleTemplateDeletedAtParams) error {
	_, err := q.db.ExecContext(ctx, setAuthzRuleTemplateDeletedAt, arg.DeletedAt, arg.ID)
	return err
}

const setConfigValueDirectoryID = `-- name: SetConfigValueDirectoryID :exec
UPDATE configs SET value_directory_id = ? WHERE id = ?
`

type SetConfigValueDirectoryIDParams struct {
	ValueDirectoryID int64
	ID               int64
}

func (q *Queries) SetConfigValueDirectoryID(ctx context.Context, arg SetConfigValueDirectoryIDParams) error {
	_, err := q.db.ExecContext(ctx, setConfigValueDirectoryID, arg.ValueDirectoryID, arg.ID)
	return err
}

const setSecretValueDirectoryID = `-- name: SetSecretValueDirectoryID :exec
UPDATE secrets SET value_directory_id = ? WHERE id = ?
`

type SetSecretValueDirectoryIDParams struct {
	ValueDirectoryID int64
	ID               int64
}

func (q *Queries) SetSecretValueDirectoryID(ctx context.Context, arg SetSecretValueDirectoryIDParams) error {
	_, err := q.db.ExecContext(ctx, setSecretValueDirectoryID, arg.ValueDirectoryID, arg.ID)
	return err
}

const setValueDirectoryName = `-- name: SetValueDirectoryName :exec
UPDATE value_directories SET name = ? WHERE id = ?
`

type SetValueDirectoryNameParams struct {
	Name string
	ID   int64
}

func (q *Queries) SetValueDirectoryName(ctx context.Context, arg SetValueDirectoryNameParams) error {
	_, err := q.db.ExecContext(ctx, setValueDirectoryName, arg.Name, arg.ID)
	return err
}

const setValueDirectoryParent = `-- name: SetValueDirectoryParent :exec
UPDATE value_directories SET parent_id = ? WHERE id = ?
`

type SetValueDirectoryParentParams struct {
	ParentID int64
	ID       int64
}

func (q *Queries) SetValueDirectoryParent(ctx context.Context, arg SetValueDirectoryParentParams) error {
	_, err := q.db.ExecContext(ctx, setValueDirectoryParent, arg.ParentID, arg.ID)
	return err
}

const softDeleteAssetRow = `-- name: SoftDeleteAssetRow :exec
UPDATE assets SET deleted_at = ? WHERE id = ?
`

type SoftDeleteAssetRowParams struct {
	DeletedAt int64
	ID        int64
}

func (q *Queries) SoftDeleteAssetRow(ctx context.Context, arg SoftDeleteAssetRowParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteAssetRow, arg.DeletedAt, arg.ID)
	return err
}

const softDeleteConfigRow = `-- name: SoftDeleteConfigRow :exec
UPDATE configs SET deleted_at = ? WHERE id = ?
`

type SoftDeleteConfigRowParams struct {
	DeletedAt int64
	ID        int64
}

func (q *Queries) SoftDeleteConfigRow(ctx context.Context, arg SoftDeleteConfigRowParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteConfigRow, arg.DeletedAt, arg.ID)
	return err
}

const softDeleteSecretRow = `-- name: SoftDeleteSecretRow :exec
UPDATE secrets SET deleted_at = ? WHERE id = ?
`

type SoftDeleteSecretRowParams struct {
	DeletedAt int64
	ID        int64
}

func (q *Queries) SoftDeleteSecretRow(ctx context.Context, arg SoftDeleteSecretRowParams) error {
	_, err := q.db.ExecContext(ctx, softDeleteSecretRow, arg.DeletedAt, arg.ID)
	return err
}

const startAssetMigration = `-- name: StartAssetMigration :one
UPDATE asset_migrations
SET status = 'running', started_at = CASE WHEN started_at = 0 THEN ? ELSE started_at END,
    last_attempt_at = ?, last_error = ''
WHERE id = ?
RETURNING id, old_config_version_id, new_config_version_id, status, last_error,
          created_at, started_at, last_attempt_at, finished_at
`

type StartAssetMigrationParams struct {
	StartedAt     int64
	LastAttemptAt int64
	ID            int64
}

func (q *Queries) StartAssetMigration(ctx context.Context, arg StartAssetMigrationParams) (AssetMigration, error) {
	row := q.db.QueryRowContext(ctx, startAssetMigration, arg.StartedAt, arg.LastAttemptAt, arg.ID)
	var i AssetMigration
	err := row.Scan(
		&i.ID,
		&i.OldConfigVersionID,
		&i.NewConfigVersionID,
		&i.Status,
		&i.LastError,
		&i.CreatedAt,
		&i.StartedAt,
		&i.LastAttemptAt,
		&i.FinishedAt,
	)
	return i, err
}

const touchPersonalSessionActivity = `-- name: TouchPersonalSessionActivity :exec
UPDATE personal_sessions SET last_active_at = ? WHERE id = ?
`

type TouchPersonalSessionActivityParams struct {
	LastActiveAt int64
	ID           string
}

func (q *Queries) TouchPersonalSessionActivity(ctx context.Context, arg TouchPersonalSessionActivityParams) error {
	_, err := q.db.ExecContext(ctx, touchPersonalSessionActivity, arg.LastActiveAt, arg.ID)
	return err
}

const touchUserLastLogin = `-- name: TouchUserLastLogin :exec
UPDATE users SET last_login_at = ? WHERE id = ?
`

type TouchUserLastLoginParams struct {
	LastLoginAt int64
	ID          int64
}

func (q *Queries) TouchUserLastLogin(ctx context.Context, arg TouchUserLastLoginParams) error {
	_, err := q.db.ExecContext(ctx, touchUserLastLogin, arg.LastLoginAt, arg.ID)
	return err
}

const updateAuthzRuleTemplateName = `-- name: UpdateAuthzRuleTemplateName :exec
UPDATE authz_rule_templates SET name = ? WHERE id = ?
`

type UpdateAuthzRuleTemplateNameParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateAuthzRuleTemplateName(ctx context.Context, arg UpdateAuthzRuleTemplateNameParams) error {
	_, err := q.db.ExecContext(ctx, updateAuthzRuleTemplateName, arg.Name, arg.ID)
	return err
}

const updateDeploymentConfigDeletedAt = `-- name: UpdateDeploymentConfigDeletedAt :exec
UPDATE deployment_configs SET deleted_at = ? WHERE deployment_id = ?
`

type UpdateDeploymentConfigDeletedAtParams struct {
	DeletedAt    int64
	DeploymentID int64
}

func (q *Queries) UpdateDeploymentConfigDeletedAt(ctx context.Context, arg UpdateDeploymentConfigDeletedAtParams) error {
	_, err := q.db.ExecContext(ctx, updateDeploymentConfigDeletedAt, arg.DeletedAt, arg.DeploymentID)
	return err
}

const updateSecretVersionCiphertext = `-- name: UpdateSecretVersionCiphertext :exec
UPDATE secret_versions SET smk_version = ?, ciphertext = ?, nonce = ? WHERE id = ?
`

type UpdateSecretVersionCiphertextParams struct {
	SmkVersion int64
	Ciphertext []byte
	Nonce      []byte
	ID         int64
}

func (q *Queries) UpdateSecretVersionCiphertext(ctx context.Context, arg UpdateSecretVersionCiphertextParams) error {
	_, err := q.db.ExecContext(ctx, updateSecretVersionCiphertext,
		arg.SmkVersion,
		arg.Ciphertext,
		arg.Nonce,
		arg.ID,
	)
	return err
}

const updateSpace = `-- name: UpdateSpace :one
UPDATE spaces SET name = ? WHERE id = ?
RETURNING id, name
`

type UpdateSpaceParams struct {
	Name string
	ID   int64
}

func (q *Queries) UpdateSpace(ctx context.Context, arg UpdateSpaceParams) (Space, error) {
	row := q.db.QueryRowContext(ctx, updateSpace, arg.Name, arg.ID)
	var i Space
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const upsertAuthzRuleTemplateIdentity = `-- name: UpsertAuthzRuleTemplateIdentity :exec
INSERT INTO authz_rule_templates (id, name, builtin, deleted_at)
VALUES (?, ?, 1, 0)
ON CONFLICT(id) DO UPDATE SET
    name = excluded.name,
    builtin = 1,
    deleted_at = 0
`

type UpsertAuthzRuleTemplateIdentityParams struct {
	ID   int64
	Name string
}

func (q *Queries) UpsertAuthzRuleTemplateIdentity(ctx context.Context, arg UpsertAuthzRuleTemplateIdentityParams) error {
	_, err := q.db.ExecContext(ctx, upsertAuthzRuleTemplateIdentity, arg.ID, arg.Name)
	return err
}

const upsertLocalKV = `-- name: UpsertLocalKV :exec
INSERT INTO local_kv (key, value) VALUES (?, ?)
ON CONFLICT(key) DO UPDATE SET value = excluded.value
`

type UpsertLocalKVParams struct {
	Key   string
	Value []byte
}

func (q *Queries) UpsertLocalKV(ctx context.Context, arg UpsertLocalKVParams) error {
	_, err := q.db.ExecContext(ctx, upsertLocalKV, arg.Key, arg.Value)
	return err
}

const upsertPublicKey = `-- name: UpsertPublicKey :exec
INSERT INTO public_keys (kid, key_bytes) VALUES (?, ?)
ON CONFLICT(kid) DO UPDATE SET key_bytes = excluded.key_bytes
`

type UpsertPublicKeyParams struct {
	Kid      string
	KeyBytes []byte
}

func (q *Queries) UpsertPublicKey(ctx context.Context, arg UpsertPublicKeyParams) error {
	_, err := q.db.ExecContext(ctx, upsertPublicKey, arg.Kid, arg.KeyBytes)
	return err
}

const upsertSecretKeyslot = `-- name: UpsertSecretKeyslot :exec
INSERT INTO secret_keyslots (slot, smk_version, wrapped_smk, nonce, kdf_salt, created_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(slot) DO UPDATE SET
    smk_version = excluded.smk_version,
    wrapped_smk = excluded.wrapped_smk,
    nonce = excluded.nonce,
    kdf_salt = excluded.kdf_salt,
    created_at = excluded.created_at
`

type UpsertSecretKeyslotParams struct {
	Slot       string
	SmkVersion int64
	WrappedSmk []byte
	Nonce      []byte
	KdfSalt    []byte
	CreatedAt  int64
}

func (q *Queries) UpsertSecretKeyslot(ctx context.Context, arg UpsertSecretKeyslotParams) error {
	_, err := q.db.ExecContext(ctx, upsertSecretKeyslot,
		arg.Slot,
		arg.SmkVersion,
		arg.WrappedSmk,
		arg.Nonce,
		arg.KdfSalt,
		arg.CreatedAt,
	)
	return err
}

const upsertSystemSecret = `-- name: UpsertSystemSecret :exec
INSERT INTO system_secrets (name, smk_version, ciphertext, nonce, created_at, updated_at)
VALUES (?, ?, ?, ?, ?, ?)
ON CONFLICT(name) DO UPDATE SET
    smk_version = excluded.smk_version,
    ciphertext = excluded.ciphertext,
    nonce = excluded.nonce,
    updated_at = excluded.updated_at
`

type UpsertSystemSecretParams struct {
	Name       string
	SmkVersion int64
	Ciphertext []byte
	Nonce      []byte
	CreatedAt  int64
	UpdatedAt  int64
}

func (q *Queries) UpsertSystemSecret(ctx context.Context, arg UpsertSystemSecretParams) error {
	_, err := q.db.ExecContext(ctx, upsertSystemSecret,
		arg.Name,
		arg.SmkVersion,
		arg.Ciphertext,
		arg.Nonce,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (id, name, data_blob, created_at) VALUES (?, ?, ?, ?)
ON CONFLICT(id) DO UPDATE SET name = excluded.name, data_blob = excluded.data_blob
`

type UpsertUserParams struct {
	ID        int64
	Name      string
	DataBlob  []byte
	CreatedAt int64
}

// UpsertUser deliberately leaves created_at and last_login_at alone on
// conflict: the same call both creates users and rewrites their credential
// blob later.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser,
		arg.ID,
		arg.Name,
		arg.DataBlob,
		arg.CreatedAt,
	)
	return err
}
