// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlite

import (
	"database/sql"
)

type Asset struct {
	ID        int64
	Key       string
	SpaceID   int64
	CreatedAt int64
	Version   int64
	Format    string
	Location  string
	SizeBytes int64
	Blob      []byte
}

type AssetMigration struct {
	ID                 int64
	OldConfigVersionID int64
	NewConfigVersionID int64
	Status             string
	LastError          string
	CreatedAt          int64
	StartedAt          int64
	LastAttemptAt      int64
	FinishedAt         int64
}

type DeploymentConfig struct {
	DeploymentID   int64
	NodeID         int64
	SpaceID        int64
	Machine        string
	Name           string
	CreatedAt      int64
	Version        int64
	UpdatedAt      int64
	UpdatedBy      int64
	SpecBlob       []byte
	DesiredVersion string
	DesiredRunning int64
	Deleted        int64
}

type DeploymentConfigHistory struct {
	DeploymentID   int64
	Version        int64
	UpdatedAt      int64
	UpdatedBy      int64
	SpecBlob       []byte
	DesiredVersion string
	DesiredRunning int64
	Deleted        int64
}

type DeploymentStatus struct {
	DeploymentID          int64
	UpdatedAt             int64
	PreparerConfigVersion sql.NullInt64
	PreparerArtifact      sql.NullString
	PreparerStatus        sql.NullInt64
	RunnerConfigVersion   sql.NullInt64
	RunnerPid             sql.NullInt64
	RunnerArtifact        sql.NullString
	RunnerStatus          sql.NullInt64
	RunnerNumRestarts     sql.NullInt64
	RunnerLastRestartAt   sql.NullInt64
	RunnerExtraBlob       []byte
}

type DeploymentStatusHistory struct {
	DeploymentID          int64
	UpdatedAt             int64
	PreparerConfigVersion sql.NullInt64
	PreparerArtifact      sql.NullString
	PreparerStatus        sql.NullInt64
	RunnerConfigVersion   sql.NullInt64
	RunnerPid             sql.NullInt64
	RunnerArtifact        sql.NullString
	RunnerStatus          sql.NullInt64
	RunnerNumRestarts     sql.NullInt64
	RunnerLastRestartAt   sql.NullInt64
	RunnerExtraBlob       []byte
}

type EnrollmentRequest struct {
	ID                  int64
	CreatedAt           int64
	UpdatedAt           int64
	RequestingIpAddress string
	RequestingMachineID string
	OpendeployVersion   string
	Status              string
}

type LocalKv struct {
	Key   string
	Value []byte
}

type NodeRow struct {
	ID           int64
	EnrollmentID sql.NullInt64
	EnrolledAt   int64
	Name         string
	Identifier   string
	Roles        string
	Addresses    string
	WgPublicKey  string
}

type NodeStatus struct {
	ID              int64
	NodeID          int64
	LastConnectedAt int64
	IsConnected     int64
}

type OpendeployConfig struct {
	ID         int64
	UpdatedAt  int64
	ConfigBlob []byte
}

type PublicKey struct {
	Kid      string
	KeyBytes []byte
}

type Secret struct {
	ID         int64
	Name       string
	Version    int64
	SpaceID    int64
	SmkVersion int64
	Ciphertext []byte
	Nonce      []byte
	CreatedAt  int64
	UpdatedBy  int64
}

type SecretKeyslot struct {
	Slot       string
	SmkVersion int64
	WrappedSmk []byte
	Nonce      []byte
	KdfSalt    []byte
	CreatedAt  int64
}

type Space struct {
	ID   int64
	Name string
}

type SystemSecret struct {
	Name       string
	SmkVersion int64
	Ciphertext []byte
	Nonce      []byte
	CreatedAt  int64
	UpdatedAt  int64
}

type User struct {
	ID       int64
	Name     string
	DataBlob []byte
}

type UserConfig struct {
	ID        int64
	Name      string
	Version   int64
	SpaceID   int64
	Value     string
	CreatedAt int64
	UpdatedBy int64
}
