// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: queries.sql

package sqlite

import (
	"context"
	"database/sql"
)

const getDeploymentConfig = `-- name: GetDeploymentConfig :one

SELECT deployment_id, seq_no, updated_at, updated_by, spec_blob,
       desired_version, desired_running, deleted
FROM deployment_configs
WHERE deployment_id = ?
`

// === deployment_configs ===
func (q *Queries) GetDeploymentConfig(ctx context.Context, deploymentID int64) (DeploymentConfig, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentConfig, deploymentID)
	var i DeploymentConfig
	err := row.Scan(
		&i.DeploymentID,
		&i.SeqNo,
		&i.UpdatedAt,
		&i.UpdatedBy,
		&i.SpecBlob,
		&i.DesiredVersion,
		&i.DesiredRunning,
		&i.Deleted,
	)
	return i, err
}

const getDeploymentIdentifier = `-- name: GetDeploymentIdentifier :one

SELECT id, environment, machine, name, created_at
FROM deployment_identifiers
WHERE environment = ? AND machine = ? AND name = ?
`

type GetDeploymentIdentifierParams struct {
	Environment string
	Machine     string
	Name        string
}

// === deployment_identifiers ===
func (q *Queries) GetDeploymentIdentifier(ctx context.Context, arg GetDeploymentIdentifierParams) (DeploymentIdentifier, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentIdentifier, arg.Environment, arg.Machine, arg.Name)
	var i DeploymentIdentifier
	err := row.Scan(
		&i.ID,
		&i.Environment,
		&i.Machine,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getDeploymentIdentifierByID = `-- name: GetDeploymentIdentifierByID :one
SELECT id, environment, machine, name, created_at
FROM deployment_identifiers
WHERE id = ?
`

func (q *Queries) GetDeploymentIdentifierByID(ctx context.Context, id int64) (DeploymentIdentifier, error) {
	row := q.db.QueryRowContext(ctx, getDeploymentIdentifierByID, id)
	var i DeploymentIdentifier
	err := row.Scan(
		&i.ID,
		&i.Environment,
		&i.Machine,
		&i.Name,
		&i.CreatedAt,
	)
	return i, err
}

const getLatestDeploymentStatus = `-- name: GetLatestDeploymentStatus :one

SELECT deployment_id, status_seq_no, timestamp,
       preparer_seq_no, preparer_artifact, preparer_status,
       runner_seq_no, runner_pid, runner_artifact, runner_status,
       runner_num_restarts, runner_last_restart_at
FROM deployment_status_history
WHERE deployment_id = ?
ORDER BY status_seq_no DESC
LIMIT 1
`

// === deployment_status_history ===
func (q *Queries) GetLatestDeploymentStatus(ctx context.Context, deploymentID int64) (DeploymentStatusHistory, error) {
	row := q.db.QueryRowContext(ctx, getLatestDeploymentStatus, deploymentID)
	var i DeploymentStatusHistory
	err := row.Scan(
		&i.DeploymentID,
		&i.StatusSeqNo,
		&i.Timestamp,
		&i.PreparerSeqNo,
		&i.PreparerArtifact,
		&i.PreparerStatus,
		&i.RunnerSeqNo,
		&i.RunnerPid,
		&i.RunnerArtifact,
		&i.RunnerStatus,
		&i.RunnerNumRestarts,
		&i.RunnerLastRestartAt,
	)
	return i, err
}

const getLatestUserConfigVersion = `-- name: GetLatestUserConfigVersion :one

SELECT version, timestamp, updated_by, yaml_content
FROM user_config_versions
ORDER BY version DESC
LIMIT 1
`

// === user_config_versions ===
func (q *Queries) GetLatestUserConfigVersion(ctx context.Context) (UserConfigVersion, error) {
	row := q.db.QueryRowContext(ctx, getLatestUserConfigVersion)
	var i UserConfigVersion
	err := row.Scan(
		&i.Version,
		&i.Timestamp,
		&i.UpdatedBy,
		&i.YamlContent,
	)
	return i, err
}

const getPublicKey = `-- name: GetPublicKey :one

SELECT kid, key_bytes FROM public_keys WHERE kid = ?
`

// === public_keys ===
func (q *Queries) GetPublicKey(ctx context.Context, kid string) (PublicKey, error) {
	row := q.db.QueryRowContext(ctx, getPublicKey, kid)
	var i PublicKey
	err := row.Scan(&i.Kid, &i.KeyBytes)
	return i, err
}

const getUser = `-- name: GetUser :one

SELECT id, name, data_blob FROM users WHERE id = ?
`

// === users ===
func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(&i.ID, &i.Name, &i.DataBlob)
	return i, err
}

const insertDeploymentConfigHistory = `-- name: InsertDeploymentConfigHistory :exec

INSERT INTO deployment_config_history (deployment_id, seq_no, updated_at, updated_by, spec_blob, desired_version, desired_running, deleted)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDeploymentConfigHistoryParams struct {
	DeploymentID   int64
	SeqNo          int64
	UpdatedAt      int64
	UpdatedBy      int64
	SpecBlob       []byte
	DesiredVersion string
	DesiredRunning int64
	Deleted        int64
}

// === deployment_config_history ===
func (q *Queries) InsertDeploymentConfigHistory(ctx context.Context, arg InsertDeploymentConfigHistoryParams) error {
	_, err := q.db.ExecContext(ctx, insertDeploymentConfigHistory,
		arg.DeploymentID,
		arg.SeqNo,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.SpecBlob,
		arg.DesiredVersion,
		arg.DesiredRunning,
		arg.Deleted,
	)
	return err
}

const insertDeploymentStatus = `-- name: InsertDeploymentStatus :exec
INSERT INTO deployment_status_history (
    deployment_id, status_seq_no, timestamp,
    preparer_seq_no, preparer_artifact, preparer_status,
    runner_seq_no, runner_pid, runner_artifact, runner_status,
    runner_num_restarts, runner_last_restart_at
) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertDeploymentStatusParams struct {
	DeploymentID        int64
	StatusSeqNo         int64
	Timestamp           int64
	PreparerSeqNo       sql.NullInt64
	PreparerArtifact    sql.NullString
	PreparerStatus      sql.NullInt64
	RunnerSeqNo         sql.NullInt64
	RunnerPid           sql.NullInt64
	RunnerArtifact      sql.NullString
	RunnerStatus        sql.NullInt64
	RunnerNumRestarts   sql.NullInt64
	RunnerLastRestartAt sql.NullInt64
}

func (q *Queries) InsertDeploymentStatus(ctx context.Context, arg InsertDeploymentStatusParams) error {
	_, err := q.db.ExecContext(ctx, insertDeploymentStatus,
		arg.DeploymentID,
		arg.StatusSeqNo,
		arg.Timestamp,
		arg.PreparerSeqNo,
		arg.PreparerArtifact,
		arg.PreparerStatus,
		arg.RunnerSeqNo,
		arg.RunnerPid,
		arg.RunnerArtifact,
		arg.RunnerStatus,
		arg.RunnerNumRestarts,
		arg.RunnerLastRestartAt,
	)
	return err
}

const insertUserConfigVersion = `-- name: InsertUserConfigVersion :one
INSERT INTO user_config_versions (version, timestamp, updated_by, yaml_content)
VALUES (
    (SELECT COALESCE(MAX(version), 0) + 1 FROM user_config_versions),
    ?, ?, ?
)
RETURNING version, timestamp, updated_by, yaml_content
`

type InsertUserConfigVersionParams struct {
	Timestamp   int64
	UpdatedBy   int64
	YamlContent string
}

func (q *Queries) InsertUserConfigVersion(ctx context.Context, arg InsertUserConfigVersionParams) (UserConfigVersion, error) {
	row := q.db.QueryRowContext(ctx, insertUserConfigVersion, arg.Timestamp, arg.UpdatedBy, arg.YamlContent)
	var i UserConfigVersion
	err := row.Scan(
		&i.Version,
		&i.Timestamp,
		&i.UpdatedBy,
		&i.YamlContent,
	)
	return i, err
}

const listAllDeploymentConfigs = `-- name: ListAllDeploymentConfigs :many
SELECT dc.deployment_id, dc.seq_no, dc.updated_at, dc.updated_by, dc.spec_blob,
       dc.desired_version, dc.desired_running, dc.deleted,
       di.environment, di.machine, di.name
FROM deployment_configs dc
JOIN deployment_identifiers di ON di.id = dc.deployment_id
WHERE dc.deleted = 0
`

type ListAllDeploymentConfigsRow struct {
	DeploymentID   int64
	SeqNo          int64
	UpdatedAt      int64
	UpdatedBy      int64
	SpecBlob       []byte
	DesiredVersion string
	DesiredRunning int64
	Deleted        int64
	Environment    string
	Machine        string
	Name           string
}

func (q *Queries) ListAllDeploymentConfigs(ctx context.Context) ([]ListAllDeploymentConfigsRow, error) {
	rows, err := q.db.QueryContext(ctx, listAllDeploymentConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAllDeploymentConfigsRow
	for rows.Next() {
		var i ListAllDeploymentConfigsRow
		if err := rows.Scan(
			&i.DeploymentID,
			&i.SeqNo,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.SpecBlob,
			&i.DesiredVersion,
			&i.DesiredRunning,
			&i.Deleted,
			&i.Environment,
			&i.Machine,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentConfigHistory = `-- name: ListDeploymentConfigHistory :many
SELECT deployment_id, seq_no, updated_at, updated_by, spec_blob,
       desired_version, desired_running, deleted
FROM deployment_config_history
WHERE deployment_id = ?
ORDER BY seq_no ASC
`

func (q *Queries) ListDeploymentConfigHistory(ctx context.Context, deploymentID int64) ([]DeploymentConfigHistory, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentConfigHistory, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentConfigHistory
	for rows.Next() {
		var i DeploymentConfigHistory
		if err := rows.Scan(
			&i.DeploymentID,
			&i.SeqNo,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.SpecBlob,
			&i.DesiredVersion,
			&i.DesiredRunning,
			&i.Deleted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentConfigsByMachine = `-- name: ListDeploymentConfigsByMachine :many
SELECT dc.deployment_id, dc.seq_no, dc.updated_at, dc.updated_by, dc.spec_blob,
       dc.desired_version, dc.desired_running, dc.deleted,
       di.environment, di.machine, di.name
FROM deployment_configs dc
JOIN deployment_identifiers di ON di.id = dc.deployment_id
WHERE di.machine = ? AND dc.deleted = 0
`

type ListDeploymentConfigsByMachineRow struct {
	DeploymentID   int64
	SeqNo          int64
	UpdatedAt      int64
	UpdatedBy      int64
	SpecBlob       []byte
	DesiredVersion string
	DesiredRunning int64
	Deleted        int64
	Environment    string
	Machine        string
	Name           string
}

func (q *Queries) ListDeploymentConfigsByMachine(ctx context.Context, machine string) ([]ListDeploymentConfigsByMachineRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentConfigsByMachine, machine)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDeploymentConfigsByMachineRow
	for rows.Next() {
		var i ListDeploymentConfigsByMachineRow
		if err := rows.Scan(
			&i.DeploymentID,
			&i.SeqNo,
			&i.UpdatedAt,
			&i.UpdatedBy,
			&i.SpecBlob,
			&i.DesiredVersion,
			&i.DesiredRunning,
			&i.Deleted,
			&i.Environment,
			&i.Machine,
			&i.Name,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeploymentStatusHistory = `-- name: ListDeploymentStatusHistory :many
SELECT deployment_id, status_seq_no, timestamp,
       preparer_seq_no, preparer_artifact, preparer_status,
       runner_seq_no, runner_pid, runner_artifact, runner_status,
       runner_num_restarts, runner_last_restart_at
FROM deployment_status_history
WHERE deployment_id = ?
ORDER BY status_seq_no ASC
`

func (q *Queries) ListDeploymentStatusHistory(ctx context.Context, deploymentID int64) ([]DeploymentStatusHistory, error) {
	rows, err := q.db.QueryContext(ctx, listDeploymentStatusHistory, deploymentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentStatusHistory
	for rows.Next() {
		var i DeploymentStatusHistory
		if err := rows.Scan(
			&i.DeploymentID,
			&i.StatusSeqNo,
			&i.Timestamp,
			&i.PreparerSeqNo,
			&i.PreparerArtifact,
			&i.PreparerStatus,
			&i.RunnerSeqNo,
			&i.RunnerPid,
			&i.RunnerArtifact,
			&i.RunnerStatus,
			&i.RunnerNumRestarts,
			&i.RunnerLastRestartAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLatestDeploymentStatuses = `-- name: ListLatestDeploymentStatuses :many
SELECT dsh.deployment_id, dsh.status_seq_no, dsh.timestamp,
       dsh.preparer_seq_no, dsh.preparer_artifact, dsh.preparer_status,
       dsh.runner_seq_no, dsh.runner_pid, dsh.runner_artifact, dsh.runner_status,
       dsh.runner_num_restarts, dsh.runner_last_restart_at
FROM deployment_status_history dsh
INNER JOIN (
    SELECT deployment_id, MAX(status_seq_no) AS max_seq
    FROM deployment_status_history
    GROUP BY deployment_id
) latest ON dsh.deployment_id = latest.deployment_id AND dsh.status_seq_no = latest.max_seq
`

func (q *Queries) ListLatestDeploymentStatuses(ctx context.Context) ([]DeploymentStatusHistory, error) {
	rows, err := q.db.QueryContext(ctx, listLatestDeploymentStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DeploymentStatusHistory
	for rows.Next() {
		var i DeploymentStatusHistory
		if err := rows.Scan(
			&i.DeploymentID,
			&i.StatusSeqNo,
			&i.Timestamp,
			&i.PreparerSeqNo,
			&i.PreparerArtifact,
			&i.PreparerStatus,
			&i.RunnerSeqNo,
			&i.RunnerPid,
			&i.RunnerArtifact,
			&i.RunnerStatus,
			&i.RunnerNumRestarts,
			&i.RunnerLastRestartAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPublicKeys = `-- name: ListPublicKeys :many
SELECT kid, key_bytes FROM public_keys ORDER BY kid
`

func (q *Queries) ListPublicKeys(ctx context.Context) ([]PublicKey, error) {
	rows, err := q.db.QueryContext(ctx, listPublicKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PublicKey
	for rows.Next() {
		var i PublicKey
		if err := rows.Scan(&i.Kid, &i.KeyBytes); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUserConfigVersions = `-- name: ListUserConfigVersions :many
SELECT version, timestamp, updated_by, yaml_content
FROM user_config_versions
ORDER BY version DESC
`

func (q *Queries) ListUserConfigVersions(ctx context.Context) ([]UserConfigVersion, error) {
	rows, err := q.db.QueryContext(ctx, listUserConfigVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []UserConfigVersion
	for rows.Next() {
		var i UserConfigVersion
		if err := rows.Scan(
			&i.Version,
			&i.Timestamp,
			&i.UpdatedBy,
			&i.YamlContent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, data_blob FROM users ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(&i.ID, &i.Name, &i.DataBlob); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDesiredState = `-- name: UpdateDesiredState :exec
UPDATE deployment_configs
SET desired_version = ?, desired_running = ?, seq_no = seq_no + 1, updated_at = ?, updated_by = ?
WHERE deployment_id = ?
`

type UpdateDesiredStateParams struct {
	DesiredVersion string
	DesiredRunning int64
	UpdatedAt      int64
	UpdatedBy      int64
	DeploymentID   int64
}

func (q *Queries) UpdateDesiredState(ctx context.Context, arg UpdateDesiredStateParams) error {
	_, err := q.db.ExecContext(ctx, updateDesiredState,
		arg.DesiredVersion,
		arg.DesiredRunning,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.DeploymentID,
	)
	return err
}

const upsertDeploymentConfig = `-- name: UpsertDeploymentConfig :exec
INSERT INTO deployment_configs (deployment_id, seq_no, updated_at, updated_by, spec_blob, desired_version, desired_running, deleted)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(deployment_id) DO UPDATE SET
    seq_no = excluded.seq_no,
    updated_at = excluded.updated_at,
    updated_by = excluded.updated_by,
    spec_blob = excluded.spec_blob,
    desired_version = excluded.desired_version,
    desired_running = excluded.desired_running,
    deleted = excluded.deleted
`

type UpsertDeploymentConfigParams struct {
	DeploymentID   int64
	SeqNo          int64
	UpdatedAt      int64
	UpdatedBy      int64
	SpecBlob       []byte
	DesiredVersion string
	DesiredRunning int64
	Deleted        int64
}

func (q *Queries) UpsertDeploymentConfig(ctx context.Context, arg UpsertDeploymentConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertDeploymentConfig,
		arg.DeploymentID,
		arg.SeqNo,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.SpecBlob,
		arg.DesiredVersion,
		arg.DesiredRunning,
		arg.Deleted,
	)
	return err
}

const upsertDeploymentID = `-- name: UpsertDeploymentID :one
INSERT INTO deployment_identifiers (environment, machine, name, created_at)
VALUES (?, ?, ?, ?)
ON CONFLICT(environment, machine, name) DO UPDATE SET
    created_at = deployment_identifiers.created_at
RETURNING id
`

type UpsertDeploymentIDParams struct {
	Environment string
	Machine     string
	Name        string
	CreatedAt   int64
}

func (q *Queries) UpsertDeploymentID(ctx context.Context, arg UpsertDeploymentIDParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, upsertDeploymentID,
		arg.Environment,
		arg.Machine,
		arg.Name,
		arg.CreatedAt,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertPublicKey = `-- name: UpsertPublicKey :exec
INSERT INTO public_keys (kid, key_bytes) VALUES (?, ?)
ON CONFLICT(kid) DO UPDATE SET key_bytes = excluded.key_bytes
`

type UpsertPublicKeyParams struct {
	Kid      string
	KeyBytes []byte
}

func (q *Queries) UpsertPublicKey(ctx context.Context, arg UpsertPublicKeyParams) error {
	_, err := q.db.ExecContext(ctx, upsertPublicKey, arg.Kid, arg.KeyBytes)
	return err
}

const upsertUser = `-- name: UpsertUser :exec
INSERT INTO users (id, name, data_blob) VALUES (?, ?, ?)
ON CONFLICT(id) DO UPDATE SET name = excluded.name, data_blob = excluded.data_blob
`

type UpsertUserParams struct {
	ID       int64
	Name     string
	DataBlob []byte
}

func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) error {
	_, err := q.db.ExecContext(ctx, upsertUser, arg.ID, arg.Name, arg.DataBlob)
	return err
}
