// Code generated by cleanproto. DO NOT EDIT.

package apigen

func (m *Author) Encode() []byte {
	var b []byte
	b = AppendInt64Field(b, m.ID, 1)
	b = AppendStringField(b, m.Name, 2)
	return b
}

func DecodeAuthor(b []byte) (*Author, error) {
	var m Author
	var num Number
	var typ Type
	var err error
	for len(b) > 0 {
		b, num, typ, err = ConsumeTag(b)
		if err != nil {
			return nil, err
		}
		switch num {
		case 1:
			b, m.ID, err = ConsumeVarInt64(b, typ)
		case 2:
			b, m.Name, err = ConsumeString(b, typ)
		default:
			b, err = SkipFieldValue(b, num, typ)
		}
		if err != nil {
			return nil, err
		}
	}
	return &m, nil
}

func (m *Genre) Encode() []byte {
	var b []byte
	b = AppendInt64Field(b, m.ID, 1)
	b = AppendStringField(b, m.Name, 2)
	return b
}

func DecodeGenre(b []byte) (*Genre, error) {
	var m Genre
	var num Number
	var typ Type
	var err error
	for len(b) > 0 {
		b, num, typ, err = ConsumeTag(b)
		if err != nil {
			return nil, err
		}
		switch num {
		case 1:
			b, m.ID, err = ConsumeVarInt64(b, typ)
		case 2:
			b, m.Name, err = ConsumeString(b, typ)
		default:
			b, err = SkipFieldValue(b, num, typ)
		}
		if err != nil {
			return nil, err
		}
	}
	return &m, nil
}

func (m *Book) Encode() []byte {
	var b []byte
	b = AppendInt64Field(b, m.ID, 1)
	b = AppendStringField(b, m.Title, 2)
	b = AppendInt64Field(b, m.AuthorID, 3)
	b = AppendStringField(b, m.AuthorName, 4)
	b = AppendInt64Field(b, m.GenreID, 5)
	b = AppendStringField(b, m.GenreName, 6)
	b = AppendInt32Field(b, m.PublicationYear, 7)
	return b
}

func DecodeBook(b []byte) (*Book, error) {
	var m Book
	var num Number
	var typ Type
	var err error
	for len(b) > 0 {
		b, num, typ, err = ConsumeTag(b)
		if err != nil {
			return nil, err
		}
		switch num {
		case 1:
			b, m.ID, err = ConsumeVarInt64(b, typ)
		case 2:
			b, m.Title, err = ConsumeString(b, typ)
		case 3:
			b, m.AuthorID, err = ConsumeVarInt64(b, typ)
		case 4:
			b, m.AuthorName, err = ConsumeString(b, typ)
		case 5:
			b, m.GenreID, err = ConsumeVarInt64(b, typ)
		case 6:
			b, m.GenreName, err = ConsumeString(b, typ)
		case 7:
			b, m.PublicationYear, err = ConsumeVarInt32(b, typ)
		default:
			b, err = SkipFieldValue(b, num, typ)
		}
		if err != nil {
			return nil, err
		}
	}
	return &m, nil
}

func (m *LibrarySnapshot) Encode() []byte {
	var b []byte
	for _, item := range m.Authors {
		if item == nil {
			continue
		}
		b = AppendTag(b, 1, BytesType)
		b = AppendBytes(b, item.Encode())
	}
	for _, item := range m.Genres {
		if item == nil {
			continue
		}
		b = AppendTag(b, 2, BytesType)
		b = AppendBytes(b, item.Encode())
	}
	for _, item := range m.Books {
		if item == nil {
			continue
		}
		b = AppendTag(b, 3, BytesType)
		b = AppendBytes(b, item.Encode())
	}
	return b
}

func DecodeLibrarySnapshot(b []byte) (*LibrarySnapshot, error) {
	var m LibrarySnapshot
	var num Number
	var typ Type
	var err error
	var msgBytes []byte
	for len(b) > 0 {
		b, num, typ, err = ConsumeTag(b)
		if err != nil {
			return nil, err
		}
		switch num {
		case 1:
			b, msgBytes, err = ConsumeMessage(b, typ)
			if err == nil {
				var item *Author
				item, err = DecodeAuthor(msgBytes)
				if err == nil {
					m.Authors = append(m.Authors, item)
				}
			}
		case 2:
			b, msgBytes, err = ConsumeMessage(b, typ)
			if err == nil {
				var item *Genre
				item, err = DecodeGenre(msgBytes)
				if err == nil {
					m.Genres = append(m.Genres, item)
				}
			}
		case 3:
			b, msgBytes, err = ConsumeMessage(b, typ)
			if err == nil {
				var item *Book
				item, err = DecodeBook(msgBytes)
				if err == nil {
					m.Books = append(m.Books, item)
				}
			}
		default:
			b, err = SkipFieldValue(b, num, typ)
		}
		if err != nil {
			return nil, err
		}
	}
	return &m, nil
}

func (m *AddAuthorRequest) Encode() []byte {
	var b []byte
	b = AppendStringField(b, m.Name, 1)
	return b
}

func DecodeAddAuthorRequest(b []byte) (*AddAuthorRequest, error) {
	var m AddAuthorRequest
	var num Number
	var typ Type
	var err error
	for len(b) > 0 {
		b, num, typ, err = ConsumeTag(b)
		if err != nil {
			return nil, err
		}
		switch num {
		case 1:
			b, m.Name, err = ConsumeString(b, typ)
		default:
			b, err = SkipFieldValue(b, num, typ)
		}
		if err != nil {
			return nil, err
		}
	}
	return &m, nil
}

func (m *AddGenreRequest) Encode() []byte {
	var b []byte
	b = AppendStringField(b, m.Name, 1)
	return b
}

func DecodeAddGenreRequest(b []byte) (*AddGenreRequest, error) {
	var m AddGenreRequest
	var num Number
	var typ Type
	var err error
	for len(b) > 0 {
		b, num, typ, err = ConsumeTag(b)
		if err != nil {
			return nil, err
		}
		switch num {
		case 1:
			b, m.Name, err = ConsumeString(b, typ)
		default:
			b, err = SkipFieldValue(b, num, typ)
		}
		if err != nil {
			return nil, err
		}
	}
	return &m, nil
}

func (m *AddBookRequest) Encode() []byte {
	var b []byte
	b = AppendStringField(b, m.Title, 1)
	b = AppendInt64Field(b, m.AuthorID, 2)
	b = AppendInt64Field(b, m.GenreID, 3)
	b = AppendInt32Field(b, m.PublicationYear, 4)
	return b
}

func DecodeAddBookRequest(b []byte) (*AddBookRequest, error) {
	var m AddBookRequest
	var num Number
	var typ Type
	var err error
	for len(b) > 0 {
		b, num, typ, err = ConsumeTag(b)
		if err != nil {
			return nil, err
		}
		switch num {
		case 1:
			b, m.Title, err = ConsumeString(b, typ)
		case 2:
			b, m.AuthorID, err = ConsumeVarInt64(b, typ)
		case 3:
			b, m.GenreID, err = ConsumeVarInt64(b, typ)
		case 4:
			b, m.PublicationYear, err = ConsumeVarInt32(b, typ)
		default:
			b, err = SkipFieldValue(b, num, typ)
		}
		if err != nil {
			return nil, err
		}
	}
	return &m, nil
}

func (m *AccessPolicy) Encode() []byte {
	var b []byte
	b = AppendInt32Field(b, int32(m.PolicyType), 1)
	b = AppendRepeated(b, m.Scopes, AppendFieldDecorator(AppendStringField, 2))
	return b
}

func DecodeAccessPolicy(b []byte) (*AccessPolicy, error) {
	var m AccessPolicy
	var num Number
	var typ Type
	var err error
	for len(b) > 0 {
		b, num, typ, err = ConsumeTag(b)
		if err != nil {
			return nil, err
		}
		switch num {
		case 1:
			var raw int32
			b, raw, err = ConsumeVarInt32(b, typ)
			if err == nil {
				m.PolicyType = AccessPolicyType(raw)
			}
		case 2:
			var item string
			b, item, err = ConsumeRepeatedElement(b, typ, ConsumeString)
			if err == nil {
				m.Scopes = append(m.Scopes, item)
			}
		default:
			b, err = SkipFieldValue(b, num, typ)
		}
		if err != nil {
			return nil, err
		}
	}
	return &m, nil
}

func (m *ApiErr) Encode() []byte {
	var b []byte
	b = AppendInt32Field(b, m.Code, 1)
	b = AppendStringField(b, m.DisplayErr, 2)
	return b
}

func DecodeApiErr(b []byte) (*ApiErr, error) {
	var m ApiErr
	var num Number
	var typ Type
	var err error
	for len(b) > 0 {
		b, num, typ, err = ConsumeTag(b)
		if err != nil {
			return nil, err
		}
		switch num {
		case 1:
			b, m.Code, err = ConsumeVarInt32(b, typ)
		case 2:
			b, m.DisplayErr, err = ConsumeString(b, typ)
		case 3:
			b, m.InternalErr, err = ConsumeString(b, typ)
		default:
			b, err = SkipFieldValue(b, num, typ)
		}
		if err != nil {
			return nil, err
		}
	}
	return &m, nil
}
