-- Add migrations here. Statements re-run on every startup, so each must be
-- idempotent (sqlitedb.ApplyMigrations tolerates "already applied" errors:
-- duplicate column, no such column, no such table). Comments must not contain
-- semicolons — statements are split on them.
--
-- History note: every migration and Go-side startup migration up to and
-- including the v0.0.615 write log materialisation was removed on 2026-10-05,
-- once every active cluster ran v0.0.615. pq.Open refuses a database that
-- v0.0.615 never opened (one that still has a deployment_event_log table).
-- Upgrading an older database requires stepping through v0.0.614 and then
-- v0.0.615 first. Databases migrated through v0.0.541 keep a dead NULL-only
-- nodes.enrollment_id column: its UNIQUE constraint blocks ALTER TABLE DROP
-- COLUMN, and no query references it.
