-- Add migrations here. Statements re-run on every startup, so each must be
-- idempotent (sqlitedb.ApplyMigrations tolerates "already applied" errors:
-- duplicate column, no such column, no such table). Comments must not contain
-- semicolons — statements are split on them.
--
-- History note: all migrations accumulated up to v0.0.541 (2026-08-31),
-- ending with the node_versions split and the merge of enrollment_requests
-- into nodes, were removed after every active cluster had been rolled
-- forward. The spec-version column renames and the one-time deployment event
-- log migration (v0.0.549) were removed likewise after the v0.0.550 rollout,
-- the legacy deployment table drops plus the event_time rename and
-- created_time backfill (v0.0.553 Deployment/DeploymentDef split) after the
-- v0.0.553 rollout, the scheduled_instances deployment_version column
-- add with its Go-side backfill (v0.0.554) after the v0.0.555 rollout,
-- the merge of scheduled_instances + scheduled_instance_versions into
-- scheduled_instance_event_log with the legacy table drops (v0.0.559) after
-- the v0.0.559 rollout, and the event log consolidation of secrets, configs,
-- assets, network policies and nodes (v0.0.563: Go-side value-entity copies
-- in pq/migrate_values.go, node/policy SQL copies with synthetic policy
-- delete events, and the 13 legacy table drops) after the v0.0.563 rollout,
-- and the authz event log merge (v0.0.566: template/grant/global-rule copies
-- with synthetic delete events and the 4 legacy table drops) after the
-- v0.0.566 rollout, and the event-log changed-flag rebuild (v0.0.569:
-- *_changed columns plus NOT NULL carried-forward payloads on the
-- deployment/asset/secret/config logs, a Go shape migration in
-- pq/migrate_event_flags.go) after the v0.0.570 rollout.
-- Upgrading a database from before then requires stepping through a release
-- that still carried them. Databases migrated through v0.0.541 keep a dead
-- NULL-only nodes.enrollment_id column: its UNIQUE constraint blocks
-- ALTER TABLE DROP COLUMN, and no query references it.

ALTER TABLE node_statuses ADD COLUMN host_addresses TEXT NOT NULL DEFAULT '[]';
