-- Add migrations here. Statements re-run on every startup, so each must be
-- idempotent (sqlitedb.ApplyMigrations tolerates "already applied" errors:
-- duplicate column, no such column, no such table). Comments must not contain
-- semicolons — statements are split on them.
--
-- History note: all migrations accumulated up to the 2026-08 storage split
-- (deployment_status drops, preparer stage split, agent_sessions request/
-- approve columns, nodes.allowed_spaces) were removed after every active
-- cluster had been rolled forward. A second sweep (2026-08-13) removed the
-- asset_versions created_by attribution, the run-once authz cluster_admin
-- grant backfill (its local_kv marker 'migration.authz-cluster-admin-grants'
-- may linger in older databases and is harmless), and the users created_at /
-- last_login_at column adds and backfill. A third sweep (2026-08-15, after
-- every active cluster reached v0.0.426) removed the run-once authz verb
-- renumber fixup (its local_kv marker 'migration.authz-verb-renumber' may
-- linger and is harmless). A fourth sweep (2026-08-15, after every active
-- cluster reached v0.0.432) removed the deployment config identity/versions
-- split (deployment_config_history into deployment_config_versions plus the
-- deployment_configs column drops). A fifth sweep (2026-08-17, after every
-- active cluster reached v0.0.433) removed the rebuild of
-- deployment_config_versions into deployment_versions. A sixth sweep
-- (2026-08-17, after every active cluster reached v0.0.434) removed the
-- scheduled instance state split (the scheduled_instance_versions backfill
-- plus the scheduled_instances created_at/state column and index drops). A
-- seventh sweep (2026-08-17, after every active cluster reached v0.0.435 and
-- its converter had hashed away all 'legacy:' placeholder shas) removed the
-- asset content split (the asset_store backfill, the asset_versions sha256
-- column add and blob/location drops, and the background legacy-sha
-- converter). An eighth sweep (2026-08-17, after every active cluster reached
-- v0.0.437) removed the authz rule template identity/versions split (the
-- authz_rule_template_versions backfill and authz_rule_templates column
-- drops) and the authz_grants deleted column add. A ninth sweep (2026-08-17,
-- after every active cluster reached v0.0.440) removed the created_by to
-- author column renames across twelve tables and the container-level author
-- column drops on assets/secrets/configs. A tenth sweep (2026-08-17, after
-- every active cluster reached v0.0.442) removed the deleted-flag to
-- deleted_at conversion (the purge of previously soft-deleted deployment/
-- authz rows with their version and scheduled-instance history, the column
-- renames, and the deleted_at adds on assets/secrets/configs) and the
-- *_spaces space-assignment log backfills with their space_id column drops.
-- Upgrading a database from before then requires stepping through a release
-- that still carried them.
