// Code generated by cleanproto. DO NOT EDIT.

import {
  decodeAgentSession,
  decodeAgentSessionCreated,
  decodeAgentSessionList,
  decodeAgentSessionPickup,
  decodeAgentSessionRequest,
  decodeAssetDirectory,
  decodeAssetDirectoryList,
  decodeAssetList,
  decodeAssetMeta,
  decodeAssetVersion,
  decodeAuthzGlobalRuleList,
  decodeAuthzGlobalRuleRecord,
  decodeAuthzGrantList,
  decodeAuthzGrantRecord,
  decodeAuthzRuleTemplateList,
  decodeAuthzRuleTemplateRecord,
  decodeClusterConfigsResponse,
  decodeClusterNode,
  decodeClusterSecretsResponse,
  decodeClusterSettings,
  decodeConfigList,
  decodeConfigMeta,
  decodeDeploymentConfig,
  decodeDeploymentHistory,
  decodeDeploymentState,
  decodeDeploymentVersions,
  decodeEnrollmentPrimaryMsg,
  decodeEnrollmentRequestList,
  decodeEnrollmentRequestStatus,
  decodeExportedConfigBlob,
  decodeGithubCredentials,
  decodeGlobalState,
  decodeLogLineBatch,
  decodeLoginResponse,
  decodeMsgToWorker,
  decodeNodeEnrollmentInfo,
  decodeNodeStatusResponse,
  decodePrepareOutputChunk,
  decodeRecentlyDeletedDeployments,
  decodeRepoValidateResponse,
  decodeSecretList,
  decodeSecretMeta,
  decodeSecretRecoveryCodeResponse,
  decodeSecretRevealResponse,
  decodeSecretsStatusResponse,
  decodeSpace,
  decodeState,
  decodeValueDirectory,
  decodeValueDirectoryList,
  decodeWebAuthNOptionsResponse,
  encodeAgentSessionApproveRequest,
  encodeAgentSessionGetRequest,
  encodeAgentSessionRequestStartRequest,
  encodeAgentSessionRevokeRequest,
  encodeAssetCreateRequest,
  encodeAssetDeleteRequest,
  encodeAssetDirectoryCreateRequest,
  encodeAssetDirectoryDeleteRequest,
  encodeAssetDirectoryMoveRequest,
  encodeAssetDirectoryRenameRequest,
  encodeAssetGetRequest,
  encodeAssetMoveRequest,
  encodeAssetRenameRequest,
  encodeAssetSetRequest,
  encodeAuthzGlobalRuleCreateRequest,
  encodeAuthzGlobalRuleDeleteRequest,
  encodeAuthzGrantCreateRequest,
  encodeAuthzGrantDeleteRequest,
  encodeAuthzRuleTemplateCreateRequest,
  encodeAuthzRuleTemplateDeleteRequest,
  encodeAuthzRuleTemplateUpdateRequest,
  encodeClusterConfigsRequest,
  encodeClusterSecretsRequest,
  encodeClusterSettings,
  encodeConfigCreateRequest,
  encodeConfigDeleteRequest,
  encodeConfigMoveRequest,
  encodeConfigRenameRequest,
  encodeConfigSetRequest,
  encodeDeploymentCreateRequest,
  encodeDeploymentDeleteRequest,
  encodeDeploymentGetRequest,
  encodeDeploymentHistoryRequest,
  encodeDeploymentUpdateRequest,
  encodeDeploymentVersionsRequest,
  encodeEmptyRequest,
  encodeEnrollmentAcceptRequest,
  encodeEnrollmentWorkerMsg,
  encodeLogSearchRequest,
  encodeMasterPasswordRequest,
  encodeMasterPasswordSaveRequest,
  encodeMasterPasswordVerifyRequest,
  encodeMsgToMaster,
  encodeNodeAllowedSpacesRequest,
  encodeNodeRenameRequest,
  encodePrepareOutputRequest,
  encodeRecentlyDeletedDeploymentsRequest,
  encodeRepoValidateRequest,
  encodeSecretCreateRequest,
  encodeSecretDeleteRequest,
  encodeSecretGenerateRequest,
  encodeSecretMoveRequest,
  encodeSecretRenameRequest,
  encodeSecretRevealRequest,
  encodeSecretSetRequest,
  encodeSecretUnlockRequest,
  encodeSpaceDeleteRequest,
  encodeSpaceSetRequest,
  encodeValueDirectoryCreateRequest,
  encodeValueDirectoryDeleteRequest,
  encodeValueDirectoryMoveRequest,
  encodeValueDirectoryRenameRequest,
  encodeWebAuthNFinishRequest,
} from './model.js';

/** @typedef {() => Object.<string, string>} HeaderProvider */
/** @typedef {(response: Response) => Promise<never>} ErrorHandler */
/** @typedef {BodyInit|Uint8Array} RequestBody */

async function* readLengthPrefixedFrames(body, decode) {
  const reader = body.getReader();
  let buf = new Uint8Array(0);
  while (true) {
    let len = 0;
    let shift = 0;
    let headerLen = 0;
    let parsed = false;
    for (let i = 0; i < buf.length && i < 10; i++) {
      const byte = buf[i];
      len |= (byte & 0x7f) << shift;
      shift += 7;
      if ((byte & 0x80) === 0) {
        headerLen = i + 1;
        parsed = true;
        break;
      }
    }
    if (!parsed) {
      const { done, value } = await reader.read();
      if (done) {
        if (buf.length === 0) return;
        throw new Error('stream truncated mid-frame header');
      }
      const next = new Uint8Array(buf.length + value.length);
      next.set(buf, 0);
      next.set(value, buf.length);
      buf = next;
      continue;
    }
    while (buf.length < headerLen + len) {
      const { done, value } = await reader.read();
      if (done) throw new Error('stream truncated mid-frame body');
      const next = new Uint8Array(buf.length + value.length);
      next.set(buf, 0);
      next.set(value, buf.length);
      buf = next;
    }
    const payload = buf.slice(headerLen, headerLen + len);
    yield decode(payload.buffer);
    buf = buf.slice(headerLen + len);
  }
}

function writeLengthPrefixedFrames(asyncIterable, encode) {
  return new ReadableStream({
    async start(controller) {
      try {
        for await (const item of asyncIterable) {
          const payload = encode(item);
          const header = new Uint8Array(10);
          let pos = 0;
          let v = payload.length;
          while (v > 0x7f) {
            header[pos++] = (v & 0x7f) | 0x80;
            v = Math.floor(v / 128);
          }
          header[pos++] = v & 0x7f;
          const frame = new Uint8Array(pos + payload.length);
          frame.set(header.subarray(0, pos), 0);
          frame.set(payload, pos);
          controller.enqueue(frame);
        }
        controller.close();
      } catch (err) {
        controller.error(err);
      }
    },
  });
}

export class Capi {
  /**
   * @param {string} [baseURL='']
   * @param {HeaderProvider | null} [headerProvider=null]
   * @param {ErrorHandler | null} [errorHandler=null]
   */
  constructor(baseURL = '', headerProvider = null, errorHandler = null) {
    this.baseURL = baseURL;
    this.headerProvider = headerProvider == null ? () => ({}) : headerProvider;
    this.errorHandler = errorHandler == null ? async (response) => { throw new Error(`HTTP ${response.status}`); } : errorHandler;
  }

  /**
   * @param {string} path
   * @param {{ method?: string, body?: RequestBody, signal?: AbortSignal, contentType?: string, duplex?: 'half' }} [options={}]
   * @returns {Promise<Response>}
   */
  async #request(path, { method = 'GET', body, signal, contentType, duplex } = {}) {
    const headers = this.headerProvider() || {};
    headers['Accept'] = 'application/x-protobuf';
    if (body !== undefined) {
      headers['Content-Type'] = contentType || 'application/x-protobuf';
    }
    const init = { method, headers, body, signal };
    if (duplex) { init.duplex = duplex; }
    return fetch(`${this.baseURL}${path}`, init);
  }

  /**
   * @returns {Promise<void>}
   */
  async getV1Healthz() {
    const response = await this.#request("/v1/healthz", { method: 'GET' });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    await response.arrayBuffer();
  }

  /**
   * @param {EmptyRequest} payload
   * @returns {Promise<ClusterSettings>}
   */
  async postV1ClusterSettingsGet(payload) {
    const response = await this.#request("/v1/cluster-settings/get", { method: 'POST', body: encodeEmptyRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeClusterSettings(await response.arrayBuffer());
  }

  /**
   * @param {ClusterSettings} payload
   * @returns {Promise<ClusterSettings>}
   */
  async postV1ClusterSettingsUpdate(payload) {
    const response = await this.#request("/v1/cluster-settings/update", { method: 'POST', body: encodeClusterSettings(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeClusterSettings(await response.arrayBuffer());
  }

  /**
   * @param {MasterPasswordRequest} payload
   * @returns {Promise<LoginResponse>}
   */
  async postV1AuthMaster(payload) {
    const response = await this.#request("/v1/auth/master", { method: 'POST', body: encodeMasterPasswordRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeLoginResponse(await response.arrayBuffer());
  }

  /**
   * @param {MasterPasswordSaveRequest} payload
   * @returns {Promise<void>}
   */
  async postV1AuthMasterPasswordSave(payload) {
    const response = await this.#request("/v1/auth/master/password/save", { method: 'POST', body: encodeMasterPasswordSaveRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    await response.arrayBuffer();
  }

  /**
   * @param {MasterPasswordVerifyRequest} payload
   * @returns {Promise<void>}
   */
  async postV1AuthMasterPasswordVerify(payload) {
    const response = await this.#request("/v1/auth/master/password/verify", { method: 'POST', body: encodeMasterPasswordVerifyRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    await response.arrayBuffer();
  }

  /**
   * @returns {Promise<LoginResponse>}
   */
  async getV1AuthCurrentSession() {
    const response = await this.#request("/v1/auth/current/session", { method: 'GET' });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeLoginResponse(await response.arrayBuffer());
  }

  /**
   * @param {EmptyRequest} payload
   * @returns {Promise<WebAuthNOptionsResponse>}
   */
  async postV1AuthPasskeyRegisterStart(payload) {
    const response = await this.#request("/v1/auth/passkey/register/start", { method: 'POST', body: encodeEmptyRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeWebAuthNOptionsResponse(await response.arrayBuffer());
  }

  /**
   * @param {WebAuthNFinishRequest} payload
   * @returns {Promise<LoginResponse>}
   */
  async postV1AuthPasskeyRegisterFinish(payload) {
    const response = await this.#request("/v1/auth/passkey/register/finish", { method: 'POST', body: encodeWebAuthNFinishRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeLoginResponse(await response.arrayBuffer());
  }

  /**
   * @param {EmptyRequest} payload
   * @returns {Promise<WebAuthNOptionsResponse>}
   */
  async postV1AuthPasskeyLoginStart(payload) {
    const response = await this.#request("/v1/auth/passkey/login/start", { method: 'POST', body: encodeEmptyRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeWebAuthNOptionsResponse(await response.arrayBuffer());
  }

  /**
   * @param {WebAuthNFinishRequest} payload
   * @returns {Promise<LoginResponse>}
   */
  async postV1AuthPasskeyLoginFinish(payload) {
    const response = await this.#request("/v1/auth/passkey/login/finish", { method: 'POST', body: encodeWebAuthNFinishRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeLoginResponse(await response.arrayBuffer());
  }

  /**
   * @returns {Promise<void>}
   */
  async getV1AgentSessionsInstructions() {
    const response = await this.#request("/v1/agent-sessions/instructions", { method: 'GET' });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    await response.arrayBuffer();
  }

  /**
   * @param {AgentSessionRequestStartRequest} payload
   * @returns {Promise<AgentSessionRequest>}
   */
  async postV1AgentSessionsRequestStart(payload) {
    const response = await this.#request("/v1/agent-sessions/request-start", { method: 'POST', body: encodeAgentSessionRequestStartRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeAgentSessionRequest(await response.arrayBuffer());
  }

  /**
   * @param {AgentSessionGetRequest} payload
   * @returns {Promise<AgentSessionPickup>}
   */
  async postV1AgentSessionsGetSession(payload) {
    const response = await this.#request("/v1/agent-sessions/get-session", { method: 'POST', body: encodeAgentSessionGetRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeAgentSessionPickup(await response.arrayBuffer());
  }

  /**
   * @param {AgentSessionApproveRequest} payload
   * @returns {Promise<AgentSession>}
   */
  async postV1AgentSessionsApprove(payload) {
    const response = await this.#request("/v1/agent-sessions/approve", { method: 'POST', body: encodeAgentSessionApproveRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeAgentSession(await response.arrayBuffer());
  }

  /**
   * @returns {Promise<AgentSessionCreated>}
   */
  async postV1AgentSessionsCreate() {
    const response = await this.#request("/v1/agent-sessions/create", { method: 'POST' });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeAgentSessionCreated(await response.arrayBuffer());
  }

  /**
   * @param {EmptyRequest} payload
   * @returns {Promise<AgentSessionList>}
   */
  async postV1AgentSessionsList(payload) {
    const response = await this.#request("/v1/agent-sessions/list", { method: 'POST', body: encodeEmptyRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeAgentSessionList(await response.arrayBuffer());
  }

  /**
   * @param {AgentSessionRevokeRequest} payload
   * @returns {Promise<void>}
   */
  async postV1AgentSessionsRevoke(payload) {
    const response = await this.#request("/v1/agent-sessions/revoke", { method: 'POST', body: encodeAgentSessionRevokeRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    await response.arrayBuffer();
  }

  /**
   * @param {EmptyRequest} payload
   * @returns {Promise<AuthzRuleTemplateList>}
   */
  async postV1AccessRuleTemplatesList(payload) {
    const response = await this.#request("/v1/access/rule-templates/list", { method: 'POST', body: encodeEmptyRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeAuthzRuleTemplateList(await response.arrayBuffer());
  }

  /**
   * @param {AuthzRuleTemplateCreateRequest} payload
   * @returns {Promise<AuthzRuleTemplateRecord>}
   */
  async postV1AccessRuleTemplatesCreate(payload) {
    const response = await this.#request("/v1/access/rule-templates/create", { method: 'POST', body: encodeAuthzRuleTemplateCreateRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeAuthzRuleTemplateRecord(await response.arrayBuffer());
  }

  /**
   * @param {AuthzRuleTemplateUpdateRequest} payload
   * @returns {Promise<AuthzRuleTemplateRecord>}
   */
  async postV1AccessRuleTemplatesUpdate(payload) {
    const response = await this.#request("/v1/access/rule-templates/update", { method: 'POST', body: encodeAuthzRuleTemplateUpdateRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeAuthzRuleTemplateRecord(await response.arrayBuffer());
  }

  /**
   * @param {AuthzRuleTemplateDeleteRequest} payload
   * @returns {Promise<void>}
   */
  async postV1AccessRuleTemplatesDelete(payload) {
    const response = await this.#request("/v1/access/rule-templates/delete", { method: 'POST', body: encodeAuthzRuleTemplateDeleteRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    await response.arrayBuffer();
  }

  /**
   * @param {EmptyRequest} payload
   * @returns {Promise<AuthzGrantList>}
   */
  async postV1AccessGrantsList(payload) {
    const response = await this.#request("/v1/access/grants/list", { method: 'POST', body: encodeEmptyRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeAuthzGrantList(await response.arrayBuffer());
  }

  /**
   * @param {AuthzGrantCreateRequest} payload
   * @returns {Promise<AuthzGrantRecord>}
   */
  async postV1AccessGrantsCreate(payload) {
    const response = await this.#request("/v1/access/grants/create", { method: 'POST', body: encodeAuthzGrantCreateRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeAuthzGrantRecord(await response.arrayBuffer());
  }

  /**
   * @param {AuthzGrantDeleteRequest} payload
   * @returns {Promise<void>}
   */
  async postV1AccessGrantsDelete(payload) {
    const response = await this.#request("/v1/access/grants/delete", { method: 'POST', body: encodeAuthzGrantDeleteRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    await response.arrayBuffer();
  }

  /**
   * @param {EmptyRequest} payload
   * @returns {Promise<AuthzGlobalRuleList>}
   */
  async postV1AccessGlobalRulesList(payload) {
    const response = await this.#request("/v1/access/global-rules/list", { method: 'POST', body: encodeEmptyRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeAuthzGlobalRuleList(await response.arrayBuffer());
  }

  /**
   * @param {AuthzGlobalRuleCreateRequest} payload
   * @returns {Promise<AuthzGlobalRuleRecord>}
   */
  async postV1AccessGlobalRulesCreate(payload) {
    const response = await this.#request("/v1/access/global-rules/create", { method: 'POST', body: encodeAuthzGlobalRuleCreateRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeAuthzGlobalRuleRecord(await response.arrayBuffer());
  }

  /**
   * @param {AuthzGlobalRuleDeleteRequest} payload
   * @returns {Promise<void>}
   */
  async postV1AccessGlobalRulesDelete(payload) {
    const response = await this.#request("/v1/access/global-rules/delete", { method: 'POST', body: encodeAuthzGlobalRuleDeleteRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    await response.arrayBuffer();
  }

  /**
   * @returns {Promise<GlobalState>}
   */
  async getV1GlobalState() {
    const response = await this.#request("/v1/global/state", { method: 'GET' });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeGlobalState(await response.arrayBuffer());
  }

  /**
   * @param {{ signal?: AbortSignal }} [options={}]
   * @returns {AsyncIterable<State>}
   */
  postV1GlobalStateStream(options = {}) {
    const self = this;
    return {
      [Symbol.asyncIterator]: async function* () {
        const response = await self.#request("/v1/global/state-stream", { method: 'POST', signal: options.signal });
        if (!response.ok) {
          return self.errorHandler(response);
        }
        yield* readLengthPrefixedFrames(response.body, decodeState);
      },
    };
  }

  /**
   * @param {EmptyRequest} payload
   * @returns {Promise<ExportedConfigBlob>}
   */
  async postV1GlobalExportedConfig(payload) {
    const response = await this.#request("/v1/global/exported-config", { method: 'POST', body: encodeEmptyRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeExportedConfigBlob(await response.arrayBuffer());
  }

  /**
   * @param {DeploymentGetRequest} payload
   * @returns {Promise<DeploymentState>}
   */
  async postV1DeploymentsGet(payload) {
    const response = await this.#request("/v1/deployments/get", { method: 'POST', body: encodeDeploymentGetRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeDeploymentState(await response.arrayBuffer());
  }

  /**
   * @param {DeploymentCreateRequest} payload
   * @returns {Promise<DeploymentConfig>}
   */
  async postV1DeploymentsCreate(payload) {
    const response = await this.#request("/v1/deployments/create", { method: 'POST', body: encodeDeploymentCreateRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeDeploymentConfig(await response.arrayBuffer());
  }

  /**
   * @param {DeploymentUpdateRequest} payload
   * @returns {Promise<DeploymentConfig>}
   */
  async postV1DeploymentsUpdate(payload) {
    const response = await this.#request("/v1/deployments/update", { method: 'POST', body: encodeDeploymentUpdateRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeDeploymentConfig(await response.arrayBuffer());
  }

  /**
   * @param {DeploymentDeleteRequest} payload
   * @returns {Promise<void>}
   */
  async postV1DeploymentsDelete(payload) {
    const response = await this.#request("/v1/deployments/delete", { method: 'POST', body: encodeDeploymentDeleteRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    await response.arrayBuffer();
  }

  /**
   * @param {RecentlyDeletedDeploymentsRequest} payload
   * @returns {Promise<RecentlyDeletedDeployments>}
   */
  async postV1DeploymentsRecentlyDeleted(payload) {
    const response = await this.#request("/v1/deployments/recently-deleted", { method: 'POST', body: encodeRecentlyDeletedDeploymentsRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeRecentlyDeletedDeployments(await response.arrayBuffer());
  }

  /**
   * @param {DeploymentHistoryRequest} payload
   * @returns {Promise<DeploymentHistory>}
   */
  async postV1DeploymentsHistory(payload) {
    const response = await this.#request("/v1/deployments/history", { method: 'POST', body: encodeDeploymentHistoryRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeDeploymentHistory(await response.arrayBuffer());
  }

  /**
   * @param {DeploymentVersionsRequest} payload
   * @returns {Promise<DeploymentVersions>}
   */
  async postV1DeploymentsVersions(payload) {
    const response = await this.#request("/v1/deployments/versions", { method: 'POST', body: encodeDeploymentVersionsRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeDeploymentVersions(await response.arrayBuffer());
  }

  /**
   * @param {LogSearchRequest} payload
   * @param {{ signal?: AbortSignal }} [options={}]
   * @returns {AsyncIterable<LogLineBatch>}
   */
  postV1DeploymentsLogSearch(payload, options = {}) {
    const self = this;
    return {
      [Symbol.asyncIterator]: async function* () {
        const response = await self.#request("/v1/deployments/log-search", { method: 'POST', body: encodeLogSearchRequest(payload), signal: options.signal });
        if (!response.ok) {
          return self.errorHandler(response);
        }
        yield* readLengthPrefixedFrames(response.body, decodeLogLineBatch);
      },
    };
  }

  /**
   * @param {PrepareOutputRequest} payload
   * @param {{ signal?: AbortSignal }} [options={}]
   * @returns {AsyncIterable<PrepareOutputChunk>}
   */
  postV1DeploymentsPrepareOutput(payload, options = {}) {
    const self = this;
    return {
      [Symbol.asyncIterator]: async function* () {
        const response = await self.#request("/v1/deployments/prepare-output", { method: 'POST', body: encodePrepareOutputRequest(payload), signal: options.signal });
        if (!response.ok) {
          return self.errorHandler(response);
        }
        yield* readLengthPrefixedFrames(response.body, decodePrepareOutputChunk);
      },
    };
  }

  /**
   * @param {RepoValidateRequest} payload
   * @returns {Promise<RepoValidateResponse>}
   */
  async postV1ReposValidate(payload) {
    const response = await this.#request("/v1/repos/validate", { method: 'POST', body: encodeRepoValidateRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeRepoValidateResponse(await response.arrayBuffer());
  }

  /**
   * @returns {Promise<NodeStatusResponse>}
   */
  async getV1NodesStatus() {
    const response = await this.#request("/v1/nodes/status", { method: 'GET' });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeNodeStatusResponse(await response.arrayBuffer());
  }

  /**
   * @param {NodeRenameRequest} payload
   * @returns {Promise<ClusterNode>}
   */
  async postV1NodesRename(payload) {
    const response = await this.#request("/v1/nodes/rename", { method: 'POST', body: encodeNodeRenameRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeClusterNode(await response.arrayBuffer());
  }

  /**
   * @param {NodeAllowedSpacesRequest} payload
   * @returns {Promise<ClusterNode>}
   */
  async postV1NodesAllowedSpaces(payload) {
    const response = await this.#request("/v1/nodes/allowed-spaces", { method: 'POST', body: encodeNodeAllowedSpacesRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeClusterNode(await response.arrayBuffer());
  }

  /**
   * @returns {Promise<NodeEnrollmentInfo>}
   */
  async getV1NodesEnrollmentsInfo() {
    const response = await this.#request("/v1/nodes/enrollments/info", { method: 'GET' });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeNodeEnrollmentInfo(await response.arrayBuffer());
  }

  /**
   * @returns {Promise<EnrollmentRequestList>}
   */
  async postV1NodesEnrollmentsList() {
    const response = await this.#request("/v1/nodes/enrollments/list", { method: 'POST' });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeEnrollmentRequestList(await response.arrayBuffer());
  }

  /**
   * @param {EnrollmentAcceptRequest} payload
   * @returns {Promise<EnrollmentRequestStatus>}
   */
  async postV1NodesEnrollmentsAccept(payload) {
    const response = await this.#request("/v1/nodes/enrollments/accept", { method: 'POST', body: encodeEnrollmentAcceptRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeEnrollmentRequestStatus(await response.arrayBuffer());
  }

  /**
   * @param {SpaceSetRequest} payload
   * @returns {Promise<Space>}
   */
  async postV1SpacesCreate(payload) {
    const response = await this.#request("/v1/spaces/create", { method: 'POST', body: encodeSpaceSetRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeSpace(await response.arrayBuffer());
  }

  /**
   * @param {SpaceSetRequest} payload
   * @returns {Promise<Space>}
   */
  async postV1SpacesUpdate(payload) {
    const response = await this.#request("/v1/spaces/update", { method: 'POST', body: encodeSpaceSetRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeSpace(await response.arrayBuffer());
  }

  /**
   * @param {SpaceDeleteRequest} payload
   * @returns {Promise<void>}
   */
  async postV1SpacesDelete(payload) {
    const response = await this.#request("/v1/spaces/delete", { method: 'POST', body: encodeSpaceDeleteRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    await response.arrayBuffer();
  }

  /**
   * @param {EmptyRequest} payload
   * @returns {Promise<SecretList>}
   */
  async postV1SecretsList(payload) {
    const response = await this.#request("/v1/secrets/list", { method: 'POST', body: encodeEmptyRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeSecretList(await response.arrayBuffer());
  }

  /**
   * @param {SecretCreateRequest} payload
   * @returns {Promise<SecretMeta>}
   */
  async postV1SecretsCreate(payload) {
    const response = await this.#request("/v1/secrets/create", { method: 'POST', body: encodeSecretCreateRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeSecretMeta(await response.arrayBuffer());
  }

  /**
   * @param {SecretSetRequest} payload
   * @returns {Promise<SecretMeta>}
   */
  async postV1SecretsSet(payload) {
    const response = await this.#request("/v1/secrets/set", { method: 'POST', body: encodeSecretSetRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeSecretMeta(await response.arrayBuffer());
  }

  /**
   * @param {SecretGenerateRequest} payload
   * @returns {Promise<SecretMeta>}
   */
  async postV1SecretsGenerate(payload) {
    const response = await this.#request("/v1/secrets/generate", { method: 'POST', body: encodeSecretGenerateRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeSecretMeta(await response.arrayBuffer());
  }

  /**
   * @param {SecretRenameRequest} payload
   * @returns {Promise<SecretMeta>}
   */
  async postV1SecretsRename(payload) {
    const response = await this.#request("/v1/secrets/rename", { method: 'POST', body: encodeSecretRenameRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeSecretMeta(await response.arrayBuffer());
  }

  /**
   * @param {SecretMoveRequest} payload
   * @returns {Promise<SecretMeta>}
   */
  async postV1SecretsMove(payload) {
    const response = await this.#request("/v1/secrets/move", { method: 'POST', body: encodeSecretMoveRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeSecretMeta(await response.arrayBuffer());
  }

  /**
   * @param {SecretRevealRequest} payload
   * @returns {Promise<SecretRevealResponse>}
   */
  async postV1SecretsReveal(payload) {
    const response = await this.#request("/v1/secrets/reveal", { method: 'POST', body: encodeSecretRevealRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeSecretRevealResponse(await response.arrayBuffer());
  }

  /**
   * @param {SecretDeleteRequest} payload
   * @returns {Promise<void>}
   */
  async postV1SecretsDelete(payload) {
    const response = await this.#request("/v1/secrets/delete", { method: 'POST', body: encodeSecretDeleteRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    await response.arrayBuffer();
  }

  /**
   * @param {EmptyRequest} payload
   * @returns {Promise<SecretsStatusResponse>}
   */
  async postV1SecretsStatus(payload) {
    const response = await this.#request("/v1/secrets/status", { method: 'POST', body: encodeEmptyRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeSecretsStatusResponse(await response.arrayBuffer());
  }

  /**
   * @param {EmptyRequest} payload
   * @returns {Promise<SecretRecoveryCodeResponse>}
   */
  async postV1SecretsRotateRecoveryCode(payload) {
    const response = await this.#request("/v1/secrets/rotate-recovery-code", { method: 'POST', body: encodeEmptyRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeSecretRecoveryCodeResponse(await response.arrayBuffer());
  }

  /**
   * @param {SecretUnlockRequest} payload
   * @returns {Promise<SecretsStatusResponse>}
   */
  async postV1SecretsUnlock(payload) {
    const response = await this.#request("/v1/secrets/unlock", { method: 'POST', body: encodeSecretUnlockRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeSecretsStatusResponse(await response.arrayBuffer());
  }

  /**
   * @param {EmptyRequest} payload
   * @returns {Promise<ConfigList>}
   */
  async postV1ConfigsList(payload) {
    const response = await this.#request("/v1/configs/list", { method: 'POST', body: encodeEmptyRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeConfigList(await response.arrayBuffer());
  }

  /**
   * @param {ConfigCreateRequest} payload
   * @returns {Promise<ConfigMeta>}
   */
  async postV1ConfigsCreate(payload) {
    const response = await this.#request("/v1/configs/create", { method: 'POST', body: encodeConfigCreateRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeConfigMeta(await response.arrayBuffer());
  }

  /**
   * @param {ConfigSetRequest} payload
   * @returns {Promise<ConfigMeta>}
   */
  async postV1ConfigsSet(payload) {
    const response = await this.#request("/v1/configs/set", { method: 'POST', body: encodeConfigSetRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeConfigMeta(await response.arrayBuffer());
  }

  /**
   * @param {ConfigRenameRequest} payload
   * @returns {Promise<ConfigMeta>}
   */
  async postV1ConfigsRename(payload) {
    const response = await this.#request("/v1/configs/rename", { method: 'POST', body: encodeConfigRenameRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeConfigMeta(await response.arrayBuffer());
  }

  /**
   * @param {ConfigDeleteRequest} payload
   * @returns {Promise<void>}
   */
  async postV1ConfigsDelete(payload) {
    const response = await this.#request("/v1/configs/delete", { method: 'POST', body: encodeConfigDeleteRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    await response.arrayBuffer();
  }

  /**
   * @param {ConfigMoveRequest} payload
   * @returns {Promise<ConfigMeta>}
   */
  async postV1ConfigsMove(payload) {
    const response = await this.#request("/v1/configs/move", { method: 'POST', body: encodeConfigMoveRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeConfigMeta(await response.arrayBuffer());
  }

  /**
   * @param {EmptyRequest} payload
   * @returns {Promise<ValueDirectoryList>}
   */
  async postV1ValueDirectoriesList(payload) {
    const response = await this.#request("/v1/value-directories/list", { method: 'POST', body: encodeEmptyRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeValueDirectoryList(await response.arrayBuffer());
  }

  /**
   * @param {ValueDirectoryCreateRequest} payload
   * @returns {Promise<ValueDirectory>}
   */
  async postV1ValueDirectoriesCreate(payload) {
    const response = await this.#request("/v1/value-directories/create", { method: 'POST', body: encodeValueDirectoryCreateRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeValueDirectory(await response.arrayBuffer());
  }

  /**
   * @param {ValueDirectoryMoveRequest} payload
   * @returns {Promise<ValueDirectory>}
   */
  async postV1ValueDirectoriesMove(payload) {
    const response = await this.#request("/v1/value-directories/move", { method: 'POST', body: encodeValueDirectoryMoveRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeValueDirectory(await response.arrayBuffer());
  }

  /**
   * @param {ValueDirectoryRenameRequest} payload
   * @returns {Promise<ValueDirectory>}
   */
  async postV1ValueDirectoriesRename(payload) {
    const response = await this.#request("/v1/value-directories/rename", { method: 'POST', body: encodeValueDirectoryRenameRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeValueDirectory(await response.arrayBuffer());
  }

  /**
   * @param {ValueDirectoryDeleteRequest} payload
   * @returns {Promise<void>}
   */
  async postV1ValueDirectoriesDelete(payload) {
    const response = await this.#request("/v1/value-directories/delete", { method: 'POST', body: encodeValueDirectoryDeleteRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    await response.arrayBuffer();
  }

  /**
   * @param {EmptyRequest} payload
   * @returns {Promise<AssetList>}
   */
  async postV1AssetsList(payload) {
    const response = await this.#request("/v1/assets/list", { method: 'POST', body: encodeEmptyRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeAssetList(await response.arrayBuffer());
  }

  /**
   * @param {AssetGetRequest} payload
   * @returns {Promise<AssetVersion>}
   */
  async postV1AssetsGet(payload) {
    const response = await this.#request("/v1/assets/get", { method: 'POST', body: encodeAssetGetRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeAssetVersion(await response.arrayBuffer());
  }

  /**
   * @param {AssetCreateRequest} payload
   * @returns {Promise<AssetVersion>}
   */
  async postV1AssetsCreate(payload) {
    const response = await this.#request("/v1/assets/create", { method: 'POST', body: encodeAssetCreateRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeAssetVersion(await response.arrayBuffer());
  }

  /**
   * @param {AssetSetRequest} payload
   * @returns {Promise<AssetVersion>}
   */
  async postV1AssetsSet(payload) {
    const response = await this.#request("/v1/assets/set", { method: 'POST', body: encodeAssetSetRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeAssetVersion(await response.arrayBuffer());
  }

  /**
   * @returns {Promise<AssetVersion>}
   */
  async postV1AssetsUpload() {
    const response = await this.#request("/v1/assets/upload", { method: 'POST' });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeAssetVersion(await response.arrayBuffer());
  }

  /**
   * @param {AssetRenameRequest} payload
   * @returns {Promise<AssetMeta>}
   */
  async postV1AssetsRename(payload) {
    const response = await this.#request("/v1/assets/rename", { method: 'POST', body: encodeAssetRenameRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeAssetMeta(await response.arrayBuffer());
  }

  /**
   * @param {AssetDeleteRequest} payload
   * @returns {Promise<void>}
   */
  async postV1AssetsDelete(payload) {
    const response = await this.#request("/v1/assets/delete", { method: 'POST', body: encodeAssetDeleteRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    await response.arrayBuffer();
  }

  /**
   * @param {AssetMoveRequest} payload
   * @returns {Promise<AssetMeta>}
   */
  async postV1AssetsMove(payload) {
    const response = await this.#request("/v1/assets/move", { method: 'POST', body: encodeAssetMoveRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeAssetMeta(await response.arrayBuffer());
  }

  /**
   * @param {EmptyRequest} payload
   * @returns {Promise<AssetDirectoryList>}
   */
  async postV1AssetDirectoriesList(payload) {
    const response = await this.#request("/v1/asset-directories/list", { method: 'POST', body: encodeEmptyRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeAssetDirectoryList(await response.arrayBuffer());
  }

  /**
   * @param {AssetDirectoryCreateRequest} payload
   * @returns {Promise<AssetDirectory>}
   */
  async postV1AssetDirectoriesCreate(payload) {
    const response = await this.#request("/v1/asset-directories/create", { method: 'POST', body: encodeAssetDirectoryCreateRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeAssetDirectory(await response.arrayBuffer());
  }

  /**
   * @param {AssetDirectoryMoveRequest} payload
   * @returns {Promise<AssetDirectory>}
   */
  async postV1AssetDirectoriesMove(payload) {
    const response = await this.#request("/v1/asset-directories/move", { method: 'POST', body: encodeAssetDirectoryMoveRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeAssetDirectory(await response.arrayBuffer());
  }

  /**
   * @param {AssetDirectoryRenameRequest} payload
   * @returns {Promise<AssetDirectory>}
   */
  async postV1AssetDirectoriesRename(payload) {
    const response = await this.#request("/v1/asset-directories/rename", { method: 'POST', body: encodeAssetDirectoryRenameRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeAssetDirectory(await response.arrayBuffer());
  }

  /**
   * @param {AssetDirectoryDeleteRequest} payload
   * @returns {Promise<void>}
   */
  async postV1AssetDirectoriesDelete(payload) {
    const response = await this.#request("/v1/asset-directories/delete", { method: 'POST', body: encodeAssetDirectoryDeleteRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    await response.arrayBuffer();
  }

  /**
   * @returns {Promise<GithubCredentials>}
   */
  async getV1ClusterGithubCredentials() {
    const response = await this.#request("/v1/cluster/github-credentials", { method: 'GET' });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeGithubCredentials(await response.arrayBuffer());
  }

  /**
   * @returns {Promise<void>}
   */
  async getV1ClusterAsset() {
    const response = await this.#request("/v1/cluster/asset", { method: 'GET' });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    await response.arrayBuffer();
  }

  /**
   * @param {ClusterSecretsRequest} payload
   * @returns {Promise<ClusterSecretsResponse>}
   */
  async getV1ClusterSecrets(payload) {
    const response = await this.#request("/v1/cluster/secrets", { method: 'GET', body: encodeClusterSecretsRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeClusterSecretsResponse(await response.arrayBuffer());
  }

  /**
   * @param {ClusterConfigsRequest} payload
   * @returns {Promise<ClusterConfigsResponse>}
   */
  async getV1ClusterConfigs(payload) {
    const response = await this.#request("/v1/cluster/configs", { method: 'GET', body: encodeClusterConfigsRequest(payload) });
    if (!response.ok) {
      return this.errorHandler(response);
    }
    return decodeClusterConfigsResponse(await response.arrayBuffer());
  }

  /**
   * @param {AsyncIterable<MsgToMaster>} stream
   * @param {{ signal?: AbortSignal }} [options={}]
   * @returns {AsyncIterable<MsgToWorker>}
   */
  postV1ClusterConnect(stream, options = {}) {
    const self = this;
    return {
      [Symbol.asyncIterator]: async function* () {
        const response = await self.#request('/v1/cluster/connect', { method: 'POST', body: writeLengthPrefixedFrames(stream, encodeMsgToMaster), signal: options.signal, contentType: 'application/protobuf-stream', duplex: 'half' });
        if (!response.ok) {
          return self.errorHandler(response);
        }
        yield* readLengthPrefixedFrames(response.body, decodeMsgToWorker);
      },
    };
  }

  /**
   * @param {AsyncIterable<EnrollmentWorkerMsg>} stream
   * @param {{ signal?: AbortSignal }} [options={}]
   * @returns {AsyncIterable<EnrollmentPrimaryMsg>}
   */
  postV1EnrollmentRequest(stream, options = {}) {
    const self = this;
    return {
      [Symbol.asyncIterator]: async function* () {
        const response = await self.#request('/v1/enrollment/request', { method: 'POST', body: writeLengthPrefixedFrames(stream, encodeEnrollmentWorkerMsg), signal: options.signal, contentType: 'application/protobuf-stream', duplex: 'half' });
        if (!response.ok) {
          return self.errorHandler(response);
        }
        yield* readLengthPrefixedFrames(response.body, decodeEnrollmentPrimaryMsg);
      },
    };
  }

}
