#!/usr/bin/env bash
set -euo pipefail

mkdir -p /srv/git /srv/releases

create_dummy_repo() {
  local owner_repo=$1
  local work
  work=$(mktemp -d)
  git init "$work" >/dev/null
  git -C "$work" config user.email localrepo@example.invalid
  git -C "$work" config user.name "OpenDeploy Local Repo"
  mkdir -p "$work/testexamples/nixdockerbuild1" "$work/testexamples/nixdockercrasher" "$work/testexamples/largeassetverify" "$work/testexamples/postgresclient"
  cat >"$work/README.md" <<EOF
# ${owner_repo}

Local test placeholder repository generated by testing/localrepocontainer.
EOF
  cat >"$work/flake.nix" <<'EOF'
{
  description = "OpenDeploy local placeholder flake";
  outputs = { self }: { };
}
EOF
  cp "$work/flake.nix" "$work/testexamples/nixdockerbuild1/flake.nix"
  cp "$work/flake.nix" "$work/testexamples/nixdockercrasher/flake.nix"
  cp "$work/flake.nix" "$work/testexamples/largeassetverify/flake.nix"
  cp "$work/flake.nix" "$work/testexamples/postgresclient/flake.nix"
  git -C "$work" add .
  git -C "$work" commit -m "local placeholder" >/dev/null
  git clone --mirror "$work" "/srv/git/${owner_repo}.git" >/dev/null
  rm -rf "$work"
}

mirror_repo() {
  local owner_repo=$1
  local url=$2
  local dst="/srv/git/${owner_repo}.git"
  mkdir -p "$(dirname "$dst")"
  if git clone --mirror "$url" "$dst"; then
    git -C "$dst" update-server-info
    return
  fi
  echo "warning: cloning ${url} failed; creating placeholder ${owner_repo}" >&2
  rm -rf "$dst"
  create_dummy_repo "$owner_repo"
  git -C "$dst" update-server-info
}

download_file() {
  local url=$1
  local dst=$2
  mkdir -p "$(dirname "$dst")"
  if [[ -s "$dst" ]]; then
    return
  fi
  curl -fL --retry 3 --retry-delay 2 "$url" -o "$dst"
}

mirror_repo jptrs93/opsagent https://github.com/jptrs93/opsagent.git
mirror_repo jptrs93/jnotes https://github.com/jptrs93/jnotes.git

for version in ${OPD_RELEASES}; do
  release_dir="/srv/releases/jptrs93/opsagent/${version}"
  mkdir -p "$release_dir"
  for arch in ${OPD_ARCHES}; do
    download_file "https://github.com/jptrs93/opsagent/releases/download/${version}/opendeploy-linux-${arch}" \
      "${release_dir}/opendeploy-linux-${arch}"
  done
  download_file "https://github.com/jptrs93/opsagent/releases/download/${version}/sha256sums.txt" \
    "${release_dir}/sha256sums.txt"
done
printf '%s\n' "${OPD_LATEST_RELEASE}" > /srv/releases/jptrs93/opsagent/latest

for arch in ${OPD_ARCHES}; do
  download_file "https://github.com/containerd/containerd/releases/download/v${CONTAINERD_VERSION}/containerd-${CONTAINERD_VERSION}-linux-${arch}.tar.gz" \
    "/srv/releases/containerd/containerd/v${CONTAINERD_VERSION}/containerd-${CONTAINERD_VERSION}-linux-${arch}.tar.gz"
  download_file "https://github.com/opencontainers/runc/releases/download/v${RUNC_VERSION}/runc.${arch}" \
    "/srv/releases/opencontainers/runc/v${RUNC_VERSION}/runc.${arch}"
done
