-- Add migrations here. Statements re-run on every startup, so each must be
-- idempotent (sqlitedb.ApplyMigrations tolerates "already applied" errors:
-- duplicate column, no such column, no such table). Comments must not contain
-- semicolons — statements are split on them.
--
-- History note: all migrations and cache conversions up to the v0.0.616 data
-- model conversion were removed on 2026-10-06. sq.Open refuses a database
-- without the current format_version key and names v0.0.616 as the release
-- to start first.
