syntax = "proto3";

package opsagent.v1;

import "api-contract/options.proto";
import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";

option go_package = "github.com/jptrs93/opsagent/backend/apigen";

message AuthzGrantTemplateList {
  repeated AuthzGrantTemplate items = 1;
}

message AuthzGrantTemplateCreateRequest {
  string name = 1;
  AuthzGrantTemplateSpec spec = 2 [(cp.go_value) = true];
}

message AuthzGrantTemplateUpdateRequest {
  uint64 id = 1 [(cp.js_type) = "number"];
  string name = 2;
  AuthzGrantTemplateSpec spec = 3 [(cp.go_value) = true];
}

message AuthzGrantTemplateDeleteRequest {
  uint64 id = 1 [(cp.js_type) = "number"];
}

message AuthzGrantCreateRequest {
  uint64 user_id = 1 [(cp.js_type) = "number"];
  AuthzGrantSource grant = 2 [(cp.go_value) = true];
}

message AuthzGrantDeleteRequest {
  uint64 user_id = 1 [(cp.js_type) = "number"];
  uint64 id = 2 [(cp.js_type) = "number"];
}

message AuthzGlobalRuleList {
  repeated AuthzGlobalRule items = 1;
}

message AuthzGlobalRuleCreateRequest {
  string name = 1;
  AuthzRule rule = 2 [(cp.go_value) = true];
}

message AuthzGlobalRuleDeleteRequest {
  uint64 id = 1 [(cp.js_type) = "number"];
}
