// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package logdb

type LogFile struct {
	ID           int64
	DeploymentID int64
	Day          int64
	Level        int64
	Node         int64
	Seq          int64
	MinTime      int64
	MaxTime      int64
	RowCount     int64
	ByteSize     int64
	CreatedAt    int64
}

type LogStreamCommitMarker struct {
	DeploymentID int64
	Day          int64
	Bucket       int64
	RecordTime   int64
	ByteOffset   int64
	UpdatedAt    int64
	File         string
}
