// Code generated by cleanproto. DO NOT EDIT.

package apigen

import (
	"bytes"
	"context"
	"fmt"
	"io"
	"iter"
	"net/http"
	"strings"
)

func defaultGoCapiErrorHandler(_ context.Context, resp *http.Response) error {
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return err
	}
	if len(body) > 0 {
		apiErr, err := DecodeApiErr(body)
		if err == nil && apiErr != nil {
			return apiErr
		}
	}
	return fmt.Errorf("HTTP %d", resp.StatusCode)
}

func writeGoCapiClientStream[T Encodable](items iter.Seq2[T, error]) io.Reader {
	pr, pw := io.Pipe()
	go func() {
		for item, err := range items {
			if err != nil {
				_ = pw.CloseWithError(err)
				return
			}
			if err := WriteStreamFrame(pw, item.Encode()); err != nil {
				_ = pw.CloseWithError(err)
				return
			}
		}
		_ = pw.Close()
	}()
	return pr
}

type OpsagentHttpV1Capi struct {
	BaseURL        string
	HTTPClient     *http.Client
	HeaderProvider func(context.Context) http.Header
	ErrorHandler   func(context.Context, *http.Response) error
}

type OpsagentHttpV1CapiOption func(*OpsagentHttpV1Capi)

func NewOpsagentHttpV1Capi(baseURL string, opts ...OpsagentHttpV1CapiOption) *OpsagentHttpV1Capi {
	c := &OpsagentHttpV1Capi{
		BaseURL:      strings.TrimRight(baseURL, "/"),
		HTTPClient:   http.DefaultClient,
		ErrorHandler: defaultGoCapiErrorHandler,
	}
	for _, opt := range opts {
		opt(c)
	}
	return c
}

func WithOpsagentHttpV1CapiHTTPClient(httpClient *http.Client) OpsagentHttpV1CapiOption {
	return func(c *OpsagentHttpV1Capi) {
		if httpClient != nil {
			c.HTTPClient = httpClient
		}
	}
}

func WithOpsagentHttpV1CapiHeaderProvider(provider func(context.Context) http.Header) OpsagentHttpV1CapiOption {
	return func(c *OpsagentHttpV1Capi) {
		c.HeaderProvider = provider
	}
}

func WithOpsagentHttpV1CapiErrorHandler(handler func(context.Context, *http.Response) error) OpsagentHttpV1CapiOption {
	return func(c *OpsagentHttpV1Capi) {
		if handler != nil {
			c.ErrorHandler = handler
		}
	}
}

func (c *OpsagentHttpV1Capi) do(ctx context.Context, method string, path string, body io.Reader, contentType string, accept string) (*http.Response, error) {
	httpClient := c.HTTPClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	req, err := http.NewRequestWithContext(ctx, method, c.BaseURL+path, body)
	if err != nil {
		return nil, err
	}
	if accept == "" {
		accept = "application/protobuf"
	}
	req.Header.Set("Accept", accept)
	if body != nil {
		req.Header.Set("Content-Type", contentType)
	}
	if c.HeaderProvider != nil {
		for key, values := range c.HeaderProvider(ctx) {
			for _, value := range values {
				req.Header.Add(key, value)
			}
		}
	}
	return httpClient.Do(req)
}

func (c *OpsagentHttpV1Capi) Get(ctx context.Context) error {
	resp, err := c.do(ctx, "GET", "/", nil, "application/protobuf", "application/protobuf")
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return c.ErrorHandler(ctx, resp)
	}
	return nil
}

func (c *OpsagentHttpV1Capi) GetV1Healthz(ctx context.Context) error {
	resp, err := c.do(ctx, "GET", "/v1/healthz", nil, "application/protobuf", "application/protobuf")
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return c.ErrorHandler(ctx, resp)
	}
	return nil
}

func (c *OpsagentHttpV1Capi) PostV1AuthMaster(ctx context.Context, req *MasterPasswordRequest) (*LoginResponse, error) {
	if req == nil {
		return nil, fmt.Errorf("PostV1AuthMaster request is nil")
	}
	resp, err := c.do(ctx, "POST", "/v1/auth/master", bytes.NewReader(req.Encode()), "application/protobuf", "application/protobuf")
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, c.ErrorHandler(ctx, resp)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	return DecodeLoginResponse(body)
}

func (c *OpsagentHttpV1Capi) GetV1AuthCurrentSession(ctx context.Context) (*LoginResponse, error) {
	resp, err := c.do(ctx, "GET", "/v1/auth/current/session", nil, "application/protobuf", "application/protobuf")
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, c.ErrorHandler(ctx, resp)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	return DecodeLoginResponse(body)
}

func (c *OpsagentHttpV1Capi) PostV1AuthPasskeyRegisterStart(ctx context.Context, req *EmptyRequest) (*WebAuthNOptionsResponse, error) {
	if req == nil {
		return nil, fmt.Errorf("PostV1AuthPasskeyRegisterStart request is nil")
	}
	resp, err := c.do(ctx, "POST", "/v1/auth/passkey/register/start", bytes.NewReader(req.Encode()), "application/protobuf", "application/protobuf")
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, c.ErrorHandler(ctx, resp)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	return DecodeWebAuthNOptionsResponse(body)
}

func (c *OpsagentHttpV1Capi) PostV1AuthPasskeyRegisterFinish(ctx context.Context, req *WebAuthNFinishRequest) (*LoginResponse, error) {
	if req == nil {
		return nil, fmt.Errorf("PostV1AuthPasskeyRegisterFinish request is nil")
	}
	resp, err := c.do(ctx, "POST", "/v1/auth/passkey/register/finish", bytes.NewReader(req.Encode()), "application/protobuf", "application/protobuf")
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, c.ErrorHandler(ctx, resp)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	return DecodeLoginResponse(body)
}

func (c *OpsagentHttpV1Capi) PostV1AuthPasskeyLoginStart(ctx context.Context, req *EmptyRequest) (*WebAuthNOptionsResponse, error) {
	if req == nil {
		return nil, fmt.Errorf("PostV1AuthPasskeyLoginStart request is nil")
	}
	resp, err := c.do(ctx, "POST", "/v1/auth/passkey/login/start", bytes.NewReader(req.Encode()), "application/protobuf", "application/protobuf")
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, c.ErrorHandler(ctx, resp)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	return DecodeWebAuthNOptionsResponse(body)
}

func (c *OpsagentHttpV1Capi) PostV1AuthPasskeyLoginFinish(ctx context.Context, req *WebAuthNFinishRequest) (*LoginResponse, error) {
	if req == nil {
		return nil, fmt.Errorf("PostV1AuthPasskeyLoginFinish request is nil")
	}
	resp, err := c.do(ctx, "POST", "/v1/auth/passkey/login/finish", bytes.NewReader(req.Encode()), "application/protobuf", "application/protobuf")
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, c.ErrorHandler(ctx, resp)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	return DecodeLoginResponse(body)
}

func (c *OpsagentHttpV1Capi) PostV1StateStream(ctx context.Context) iter.Seq2[*State, error] {
	return func(yield func(*State, error) bool) {
		resp, err := c.do(ctx, "POST", "/v1/state/stream", nil, "application/protobuf", "application/protobuf-stream")
		if err != nil {
			yield(nil, err)
			return
		}
		defer resp.Body.Close()
		if resp.StatusCode < 200 || resp.StatusCode >= 300 {
			yield(nil, c.ErrorHandler(ctx, resp))
			return
		}
		reader := NewStreamReader(resp.Body, 0)
		for {
			payload, ok, err := reader.Next()
			if err != nil {
				yield(nil, err)
				return
			}
			if !ok {
				return
			}
			item, err := DecodeState(payload)
			if err != nil {
				yield(nil, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}
	}
}

func (c *OpsagentHttpV1Capi) PostV1DeploymentUpdate(ctx context.Context, req *DeploymentUpdateRequest) (*DesiredState, error) {
	if req == nil {
		return nil, fmt.Errorf("PostV1DeploymentUpdate request is nil")
	}
	resp, err := c.do(ctx, "POST", "/v1/deployment/update", bytes.NewReader(req.Encode()), "application/protobuf", "application/protobuf")
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, c.ErrorHandler(ctx, resp)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	return DecodeDesiredState(body)
}

func (c *OpsagentHttpV1Capi) PostV1DeploymentHistory(ctx context.Context, req *DeploymentHistoryRequest) (*DeploymentHistory, error) {
	if req == nil {
		return nil, fmt.Errorf("PostV1DeploymentHistory request is nil")
	}
	resp, err := c.do(ctx, "POST", "/v1/deployment/history", bytes.NewReader(req.Encode()), "application/protobuf", "application/protobuf")
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, c.ErrorHandler(ctx, resp)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	return DecodeDeploymentHistory(body)
}

func (c *OpsagentHttpV1Capi) PostV1DeploymentLogs(ctx context.Context) error {
	resp, err := c.do(ctx, "POST", "/v1/deployment/logs", nil, "application/protobuf", "application/protobuf")
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return c.ErrorHandler(ctx, resp)
	}
	return nil
}

func (c *OpsagentHttpV1Capi) GetV1ClusterStatus(ctx context.Context) (*ClusterStatusResponse, error) {
	resp, err := c.do(ctx, "GET", "/v1/cluster/status", nil, "application/protobuf", "application/protobuf")
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, c.ErrorHandler(ctx, resp)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	return DecodeClusterStatusResponse(body)
}

func (c *OpsagentHttpV1Capi) PostV1DeploymentCreate(ctx context.Context, req *DeploymentCreateRequest) (*DeploymentConfig, error) {
	if req == nil {
		return nil, fmt.Errorf("PostV1DeploymentCreate request is nil")
	}
	resp, err := c.do(ctx, "POST", "/v1/deployment/create", bytes.NewReader(req.Encode()), "application/protobuf", "application/protobuf")
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, c.ErrorHandler(ctx, resp)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	return DecodeDeploymentConfig(body)
}

func (c *OpsagentHttpV1Capi) PostV1DeploymentVersions(ctx context.Context, req *DeploymentVersionsRequest) (*DeploymentVersions, error) {
	if req == nil {
		return nil, fmt.Errorf("PostV1DeploymentVersions request is nil")
	}
	resp, err := c.do(ctx, "POST", "/v1/deployment/versions", bytes.NewReader(req.Encode()), "application/protobuf", "application/protobuf")
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, c.ErrorHandler(ctx, resp)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	return DecodeDeploymentVersions(body)
}

func (c *OpsagentHttpV1Capi) PostV1RepoValidate(ctx context.Context, req *RepoValidateRequest) (*RepoValidateResponse, error) {
	if req == nil {
		return nil, fmt.Errorf("PostV1RepoValidate request is nil")
	}
	resp, err := c.do(ctx, "POST", "/v1/repo/validate", bytes.NewReader(req.Encode()), "application/protobuf", "application/protobuf")
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, c.ErrorHandler(ctx, resp)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	return DecodeRepoValidateResponse(body)
}

func (c *OpsagentHttpV1Capi) PostV1GithubAssetValidate(ctx context.Context, req *GithubAssetValidateRequest) (*RepoValidateResponse, error) {
	if req == nil {
		return nil, fmt.Errorf("PostV1GithubAssetValidate request is nil")
	}
	resp, err := c.do(ctx, "POST", "/v1/github/asset/validate", bytes.NewReader(req.Encode()), "application/protobuf", "application/protobuf")
	if err != nil {
		return nil, err
	}
	defer resp.Body.Close()
	if resp.StatusCode < 200 || resp.StatusCode >= 300 {
		return nil, c.ErrorHandler(ctx, resp)
	}
	body, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, err
	}
	return DecodeRepoValidateResponse(body)
}

type OpsagentClusterV1Capi struct {
	BaseURL        string
	HTTPClient     *http.Client
	HeaderProvider func(context.Context) http.Header
	ErrorHandler   func(context.Context, *http.Response) error
}

type OpsagentClusterV1CapiOption func(*OpsagentClusterV1Capi)

func NewOpsagentClusterV1Capi(baseURL string, opts ...OpsagentClusterV1CapiOption) *OpsagentClusterV1Capi {
	c := &OpsagentClusterV1Capi{
		BaseURL:      strings.TrimRight(baseURL, "/"),
		HTTPClient:   http.DefaultClient,
		ErrorHandler: defaultGoCapiErrorHandler,
	}
	for _, opt := range opts {
		opt(c)
	}
	return c
}

func WithOpsagentClusterV1CapiHTTPClient(httpClient *http.Client) OpsagentClusterV1CapiOption {
	return func(c *OpsagentClusterV1Capi) {
		if httpClient != nil {
			c.HTTPClient = httpClient
		}
	}
}

func WithOpsagentClusterV1CapiHeaderProvider(provider func(context.Context) http.Header) OpsagentClusterV1CapiOption {
	return func(c *OpsagentClusterV1Capi) {
		c.HeaderProvider = provider
	}
}

func WithOpsagentClusterV1CapiErrorHandler(handler func(context.Context, *http.Response) error) OpsagentClusterV1CapiOption {
	return func(c *OpsagentClusterV1Capi) {
		if handler != nil {
			c.ErrorHandler = handler
		}
	}
}

func (c *OpsagentClusterV1Capi) do(ctx context.Context, method string, path string, body io.Reader, contentType string, accept string) (*http.Response, error) {
	httpClient := c.HTTPClient
	if httpClient == nil {
		httpClient = http.DefaultClient
	}
	req, err := http.NewRequestWithContext(ctx, method, c.BaseURL+path, body)
	if err != nil {
		return nil, err
	}
	if accept == "" {
		accept = "application/protobuf"
	}
	req.Header.Set("Accept", accept)
	if body != nil {
		req.Header.Set("Content-Type", contentType)
	}
	if c.HeaderProvider != nil {
		for key, values := range c.HeaderProvider(ctx) {
			for _, value := range values {
				req.Header.Add(key, value)
			}
		}
	}
	return httpClient.Do(req)
}

func (c *OpsagentClusterV1Capi) PostV1ClusterConnect(ctx context.Context, reqs iter.Seq2[*MsgToMaster, error]) iter.Seq2[*MsgToWorker, error] {
	return func(yield func(*MsgToWorker, error) bool) {
		resp, err := c.do(ctx, "POST", "/v1/cluster/connect", writeGoCapiClientStream(reqs), "application/protobuf-stream", "application/protobuf-stream")
		if err != nil {
			yield(nil, err)
			return
		}
		defer resp.Body.Close()
		if resp.StatusCode < 200 || resp.StatusCode >= 300 {
			yield(nil, c.ErrorHandler(ctx, resp))
			return
		}
		reader := NewStreamReader(resp.Body, 0)
		for {
			payload, ok, err := reader.Next()
			if err != nil {
				yield(nil, err)
				return
			}
			if !ok {
				return
			}
			item, err := DecodeMsgToWorker(payload)
			if err != nil {
				yield(nil, err)
				return
			}
			if !yield(item, nil) {
				return
			}
		}
	}
}
