// Code generated by cleanproto. DO NOT EDIT.

package apigen

import (
	"time"
)

type ContainerUpgradeStrategy int32

const (
	ContainerUpgradeStrategy_CONTAINER_UPGRADE_STRATEGY_UNSPECIFIED ContainerUpgradeStrategy = 0
	ContainerUpgradeStrategy_RECREATE                               ContainerUpgradeStrategy = 1
	ContainerUpgradeStrategy_ROLLOVER                               ContainerUpgradeStrategy = 2
)

type NetworkingMode int32

const (
	NetworkingMode_NETWORKING_MODE_UNSPECIFIED NetworkingMode = 0
	NetworkingMode_NETWORKING_MODE_VIRTUAL     NetworkingMode = 1
	NetworkingMode_NETWORKING_MODE_HOST        NetworkingMode = 2
)

type PortForwardProtocol int32

const (
	PortForwardProtocol_PORT_FORWARD_PROTOCOL_UNSPECIFIED PortForwardProtocol = 0
	PortForwardProtocol_PORT_FORWARD_PROTOCOL_TCP         PortForwardProtocol = 1
	PortForwardProtocol_PORT_FORWARD_PROTOCOL_UDP         PortForwardProtocol = 2
)

type RunningStatus int32

const (
	RunningStatus_DEPLOYMENT_STATUS_UNKNOWN RunningStatus = 0
	RunningStatus_NO_DEPLOYMENT             RunningStatus = 1
	RunningStatus_RUNNING                   RunningStatus = 2
	RunningStatus_STOPPED                   RunningStatus = 3
	RunningStatus_STARTING                  RunningStatus = 4
	RunningStatus_CRASHED                   RunningStatus = 5
)

type PreparationStatus int32

const (
	PreparationStatus_PREPARATION_STATUS_UNKNOWN PreparationStatus = 0
	PreparationStatus_PREPARING                  PreparationStatus = 2
	PreparationStatus_DOWNLOADING                PreparationStatus = 3
	PreparationStatus_READY                      PreparationStatus = 4
	PreparationStatus_FAILED                     PreparationStatus = 5
	PreparationStatus_PULLING                    PreparationStatus = 6
)

type EndpointState int32

const (
	EndpointState_ENDPOINT_STATE_UNSPECIFIED EndpointState = 0
	EndpointState_ENDPOINT_READY             EndpointState = 1
	EndpointState_ENDPOINT_DRAINING          EndpointState = 2
	EndpointState_ENDPOINT_DOWN              EndpointState = 3
)

type AccessPolicyType int32

const (
	AccessPolicyType_ACCESS_POLICY_TYPE_UNSPECIFIED AccessPolicyType = 0
	AccessPolicyType_NO_AUTH                        AccessPolicyType = 1
	AccessPolicyType_OPTIONAL_AUTH                  AccessPolicyType = 2
	AccessPolicyType_ANY_OF                         AccessPolicyType = 3
)

type EnrollmentWorkerMsg struct {
	Hello *EnrollmentHello
}

type EnrollmentHello struct {
	RequestingMachineID      string
	WorkerCertificateRequest []byte
	OpendeployVersion        string
}

type EnrollmentPrimaryMsg struct {
	RequestStatus *EnrollmentRequestStatus
	Accepted      *EnrollmentAccepted
}

type EnrollmentRequestStatus struct {
	ID                  int32
	CreatedAt           time.Time
	UpdatedAt           time.Time
	RequestingIpAddress string
	RequestingMachineID string
	Status              string
	OpendeployVersion   string
}

type EnrollmentRequestList struct {
	Items []*EnrollmentRequestStatus
}

type EnrollmentInfo struct {
	EnrollmentTlsSpkiSha256 string
}

type EnrollmentAcceptRequest struct {
	ID         int32
	WorkerName string
}

type EnrollmentAccepted struct {
	ID                int32
	WorkerName        string
	CaCertificate     []byte
	WorkerCertificate []byte
	ClusterNetwork    *ClusterNetworkInfo
	NodeDeployment    *DeploymentWithStatus
	NodeNetDeployment *DeploymentWithStatus
}

type GithubCredentials struct {
	Token     string
	ChangedAt time.Time
}

type BackupStatus struct {
	Configured           bool
	Running              bool
	InSync               bool
	LocalTxid            uint64
	RemoteTxid           uint64
	LastSuccessfulSyncAt time.Time
	Error                string
}

type ClusterSecretsRequest struct {
	Ids []int32
}

type ClusterSecretValue struct {
	ID    int32
	Value []byte
}

type ClusterSecretsResponse struct {
	Items []*ClusterSecretValue
}

type ClusterConfigsRequest struct {
	Ids []int32
}

type ClusterConfigValue struct {
	ID    int32
	Value string
}

type ClusterConfigsResponse struct {
	Items []*ClusterConfigValue
}

type SecretRef struct {
	ID int32
}

type ConfigRef struct {
	ID int32
}

type StringSetting struct {
	Value     string
	ConfigRef ConfigRef
}

type BoolSetting struct {
	Value     bool
	ConfigRef ConfigRef
}

type Config struct {
	Settings           Settings
	MasterPasswordHash string
	NetworkUlaPrefix   []byte
}

type Settings struct {
	HttpWeb     HttpWebSettings
	HttpsWeb    HttpsWebSettings
	Cluster     ClusterSettings
	Repo        RepoSettings
	Backup      BackupSettings
	LargeAssets LargeAssetsSettings
}

type HttpWebSettings struct {
	Enabled BoolSetting
	Listen  StringSetting
}

type HttpsWebSettings struct {
	Enabled        BoolSetting
	Listen         StringSetting
	TlsSelfManaged BoolSetting
	TlsCertPem     SecretRef
	AcmeHosts      StringSetting
	AcmeEmail      StringSetting
}

type ClusterSettings struct {
	Listen           StringSetting
	EnrollmentListen StringSetting
}

type RepoSettings struct {
	GithubToken SecretRef
}

type BackupSettings struct {
	Enabled           BoolSetting
	S3AccessKeyID     StringSetting
	S3SecretAccessKey SecretRef
	S3Bucket          StringSetting
	S3Path            StringSetting
	S3Region          StringSetting
	S3Endpoint        StringSetting
}

type LargeAssetsSettings struct {
	S3Enabled         BoolSetting
	S3AccessKeyID     StringSetting
	S3SecretAccessKey SecretRef
	S3Bucket          StringSetting
	S3Path            StringSetting
	S3Region          StringSetting
	S3Endpoint        StringSetting
}

type ExportedConfigBlob struct {
	Blob []byte
}

type EmptyRequest struct {
}

type MasterPasswordRequest struct {
	Password string
	Username string
}

type MasterPasswordVerifyRequest struct {
	Password string
}

type MasterPasswordSaveRequest struct {
	Password string
}

type LoginResponse struct {
	Token  string
	UserID int32
	Scopes []string
	Name   string
	Expiry time.Time
}

type WebAuthNOptionsResponse struct {
	SessionID   string
	OptionsJson []byte
}

type WebAuthNFinishRequest struct {
	SessionID      string
	CredentialJson []byte
}

type SecretMeta struct {
	Name      string
	CreatedAt time.Time
	UpdatedBy int32
	ID        int32
	Deleted   bool
	SpaceID   int32
	Version   int32
}

type SecretList struct {
	Items []*SecretMeta
}

type SecretSetRequest struct {
	Name    string
	Value   []byte
	SpaceID int32
}

type SecretRenameRequest struct {
	Name    string
	NewName string
}

type SecretDeleteRequest struct {
	Name string
}

type SecretRevealRequest struct {
	Name string
	ID   int32
}

type SecretRevealResponse struct {
	Value []byte
}

type SecretsStatusResponse struct {
	Unlocked           bool
	RecoveryConfigured bool
}

type SecretRecoveryCodeResponse struct {
	Code string
}

type SecretUnlockRequest struct {
	Code string
}

type UserConfig struct {
	Name      string
	Value     string
	CreatedAt time.Time
	UpdatedBy int32
	ID        int32
	Deleted   bool
	SpaceID   int32
	Version   int32
}

type UserConfigList struct {
	Items []*UserConfig
}

type UserConfigSetRequest struct {
	Name    string
	Value   string
	SpaceID int32
}

type UserConfigRenameRequest struct {
	Name    string
	NewName string
}

type UserConfigDeleteRequest struct {
	Name string
}

type AssetMeta struct {
	Key       string
	CreatedAt time.Time
	Version   int32
	Format    string
	Location  string
	SizeBytes int32
	ID        int32
	SpaceID   int32
	Deleted   bool
}

type Asset struct {
	Key       string
	CreatedAt time.Time
	Version   int32
	Format    string
	Location  string
	Blob      []byte
	ID        int32
	SpaceID   int32
	SizeBytes int32
}

type AssetList struct {
	Items []*AssetMeta
}

type AssetGetRequest struct {
	Key     string
	Version int32
}

type AssetSetRequest struct {
	Key     string
	Format  string
	Blob    []byte
	SpaceID int32
}

type AssetDeleteRequest struct {
	Key string
}

type NixDockerBuildConfig struct {
	Repo  string
	Flake string
}

type GithubReleaseConfig struct {
	Repo           string
	Asset          string
	Tag            string
	DownloadScript string
}

type ContainerImageConfig struct {
	Image string
}

type PrepareConfig struct {
	GithubRelease  *GithubReleaseConfig
	ContainerImage *ContainerImageConfig
	NixDockerBuild *NixDockerBuildConfig
}

type EnvVarValue struct {
	SecretID *int32
	ConfigID *int32
	Value    *string
	Asset    string
	AssetID  int32
}

type SystemdRunnerConfig struct {
	Name    string
	BinPath string
}

type ContainerMount struct {
	Host      string
	Container string
	Readonly  bool
}

type ContainerAssetMount struct {
	Asset      string
	Path       string
	Format     string
	AssetID    int32
	Executable bool
}

type ContainerReadinessSignal struct {
	TimeoutSeconds int32
}

type ContainerRunnerConfig struct {
	User                string
	EnvVars             map[string]*EnvVarValue
	Command             []string
	WorkingDir          string
	DataMountPath       string
	DisableDataVolume   bool
	Mounts              []*ContainerMount
	AssetMounts         []*ContainerAssetMount
	UpgradeStrategy     ContainerUpgradeStrategy
	ReadinessSignal     *ContainerReadinessSignal
	DevShmSizeKb        int32
	FileDescriptorLimit int32
}

type RunnerConfig struct {
	Systemd   SystemdRunnerConfig
	Container ContainerRunnerConfig
}

type PortForward struct {
	Protocol      PortForwardProtocol
	HostPort      int32
	ContainerPort int32
}

type NetworkingConfig struct {
	Mode           NetworkingMode
	PortForwarding []*PortForward
}

type State struct {
	Heartbeat                bool
	DeploymentsSnapshot      *DeploymentWithStatusSnapshot
	DeploymentUpdate         *DeploymentWithStatus
	UsersSnapshot            []*User
	UserUpdate               *User
	EnrollmentsSnapshot      *EnrollmentRequestList
	EnrollmentUpdate         *EnrollmentRequestStatus
	SecretsSnapshot          *SecretReferenceList
	SecretUpdate             *SecretReference
	UserConfigsSnapshot      *UserConfigReferenceList
	UserConfigUpdate         *UserConfigReference
	SecretsStatusSnapshot    *SecretsStatusResponse
	SecretMetasSnapshot      *SecretList
	SecretMetaUpdate         *SecretMeta
	UserConfigValuesSnapshot *UserConfigList
	UserConfigValueUpdate    *UserConfig
	SpacesSnapshot           *SpaceList
	SpaceUpdate              *Space
	AssetsSnapshot           *AssetList
	AssetUpdate              *AssetMeta
	NodesSnapshot            *ClusterNodeList
	NodeUpdate               *ClusterNode
	NodeStatusesSnapshot     *ClusterNodeStatusList
	NodeStatusUpdate         *ClusterNodeStatus
	BackupStatusSnapshot     *BackupStatus
	BackupStatusUpdate       *BackupStatus
}

type Space struct {
	ID      int32
	Name    string
	Deleted bool
}

type SpaceList struct {
	Items []*Space
}

type SpaceSetRequest struct {
	ID   int32
	Name string
}

type SpaceDeleteRequest struct {
	ID int32
}

type SecretReference struct {
	ID      int32
	Name    string
	Deleted bool
	SpaceID int32
	Version int32
}

type SecretReferenceList struct {
	Items []*SecretReference
}

type UserConfigReference struct {
	ID      int32
	Name    string
	Deleted bool
	SpaceID int32
	Version int32
}

type UserConfigReferenceList struct {
	Items []*UserConfigReference
}

type DeploymentWithStatusSnapshot struct {
	Items []*DeploymentWithStatus
}

type ClusterMachineList struct {
	Items []*ClusterMachine
}

type DeploymentHistoryEntry struct {
	Config *DeploymentConfig
	Status *DeploymentStatus
}

type DeploymentHistory struct {
	Entries []*DeploymentHistoryEntry
}

type DeploymentUpdateRequest struct {
	DeploymentID  int32
	TargetVersion string
	Stop          bool
	Version       int32
	Spec          DeploymentSpec
	SpaceID       *int32
}

type DeploymentCreateRequest struct {
	ConfigID     DeploymentIdentifier
	Spec         DeploymentSpec
	DesiredState DesiredState
}

type DeploymentHistoryRequest struct {
	DeploymentID int32
}

type PrepareOutputRequest struct {
	DeploymentID int32
	Version      int32
}

type PrepareOutputChunk struct {
	Data []byte
}

type RunOutputRequest struct {
	DeploymentID int32
	Version      int32
}

type DeploymentLogRequest struct {
	RunnerOutput   *RunOutputRequest
	PreparerOutput *PrepareOutputRequest
	RequestID      string
}

type LogSearchRequest struct {
	DeploymentID  int32
	TimeStart     time.Time
	TimeEnd       time.Time
	LevelMin      string
	SearchKeys    map[string]string
	RequestID     string
	LogLineLimit  int32
	ConfigVersion int32
	SearchStr     string
}

type LogLine struct {
	Time    int64
	Version int32
	Run     int32
	Stream  int32
	Line    []byte
}

type LogLineBatch struct {
	Lines  []*LogLine
	LogDir string
}

type DeploymentIdentifier struct {
	SpaceID int32
	Machine string
	Name    string
}

type DeploymentSpec struct {
	Prepare    PrepareConfig
	Runner     RunnerConfig
	Networking NetworkingConfig
}

type DesiredState struct {
	Version string
	Running bool
}

type DeploymentDeleteRequest struct {
	DeploymentID int32
	Version      int32
}

type DeploymentConfig struct {
	ID           int32
	ConfigID     DeploymentIdentifier
	Version      int32
	UpdatedAt    time.Time
	UpdatedBy    int32
	Spec         DeploymentSpec
	DesiredState DesiredState
	Deleted      bool
	CreatedAt    time.Time
}

type DeploymentWithStatus struct {
	Config DeploymentConfig
	Status DeploymentStatus
}

type DeploymentStatus struct {
	UpdatedAt    time.Time
	DeploymentID int32
	Preparer     PreparerStatus
	Runner       RunnerStatus
}

type PreparerStatus struct {
	DeploymentConfigVersion int32
	Artifact                string
	Status                  PreparationStatus
}

type RunnerStatus struct {
	DeploymentConfigVersion int32
	RunningPid              int32
	RunningArtifact         string
	Status                  RunningStatus
	NumberOfRestarts        int32
	LastRestartAt           time.Time
	RunningVersion          string
	Endpoints               []*Endpoint
	NetworkDiagnostics      []string
}

type Endpoint struct {
	Ordinal int32
	Address string
	Machine string
	State   EndpointState
}

type Version struct {
	ID     string
	Label  string
	Author string
	Time   time.Time
}

type DeploymentVersions struct {
	DeploymentID   int32
	NixDockerBuild *DeploymentNixDockerBuildVersions
	GithubRelease  *DeploymentGithubReleaseVersions
	ContainerImage *DeploymentContainerImageVersions
}

type DeploymentNixDockerBuildVersions struct {
	Branches       []string
	SelectedBranch string
	Commits        []*Version
}

type DeploymentGithubReleaseVersions struct {
	Releases []*Version
}

type DeploymentContainerImageVersions struct {
	Tags []*Version
}

type DeploymentVersionsRequest struct {
	DeploymentID   int32
	SelectedBranch string
}

type ValidateSourceRequest struct {
	NixDockerBuild *ValidateNixDockerBuildSource
	ContainerImage *ValidateContainerImageSource
}

type ValidateNixDockerBuildSource struct {
	RepoUrl                  string
	SelectedBranch           string
	SelectedCommit           *Version
	SelectedFlakePath        string
	RefreshAvailableBranches bool
	RefreshAvailableCommits  bool
	CheckRepo                bool
	CheckBranch              bool
	CheckCommit              bool
	CheckFlakePath           bool
}

type ValidateNixDockerBuildSourceResponse struct {
	CheckedRepoUrl    string
	GitRepository     ValidationResult
	CheckedBranch     string
	BranchCheck       ValidationResult
	CheckedCommit     *Version
	CommitCheck       ValidationResult
	CheckedFlakePath  string
	NixFlakeFile      ValidationResult
	AvailableBranches AvailableBranches
	AvailableCommits  AvailableCommits
}

type AvailableCommits struct {
	Loaded       bool
	Branch       string
	Errormessage *string
	Commits      []*Version
}

type AvailableBranches struct {
	Loaded       bool
	Errormessage *string
	Branches     []string
}

type RepoValidationResult struct {
	Checked bool
	RepoUrl string
	Ok      bool
	Message string
}

type ValidationResult struct {
	Checked bool
	Ok      bool
	Message string
}

type ValidateContainerImageSource struct {
	Image           string
	RefreshVersions bool
}

type ValidateSourceResponse struct {
	NixDockerBuild *ValidateNixDockerBuildSourceResponse
	ContainerImage *ValidateContainerImageSourceResponse
}

type ValidateContainerImageSourceResponse struct {
	Image ValidationResult
	Tags  []*Version
}

type User struct {
	ID   int32
	Name string
}

type WebAuthnCredential struct {
	ID   []byte
	Data []byte
}

type InternalUser struct {
	ID          int32
	WebAuthNID  []byte
	Name        string
	Credentials []*WebAuthnCredential
}

type PublicKeyRecord struct {
	Kid      string
	KeyBytes []byte
}

type ClusterMachine struct {
	Name        string
	IsPrimary   bool
	Connected   bool
	ConnectedAt time.Time
}

type ClusterNode struct {
	ID           int32
	EnrollmentID int32
	Name         string
	Sni          string
	Roles        []int32
	WgPublicKey  string
	Addresses    []string
	EnrolledAt   time.Time
}

type ClusterNodeList struct {
	Items []*ClusterNode
}

type ClusterNodeStatus struct {
	ID              int32
	NodeID          int32
	LastConnectedAt time.Time
	IsConnected     bool
}

type ClusterNodeStatusList struct {
	Items []*ClusterNodeStatus
}

type ClusterStatusResponse struct {
	Machines []*ClusterMachine
}

type MsgToWorker struct {
	DeploymentsSnapshot  *DeploymentWithStatusSnapshot
	DeploymentUpdate     *DeploymentConfig
	PrepareLogRequest    *PrepareOutputRequest
	RunLogRequest        *RunOutputRequest
	DeploymentLogRequest *DeploymentLogRequest
	StopLogRequestID     string
	LogSearchRequest     *LogSearchRequest
	ClusterNetwork       *ClusterNetworkInfo
}

type ClusterNetworkInfo struct {
	UlaPrefix []byte
}

type MsgToMaster struct {
	StatusWrite  *DeploymentStatus
	LogData      []byte
	LogEnd       bool
	LogRequestID string
	LogLines     LogLineBatch
}

type NetState struct {
	Seq               int64
	UlaPrefix         []byte
	Machine           string
	DnsServices       []*DnsService
	UpstreamResolvers []string
}

type DnsService struct {
	Name        string
	Environment string
	Endpoints   []*Endpoint
}

type AccessPolicy struct {
	PolicyType AccessPolicyType
	Scopes     []string
}

type ApiErr struct {
	Code        int32
	DisplayErr  string
	InternalErr string
}
