// Code generated by cleanproto. DO NOT EDIT.

package apigen

import (
	"time"
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED EventType = 0
	EventType_EVENT_TYPE_CREATE      EventType = 1
	EventType_EVENT_TYPE_UPDATE      EventType = 2
	EventType_EVENT_TYPE_DELETE      EventType = 3
)

type NetworkingMode int32

const (
	NetworkingMode_NETWORKING_MODE_UNSPECIFIED NetworkingMode = 0
	NetworkingMode_NETWORKING_MODE_VIRTUAL     NetworkingMode = 1
	NetworkingMode_NETWORKING_MODE_HOST        NetworkingMode = 2
)

type AddressFamily int32

const (
	AddressFamily_ADDRESS_FAMILY_ANY  AddressFamily = 0
	AddressFamily_ADDRESS_FAMILY_IPV4 AddressFamily = 1
	AddressFamily_ADDRESS_FAMILY_IPV6 AddressFamily = 2
)

type ContainerUpgradeStrategy int32

const (
	ContainerUpgradeStrategy_CONTAINER_UPGRADE_STRATEGY_UNSPECIFIED ContainerUpgradeStrategy = 0
	ContainerUpgradeStrategy_RECREATE                               ContainerUpgradeStrategy = 1
	ContainerUpgradeStrategy_ROLLOVER                               ContainerUpgradeStrategy = 2
)

type PortForwardProtocol int32

const (
	PortForwardProtocol_PORT_FORWARD_PROTOCOL_UNSPECIFIED PortForwardProtocol = 0
	PortForwardProtocol_PORT_FORWARD_PROTOCOL_TCP         PortForwardProtocol = 1
	PortForwardProtocol_PORT_FORWARD_PROTOCOL_UDP         PortForwardProtocol = 2
)

type IngressKind int32

const (
	IngressKind_INGRESS_KIND_UNSPECIFIED     IngressKind = 0
	IngressKind_INGRESS_KIND_TLS_PASSTHROUGH IngressKind = 1
	IngressKind_INGRESS_KIND_HTTPS           IngressKind = 2
)

type HttpBackendProtocol int32

const (
	HttpBackendProtocol_HTTP_BACKEND_PROTOCOL_UNSPECIFIED HttpBackendProtocol = 0
	HttpBackendProtocol_HTTP_BACKEND_PROTOCOL_H2C         HttpBackendProtocol = 1
)

type FilePermission int32

const (
	FilePermission_FILE_PERMISSION_UNSPECIFIED FilePermission = 0
	FilePermission_READ_WRITE                  FilePermission = 1
	FilePermission_READ_ONLY                   FilePermission = 2
	FilePermission_READ_EXECUTE                FilePermission = 3
)

type AcmeChallenge int32

const (
	AcmeChallenge_ACME_CHALLENGE_UNSPECIFIED AcmeChallenge = 0
	AcmeChallenge_ACME_CHALLENGE_HTTP_01     AcmeChallenge = 1
)

type RunningStatus int32

const (
	RunningStatus_DEPLOYMENT_STATUS_UNKNOWN RunningStatus = 0
	RunningStatus_NO_DEPLOYMENT             RunningStatus = 1
	RunningStatus_RUNNING                   RunningStatus = 2
	RunningStatus_STOPPED                   RunningStatus = 3
	RunningStatus_STARTING                  RunningStatus = 4
	RunningStatus_CRASHED                   RunningStatus = 5
)

type PreparationStatus int32

const (
	PreparationStatus_PREPARATION_STATUS_UNKNOWN PreparationStatus = 0
	PreparationStatus_PREPARING                  PreparationStatus = 2
	PreparationStatus_DOWNLOADING                PreparationStatus = 3
	PreparationStatus_READY                      PreparationStatus = 4
	PreparationStatus_FAILED                     PreparationStatus = 5
	PreparationStatus_PULLING                    PreparationStatus = 6
)

type InputsStatus int32

const (
	InputsStatus_INPUTS_STATUS_UNKNOWN InputsStatus = 0
	InputsStatus_INPUTS_RESOLVING      InputsStatus = 1
	InputsStatus_INPUTS_READY          InputsStatus = 2
	InputsStatus_INPUTS_FAILED         InputsStatus = 3
)

type ImageStatus int32

const (
	ImageStatus_IMAGE_STATUS_UNKNOWN ImageStatus = 0
	ImageStatus_IMAGE_BUILDING       ImageStatus = 1
	ImageStatus_IMAGE_PULLING        ImageStatus = 2
	ImageStatus_IMAGE_DOWNLOADING    ImageStatus = 3
	ImageStatus_IMAGE_READY          ImageStatus = 4
	ImageStatus_IMAGE_FAILED         ImageStatus = 5
)

type ScheduledInstanceTarget int32

const (
	ScheduledInstanceTarget_SCHEDULED_INSTANCE_TARGET_RUN_SERVING  ScheduledInstanceTarget = 0
	ScheduledInstanceTarget_SCHEDULED_INSTANCE_TARGET_TERMINATE    ScheduledInstanceTarget = 1
	ScheduledInstanceTarget_SCHEDULED_INSTANCE_TARGET_FINALIZED    ScheduledInstanceTarget = 2
	ScheduledInstanceTarget_SCHEDULED_INSTANCE_TARGET_RUN_STANDBY  ScheduledInstanceTarget = 3
	ScheduledInstanceTarget_SCHEDULED_INSTANCE_TARGET_RUN_DRAINING ScheduledInstanceTarget = 4
)

type AgentSessionStatus int32

const (
	AgentSessionStatus_AGENT_SESSION_STATUS_UNKNOWN AgentSessionStatus = 0
	AgentSessionStatus_AGENT_SESSION_PENDING        AgentSessionStatus = 1
	AgentSessionStatus_AGENT_SESSION_APPROVED       AgentSessionStatus = 2
	AgentSessionStatus_AGENT_SESSION_REJECTED       AgentSessionStatus = 3
	AgentSessionStatus_AGENT_SESSION_REVOKED        AgentSessionStatus = 4
)

type AuthzVerb int32

const (
	AuthzVerb_AUTHZ_VERB_UNKNOWN          AuthzVerb = 0
	AuthzVerb_AUTHZ_VERB_CREATE           AuthzVerb = 1
	AuthzVerb_AUTHZ_VERB_UPDATE           AuthzVerb = 2
	AuthzVerb_AUTHZ_VERB_DELETE           AuthzVerb = 3
	AuthzVerb_AUTHZ_VERB_VIEW             AuthzVerb = 4
	AuthzVerb_AUTHZ_VERB_VIEW_LOGS        AuthzVerb = 5
	AuthzVerb_AUTHZ_VERB_REVEAL           AuthzVerb = 6
	AuthzVerb_AUTHZ_VERB_USE_HOST_MOUNTS  AuthzVerb = 7
	AuthzVerb_AUTHZ_VERB_USE_HOST_NETWORK AuthzVerb = 8
)

type AuthzEntity int32

const (
	AuthzEntity_AUTHZ_ENTITY_UNKNOWN    AuthzEntity = 0
	AuthzEntity_AUTHZ_ENTITY_SPACE      AuthzEntity = 1
	AuthzEntity_AUTHZ_ENTITY_DEPLOYMENT AuthzEntity = 2
	AuthzEntity_AUTHZ_ENTITY_SECRET     AuthzEntity = 3
	AuthzEntity_AUTHZ_ENTITY_CONFIG     AuthzEntity = 4
	AuthzEntity_AUTHZ_ENTITY_ASSET      AuthzEntity = 5
	AuthzEntity_AUTHZ_ENTITY_NODE       AuthzEntity = 6
	AuthzEntity_AUTHZ_ENTITY_CLUSTER    AuthzEntity = 7
	AuthzEntity_AUTHZ_ENTITY_USER       AuthzEntity = 8
	AuthzEntity_AUTHZ_ENTITY_ACCESS     AuthzEntity = 9
)

type NodeLifecycleStatus int32

const (
	NodeLifecycleStatus_NODE_STATUS_UNKNOWN             NodeLifecycleStatus = 0
	NodeLifecycleStatus_NODE_ENROLLMENT_REQUESTED       NodeLifecycleStatus = 1
	NodeLifecycleStatus_NODE_ENROLLMENT_CANCELLED       NodeLifecycleStatus = 2
	NodeLifecycleStatus_NODE_ENROLLMENT_REQUEST_EXPIRED NodeLifecycleStatus = 3
	NodeLifecycleStatus_NODE_MEMBER_NORMAL              NodeLifecycleStatus = 4
	NodeLifecycleStatus_NODE_MEMBER_UNHEALTHY           NodeLifecycleStatus = 5
	NodeLifecycleStatus_NODE_MEMBER_DRAINING            NodeLifecycleStatus = 6
	NodeLifecycleStatus_NODE_MEMBER_MISSING             NodeLifecycleStatus = 7
	NodeLifecycleStatus_NODE_MEMBER_EVICTED             NodeLifecycleStatus = 8
)

type NetProtocol int32

const (
	NetProtocol_NET_PROTOCOL_UNSPECIFIED NetProtocol = 0
	NetProtocol_NET_PROTOCOL_TCP         NetProtocol = 1
	NetProtocol_NET_PROTOCOL_UDP         NetProtocol = 2
)

type EndpointState int32

const (
	EndpointState_ENDPOINT_STATE_UNSPECIFIED EndpointState = 0
	EndpointState_ENDPOINT_READY             EndpointState = 1
	EndpointState_ENDPOINT_DRAINING          EndpointState = 2
	EndpointState_ENDPOINT_DOWN              EndpointState = 3
)

type NetworkPolicyAction int32

const (
	NetworkPolicyAction_NETWORK_POLICY_ACTION_UNSPECIFIED NetworkPolicyAction = 0
	NetworkPolicyAction_NETWORK_POLICY_ACTION_ALLOW       NetworkPolicyAction = 1
	NetworkPolicyAction_NETWORK_POLICY_ACTION_DENY        NetworkPolicyAction = 2
)

type NetworkPolicyPeerKind int32

const (
	NetworkPolicyPeerKind_NETWORK_POLICY_PEER_KIND_UNSPECIFIED NetworkPolicyPeerKind = 0
	NetworkPolicyPeerKind_NETWORK_POLICY_PEER_KIND_SPACE       NetworkPolicyPeerKind = 1
	NetworkPolicyPeerKind_NETWORK_POLICY_PEER_KIND_DEPLOYMENT  NetworkPolicyPeerKind = 2
)

type AccessPolicyType int32

const (
	AccessPolicyType_ACCESS_POLICY_TYPE_UNSPECIFIED AccessPolicyType = 0
	AccessPolicyType_NO_AUTH                        AccessPolicyType = 1
	AccessPolicyType_OPTIONAL_AUTH                  AccessPolicyType = 2
	AccessPolicyType_ANY_OF                         AccessPolicyType = 3
)

type Deployment struct {
	NodeID  int32          `json:"node_id"`
	Spec    DeploymentSpec `json:"spec"`
	SpaceID int32          `json:"space_id"`
	Name    string         `json:"name,omitempty"`
}

type DeploymentEvent struct {
	DeploymentID int32      `json:"deployment_id"`
	Version      int32      `json:"version"`
	Seq          int64      `json:"seq"`
	EventID      int64      `json:"event_id"`
	Author       int32      `json:"author"`
	EventType    EventType  `json:"event_type"`
	CreatedTime  time.Time  `json:"created_time"`
	EventTime    time.Time  `json:"event_time"`
	SpecVersion  int32      `json:"spec_version"`
	SpaceVersion int32      `json:"space_version"`
	NameVersion  int32      `json:"name_version"`
	Value        Deployment `json:"value"`
}

type DeploymentSpec struct {
	Networking     NetworkingConfig `json:"networking"`
	Container1Spec *ContainerSpec   `json:"container1_spec"`
	Container2Spec *ContainerSpec   `json:"container2_spec"`
	Container3Spec *ContainerSpec   `json:"container3_spec"`
	MicroVmSpec    *MicroVMSpec     `json:"micro_vm_spec"`
	VmSpec         *VMSpec          `json:"vm_spec"`
	OpendeploySpec *OpendeploySpec  `json:"opendeploy_spec"`
}

type NetworkingConfig struct {
	Mode           NetworkingMode `json:"mode"`
	PortForwarding []*PortForward `json:"port_forwarding,omitempty"`
	Ingress        []*Ingress     `json:"ingress,omitempty"`
}

type ContainerSpec struct {
	Source          ContainerBundleSource     `json:"source"`
	Runtime         ContainerRuntime          `json:"runtime"`
	Version         string                    `json:"version,omitempty"`
	Running         bool                      `json:"running"`
	UpgradeStrategy ContainerUpgradeStrategy  `json:"upgrade_strategy"`
	ReadinessSignal *ContainerReadinessSignal `json:"readiness_signal"`
}

type MicroVMSpec struct {
}

type VMSpec struct {
}

type OpendeploySpec struct {
	Version string `json:"version,omitempty"`
}

type PortForward struct {
	Protocol      PortForwardProtocol `json:"protocol"`
	HostPort      int32               `json:"host_port"`
	ContainerPort int32               `json:"container_port"`
	IpFilter      *IpFilter           `json:"ip_filter"`
}

type Ingress struct {
	Kind                 IngressKind           `json:"kind"`
	Hostname             string                `json:"hostname,omitempty"`
	TlsPassthroughConfig *TlsPassthroughConfig `json:"tls_passthrough_config"`
	HttpsConfig          *HttpsConfig          `json:"https_config"`
	Listen               []*IngressListen      `json:"listen,omitempty"`
}

type IngressListen struct {
	Node    *NodeSelector    `json:"node"`
	Address *AddressSelector `json:"address"`
}

type NodeSelector struct {
	Any    bool  `json:"any"`
	NodeID int32 `json:"node_id"`
}

type AddressSelector struct {
	Family   AddressFamily `json:"family"`
	Prefixes []string      `json:"prefixes,omitempty"`
}

type ContainerBundleSource struct {
	NixDockerBuild *NixDockerBuild    `json:"nix_docker_build"`
	RemoteImage    *RemoteDockerImage `json:"remote_image"`
}

type ContainerRuntime struct {
	User                  string                  `json:"user,omitempty"`
	EnvVars               map[string]*EnvVarValue `json:"env_vars,omitempty"`
	OverrideCommand       []string                `json:"override_command,omitempty"`
	OverrideWorkingDir    string                  `json:"override_working_dir,omitempty"`
	DefaultVolume         DefaultVolumeMount      `json:"default_volume"`
	CrossDeploymentMounts []*CrossDeploymentMount `json:"cross_deployment_mounts,omitempty"`
	AssetMounts           []*AssetMount           `json:"asset_mounts,omitempty"`
	Mounts                []*CustomHostMount      `json:"mounts,omitempty"`
	DevShmSizeKb          int32                   `json:"dev_shm_size_kb"`
	FileDescriptorLimit   int32                   `json:"file_descriptor_limit"`
	IssuedTlsMount        *IssuedTLSMount         `json:"issued_tls_mount"`
}

type ContainerReadinessSignal struct {
	TimeoutSeconds int32 `json:"timeout_seconds"`
}

type IpFilter struct {
	Allow []string `json:"allow,omitempty"`
	Deny  []string `json:"deny,omitempty"`
}

type TlsPassthroughConfig struct {
	HostPort      int32 `json:"host_port"`
	ContainerPort int32 `json:"container_port"`
}

type HttpsConfig struct {
	ContainerPort       int32               `json:"container_port"`
	PathPrefix          string              `json:"path_prefix,omitempty"`
	StripPrefix         bool                `json:"strip_prefix"`
	BackendProtocol     HttpBackendProtocol `json:"backend_protocol"`
	MaxRequestBodyBytes int64               `json:"max_request_body_bytes"`
	FlushIntervalMs     int32               `json:"flush_interval_ms"`
	CertSource          *CertSource         `json:"cert_source"`
}

type NixDockerBuild struct {
	Repo   string `json:"repo,omitempty"`
	Flake  string `json:"flake,omitempty"`
	Target string `json:"target,omitempty"`
}

type RemoteDockerImage struct {
	Image string `json:"image,omitempty"`
}

type EnvVarValue struct {
	SecretVersionID     *int32  `json:"secret_version_id,omitempty"`
	ConfigVersionID     *int32  `json:"config_version_id,omitempty"`
	Value               *string `json:"value,omitempty"`
	Asset               string  `json:"asset,omitempty"`
	AssetVersionID      int32   `json:"asset_version_id"`
	AddressDeploymentID *int32  `json:"address_deployment_id,omitempty"`
	AddressSpaceID      *int32  `json:"address_space_id,omitempty"`
}

type DefaultVolumeMount struct {
	ContainerPath string `json:"container_path,omitempty"`
	Disabled      bool   `json:"disabled"`
}

type CrossDeploymentMount struct {
	DeploymentID  int32          `json:"deployment_id"`
	ContainerPath string         `json:"container_path,omitempty"`
	Permission    FilePermission `json:"permission"`
}

type AssetMount struct {
	AssetVersionID int32          `json:"asset_version_id"`
	ContainerPath  string         `json:"container_path,omitempty"`
	Permission     FilePermission `json:"permission"`
}

type CustomHostMount struct {
	HostPath      string         `json:"host_path,omitempty"`
	ContainerPath string         `json:"container_path,omitempty"`
	Permission    FilePermission `json:"permission"`
}

type IssuedTLSMount struct {
	ContainerPath string   `json:"container_path,omitempty"`
	ExtraNames    []string `json:"extra_names,omitempty"`
	CaOnly        bool     `json:"ca_only"`
}

type CertSource struct {
	Acme   *AcmeCertSource   `json:"acme"`
	Secret *SecretCertSource `json:"secret"`
}

type AcmeCertSource struct {
	Challenge AcmeChallenge `json:"challenge"`
}

type SecretCertSource struct {
	SecretVersionID int32 `json:"secret_version_id"`
}

type DeploymentSpecVersionRef struct {
	ID          int32 `json:"id"`
	SpecVersion int32 `json:"spec_version"`
}

type ScheduledInstance struct {
	ID                    int32                   `json:"id"`
	CreatedAt             time.Time               `json:"created_at"`
	DeploymentID          int32                   `json:"deployment_id"`
	NodeID                int32                   `json:"node_id"`
	InstanceOrdinal       int32                   `json:"instance_ordinal"`
	State                 ScheduledInstanceTarget `json:"state"`
	DeploymentVersion     int32                   `json:"deployment_version"`
	DeploymentSpecVersion int32                   `json:"deployment_spec_version"`
	SpaceID               int32                   `json:"space_id"`
}

type ScheduledInstanceStatus struct {
	UpdatedAt           time.Time      `json:"updated_at"`
	ScheduledInstanceID int32          `json:"scheduled_instance_id"`
	DeploymentID        int32          `json:"deployment_id"`
	Preparer            PreparerStatus `json:"preparer"`
	Runner              RunnerStatus   `json:"runner"`
}

type ScheduledInstanceState struct {
	Instance ScheduledInstance       `json:"instance"`
	Config   DeploymentEvent         `json:"config"`
	Status   ScheduledInstanceStatus `json:"status"`
}

type ScheduledInstanceSnapshot struct {
	Items []*ScheduledInstanceState `json:"items,omitempty"`
}

type PreparerStatus struct {
	DeploymentSpecVersion int32        `json:"deployment_spec_version"`
	Artifact              string       `json:"artifact,omitempty"`
	Inputs                InputsStatus `json:"inputs"`
	Image                 ImageStatus  `json:"image"`
}

type RunnerStatus struct {
	DeploymentSpecVersion int32         `json:"deployment_spec_version"`
	RunningPid            int32         `json:"running_pid"`
	RunningArtifact       string        `json:"running_artifact,omitempty"`
	Status                RunningStatus `json:"status"`
	NumberOfRestarts      int32         `json:"number_of_restarts"`
	LastRestartAt         time.Time     `json:"last_restart_at"`
	RunningVersion        string        `json:"running_version,omitempty"`
	NetworkDiagnostics    []string      `json:"network_diagnostics,omitempty"`
	ExitCode              *int32        `json:"exit_code,omitempty"`
}

type ScheduledInstanceEvent struct {
	ScheduledInstanceID int32             `json:"scheduled_instance_id"`
	Version             int32             `json:"version"`
	Seq                 int64             `json:"seq"`
	EventID             int64             `json:"event_id"`
	Author              int32             `json:"author"`
	EventType           EventType         `json:"event_type"`
	CreatedTime         int64             `json:"created_time"`
	EventTime           int64             `json:"event_time"`
	Value               ScheduledInstance `json:"value"`
}

type DeploymentUpdateRequestV2 struct {
	DeploymentID        int32                `json:"deployment_id"`
	ExpectedVersion     int32                `json:"expected_version"`
	VersionOnlyUpdate   *VersionOnlyUpdate   `json:"version_only_update"`
	RunningOnlyUpdate   *RunningOnlyUpdate   `json:"running_only_update"`
	SpecUpdate          *SpecUpdate          `json:"spec_update"`
	AssignedSpaceUpdate *AssignedSpaceUpdate `json:"assigned_space_update"`
}

type VersionOnlyUpdate struct {
	TargetVersion string `json:"target_version,omitempty"`
}

type RunningOnlyUpdate struct {
	DesiredRunning bool `json:"desired_running"`
}

type SpecUpdate struct {
	Spec DeploymentSpec `json:"spec"`
}

type AssignedSpaceUpdate struct {
	SpaceID int32 `json:"space_id"`
}

type DeploymentCreateRequest struct {
	Name    string         `json:"name,omitempty"`
	SpaceID int32          `json:"space_id"`
	Spec    DeploymentSpec `json:"spec"`
	NodeID  int32          `json:"node_id"`
}

type DeploymentHistoryRequest struct {
	DeploymentID int32 `json:"deployment_id"`
}

type RecentlyDeletedDeploymentsRequest struct {
	Limit int32 `json:"limit"`
}

type RecentlyDeletedDeployments struct {
	Items []*DeploymentEvent `json:"items,omitempty"`
}

type DeploymentDeleteRequest struct {
	DeploymentID int32 `json:"deployment_id"`
	Version      int32 `json:"version"`
}

type Version struct {
	ID     string    `json:"id,omitempty"`
	Label  string    `json:"label,omitempty"`
	Author string    `json:"author,omitempty"`
	Time   time.Time `json:"time"`
}

type DeploymentVersions struct {
	DeploymentID   int32                             `json:"deployment_id"`
	NixDockerBuild *DeploymentNixDockerBuildVersions `json:"nix_docker_build"`
	GithubRelease  *DeploymentGithubReleaseVersions  `json:"github_release"`
	ContainerImage *DeploymentContainerImageVersions `json:"container_image"`
}

type DeploymentNixDockerBuildVersions struct {
	Branches       []string   `json:"branches,omitempty"`
	SelectedBranch string     `json:"selected_branch,omitempty"`
	Commits        []*Version `json:"commits,omitempty"`
}

type DeploymentGithubReleaseVersions struct {
	Releases []*Version `json:"releases,omitempty"`
}

type DeploymentContainerImageVersions struct {
	Tags []*Version `json:"tags,omitempty"`
}

type DeploymentVersionsRequest struct {
	DeploymentID   int32  `json:"deployment_id"`
	SelectedBranch string `json:"selected_branch,omitempty"`
}

type RepoValidateRequest struct {
	NixDockerBuild *ValidateNixDockerBuildSource `json:"nix_docker_build"`
	ContainerImage *ValidateContainerImageSource `json:"container_image"`
}

type ValidateNixDockerBuildSource struct {
	RepoUrl                  string   `json:"repo_url,omitempty"`
	SelectedBranch           string   `json:"selected_branch,omitempty"`
	SelectedCommit           *Version `json:"selected_commit"`
	SelectedFlakePath        string   `json:"selected_flake_path,omitempty"`
	RefreshAvailableBranches bool     `json:"refresh_available_branches"`
	RefreshAvailableCommits  bool     `json:"refresh_available_commits"`
	CheckRepo                bool     `json:"check_repo"`
	CheckBranch              bool     `json:"check_branch"`
	CheckCommit              bool     `json:"check_commit"`
	CheckFlakePath           bool     `json:"check_flake_path"`
}

type ValidateNixDockerBuildSourceResponse struct {
	CheckedRepoUrl    string            `json:"checked_repo_url,omitempty"`
	GitRepository     ValidationResult  `json:"git_repository"`
	CheckedBranch     string            `json:"checked_branch,omitempty"`
	BranchCheck       ValidationResult  `json:"branch_check"`
	CheckedCommit     *Version          `json:"checked_commit"`
	CommitCheck       ValidationResult  `json:"commit_check"`
	CheckedFlakePath  string            `json:"checked_flake_path,omitempty"`
	NixFlakeFile      ValidationResult  `json:"nix_flake_file"`
	AvailableBranches AvailableBranches `json:"available_branches"`
	AvailableCommits  AvailableCommits  `json:"available_commits"`
}

type AvailableCommits struct {
	Loaded       bool       `json:"loaded"`
	Branch       string     `json:"branch,omitempty"`
	Errormessage *string    `json:"errormessage,omitempty"`
	Commits      []*Version `json:"commits,omitempty"`
}

type AvailableBranches struct {
	Loaded       bool     `json:"loaded"`
	Errormessage *string  `json:"errormessage,omitempty"`
	Branches     []string `json:"branches,omitempty"`
}

type ValidationResult struct {
	Checked bool   `json:"checked"`
	Ok      bool   `json:"ok"`
	Message string `json:"message,omitempty"`
}

type ValidateContainerImageSource struct {
	Image           string `json:"image,omitempty"`
	RefreshVersions bool   `json:"refresh_versions"`
}

type RepoValidateResponse struct {
	NixDockerBuild *ValidateNixDockerBuildSourceResponse `json:"nix_docker_build"`
	ContainerImage *ValidateContainerImageSourceResponse `json:"container_image"`
}

type ValidateContainerImageSourceResponse struct {
	Image ValidationResult `json:"image"`
	Tags  []*Version       `json:"tags,omitempty"`
}

type DeploymentGetRequest struct {
	ID int32 `json:"id"`
}

type DeploymentGetResponse struct {
	DeploymentEvent         *DeploymentEvent           `json:"deployment_event"`
	ScheduledInstanceEvents []*ScheduledInstanceEvent  `json:"scheduled_instance_events,omitempty"`
	InstanceStatuses        []*ScheduledInstanceStatus `json:"instance_statuses,omitempty"`
}

type DeploymentHistoryEntry struct {
	Config *DeploymentEvent         `json:"config"`
	Status *ScheduledInstanceStatus `json:"status"`
}

type DeploymentHistory struct {
	Entries []*DeploymentHistoryEntry `json:"entries,omitempty"`
}

type DeploymentRunReportRequest struct {
	ScheduledInstanceID int32 `json:"scheduled_instance_id"`
	Run                 int32 `json:"run"`
}

type DeploymentRunReport struct {
	DeploymentID          int32         `json:"deployment_id"`
	DeploymentSpecVersion int32         `json:"deployment_spec_version"`
	NodeID                int32         `json:"node_id"`
	InstanceOrdinal       int32         `json:"instance_ordinal"`
	Run                   int32         `json:"run"`
	Running               bool          `json:"running"`
	StartedAt             time.Time     `json:"started_at"`
	StoppedAt             time.Time     `json:"stopped_at"`
	ExitCode              *int32        `json:"exit_code,omitempty"`
	LogLines              []string      `json:"log_lines,omitempty"`
	Warnings              []string      `json:"warnings,omitempty"`
	Status                RunningStatus `json:"status"`
}

type RawLogLine struct {
	Time            int64  `json:"time"`
	Version         int32  `json:"version"`
	Run             int32  `json:"run"`
	Stream          int32  `json:"stream"`
	Line            []byte `json:"line"`
	Deployment      int32  `json:"deployment"`
	Node            int32  `json:"node"`
	InstanceOrdinal int32  `json:"instance_ordinal"`
	Seq             int64  `json:"seq"`
}

type LogRecord struct {
	Time            int64             `json:"time"`
	Level           string            `json:"level,omitempty"`
	Msg             string            `json:"msg,omitempty"`
	Fields          map[string]string `json:"fields,omitempty"`
	Raw             []byte            `json:"raw"`
	Version         int32             `json:"version"`
	Stream          int32             `json:"stream"`
	InstanceOrdinal int32             `json:"instance_ordinal"`
	Run             int32             `json:"run"`
	Node            int32             `json:"node"`
	Seq             int64             `json:"seq"`
}

type PrepareOutputRequest struct {
	DeploymentID int32 `json:"deployment_id"`
	SpecVersion  int32 `json:"spec_version"`
}

type PrepareOutputChunk struct {
	Data []byte `json:"data"`
}

type DeploymentLogRequest struct {
	PreparerOutput *PrepareOutputRequest `json:"preparer_output"`
	RequestID      string                `json:"request_id,omitempty"`
}

type LogFilter struct {
	Field  string   `json:"field,omitempty"`
	Op     string   `json:"op,omitempty"`
	Value  string   `json:"value,omitempty"`
	Values []string `json:"values,omitempty"`
	Text   bool     `json:"text"`
}

type LogQueryRequest struct {
	DeploymentID     int32        `json:"deployment_id"`
	TargetNodeID     int32        `json:"target_node_id"`
	SpecVersion      int32        `json:"spec_version"`
	TimeStart        time.Time    `json:"time_start"`
	TimeEnd          time.Time    `json:"time_end"`
	Filters          []*LogFilter `json:"filters,omitempty"`
	Limit            int32        `json:"limit"`
	HistogramBuckets int32        `json:"histogram_buckets"`
	IncludeRaw       bool         `json:"include_raw"`
	Order            string       `json:"order,omitempty"`
	RequestID        string       `json:"request_id,omitempty"`
}

type LogQueryStats struct {
	TimeStart    time.Time `json:"time_start"`
	TimeEnd      time.Time `json:"time_end"`
	ScannedRows  int64     `json:"scanned_rows"`
	MatchedRows  int64     `json:"matched_rows"`
	ReturnedRows int32     `json:"returned_rows"`
	Truncated    bool      `json:"truncated"`
	TookMs       int32     `json:"took_ms"`
	SampledRows  int64     `json:"sampled_rows"`
}

type LogHistogramSeries struct {
	Level  string  `json:"level,omitempty"`
	Counts []int64 `json:"counts,omitempty"`
}

type LogHistogram struct {
	BucketMs  int64                 `json:"bucket_ms"`
	StartTime time.Time             `json:"start_time"`
	Series    []*LogHistogramSeries `json:"series,omitempty"`
}

type LogFieldValueCount struct {
	Value string `json:"value,omitempty"`
	Count int64  `json:"count"`
}

type LogFieldStats struct {
	Field    string                `json:"field,omitempty"`
	Coverage float64               `json:"coverage"`
	Distinct int64                 `json:"distinct"`
	Top      []*LogFieldValueCount `json:"top,omitempty"`
	Other    int64                 `json:"other"`
}

type LogQueryResponse struct {
	Stats     *LogQueryStats   `json:"stats"`
	Histogram *LogHistogram    `json:"histogram"`
	Fields    []*LogFieldStats `json:"fields,omitempty"`
	Records   []*LogRecord     `json:"records,omitempty"`
	Warnings  []string         `json:"warnings,omitempty"`
}

type MetricsSample struct {
	Time                int64    `json:"time"`
	DeploymentID        int32    `json:"deployment_id"`
	ScheduledInstanceID int32    `json:"scheduled_instance_id"`
	Ordinal             int32    `json:"ordinal"`
	SpecVersion         int32    `json:"spec_version"`
	Run                 int32    `json:"run"`
	NodeID              int32    `json:"node_id"`
	Terminal            bool     `json:"terminal"`
	CpuUsageUsec        *int64   `json:"cpu_usage_usec,omitempty"`
	CpuUserUsec         *int64   `json:"cpu_user_usec,omitempty"`
	CpuSystemUsec       *int64   `json:"cpu_system_usec,omitempty"`
	CpuThrottledUsec    *int64   `json:"cpu_throttled_usec,omitempty"`
	CpuNrThrottled      *int64   `json:"cpu_nr_throttled,omitempty"`
	MemCurrent          *int64   `json:"mem_current,omitempty"`
	MemPeak             *int64   `json:"mem_peak,omitempty"`
	MemAnon             *int64   `json:"mem_anon,omitempty"`
	MemFile             *int64   `json:"mem_file,omitempty"`
	MemKernel           *int64   `json:"mem_kernel,omitempty"`
	MemShmem            *int64   `json:"mem_shmem,omitempty"`
	MemOom              *int64   `json:"mem_oom,omitempty"`
	MemOomKill          *int64   `json:"mem_oom_kill,omitempty"`
	IoReadBytes         *int64   `json:"io_read_bytes,omitempty"`
	IoWriteBytes        *int64   `json:"io_write_bytes,omitempty"`
	IoReadOps           *int64   `json:"io_read_ops,omitempty"`
	IoWriteOps          *int64   `json:"io_write_ops,omitempty"`
	Pids                *int64   `json:"pids,omitempty"`
	PsiCpuSomeAvg10     *float64 `json:"psi_cpu_some_avg10,omitempty"`
	PsiCpuSomeAvg60     *float64 `json:"psi_cpu_some_avg60,omitempty"`
	PsiCpuSomeAvg300    *float64 `json:"psi_cpu_some_avg300,omitempty"`
	PsiCpuSomeTotalUsec *int64   `json:"psi_cpu_some_total_usec,omitempty"`
	PsiCpuFullAvg10     *float64 `json:"psi_cpu_full_avg10,omitempty"`
	PsiCpuFullAvg60     *float64 `json:"psi_cpu_full_avg60,omitempty"`
	PsiCpuFullAvg300    *float64 `json:"psi_cpu_full_avg300,omitempty"`
	PsiCpuFullTotalUsec *int64   `json:"psi_cpu_full_total_usec,omitempty"`
	PsiMemSomeAvg10     *float64 `json:"psi_mem_some_avg10,omitempty"`
	PsiMemSomeAvg60     *float64 `json:"psi_mem_some_avg60,omitempty"`
	PsiMemSomeAvg300    *float64 `json:"psi_mem_some_avg300,omitempty"`
	PsiMemSomeTotalUsec *int64   `json:"psi_mem_some_total_usec,omitempty"`
	PsiMemFullAvg10     *float64 `json:"psi_mem_full_avg10,omitempty"`
	PsiMemFullAvg60     *float64 `json:"psi_mem_full_avg60,omitempty"`
	PsiMemFullAvg300    *float64 `json:"psi_mem_full_avg300,omitempty"`
	PsiMemFullTotalUsec *int64   `json:"psi_mem_full_total_usec,omitempty"`
	PsiIoSomeAvg10      *float64 `json:"psi_io_some_avg10,omitempty"`
	PsiIoSomeAvg60      *float64 `json:"psi_io_some_avg60,omitempty"`
	PsiIoSomeAvg300     *float64 `json:"psi_io_some_avg300,omitempty"`
	PsiIoSomeTotalUsec  *int64   `json:"psi_io_some_total_usec,omitempty"`
	PsiIoFullAvg10      *float64 `json:"psi_io_full_avg10,omitempty"`
	PsiIoFullAvg60      *float64 `json:"psi_io_full_avg60,omitempty"`
	PsiIoFullAvg300     *float64 `json:"psi_io_full_avg300,omitempty"`
	PsiIoFullTotalUsec  *int64   `json:"psi_io_full_total_usec,omitempty"`
	NetRxBytes          *int64   `json:"net_rx_bytes,omitempty"`
	NetRxPackets        *int64   `json:"net_rx_packets,omitempty"`
	NetRxDropped        *int64   `json:"net_rx_dropped,omitempty"`
	NetTxBytes          *int64   `json:"net_tx_bytes,omitempty"`
	NetTxPackets        *int64   `json:"net_tx_packets,omitempty"`
	NetTxDropped        *int64   `json:"net_tx_dropped,omitempty"`
	TcpEstablished      *int64   `json:"tcp_established,omitempty"`
	TcpListen           *int64   `json:"tcp_listen,omitempty"`
	TcpTimeWait         *int64   `json:"tcp_time_wait,omitempty"`
	TcpCloseWait        *int64   `json:"tcp_close_wait,omitempty"`
	TcpOther            *int64   `json:"tcp_other,omitempty"`
	OpenFds             *int64   `json:"open_fds,omitempty"`
}

type MetricsQueryRequest struct {
	DeploymentID        int32     `json:"deployment_id"`
	TargetNodeID        int32     `json:"target_node_id"`
	ScheduledInstanceID int32     `json:"scheduled_instance_id"`
	SpecVersion         int32     `json:"spec_version"`
	Run                 int32     `json:"run"`
	TimeStart           time.Time `json:"time_start"`
	TimeEnd             time.Time `json:"time_end"`
	StepMs              int64     `json:"step_ms"`
	Fields              []string  `json:"fields,omitempty"`
	RequestID           string    `json:"request_id,omitempty"`
}

type MetricsSeries struct {
	ScheduledInstanceID int32     `json:"scheduled_instance_id"`
	Ordinal             int32     `json:"ordinal"`
	SpecVersion         int32     `json:"spec_version"`
	Run                 int32     `json:"run"`
	NodeID              int32     `json:"node_id"`
	Field               string    `json:"field,omitempty"`
	Kind                int32     `json:"kind"`
	Values              []float64 `json:"values,omitempty"`
}

type MetricsQueryResponse struct {
	TimeStart   time.Time        `json:"time_start"`
	StepMs      int64            `json:"step_ms"`
	Buckets     int32            `json:"buckets"`
	Series      []*MetricsSeries `json:"series,omitempty"`
	ScannedRows int64            `json:"scanned_rows"`
	TookMs      int32            `json:"took_ms"`
	Warnings    []string         `json:"warnings,omitempty"`
}

type MetricsLatestRequest struct {
	RequestID string `json:"request_id,omitempty"`
}

type MetricsRate struct {
	Field     string  `json:"field,omitempty"`
	PerSecond float64 `json:"per_second"`
}

type MetricsLatestEntry struct {
	Sample *MetricsSample `json:"sample"`
	Rates  []*MetricsRate `json:"rates,omitempty"`
}

type MetricsLatestResponse struct {
	Entries  []*MetricsLatestEntry `json:"entries,omitempty"`
	Warnings []string              `json:"warnings,omitempty"`
}

type SecretEvent struct {
	SecretID     int32     `json:"secret_id"`
	Version      int32     `json:"version"`
	Seq          int64     `json:"seq"`
	EventID      int64     `json:"event_id"`
	Author       int32     `json:"author"`
	EventType    EventType `json:"event_type"`
	CreatedTime  int64     `json:"created_time"`
	EventTime    int64     `json:"event_time"`
	ValueVersion int32     `json:"value_version"`
	SpaceVersion int32     `json:"space_version"`
	Value        Secret    `json:"value"`
}

type Secret struct {
	Fs      *SecretFs `json:"fs"`
	SpaceID int32     `json:"space_id"`
}

type SecretFs struct {
	Name        string `json:"name,omitempty"`
	DirectoryID int32  `json:"directory_id"`
}

type SecretEventList struct {
	Items []*SecretEvent `json:"items,omitempty"`
}

type SecretCreateRequest struct {
	Name             string `json:"name,omitempty"`
	Value            []byte `json:"value"`
	SpaceID          int32  `json:"space_id"`
	ValueDirectoryID int32  `json:"value_directory_id"`
}

type SecretSetRequest struct {
	SecretID                     int32                       `json:"secret_id"`
	Value                        []byte                      `json:"value"`
	UpdateReferencingDeployments bool                        `json:"update_referencing_deployments"`
	ReferencingDeployments       []*DeploymentSpecVersionRef `json:"referencing_deployments,omitempty"`
}

type SecretPasswordSpec struct {
	Length         int32 `json:"length"`
	IncludeSymbols bool  `json:"include_symbols"`
}

type SecretGenerateRequest struct {
	Name     string              `json:"name,omitempty"`
	SpaceID  int32               `json:"space_id"`
	Password *SecretPasswordSpec `json:"password"`
}

type SecretRenameRequest struct {
	SecretID int32  `json:"secret_id"`
	NewName  string `json:"new_name,omitempty"`
}

type SecretMoveRequest struct {
	SecretID         int32 `json:"secret_id"`
	ValueDirectoryID int32 `json:"value_directory_id"`
	SpaceID          int32 `json:"space_id"`
}

type SecretDeleteRequest struct {
	SecretID int32 `json:"secret_id"`
}

type SecretRevealRequest struct {
	ID int32 `json:"id"`
}

type SecretRevealResponse struct {
	Value []byte `json:"value"`
}

type SecretsStatusResponse struct {
	Unlocked           bool `json:"unlocked"`
	RecoveryConfigured bool `json:"recovery_configured"`
}

type SecretRecoveryCodeResponse struct {
	Code string `json:"code,omitempty"`
}

type SecretUnlockRequest struct {
	Code string `json:"code,omitempty"`
}

type ConfigEvent struct {
	ConfigID     int32     `json:"config_id"`
	Version      int32     `json:"version"`
	Seq          int64     `json:"seq"`
	EventID      int64     `json:"event_id"`
	Author       int32     `json:"author"`
	EventType    EventType `json:"event_type"`
	CreatedTime  int64     `json:"created_time"`
	EventTime    int64     `json:"event_time"`
	ValueVersion int32     `json:"value_version"`
	SpaceVersion int32     `json:"space_version"`
	Value        Config    `json:"value"`
}

type Config struct {
	Fs      *ConfigFs `json:"fs"`
	SpaceID int32     `json:"space_id"`
	Value   string    `json:"value,omitempty"`
}

type ConfigFs struct {
	Name        string `json:"name,omitempty"`
	DirectoryID int32  `json:"directory_id"`
}

type ValueDirectory struct {
	ID        int32     `json:"id"`
	SpaceID   int32     `json:"space_id"`
	Name      string    `json:"name,omitempty"`
	ParentID  int32     `json:"parent_id"`
	CreatedAt time.Time `json:"created_at"`
	Author    int32     `json:"author"`
	Deleted   bool      `json:"deleted"`
}

type ConfigEventList struct {
	Items []*ConfigEvent `json:"items,omitempty"`
}

type ConfigCreateRequest struct {
	Name             string `json:"name,omitempty"`
	Value            string `json:"value,omitempty"`
	SpaceID          int32  `json:"space_id"`
	ValueDirectoryID int32  `json:"value_directory_id"`
}

type ConfigSetRequest struct {
	ConfigID                     int32                       `json:"config_id"`
	Value                        string                      `json:"value,omitempty"`
	UpdateReferencingDeployments bool                        `json:"update_referencing_deployments"`
	ReferencingDeployments       []*DeploymentSpecVersionRef `json:"referencing_deployments,omitempty"`
}

type ConfigRenameRequest struct {
	ConfigID int32  `json:"config_id"`
	NewName  string `json:"new_name,omitempty"`
}

type ConfigDeleteRequest struct {
	ConfigID int32 `json:"config_id"`
}

type ConfigMoveRequest struct {
	ConfigID         int32 `json:"config_id"`
	ValueDirectoryID int32 `json:"value_directory_id"`
	SpaceID          int32 `json:"space_id"`
}

type AssetEvent struct {
	AssetID      int32     `json:"asset_id"`
	Version      int32     `json:"version"`
	Seq          int64     `json:"seq"`
	EventID      int64     `json:"event_id"`
	Author       int32     `json:"author"`
	EventType    EventType `json:"event_type"`
	CreatedTime  int64     `json:"created_time"`
	EventTime    int64     `json:"event_time"`
	ValueVersion int32     `json:"value_version"`
	SpaceVersion int32     `json:"space_version"`
	Value        Asset     `json:"value"`
}

type Asset struct {
	Fs        *AssetFs `json:"fs"`
	SpaceID   int32    `json:"space_id"`
	Sha256    string   `json:"sha256,omitempty"`
	SizeBytes int64    `json:"size_bytes"`
}

type AssetFs struct {
	Key         string `json:"key,omitempty"`
	DirectoryID int32  `json:"directory_id"`
}

type AssetDirectory struct {
	ID        int32     `json:"id"`
	SpaceID   int32     `json:"space_id"`
	Key       string    `json:"key,omitempty"`
	ParentID  int32     `json:"parent_id"`
	CreatedAt time.Time `json:"created_at"`
	Author    int32     `json:"author"`
	Deleted   bool      `json:"deleted"`
}

type AssetEventList struct {
	Items []*AssetEvent `json:"items,omitempty"`
}

type AssetRenameRequest struct {
	AssetID int32  `json:"asset_id"`
	NewKey  string `json:"new_key,omitempty"`
}

type AssetDeleteRequest struct {
	AssetID int32 `json:"asset_id"`
}

type AssetMoveRequest struct {
	AssetID          int32 `json:"asset_id"`
	AssetDirectoryID int32 `json:"asset_directory_id"`
	SpaceID          int32 `json:"space_id"`
}

type ValueDirectoryList struct {
	Items []*ValueDirectory `json:"items,omitempty"`
}

type ValueDirectoryCreateRequest struct {
	SpaceID  int32  `json:"space_id"`
	ParentID int32  `json:"parent_id"`
	Name     string `json:"name,omitempty"`
}

type ValueDirectoryMoveRequest struct {
	DirectoryID int32 `json:"directory_id"`
	NewParentID int32 `json:"new_parent_id"`
	SpaceID     int32 `json:"space_id"`
}

type ValueDirectoryRenameRequest struct {
	DirectoryID int32  `json:"directory_id"`
	NewName     string `json:"new_name,omitempty"`
}

type ValueDirectoryDeleteRequest struct {
	DirectoryID int32 `json:"directory_id"`
}

type AssetDirectoryList struct {
	Items []*AssetDirectory `json:"items,omitempty"`
}

type AssetDirectoryCreateRequest struct {
	SpaceID  int32  `json:"space_id"`
	ParentID int32  `json:"parent_id"`
	Key      string `json:"key,omitempty"`
}

type AssetDirectoryMoveRequest struct {
	DirectoryID int32 `json:"directory_id"`
	NewParentID int32 `json:"new_parent_id"`
	SpaceID     int32 `json:"space_id"`
}

type AssetDirectoryRenameRequest struct {
	DirectoryID int32  `json:"directory_id"`
	NewKey      string `json:"new_key,omitempty"`
}

type AssetDirectoryDeleteRequest struct {
	DirectoryID int32 `json:"directory_id"`
}

type Space struct {
	ID      int32  `json:"id"`
	Name    string `json:"name,omitempty"`
	Deleted bool   `json:"deleted"`
}

type SpaceList struct {
	Items []*Space `json:"items,omitempty"`
}

type SpaceSetRequest struct {
	ID   int32  `json:"id"`
	Name string `json:"name,omitempty"`
}

type SpaceDeleteRequest struct {
	ID int32 `json:"id"`
}

type User struct {
	ID          int32  `json:"id"`
	Name        string `json:"name,omitempty"`
	CreatedAt   int64  `json:"created_at"`
	LastLoginAt int64  `json:"last_login_at"`
}

type WebAuthnCredential struct {
	ID   []byte `json:"id"`
	Data []byte `json:"data"`
}

type InternalUser struct {
	ID          int32                 `json:"id"`
	WebAuthNID  []byte                `json:"web_auth_n_id"`
	Name        string                `json:"name,omitempty"`
	Credentials []*WebAuthnCredential `json:"credentials,omitempty"`
	Delegated   bool                  `json:"delegated"`
}

type PublicKeyRecord struct {
	Kid      string `json:"kid,omitempty"`
	KeyBytes []byte `json:"key_bytes"`
}

type MasterPasswordRequest struct {
	Password string `json:"password,omitempty"`
	Username string `json:"username,omitempty"`
}

type MasterPasswordVerifyRequest struct {
	Password string `json:"password,omitempty"`
}

type MasterPasswordSaveRequest struct {
	Password string `json:"password,omitempty"`
}

type PasswordLoginRequest struct {
	Username string `json:"username,omitempty"`
	Password string `json:"password,omitempty"`
}

type AuthMethodsResponse struct {
	PasskeyLoginEnabled  bool `json:"passkey_login_enabled"`
	PasswordLoginEnabled bool `json:"password_login_enabled"`
	LocalCaAvailable     bool `json:"local_ca_available"`
}

type LoginResponse struct {
	Token  string    `json:"token,omitempty"`
	UserID int32     `json:"user_id"`
	Scopes []string  `json:"scopes,omitempty"`
	Name   string    `json:"name,omitempty"`
	Expiry time.Time `json:"expiry"`
}

type WebAuthNOptionsResponse struct {
	SessionID   string `json:"session_id,omitempty"`
	OptionsJson []byte `json:"options_json"`
}

type WebAuthNFinishRequest struct {
	SessionID      string `json:"session_id,omitempty"`
	CredentialJson []byte `json:"credential_json"`
}

type AgentSession struct {
	UserID            int32              `json:"user_id"`
	ID                string             `json:"id,omitempty"`
	CreatedAt         time.Time          `json:"created_at"`
	ExpiresAt         time.Time          `json:"expires_at"`
	TokenPrefix       string             `json:"token_prefix,omitempty"`
	Scopes            []string           `json:"scopes,omitempty"`
	Status            AgentSessionStatus `json:"status"`
	RequestingAddress string             `json:"requesting_address,omitempty"`
	ApprovalCode      string             `json:"approval_code,omitempty"`
	ApprovedAt        time.Time          `json:"approved_at"`
}

type PersonalSession struct {
	ID                string    `json:"id,omitempty"`
	CreatedAt         time.Time `json:"created_at"`
	ExpiresAt         time.Time `json:"expires_at"`
	RevokedAt         time.Time `json:"revoked_at"`
	RequestingAddress string    `json:"requesting_address,omitempty"`
	UserAgent         string    `json:"user_agent,omitempty"`
	LastActiveAt      time.Time `json:"last_active_at"`
	Current           bool      `json:"current"`
}

type AgentSessionRequest struct {
	ID               string             `json:"id,omitempty"`
	ApprovalCode     string             `json:"approval_code,omitempty"`
	Status           AgentSessionStatus `json:"status"`
	RequestExpiresAt time.Time          `json:"request_expires_at"`
}

type AgentSessionList struct {
	Items []*AgentSession `json:"items,omitempty"`
}

type AgentSessionCreated struct {
	Token   string        `json:"token,omitempty"`
	Session *AgentSession `json:"session"`
}

type AgentSessionRevokeRequest struct {
	ID string `json:"id,omitempty"`
}

type PersonalSessionList struct {
	Items []*PersonalSession `json:"items,omitempty"`
}

type PersonalSessionRevokeRequest struct {
	ID string `json:"id,omitempty"`
}

type AgentSessionRequestStartRequest struct {
	UserID int32 `json:"user_id"`
}

type AgentSessionGetRequest struct {
	ID string `json:"id,omitempty"`
}

type AgentSessionPickup struct {
	Status    AgentSessionStatus `json:"status"`
	Token     string             `json:"token,omitempty"`
	ExpiresAt time.Time          `json:"expires_at"`
}

type AgentSessionApproveRequest struct {
	ID string `json:"id,omitempty"`
}

type AuthzSelector struct {
	Wildcard   bool    `json:"wildcard"`
	ArgumentID int64   `json:"argument_id"`
	Include    []int64 `json:"include,omitempty"`
	Exclude    []int64 `json:"exclude,omitempty"`
}

type AuthzRule struct {
	Permissions       *AuthzSelector `json:"permissions"`
	Spaces            *AuthzSelector `json:"spaces"`
	EntityTypes       *AuthzSelector `json:"entity_types"`
	EntityRefs        *AuthzSelector `json:"entity_refs"`
	DelegationAllowed bool           `json:"delegation_allowed"`
}

type AuthzTemplateArgument struct {
	ID   int64  `json:"id"`
	Name string `json:"name,omitempty"`
}

type AuthzRuleTemplate struct {
	Arguments []*AuthzTemplateArgument `json:"arguments,omitempty"`
	Rules     []*AuthzRule             `json:"rules,omitempty"`
}

type AuthzRuleTemplateRecord struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name,omitempty"`
	Builtin   bool               `json:"builtin"`
	Deleted   bool               `json:"deleted"`
	Author    int64              `json:"author"`
	CreatedAt int64              `json:"created_at"`
	Template  *AuthzRuleTemplate `json:"template"`
}

type AuthzArgumentBinding struct {
	ArgumentID int64   `json:"argument_id"`
	Values     []int64 `json:"values,omitempty"`
}

type AuthzGrant struct {
	Args []*AuthzArgumentBinding `json:"args,omitempty"`
	Rule *AuthzRule              `json:"rule"`
}

type AuthzGrantRecord struct {
	ID         int64       `json:"id"`
	UserID     int64       `json:"user_id"`
	TemplateID int64       `json:"template_id"`
	Author     int64       `json:"author"`
	CreatedAt  int64       `json:"created_at"`
	Grant      *AuthzGrant `json:"grant"`
}

type AuthzGlobalRule struct {
	Permissions       *AuthzSelector `json:"permissions"`
	Spaces            *AuthzSelector `json:"spaces"`
	EntityTypes       *AuthzSelector `json:"entity_types"`
	EntityRefs        *AuthzSelector `json:"entity_refs"`
	DelegatedOnly     bool           `json:"delegated_only"`
	DelegationAllowed bool           `json:"delegation_allowed"`
	Deny              bool           `json:"deny"`
}

type AuthzGlobalRuleRecord struct {
	ID        int64            `json:"id"`
	Name      string           `json:"name,omitempty"`
	Author    int64            `json:"author"`
	CreatedAt int64            `json:"created_at"`
	Rule      *AuthzGlobalRule `json:"rule"`
}

type AuthzGrantValue struct {
	UserID     int64       `json:"user_id"`
	TemplateID int64       `json:"template_id"`
	Grant      *AuthzGrant `json:"grant"`
}

type AuthzGrantEvent struct {
	AuthzGrantID int64           `json:"authz_grant_id"`
	Version      int32           `json:"version"`
	Seq          int64           `json:"seq"`
	EventID      int64           `json:"event_id"`
	Author       int64           `json:"author"`
	EventType    EventType       `json:"event_type"`
	CreatedTime  int64           `json:"created_time"`
	EventTime    int64           `json:"event_time"`
	Value        AuthzGrantValue `json:"value"`
}

type AuthzRuleTemplateList struct {
	Items []*AuthzRuleTemplateRecord `json:"items,omitempty"`
}

type AuthzRuleTemplateCreateRequest struct {
	Name     string             `json:"name,omitempty"`
	Template *AuthzRuleTemplate `json:"template"`
}

type AuthzRuleTemplateUpdateRequest struct {
	ID       int64              `json:"id"`
	Name     string             `json:"name,omitempty"`
	Template *AuthzRuleTemplate `json:"template"`
}

type AuthzRuleTemplateDeleteRequest struct {
	ID int64 `json:"id"`
}

type AuthzGrantList struct {
	Items []*AuthzGrantRecord `json:"items,omitempty"`
}

type AuthzGrantCreateRequest struct {
	UserID     int64       `json:"user_id"`
	TemplateID int64       `json:"template_id"`
	Grant      *AuthzGrant `json:"grant"`
}

type AuthzGrantDeleteRequest struct {
	UserID int64 `json:"user_id"`
	ID     int64 `json:"id"`
}

type AuthzGlobalRuleList struct {
	Items []*AuthzGlobalRuleRecord `json:"items,omitempty"`
}

type AuthzGlobalRuleCreateRequest struct {
	Name string           `json:"name,omitempty"`
	Rule *AuthzGlobalRule `json:"rule"`
}

type AuthzGlobalRuleDeleteRequest struct {
	ID int64 `json:"id"`
}

type NodeReported struct {
	Identifier           string   `json:"identifier,omitempty"`
	UnderlayAddress      string   `json:"underlay_address,omitempty"`
	WgPublicKey          string   `json:"wg_public_key,omitempty"`
	HostAddresses        []string `json:"host_addresses,omitempty"`
	HostAddressesUnknown bool     `json:"host_addresses_unknown"`
}

type NodeOperator struct {
	Name          string  `json:"name,omitempty"`
	Roles         []int32 `json:"roles,omitempty"`
	AllowedSpaces []int32 `json:"allowed_spaces,omitempty"`
	EnrolledTime  int64   `json:"enrolled_time"`
}

type Node struct {
	Status                NodeLifecycleStatus `json:"status"`
	EnrollmentRequestedAt int64               `json:"enrollment_requested_at"`
	Operator              NodeOperator        `json:"operator"`
	Reported              NodeReported        `json:"reported"`
}

type NodeEvent struct {
	NodeID      int32     `json:"node_id"`
	Version     int32     `json:"version"`
	Seq         int64     `json:"seq"`
	EventID     int64     `json:"event_id"`
	Author      int32     `json:"author"`
	EventType   EventType `json:"event_type"`
	CreatedTime int64     `json:"created_time"`
	EventTime   int64     `json:"event_time"`
	Value       Node      `json:"value"`
}

type NodeStatus struct {
	NodeID            int32     `json:"node_id"`
	UpdatedAt         time.Time `json:"updated_at"`
	IsConnected       bool      `json:"is_connected"`
	LastConnectedAt   time.Time `json:"last_connected_at"`
	RemoteAddress     string    `json:"remote_address,omitempty"`
	OpendeployVersion string    `json:"opendeploy_version,omitempty"`
}

type EnrollmentRequestStatus struct {
	ID                  int32               `json:"id"`
	CreatedAt           time.Time           `json:"created_at"`
	RequestingIpAddress string              `json:"requesting_ip_address,omitempty"`
	RequestingMachineID string              `json:"requesting_machine_id,omitempty"`
	OpendeployVersion   string              `json:"opendeploy_version,omitempty"`
	UnderlayAddress     string              `json:"underlay_address,omitempty"`
	Status              NodeLifecycleStatus `json:"status"`
	IsConnected         bool                `json:"is_connected"`
}

type NodeEnrollmentInfo struct {
	EnrollmentTlsSpkiSha256 string `json:"enrollment_tls_spki_sha256,omitempty"`
}

type NodeRenameRequest struct {
	Identifier string `json:"identifier,omitempty"`
	Name       string `json:"name,omitempty"`
}

type NodeAllowedSpacesRequest struct {
	Identifier string  `json:"identifier,omitempty"`
	SpaceIds   []int32 `json:"space_ids,omitempty"`
}

type NodeEventList struct {
	Items []*NodeEvent `json:"items,omitempty"`
}

type NodeStatusList struct {
	Items []*NodeStatus `json:"items,omitempty"`
}

type AcmeState struct {
	Seq          int64                `json:"seq"`
	CertBindings []*AcmeCertBinding   `json:"cert_bindings,omitempty"`
	Challenges   []*AcmeHttpChallenge `json:"challenges,omitempty"`
}

type AcmeCertBinding struct {
	Hostname        string `json:"hostname,omitempty"`
	SecretVersionID int32  `json:"secret_version_id"`
}

type ClusterNetworkInfo struct {
	UlaPrefix []byte `json:"ula_prefix"`
}

type ClusterNetMap struct {
	TargetNodeID   int32                   `json:"target_node_id"`
	UlaPrefix      []byte                  `json:"ula_prefix"`
	Nodes          []*ClusterNetMapNode    `json:"nodes,omitempty"`
	Routes         []*ClusterNetMapRoute   `json:"routes,omitempty"`
	DerivedFromSeq int64                   `json:"derived_from_seq"`
	PolicyRules    []*NetPolicyRule        `json:"policy_rules,omitempty"`
	DnsServices    []*ClusterNetMapService `json:"dns_services,omitempty"`
}

type ClusterNetMapService struct {
	Name         string                         `json:"name,omitempty"`
	SpaceID      int32                          `json:"space_id"`
	DeploymentID int32                          `json:"deployment_id"`
	Ordinals     []*ClusterNetMapServiceOrdinal `json:"ordinals,omitempty"`
}

type ClusterNetMapServiceOrdinal struct {
	Ordinal int32 `json:"ordinal"`
}

type NetPolicyRule struct {
	Source      *NetPolicyPeer  `json:"source"`
	Destination *NetPolicyPeer  `json:"destination"`
	Ports       []*NetPortMatch `json:"ports,omitempty"`
}

type NetPolicyPeer struct {
	SpaceID      int32 `json:"space_id"`
	DeploymentID int32 `json:"deployment_id"`
}

type NetPortMatch struct {
	Protocol NetProtocol `json:"protocol"`
	Port     int32       `json:"port"`
	PortEnd  int32       `json:"port_end"`
}

type ClusterNetMapNode struct {
	NodeID          int32             `json:"node_id"`
	UnderlayAddress string            `json:"underlay_address,omitempty"`
	WgPublicKey     string            `json:"wg_public_key,omitempty"`
	WgListenPort    int32             `json:"wg_listen_port"`
	IngressPublish  []*IngressPublish `json:"ingress_publish,omitempty"`
}

type IngressPublish struct {
	Address string `json:"address,omitempty"`
	Port    int32  `json:"port"`
}

type IngressDiagnostic struct {
	DeploymentID int32  `json:"deployment_id"`
	Message      string `json:"message,omitempty"`
}

type IngressDiagnosticList struct {
	Items []*IngressDiagnostic `json:"items,omitempty"`
}

type ClusterNetMapRoute struct {
	LogicalPrefix string `json:"logical_prefix,omitempty"`
	HostingNodeID int32  `json:"hosting_node_id"`
}

type NetMapStatus struct {
	PersistedSeq        int64  `json:"persisted_seq"`
	AppliedSeq          int64  `json:"applied_seq"`
	ReconciliationError string `json:"reconciliation_error,omitempty"`
}

type NetState struct {
	Seq               int64                `json:"seq"`
	UlaPrefix         []byte               `json:"ula_prefix"`
	NodeIdentifier    string               `json:"node_identifier,omitempty"`
	DnsServices       []*DnsService        `json:"dns_services,omitempty"`
	UpstreamResolvers []string             `json:"upstream_resolvers,omitempty"`
	Ingress           []*NetIngress        `json:"ingress,omitempty"`
	AcmeChallenges    []*AcmeHttpChallenge `json:"acme_challenges,omitempty"`
}

type AcmeHttpChallenge struct {
	Token            string `json:"token,omitempty"`
	KeyAuthorization string `json:"key_authorization,omitempty"`
}

type DnsService struct {
	Name        string      `json:"name,omitempty"`
	Environment string      `json:"environment,omitempty"`
	Endpoints   []*Endpoint `json:"endpoints,omitempty"`
}

type Endpoint struct {
	Ordinal int32         `json:"ordinal"`
	Address string        `json:"address,omitempty"`
	State   EndpointState `json:"state"`
}

type NetIngress struct {
	Kind           IngressKind               `json:"kind"`
	Hostname       string                    `json:"hostname,omitempty"`
	TlsPassthrough *TlsPassthroughNetIngress `json:"tls_passthrough"`
	Https          *HttpsNetIngress          `json:"https"`
}

type HttpsNetIngress struct {
	PathPrefix          string              `json:"path_prefix,omitempty"`
	StripPrefix         bool                `json:"strip_prefix"`
	BackendProtocol     HttpBackendProtocol `json:"backend_protocol"`
	MaxRequestBodyBytes int64               `json:"max_request_body_bytes"`
	FlushIntervalMs     int32               `json:"flush_interval_ms"`
	CertID              string              `json:"cert_id,omitempty"`
	Backends            []*IngressBackend   `json:"backends,omitempty"`
}

type CertBundle struct {
	Seq   int64              `json:"seq"`
	Certs []*CertBundleEntry `json:"certs,omitempty"`
}

type CertBundleEntry struct {
	CertID string `json:"cert_id,omitempty"`
	Pem    []byte `json:"pem"`
}

type TlsPassthroughNetIngress struct {
	HostPort int32             `json:"host_port"`
	Backends []*IngressBackend `json:"backends,omitempty"`
}

type IngressBackend struct {
	Address string `json:"address,omitempty"`
	Port    int32  `json:"port"`
}

type NetworkPolicy struct {
	Action      NetworkPolicyAction   `json:"action"`
	Source      *NetworkPolicyPeerRef `json:"source"`
	Destination *NetworkPolicyPeerRef `json:"destination"`
	Ports       []*NetPortMatch       `json:"ports,omitempty"`
}

type NetworkPolicyPeerRef struct {
	Kind NetworkPolicyPeerKind `json:"kind"`
	ID   int32                 `json:"id"`
}

type NetworkPolicyEvent struct {
	NetworkPolicyID int32         `json:"network_policy_id"`
	Version         int32         `json:"version"`
	Seq             int64         `json:"seq"`
	EventID         int64         `json:"event_id"`
	Author          int32         `json:"author"`
	EventType       EventType     `json:"event_type"`
	CreatedTime     int64         `json:"created_time"`
	EventTime       int64         `json:"event_time"`
	Value           NetworkPolicy `json:"value"`
}

type NetworkPolicyEventList struct {
	Items []*NetworkPolicyEvent `json:"items,omitempty"`
}

type NetworkPolicyCreateRequest struct {
	Action      NetworkPolicyAction   `json:"action"`
	Source      *NetworkPolicyPeerRef `json:"source"`
	Destination *NetworkPolicyPeerRef `json:"destination"`
	Ports       []*NetPortMatch       `json:"ports,omitempty"`
}

type NetworkPolicyUpdateRequest struct {
	ID          int32                 `json:"id"`
	Version     int32                 `json:"version"`
	Action      NetworkPolicyAction   `json:"action"`
	Source      *NetworkPolicyPeerRef `json:"source"`
	Destination *NetworkPolicyPeerRef `json:"destination"`
	Ports       []*NetPortMatch       `json:"ports,omitempty"`
}

type NetworkPolicyDeleteRequest struct {
	ID int32 `json:"id"`
}

type GithubCredentials struct {
	Token     string    `json:"token,omitempty"`
	ChangedAt time.Time `json:"changed_at"`
}

type MsgToSecondary struct {
	ScheduledInstancesSnapshot *ScheduledInstanceSnapshot `json:"scheduled_instances_snapshot"`
	ScheduledInstanceUpdate    *ScheduledInstanceState    `json:"scheduled_instance_update"`
	DeploymentLogRequest       *DeploymentLogRequest      `json:"deployment_log_request"`
	StopLogRequestID           string                     `json:"stop_log_request_id,omitempty"`
	ClusterNetwork             *ClusterNetworkInfo        `json:"cluster_network"`
	ClusterNetMap              *ClusterNetMap             `json:"cluster_net_map"`
	ClusterProtocolVersion     int32                      `json:"cluster_protocol_version"`
	AcmeState                  *AcmeState                 `json:"acme_state"`
	LogQueryRequest            *LogQueryRequest           `json:"log_query_request"`
	MetricsQueryRequest        *MetricsQueryRequest       `json:"metrics_query_request"`
	MetricsLatestRequest       *MetricsLatestRequest      `json:"metrics_latest_request"`
	NixStoreResets             *NixStoreResets            `json:"nix_store_resets"`
}

type NixStoreReset struct {
	Repo        string `json:"repo,omitempty"`
	RequestedAt int64  `json:"requested_at"`
}

type NixStoreResets struct {
	Items []*NixStoreReset `json:"items,omitempty"`
}

type NixStoreResetRequest struct {
	Repo string `json:"repo,omitempty"`
}

type ClusterHello struct {
	OpendeployVersion      string        `json:"opendeploy_version,omitempty"`
	Reported               *NodeReported `json:"reported"`
	ClusterProtocolVersion int32         `json:"cluster_protocol_version"`
}

type MsgToPrimary struct {
	StatusWrite           *ScheduledInstanceStatus `json:"status_write"`
	LogData               []byte                   `json:"log_data"`
	LogEnd                bool                     `json:"log_end"`
	LogRequestID          string                   `json:"log_request_id,omitempty"`
	NetMapStatus          *NetMapStatus            `json:"net_map_status"`
	ClusterHello          *ClusterHello            `json:"cluster_hello"`
	LogQueryResponse      *LogQueryResponse        `json:"log_query_response"`
	LogQueryError         string                   `json:"log_query_error,omitempty"`
	MetricsQueryResponse  *MetricsQueryResponse    `json:"metrics_query_response"`
	MetricsLatestResponse *MetricsLatestResponse   `json:"metrics_latest_response"`
}

type ClusterSecretsRequest struct {
	Ids []int32 `json:"ids,omitempty"`
}

type ClusterSecretValue struct {
	ID    int32  `json:"id"`
	Value []byte `json:"value"`
}

type ClusterSecretsResponse struct {
	Items []*ClusterSecretValue `json:"items,omitempty"`
}

type ClusterConfigsRequest struct {
	Ids []int32 `json:"ids,omitempty"`
}

type ClusterConfigValue struct {
	ID    int32  `json:"id"`
	Value string `json:"value,omitempty"`
}

type ClusterConfigsResponse struct {
	Items []*ClusterConfigValue `json:"items,omitempty"`
}

type ClusterIssuedTLSRequest struct {
	DeploymentID          int32 `json:"deployment_id"`
	DeploymentSpecVersion int32 `json:"deployment_spec_version"`
}

type ClusterIssuedTLSResponse struct {
	CertPem   []byte `json:"cert_pem"`
	KeyPem    []byte `json:"key_pem"`
	CaCertPem []byte `json:"ca_cert_pem"`
	IssuedAt  int64  `json:"issued_at"`
	NotAfter  int64  `json:"not_after"`
}

type ClusterRenewCertificateResponse struct {
	CertPem   []byte `json:"cert_pem"`
	CaCertPem []byte `json:"ca_cert_pem"`
	NotAfter  int64  `json:"not_after"`
}

type EnrollmentSecondaryMsg struct {
	Hello *EnrollmentHello `json:"hello"`
}

type EnrollmentHello struct {
	Reported                    *NodeReported `json:"reported"`
	SecondaryCertificateRequest []byte        `json:"secondary_certificate_request"`
	OpendeployVersion           string        `json:"opendeploy_version,omitempty"`
}

type EnrollmentPrimaryMsg struct {
	RequestStatus *EnrollmentRequestStatus `json:"request_status"`
	Accepted      *EnrollmentAccepted      `json:"accepted"`
}

type EnrollmentRequestList struct {
	Items []*EnrollmentRequestStatus `json:"items,omitempty"`
}

type EnrollmentAcceptRequest struct {
	ExpectedVersion int32  `json:"expected_version"`
	ID              int32  `json:"id"`
	NodeName        string `json:"node_name,omitempty"`
}

type EnrollmentAccepted struct {
	ID                   int32                   `json:"id"`
	NodeName             string                  `json:"node_name,omitempty"`
	CaCertificate        []byte                  `json:"ca_certificate"`
	SecondaryCertificate []byte                  `json:"secondary_certificate"`
	ClusterNetwork       *ClusterNetworkInfo     `json:"cluster_network"`
	NodeDeployment       *ScheduledInstanceState `json:"node_deployment"`
	NodeNetDeployment    *ScheduledInstanceState `json:"node_net_deployment"`
	ClusterNetMap        *ClusterNetMap          `json:"cluster_net_map"`
}

type SecretRef struct {
	VersionID int32 `json:"version_id"`
}

type ConfigRef struct {
	VersionID int32 `json:"version_id"`
}

type StringSetting struct {
	Value     string    `json:"value,omitempty"`
	ConfigRef ConfigRef `json:"config_ref"`
}

type BoolSetting struct {
	Value     bool      `json:"value"`
	ConfigRef ConfigRef `json:"config_ref"`
}

type SystemConfig struct {
	Settings           ClusterSettings `json:"settings"`
	MasterPasswordHash string          `json:"master_password_hash,omitempty"`
	NetworkUlaPrefix   []byte          `json:"network_ula_prefix"`
}

type SystemConfigVersion struct {
	Version   int64        `json:"version"`
	UpdatedAt time.Time    `json:"updated_at"`
	Config    SystemConfig `json:"config"`
}

type ClusterSettings struct {
	HttpWeb     HttpWebSettings       `json:"http_web"`
	HttpsWeb    HttpsWebSettings      `json:"https_web"`
	Cluster     ClusterListenSettings `json:"cluster"`
	Repo        RepoSettings          `json:"repo"`
	Backup      BackupSettings        `json:"backup"`
	LargeAssets LargeAssetsSettings   `json:"large_assets"`
	Auth        AuthSettings          `json:"auth"`
}

type HttpWebSettings struct {
	Enabled BoolSetting   `json:"enabled"`
	Listen  StringSetting `json:"listen"`
}

type HttpsWebSettings struct {
	Enabled        BoolSetting   `json:"enabled"`
	Listen         StringSetting `json:"listen"`
	TlsSelfManaged BoolSetting   `json:"tls_self_managed"`
	TlsCertPem     SecretRef     `json:"tls_cert_pem"`
	AcmeHosts      StringSetting `json:"acme_hosts"`
	AcmeEmail      StringSetting `json:"acme_email"`
}

type AuthSettings struct {
	PasswordLoginEnabled BoolSetting `json:"password_login_enabled"`
}

type ClusterListenSettings struct {
	Listen           StringSetting `json:"listen"`
	EnrollmentListen StringSetting `json:"enrollment_listen"`
}

type RepoSettings struct {
	GithubToken SecretRef `json:"github_token"`
}

type BackupSettings struct {
	Enabled           BoolSetting   `json:"enabled"`
	S3AccessKeyID     StringSetting `json:"s3_access_key_id"`
	S3SecretAccessKey SecretRef     `json:"s3_secret_access_key"`
	S3Bucket          StringSetting `json:"s3_bucket"`
	S3Path            StringSetting `json:"s3_path"`
	S3Region          StringSetting `json:"s3_region"`
	S3Endpoint        StringSetting `json:"s3_endpoint"`
}

type LargeAssetsSettings struct {
	UseSeparateS3     BoolSetting   `json:"use_separate_s3"`
	S3AccessKeyID     StringSetting `json:"s3_access_key_id"`
	S3SecretAccessKey SecretRef     `json:"s3_secret_access_key"`
	S3Bucket          StringSetting `json:"s3_bucket"`
	S3Path            StringSetting `json:"s3_path"`
	S3Region          StringSetting `json:"s3_region"`
	S3Endpoint        StringSetting `json:"s3_endpoint"`
}

type ExportedConfigBlob struct {
	Blob []byte `json:"blob"`
}

type BackupStatus struct {
	Configured            bool      `json:"configured"`
	Running               bool      `json:"running"`
	InSync                bool      `json:"in_sync"`
	LocalTxid             uint64    `json:"local_txid"`
	RemoteTxid            uint64    `json:"remote_txid"`
	LastSuccessfulSyncAt  time.Time `json:"last_successful_sync_at"`
	Error                 string    `json:"error,omitempty"`
	AssetMigrationRunning bool      `json:"asset_migration_running"`
	AssetPending          uint32    `json:"asset_pending"`
	AssetTargetS3         bool      `json:"asset_target_s3"`
	AssetError            string    `json:"asset_error,omitempty"`
}

type Snapshot struct {
	Seq                     int64                      `json:"seq"`
	DeploymentEvents        []*DeploymentEvent         `json:"deployment_events,omitempty"`
	ScheduledInstanceEvents []*ScheduledInstanceEvent  `json:"scheduled_instance_events,omitempty"`
	InstanceStatuses        []*ScheduledInstanceStatus `json:"instance_statuses,omitempty"`
	NodeEvents              []*NodeEvent               `json:"node_events,omitempty"`
	NodeStatuses            []*NodeStatus              `json:"node_statuses,omitempty"`
	SecretEvents            []*SecretEvent             `json:"secret_events,omitempty"`
	ConfigEvents            []*ConfigEvent             `json:"config_events,omitempty"`
	AssetEvents             []*AssetEvent              `json:"asset_events,omitempty"`
	ValueDirectories        []*ValueDirectory          `json:"value_directories,omitempty"`
	AssetDirectories        []*AssetDirectory          `json:"asset_directories,omitempty"`
	Spaces                  []*Space                   `json:"spaces,omitempty"`
	NetworkPolicyEvents     []*NetworkPolicyEvent      `json:"network_policy_events,omitempty"`
	Users                   []*User                    `json:"users,omitempty"`
	AgentSessions           []*AgentSession            `json:"agent_sessions,omitempty"`
	AuthzRuleTemplates      []*AuthzRuleTemplateRecord `json:"authz_rule_templates,omitempty"`
	AuthzGrantEvents        []*AuthzGrantEvent         `json:"authz_grant_events,omitempty"`
	AuthzGlobalRules        []*AuthzGlobalRuleRecord   `json:"authz_global_rules,omitempty"`
	SecretsStatus           *SecretsStatusResponse     `json:"secrets_status"`
	BackupStatus            *BackupStatus              `json:"backup_status"`
	SystemConfig            *SystemConfigVersion       `json:"system_config"`
	IngressDiagnostics      *IngressDiagnosticList     `json:"ingress_diagnostics"`
}

type CoreUpdate struct {
	Seq                     int64                      `json:"seq"`
	DeploymentEvents        []*DeploymentEvent         `json:"deployment_events,omitempty"`
	ScheduledInstanceEvents []*ScheduledInstanceEvent  `json:"scheduled_instance_events,omitempty"`
	NodeEvents              []*NodeEvent               `json:"node_events,omitempty"`
	SecretEvents            []*SecretEvent             `json:"secret_events,omitempty"`
	ConfigEvents            []*ConfigEvent             `json:"config_events,omitempty"`
	AssetEvents             []*AssetEvent              `json:"asset_events,omitempty"`
	NetworkPolicyEvents     []*NetworkPolicyEvent      `json:"network_policy_events,omitempty"`
	Spaces                  []*Space                   `json:"spaces,omitempty"`
	Users                   []*User                    `json:"users,omitempty"`
	ValueDirectories        []*ValueDirectory          `json:"value_directories,omitempty"`
	AssetDirectories        []*AssetDirectory          `json:"asset_directories,omitempty"`
	AuthzRuleTemplates      *AuthzRuleTemplateList     `json:"authz_rule_templates"`
	AuthzGrantEvents        []*AuthzGrantEvent         `json:"authz_grant_events,omitempty"`
	AuthzGlobalRules        *AuthzGlobalRuleList       `json:"authz_global_rules"`
	SystemConfig            *SystemConfigVersion       `json:"system_config"`
	InstanceStatuses        []*ScheduledInstanceStatus `json:"instance_statuses,omitempty"`
	NodeStatuses            []*NodeStatus              `json:"node_statuses,omitempty"`
}

type StateStreamMsg struct {
	Snapshot           *Snapshot              `json:"snapshot"`
	Core               *CoreUpdate            `json:"core"`
	Heartbeat          bool                   `json:"heartbeat"`
	BackupStatus       *BackupStatus          `json:"backup_status"`
	IngressDiagnostics *IngressDiagnosticList `json:"ingress_diagnostics"`
	SecretsStatus      *SecretsStatusResponse `json:"secrets_status"`
	AgentSessions      *AgentSessionList      `json:"agent_sessions"`
}

type AccessPolicy struct {
	PolicyType AccessPolicyType `json:"policy_type"`
	Scopes     []string         `json:"scopes,omitempty"`
}

type ApiErr struct {
	Code        int32  `json:"code"`
	DisplayErr  string `json:"display_err,omitempty"`
	InternalErr string `json:"-"`
}
