// Code generated by cleanproto. DO NOT EDIT.

package apigen

import (
	"context"
	"fmt"
	"iter"
	"net/http"
)

type HandlerFunc = func(context.Context, http.ResponseWriter, *http.Request)
type MiddlewareFunc func(next HandlerFunc) HandlerFunc

type VerifyAuthFunc func(context.Context, http.ResponseWriter, *http.Request, AccessPolicy) (Context, error)

type PostAuthHandlerFunc func(Context, http.ResponseWriter, *http.Request)
type PostAuthMiddlewareFunc func(next PostAuthHandlerFunc) PostAuthHandlerFunc

type AuditFunc func(Context, string, error, any, any)

type MuxConfig struct {
	VerifyAuth          VerifyAuthFunc
	Audit               AuditFunc
	MaxRequestBodySize  int
	UnaryCompression    func(http.Handler) http.HandlerFunc
	StreamCompression   func(http.Handler) http.HandlerFunc
	Middlewares         []MiddlewareFunc
	PostAuthMiddlewares []PostAuthMiddlewareFunc
}

func ApplyMiddlewares(h HandlerFunc, middlewares ...MiddlewareFunc) http.HandlerFunc {
	for _, m := range middlewares {
		h = m(h)
	}
	return func(w http.ResponseWriter, r *http.Request) {
		h(r.Context(), w, r)
	}
}

func ApplyPostAuthMiddlewares(h PostAuthHandlerFunc, middlewares ...PostAuthMiddlewareFunc) PostAuthHandlerFunc {
	for _, m := range middlewares {
		h = m(h)
	}
	return h
}

func buildHandlerFunc(config *MuxConfig, verifyAuth VerifyAuthFunc, policy AccessPolicy, postAuthHandler PostAuthHandlerFunc, compressionMode int32, streaming bool) http.HandlerFunc {
	postAuthHandler = ApplyPostAuthMiddlewares(postAuthHandler, config.PostAuthMiddlewares...)
	routeHandler := ApplyMiddlewares(func(ctx context.Context, w http.ResponseWriter, r *http.Request) {
		authCtx, err := verifyAuth(ctx, w, r, policy)
		if err != nil {
			HandleReqErr(ctx, err, r, w)
			return
		}
		postAuthHandler(authCtx, w, r)
	}, config.Middlewares...)
	if compressionMode == compressionModeNever {
		return routeHandler
	}
	compress := config.UnaryCompression
	if streaming {
		compress = config.StreamCompression
	}
	if compress == nil {
		return routeHandler
	}
	return compress(routeHandler)
}

type OpsagentHttpV1Handler interface {
	Get(Context, *http.Request, http.ResponseWriter) error
	GetV1Healthz(Context, *http.Request, http.ResponseWriter) error
	PostV1AuthMaster(Context, *MasterPasswordRequest) (*LoginResponse, error)
	PostV1AuthMasterPasswordSave(Context, *MasterPasswordSaveRequest) error
	PostV1AuthMasterPasswordVerify(Context, *MasterPasswordVerifyRequest) error
	GetV1AuthCurrentSession(Context) (*LoginResponse, error)
	PostV1AuthPasskeyRegisterStart(Context, *EmptyRequest) (*WebAuthNOptionsResponse, error)
	PostV1AuthPasskeyRegisterFinish(Context, *WebAuthNFinishRequest) (*LoginResponse, error)
	PostV1AuthPasskeyLoginStart(Context, *EmptyRequest) (*WebAuthNOptionsResponse, error)
	PostV1AuthPasskeyLoginFinish(Context, *WebAuthNFinishRequest) (*LoginResponse, error)
	PostV1StateStream(Context) iter.Seq2[*State, error]
	PostV1DeploymentUpdate(Context, *DeploymentUpdateRequest) (*DeploymentConfig2, error)
	PostV1DeploymentDelete(Context, *DeploymentDeleteRequest) error
	PostV1DeploymentHistory(Context, *DeploymentHistoryRequest) (*DeploymentHistory, error)
	PostV1DeploymentLogSearch(Context, *LogSearchRequest) iter.Seq2[*LogLineBatch, error]
	PostV1DeploymentPrepareOutput(Context, *PrepareOutputRequest) iter.Seq2[*PrepareOutputChunk, error]
	GetV1ClusterStatus(Context, *http.Request, http.ResponseWriter) error
	PostV1ClusterRename(Context, *NodeRenameRequest) (*ClusterNode, error)
	PostV1DeploymentCreate(Context, *DeploymentCreateRequest) (*DeploymentConfig2, error)
	PostV1SpacesCreate(Context, *SpaceSetRequest) (*Space, error)
	PostV1SpacesUpdate(Context, *SpaceSetRequest) (*Space, error)
	PostV1SpacesDelete(Context, *SpaceDeleteRequest) error
	PostV1DeploymentVersions(Context, *DeploymentVersionsRequest) (*DeploymentVersions, error)
	PostV1RepoValidate(Context, *ValidateSourceRequest) (*ValidateSourceResponse, error)
	GetV1Settings(Context) (*Settings, error)
	GetV1EnrollmentInfo(Context) (*EnrollmentInfo, error)
	PutV1Settings(Context, *Settings) (*Settings, error)
	PostV1GenerateExportedConfig(Context, *EmptyRequest) (*ExportedConfigBlob, error)
	PostV1SecretsList(Context, *EmptyRequest) (*SecretList, error)
	PostV1SecretsSet(Context, *SecretSetRequest) (*SecretMeta, error)
	PostV1SecretsRename(Context, *SecretRenameRequest) (*SecretMeta, error)
	PostV1SecretsReveal(Context, *SecretRevealRequest) (*SecretRevealResponse, error)
	PostV1SecretsDelete(Context, *SecretDeleteRequest) error
	PostV1SecretsStatus(Context, *EmptyRequest) (*SecretsStatusResponse, error)
	PostV1SecretsGenerateRecoveryCode(Context, *EmptyRequest) (*SecretRecoveryCodeResponse, error)
	PostV1SecretsUnlock(Context, *SecretUnlockRequest) (*SecretsStatusResponse, error)
	PostV1UserConfigsList(Context, *EmptyRequest) (*UserConfigList, error)
	PostV1UserConfigsSet(Context, *UserConfigSetRequest) (*UserConfig, error)
	PostV1UserConfigsRename(Context, *UserConfigRenameRequest) (*UserConfig, error)
	PostV1UserConfigsDelete(Context, *UserConfigDeleteRequest) error
	PostV1AssetsList(Context, *EmptyRequest) (*AssetList, error)
	PostV1AssetsGet(Context, *AssetGetRequest) (*Asset, error)
	PostV1AssetsSet(Context, *AssetSetRequest) (*Asset, error)
	PostV1AssetsUpload(Context, *http.Request, http.ResponseWriter) error
	PostV1AssetsRename(Context, *AssetRenameRequest) (*Asset, error)
	PostV1AssetsDelete(Context, *AssetDeleteRequest) error
	PostV1EnrollmentList(Context) (*EnrollmentRequestList, error)
	PostV1EnrollmentAccept(Context, *EnrollmentAcceptRequest) (*EnrollmentRequestStatus, error)
}

func CreateOpsagentHttpV1Mux(h OpsagentHttpV1Handler, config *MuxConfig) *http.ServeMux {
	if config == nil {
		config = &MuxConfig{}
	}
	verifyAuth := config.VerifyAuth
	if verifyAuth == nil {
		verifyAuth = func(ctx context.Context, _ http.ResponseWriter, _ *http.Request, _ AccessPolicy) (Context, error) {
			var authCtx Context
			return authCtx, nil
		}
	}
	m := http.NewServeMux()
	getAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_NO_AUTH}
	postAuthHandlerGet := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		err := h.Get(authCtx, r, w)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
	}
	m.HandleFunc("GET /", buildHandlerFunc(config, verifyAuth, getAccessPolicy, postAuthHandlerGet, compressionModeAuto, false))
	getV1HealthzAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_NO_AUTH}
	postAuthHandlerGetV1Healthz := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		err := h.GetV1Healthz(authCtx, r, w)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
	}
	m.HandleFunc("GET /v1/healthz", buildHandlerFunc(config, verifyAuth, getV1HealthzAccessPolicy, postAuthHandlerGetV1Healthz, compressionModeAuto, false))
	postV1AuthMasterAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_NO_AUTH}
	postAuthHandlerPostV1AuthMaster := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeMasterPasswordRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1AuthMaster(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/auth/master", buildHandlerFunc(config, verifyAuth, postV1AuthMasterAccessPolicy, postAuthHandlerPostV1AuthMaster, compressionModeAuto, false))
	postV1AuthMasterPasswordSaveAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1AuthMasterPasswordSave := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeMasterPasswordSaveRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		err = h.PostV1AuthMasterPasswordSave(authCtx, req)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		w.WriteHeader(http.StatusNoContent)
	}
	m.HandleFunc("POST /v1/auth/master/password/save", buildHandlerFunc(config, verifyAuth, postV1AuthMasterPasswordSaveAccessPolicy, postAuthHandlerPostV1AuthMasterPasswordSave, compressionModeAuto, false))
	postV1AuthMasterPasswordVerifyAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1AuthMasterPasswordVerify := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeMasterPasswordVerifyRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		err = h.PostV1AuthMasterPasswordVerify(authCtx, req)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		w.WriteHeader(http.StatusNoContent)
	}
	m.HandleFunc("POST /v1/auth/master/password/verify", buildHandlerFunc(config, verifyAuth, postV1AuthMasterPasswordVerifyAccessPolicy, postAuthHandlerPostV1AuthMasterPasswordVerify, compressionModeAuto, false))
	getV1AuthCurrentSessionAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"passkey:create", "default"}}
	postAuthHandlerGetV1AuthCurrentSession := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		res, err := h.GetV1AuthCurrentSession(authCtx)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("GET /v1/auth/current/session", buildHandlerFunc(config, verifyAuth, getV1AuthCurrentSessionAccessPolicy, postAuthHandlerGetV1AuthCurrentSession, compressionModeAuto, false))
	postV1AuthPasskeyRegisterStartAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"passkey:create", "default"}}
	postAuthHandlerPostV1AuthPasskeyRegisterStart := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeEmptyRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1AuthPasskeyRegisterStart(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/auth/passkey/register/start", buildHandlerFunc(config, verifyAuth, postV1AuthPasskeyRegisterStartAccessPolicy, postAuthHandlerPostV1AuthPasskeyRegisterStart, compressionModeAuto, false))
	postV1AuthPasskeyRegisterFinishAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"passkey:create", "default"}}
	postAuthHandlerPostV1AuthPasskeyRegisterFinish := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeWebAuthNFinishRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1AuthPasskeyRegisterFinish(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/auth/passkey/register/finish", buildHandlerFunc(config, verifyAuth, postV1AuthPasskeyRegisterFinishAccessPolicy, postAuthHandlerPostV1AuthPasskeyRegisterFinish, compressionModeAuto, false))
	postV1AuthPasskeyLoginStartAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_NO_AUTH}
	postAuthHandlerPostV1AuthPasskeyLoginStart := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeEmptyRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1AuthPasskeyLoginStart(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/auth/passkey/login/start", buildHandlerFunc(config, verifyAuth, postV1AuthPasskeyLoginStartAccessPolicy, postAuthHandlerPostV1AuthPasskeyLoginStart, compressionModeAuto, false))
	postV1AuthPasskeyLoginFinishAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_NO_AUTH}
	postAuthHandlerPostV1AuthPasskeyLoginFinish := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeWebAuthNFinishRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1AuthPasskeyLoginFinish(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/auth/passkey/login/finish", buildHandlerFunc(config, verifyAuth, postV1AuthPasskeyLoginFinishAccessPolicy, postAuthHandlerPostV1AuthPasskeyLoginFinish, compressionModeAuto, false))
	postV1StateStreamAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1StateStream := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		seq := h.PostV1StateStream(authCtx)
		stream := NewStreamWriter(w)
		var streamErr error
		for resp, yieldErr := range seq {
			if yieldErr != nil {
				streamErr = fmt.Errorf("streaming err: %w", yieldErr)
				break
			}
			if werr := stream.Write(resp.Encode()); werr != nil {
				streamErr = fmt.Errorf("writing stream resp: %w", werr)
				break
			}
		}
		stream.Finish(authCtx, streamErr)
	}
	m.HandleFunc("POST /v1/state/stream", buildHandlerFunc(config, verifyAuth, postV1StateStreamAccessPolicy, postAuthHandlerPostV1StateStream, compressionModeAuto, true))
	postV1DeploymentUpdateAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1DeploymentUpdate := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeDeploymentUpdateRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1DeploymentUpdate(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/deployment/update", buildHandlerFunc(config, verifyAuth, postV1DeploymentUpdateAccessPolicy, postAuthHandlerPostV1DeploymentUpdate, compressionModeAuto, false))
	postV1DeploymentDeleteAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1DeploymentDelete := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeDeploymentDeleteRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		err = h.PostV1DeploymentDelete(authCtx, req)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		w.WriteHeader(http.StatusNoContent)
	}
	m.HandleFunc("POST /v1/deployment/delete", buildHandlerFunc(config, verifyAuth, postV1DeploymentDeleteAccessPolicy, postAuthHandlerPostV1DeploymentDelete, compressionModeAuto, false))
	postV1DeploymentHistoryAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1DeploymentHistory := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeDeploymentHistoryRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1DeploymentHistory(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/deployment/history", buildHandlerFunc(config, verifyAuth, postV1DeploymentHistoryAccessPolicy, postAuthHandlerPostV1DeploymentHistory, compressionModeAuto, false))
	postV1DeploymentLogSearchAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1DeploymentLogSearch := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeLogSearchRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		seq := h.PostV1DeploymentLogSearch(authCtx, req)
		stream := NewStreamWriter(w)
		var streamErr error
		for resp, yieldErr := range seq {
			if yieldErr != nil {
				streamErr = fmt.Errorf("streaming err: %w", yieldErr)
				break
			}
			if werr := stream.Write(resp.Encode()); werr != nil {
				streamErr = fmt.Errorf("writing stream resp: %w", werr)
				break
			}
		}
		stream.Finish(authCtx, streamErr)
	}
	m.HandleFunc("POST /v1/deployment/log-search", buildHandlerFunc(config, verifyAuth, postV1DeploymentLogSearchAccessPolicy, postAuthHandlerPostV1DeploymentLogSearch, compressionModeAuto, true))
	postV1DeploymentPrepareOutputAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1DeploymentPrepareOutput := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodePrepareOutputRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		seq := h.PostV1DeploymentPrepareOutput(authCtx, req)
		stream := NewStreamWriter(w)
		var streamErr error
		for resp, yieldErr := range seq {
			if yieldErr != nil {
				streamErr = fmt.Errorf("streaming err: %w", yieldErr)
				break
			}
			if werr := stream.Write(resp.Encode()); werr != nil {
				streamErr = fmt.Errorf("writing stream resp: %w", werr)
				break
			}
		}
		stream.Finish(authCtx, streamErr)
	}
	m.HandleFunc("POST /v1/deployment/prepare-output", buildHandlerFunc(config, verifyAuth, postV1DeploymentPrepareOutputAccessPolicy, postAuthHandlerPostV1DeploymentPrepareOutput, compressionModeAuto, true))
	getV1ClusterStatusAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerGetV1ClusterStatus := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		err := h.GetV1ClusterStatus(authCtx, r, w)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
	}
	m.HandleFunc("GET /v1/cluster/status", buildHandlerFunc(config, verifyAuth, getV1ClusterStatusAccessPolicy, postAuthHandlerGetV1ClusterStatus, compressionModeAuto, false))
	postV1ClusterRenameAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1ClusterRename := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeNodeRenameRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1ClusterRename(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/cluster/rename", buildHandlerFunc(config, verifyAuth, postV1ClusterRenameAccessPolicy, postAuthHandlerPostV1ClusterRename, compressionModeAuto, false))
	postV1DeploymentCreateAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1DeploymentCreate := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeDeploymentCreateRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1DeploymentCreate(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/deployment/create", buildHandlerFunc(config, verifyAuth, postV1DeploymentCreateAccessPolicy, postAuthHandlerPostV1DeploymentCreate, compressionModeAuto, false))
	postV1SpacesCreateAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1SpacesCreate := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeSpaceSetRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1SpacesCreate(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/spaces/create", buildHandlerFunc(config, verifyAuth, postV1SpacesCreateAccessPolicy, postAuthHandlerPostV1SpacesCreate, compressionModeAuto, false))
	postV1SpacesUpdateAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1SpacesUpdate := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeSpaceSetRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1SpacesUpdate(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/spaces/update", buildHandlerFunc(config, verifyAuth, postV1SpacesUpdateAccessPolicy, postAuthHandlerPostV1SpacesUpdate, compressionModeAuto, false))
	postV1SpacesDeleteAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1SpacesDelete := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeSpaceDeleteRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		err = h.PostV1SpacesDelete(authCtx, req)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		w.WriteHeader(http.StatusNoContent)
	}
	m.HandleFunc("POST /v1/spaces/delete", buildHandlerFunc(config, verifyAuth, postV1SpacesDeleteAccessPolicy, postAuthHandlerPostV1SpacesDelete, compressionModeAuto, false))
	postV1DeploymentVersionsAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1DeploymentVersions := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeDeploymentVersionsRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1DeploymentVersions(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/deployment/versions", buildHandlerFunc(config, verifyAuth, postV1DeploymentVersionsAccessPolicy, postAuthHandlerPostV1DeploymentVersions, compressionModeAuto, false))
	postV1RepoValidateAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1RepoValidate := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeValidateSourceRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1RepoValidate(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/repo/validate", buildHandlerFunc(config, verifyAuth, postV1RepoValidateAccessPolicy, postAuthHandlerPostV1RepoValidate, compressionModeAuto, false))
	getV1SettingsAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerGetV1Settings := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		res, err := h.GetV1Settings(authCtx)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("GET /v1/settings", buildHandlerFunc(config, verifyAuth, getV1SettingsAccessPolicy, postAuthHandlerGetV1Settings, compressionModeAuto, false))
	getV1EnrollmentInfoAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerGetV1EnrollmentInfo := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		res, err := h.GetV1EnrollmentInfo(authCtx)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("GET /v1/enrollment/info", buildHandlerFunc(config, verifyAuth, getV1EnrollmentInfoAccessPolicy, postAuthHandlerGetV1EnrollmentInfo, compressionModeAuto, false))
	putV1SettingsAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPutV1Settings := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeSettings)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PutV1Settings(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("PUT /v1/settings", buildHandlerFunc(config, verifyAuth, putV1SettingsAccessPolicy, postAuthHandlerPutV1Settings, compressionModeAuto, false))
	postV1GenerateExportedConfigAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1GenerateExportedConfig := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeEmptyRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1GenerateExportedConfig(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/generate-exported-config", buildHandlerFunc(config, verifyAuth, postV1GenerateExportedConfigAccessPolicy, postAuthHandlerPostV1GenerateExportedConfig, compressionModeAuto, false))
	postV1SecretsListAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1SecretsList := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeEmptyRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1SecretsList(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/secrets/list", buildHandlerFunc(config, verifyAuth, postV1SecretsListAccessPolicy, postAuthHandlerPostV1SecretsList, compressionModeAuto, false))
	postV1SecretsSetAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1SecretsSet := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeSecretSetRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1SecretsSet(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/secrets/set", buildHandlerFunc(config, verifyAuth, postV1SecretsSetAccessPolicy, postAuthHandlerPostV1SecretsSet, compressionModeAuto, false))
	postV1SecretsRenameAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1SecretsRename := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeSecretRenameRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1SecretsRename(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/secrets/rename", buildHandlerFunc(config, verifyAuth, postV1SecretsRenameAccessPolicy, postAuthHandlerPostV1SecretsRename, compressionModeAuto, false))
	postV1SecretsRevealAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1SecretsReveal := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeSecretRevealRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1SecretsReveal(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/secrets/reveal", buildHandlerFunc(config, verifyAuth, postV1SecretsRevealAccessPolicy, postAuthHandlerPostV1SecretsReveal, compressionModeAuto, false))
	postV1SecretsDeleteAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1SecretsDelete := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeSecretDeleteRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		err = h.PostV1SecretsDelete(authCtx, req)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		w.WriteHeader(http.StatusNoContent)
	}
	m.HandleFunc("POST /v1/secrets/delete", buildHandlerFunc(config, verifyAuth, postV1SecretsDeleteAccessPolicy, postAuthHandlerPostV1SecretsDelete, compressionModeAuto, false))
	postV1SecretsStatusAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1SecretsStatus := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeEmptyRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1SecretsStatus(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/secrets/status", buildHandlerFunc(config, verifyAuth, postV1SecretsStatusAccessPolicy, postAuthHandlerPostV1SecretsStatus, compressionModeAuto, false))
	postV1SecretsGenerateRecoveryCodeAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1SecretsGenerateRecoveryCode := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeEmptyRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1SecretsGenerateRecoveryCode(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/secrets/generate/recovery/code", buildHandlerFunc(config, verifyAuth, postV1SecretsGenerateRecoveryCodeAccessPolicy, postAuthHandlerPostV1SecretsGenerateRecoveryCode, compressionModeAuto, false))
	postV1SecretsUnlockAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1SecretsUnlock := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeSecretUnlockRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1SecretsUnlock(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/secrets/unlock", buildHandlerFunc(config, verifyAuth, postV1SecretsUnlockAccessPolicy, postAuthHandlerPostV1SecretsUnlock, compressionModeAuto, false))
	postV1UserConfigsListAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1UserConfigsList := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeEmptyRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1UserConfigsList(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/user/configs/list", buildHandlerFunc(config, verifyAuth, postV1UserConfigsListAccessPolicy, postAuthHandlerPostV1UserConfigsList, compressionModeAuto, false))
	postV1UserConfigsSetAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1UserConfigsSet := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeUserConfigSetRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1UserConfigsSet(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/user/configs/set", buildHandlerFunc(config, verifyAuth, postV1UserConfigsSetAccessPolicy, postAuthHandlerPostV1UserConfigsSet, compressionModeAuto, false))
	postV1UserConfigsRenameAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1UserConfigsRename := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeUserConfigRenameRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1UserConfigsRename(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/user/configs/rename", buildHandlerFunc(config, verifyAuth, postV1UserConfigsRenameAccessPolicy, postAuthHandlerPostV1UserConfigsRename, compressionModeAuto, false))
	postV1UserConfigsDeleteAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1UserConfigsDelete := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeUserConfigDeleteRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		err = h.PostV1UserConfigsDelete(authCtx, req)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		w.WriteHeader(http.StatusNoContent)
	}
	m.HandleFunc("POST /v1/user/configs/delete", buildHandlerFunc(config, verifyAuth, postV1UserConfigsDeleteAccessPolicy, postAuthHandlerPostV1UserConfigsDelete, compressionModeAuto, false))
	postV1AssetsListAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1AssetsList := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeEmptyRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1AssetsList(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/assets/list", buildHandlerFunc(config, verifyAuth, postV1AssetsListAccessPolicy, postAuthHandlerPostV1AssetsList, compressionModeAuto, false))
	postV1AssetsGetAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1AssetsGet := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeAssetGetRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1AssetsGet(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/assets/get", buildHandlerFunc(config, verifyAuth, postV1AssetsGetAccessPolicy, postAuthHandlerPostV1AssetsGet, compressionModeAuto, false))
	postV1AssetsSetAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1AssetsSet := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeAssetSetRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1AssetsSet(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/assets/set", buildHandlerFunc(config, verifyAuth, postV1AssetsSetAccessPolicy, postAuthHandlerPostV1AssetsSet, compressionModeAuto, false))
	postV1AssetsUploadAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1AssetsUpload := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		err := h.PostV1AssetsUpload(authCtx, r, w)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
	}
	m.HandleFunc("POST /v1/assets/upload", buildHandlerFunc(config, verifyAuth, postV1AssetsUploadAccessPolicy, postAuthHandlerPostV1AssetsUpload, compressionModeAuto, false))
	postV1AssetsRenameAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1AssetsRename := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeAssetRenameRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1AssetsRename(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/assets/rename", buildHandlerFunc(config, verifyAuth, postV1AssetsRenameAccessPolicy, postAuthHandlerPostV1AssetsRename, compressionModeAuto, false))
	postV1AssetsDeleteAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1AssetsDelete := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeAssetDeleteRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		err = h.PostV1AssetsDelete(authCtx, req)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		w.WriteHeader(http.StatusNoContent)
	}
	m.HandleFunc("POST /v1/assets/delete", buildHandlerFunc(config, verifyAuth, postV1AssetsDeleteAccessPolicy, postAuthHandlerPostV1AssetsDelete, compressionModeAuto, false))
	postV1EnrollmentListAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1EnrollmentList := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		res, err := h.PostV1EnrollmentList(authCtx)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/enrollment/list", buildHandlerFunc(config, verifyAuth, postV1EnrollmentListAccessPolicy, postAuthHandlerPostV1EnrollmentList, compressionModeAuto, false))
	postV1EnrollmentAcceptAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_ANY_OF, Scopes: []string{"default"}}
	postAuthHandlerPostV1EnrollmentAccept := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeEnrollmentAcceptRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.PostV1EnrollmentAccept(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("POST /v1/enrollment/accept", buildHandlerFunc(config, verifyAuth, postV1EnrollmentAcceptAccessPolicy, postAuthHandlerPostV1EnrollmentAccept, compressionModeAuto, false))
	return m
}

type OpsagentClusterV1Handler interface {
	GetV1ClusterGithubCredentials(Context) (*GithubCredentials, error)
	GetV1ClusterAsset(Context, *http.Request, http.ResponseWriter) error
	GetV1ClusterSecrets(Context, *ClusterSecretsRequest) (*ClusterSecretsResponse, error)
	GetV1ClusterConfigs(Context, *ClusterConfigsRequest) (*ClusterConfigsResponse, error)
	PostV1ClusterConnect(Context, iter.Seq2[*MsgToMaster, error]) iter.Seq2[*MsgToWorker, error]
}

func CreateOpsagentClusterV1Mux(h OpsagentClusterV1Handler, config *MuxConfig) *http.ServeMux {
	if config == nil {
		config = &MuxConfig{}
	}
	verifyAuth := config.VerifyAuth
	if verifyAuth == nil {
		verifyAuth = func(ctx context.Context, _ http.ResponseWriter, _ *http.Request, _ AccessPolicy) (Context, error) {
			var authCtx Context
			return authCtx, nil
		}
	}
	m := http.NewServeMux()
	getV1ClusterGithubCredentialsAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_NO_AUTH}
	postAuthHandlerGetV1ClusterGithubCredentials := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		res, err := h.GetV1ClusterGithubCredentials(authCtx)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("GET /v1/cluster/github-credentials", buildHandlerFunc(config, verifyAuth, getV1ClusterGithubCredentialsAccessPolicy, postAuthHandlerGetV1ClusterGithubCredentials, compressionModeAuto, false))
	getV1ClusterAssetAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_NO_AUTH}
	postAuthHandlerGetV1ClusterAsset := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		err := h.GetV1ClusterAsset(authCtx, r, w)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
	}
	m.HandleFunc("GET /v1/cluster/asset", buildHandlerFunc(config, verifyAuth, getV1ClusterAssetAccessPolicy, postAuthHandlerGetV1ClusterAsset, compressionModeNever, false))
	getV1ClusterSecretsAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_NO_AUTH}
	postAuthHandlerGetV1ClusterSecrets := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeClusterSecretsRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.GetV1ClusterSecrets(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("GET /v1/cluster/secrets", buildHandlerFunc(config, verifyAuth, getV1ClusterSecretsAccessPolicy, postAuthHandlerGetV1ClusterSecrets, compressionModeAuto, false))
	getV1ClusterConfigsAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_NO_AUTH}
	postAuthHandlerGetV1ClusterConfigs := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		req, err := decodeWithMaxBodySize(r, config.MaxRequestBodySize, DecodeClusterConfigsRequest)
		if err != nil {
			HandleReqErr(authCtx, err, r, w)
			return
		}
		res, err := h.GetV1ClusterConfigs(authCtx, req)
		Respond(authCtx, r, w, res, err)
	}
	m.HandleFunc("GET /v1/cluster/configs", buildHandlerFunc(config, verifyAuth, getV1ClusterConfigsAccessPolicy, postAuthHandlerGetV1ClusterConfigs, compressionModeAuto, false))
	postV1ClusterConnectAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_NO_AUTH}
	postAuthHandlerPostV1ClusterConnect := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		sr := NewStreamReader(r.Body, config.MaxRequestBodySize)
		reqSeq := func(yield func(*MsgToMaster, error) bool) {
			for {
				payload, ok, err := sr.Next()
				if err != nil {
					yield(nil, err)
					return
				}
				if !ok {
					return
				}
				req, err := DecodeMsgToMaster(payload)
				if err != nil {
					yield(nil, err)
					return
				}
				if !yield(req, nil) {
					return
				}
			}
		}
		respSeq := h.PostV1ClusterConnect(authCtx, reqSeq)
		stream := NewStreamWriter(w)
		var streamErr error
		for resp, yieldErr := range respSeq {
			if yieldErr != nil {
				streamErr = fmt.Errorf("streaming err: %w", yieldErr)
				break
			}
			if werr := stream.Write(resp.Encode()); werr != nil {
				streamErr = fmt.Errorf("writing stream resp: %w", werr)
				break
			}
		}
		stream.Finish(authCtx, streamErr)
	}
	m.HandleFunc("POST /v1/cluster/connect", buildHandlerFunc(config, verifyAuth, postV1ClusterConnectAccessPolicy, postAuthHandlerPostV1ClusterConnect, compressionModeAuto, true))
	return m
}

type EnrollmentV1Handler interface {
	PostV1EnrollmentRequest(Context, iter.Seq2[*EnrollmentWorkerMsg, error]) iter.Seq2[*EnrollmentPrimaryMsg, error]
}

func CreateEnrollmentV1Mux(h EnrollmentV1Handler, config *MuxConfig) *http.ServeMux {
	if config == nil {
		config = &MuxConfig{}
	}
	verifyAuth := config.VerifyAuth
	if verifyAuth == nil {
		verifyAuth = func(ctx context.Context, _ http.ResponseWriter, _ *http.Request, _ AccessPolicy) (Context, error) {
			var authCtx Context
			return authCtx, nil
		}
	}
	m := http.NewServeMux()
	postV1EnrollmentRequestAccessPolicy := AccessPolicy{PolicyType: AccessPolicyType_NO_AUTH}
	postAuthHandlerPostV1EnrollmentRequest := func(authCtx Context, w http.ResponseWriter, r *http.Request) {
		sr := NewStreamReader(r.Body, config.MaxRequestBodySize)
		reqSeq := func(yield func(*EnrollmentWorkerMsg, error) bool) {
			for {
				payload, ok, err := sr.Next()
				if err != nil {
					yield(nil, err)
					return
				}
				if !ok {
					return
				}
				req, err := DecodeEnrollmentWorkerMsg(payload)
				if err != nil {
					yield(nil, err)
					return
				}
				if !yield(req, nil) {
					return
				}
			}
		}
		respSeq := h.PostV1EnrollmentRequest(authCtx, reqSeq)
		stream := NewStreamWriter(w)
		var streamErr error
		for resp, yieldErr := range respSeq {
			if yieldErr != nil {
				streamErr = fmt.Errorf("streaming err: %w", yieldErr)
				break
			}
			if werr := stream.Write(resp.Encode()); werr != nil {
				streamErr = fmt.Errorf("writing stream resp: %w", werr)
				break
			}
		}
		stream.Finish(authCtx, streamErr)
	}
	m.HandleFunc("POST /v1/enrollment/request", buildHandlerFunc(config, verifyAuth, postV1EnrollmentRequestAccessPolicy, postAuthHandlerPostV1EnrollmentRequest, compressionModeAuto, true))
	return m
}
