// Code generated by cleanproto. DO NOT EDIT.

package apigen

import (
	"bufio"
	"context"
	"encoding/binary"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"log/slog"
	"mime"
	"net/http"
	"strings"
)

// negotiatedJSONResponse reports whether the caller asked for a JSON response
// body. A wildcard Accept does not count: protobuf stays the default so that
// existing clients sending a wildcard Accept keep getting protobuf.
func negotiatedJSONResponse(r *http.Request) bool {
	if r == nil {
		return false
	}
	return hasJSONMediaType(r.Header.Get("Accept"))
}

// negotiatedJSONRequest reports whether the request body is JSON rather than
// protobuf, based on its Content-Type.
func negotiatedJSONRequest(r *http.Request) bool {
	if r == nil {
		return false
	}
	return hasJSONMediaType(r.Header.Get("Content-Type"))
}

// hasJSONMediaType reports whether a comma-separated media type header lists
// application/json or any structured JSON suffix type such as
// application/merge-patch+json. Unparseable entries are skipped rather than
// failing the whole header, since one malformed entry should not decide the
// content type of the exchange.
func hasJSONMediaType(header string) bool {
	for _, entry := range strings.Split(header, ",") {
		entry = strings.TrimSpace(entry)
		if entry == "" {
			continue
		}
		mediaType, _, err := mime.ParseMediaType(entry)
		if err != nil {
			continue
		}
		if mediaType == "application/json" || strings.HasSuffix(mediaType, "+json") {
			return true
		}
	}
	return false
}

func Respond(ctx context.Context, r *http.Request, w http.ResponseWriter, res Encodable, resultErr error) {
	if resultErr != nil {
		HandleReqErr(ctx, resultErr, r, w)
		return
	}
	if res != nil {
		if negotiatedJSONResponse(r) {
			b, err := json.Marshal(res)
			if err != nil {
				HandleReqErr(ctx, fmt.Errorf("encoding json response: %w", err), r, w)
				return
			}
			w.Header().Set("Content-Type", "application/json")
			RespondWithStatus(ctx, w, b, http.StatusOK)
			return
		}
		w.Header().Set("Content-Type", "application/protobuf")
		RespondWithStatus(ctx, w, res.Encode(), http.StatusOK)
		return
	}
	RespondWithStatus(ctx, w, nil, http.StatusOK)
}

func RespondWithStatus(ctx context.Context, w http.ResponseWriter, b []byte, code int) {
	w.WriteHeader(code)
	if len(b) == 0 {
		return
	}
	if _, err := w.Write(b); err != nil {
		slog.ErrorContext(ctx, fmt.Sprintf("writing response body: %v", err))
	}
}

func HandleReqErr(ctx context.Context, err error, r *http.Request, w http.ResponseWriter) {
	path := ""
	if r != nil {
		path = r.URL.Path
	}
	handleReqErr(ctx, err, path, negotiatedJSONResponse(r), w)
}

func handleReqErr(ctx context.Context, err error, path string, useJSON bool, w http.ResponseWriter) {
	httpErr := resolveApiErr(err)
	if err != nil && len(err.Error()) > 0 {
		msg := fmt.Sprintf("err: %v", err.Error())
		if path != "" {
			msg = fmt.Sprintf("%v err: %v", path, err.Error())
		}
		// A 4xx is the client being told something it can act on - a bad field, an
		// expired token, a limit reached. Those are normal traffic, and logging
		// them at error level buries the 5xx that actually need attention.
		if httpErr.Code >= 400 && httpErr.Code < 500 {
			slog.InfoContext(ctx, msg)
		} else {
			slog.ErrorContext(ctx, msg)
		}
	}
	// A JSON caller gets a JSON error body. Marshalling ApiErr cannot fail, but
	// if it somehow did there is no better body to send than the protobuf one.
	if useJSON {
		if b, marshalErr := json.Marshal(httpErr); marshalErr == nil {
			w.Header().Set("Content-Type", "application/json")
			RespondWithStatus(ctx, w, b, int(httpErr.Code))
			return
		}
	}
	w.Header().Set("Content-Type", "application/protobuf")
	RespondWithStatus(ctx, w, httpErr.Encode(), int(httpErr.Code))
}

// resolveApiErr maps err onto the ApiErr sent back to the client. Anything that
// is not an ApiErr or a validation failure is an unhandled fault, so it becomes
// a 500 with no detail leaked to the caller.
func resolveApiErr(err error) ApiErr {
	var httpErr ApiErr
	if errors.As(err, &httpErr) {
		return httpErr
	}
	var httpErrPtr *ApiErr
	if errors.As(err, &httpErrPtr) && httpErrPtr != nil {
		return *httpErrPtr
	}
	var validationErr *ValidationError
	if errors.As(err, &validationErr) {
		return ApiErr{DisplayErr: validationErr.Error(), Code: http.StatusBadRequest}
	}
	return ApiErr{DisplayErr: "Unknown server error", Code: http.StatusInternalServerError}
}

const (
	compressionModeAuto int32 = iota
	compressionModeAlways
	compressionModeNever
)

func decodeBody[T any](r *http.Request, decode func([]byte) (*T, error)) (*T, error) {
	b, err := io.ReadAll(r.Body)
	if err != nil {
		return nil, err
	}
	return decodeRequestPayload(r, b, decode)
}

func decodeWithMaxBodySize[T any](r *http.Request, maxRequestBodySize int, decode func([]byte) (*T, error)) (*T, error) {
	if maxRequestBodySize <= 0 {
		return decodeBody(r, decode)
	}
	limit := int64(maxRequestBodySize)
	b, err := io.ReadAll(io.LimitReader(r.Body, limit+1))
	if err != nil {
		return nil, err
	}
	if int64(len(b)) > limit {
		return nil, ApiErr{DisplayErr: "Request body too large", InternalErr: "request body exceeds max size", Code: http.StatusRequestEntityTooLarge}
	}
	return decodeRequestPayload(r, b, decode)
}

// decodeRequestPayload unmarshals b as JSON when the request declared a JSON
// Content-Type, and as protobuf otherwise. An empty body yields the zero
// message either way, matching how protobuf decodes zero bytes.
func decodeRequestPayload[T any](r *http.Request, b []byte, decode func([]byte) (*T, error)) (*T, error) {
	if !negotiatedJSONRequest(r) {
		return decode(b)
	}
	var m T
	if len(b) == 0 {
		return &m, nil
	}
	if err := json.Unmarshal(b, &m); err != nil {
		return nil, ApiErr{DisplayErr: "Malformed JSON request body", InternalErr: err.Error(), Code: http.StatusBadRequest}
	}
	return &m, nil
}

// StreamReader reads uvarint length-prefixed protobuf frames from r. It is used
// by generated client-streaming handlers to lazily decode request frames.
type StreamReader struct {
	r            *bufio.Reader
	maxFrameSize int
}

// NewStreamReader wraps r with a buffered reader for length-prefixed frames.
// If maxFrameSize > 0, frames whose payload exceeds it are rejected with an
// ApiErr carrying http.StatusRequestEntityTooLarge.
func NewStreamReader(r io.Reader, maxFrameSize int) *StreamReader {
	return &StreamReader{r: bufio.NewReader(r), maxFrameSize: maxFrameSize}
}

// Next returns the payload bytes of the next frame. At end-of-stream returns
// (nil, false, nil). Framing or size errors return (nil, false, err).
func (s *StreamReader) Next() ([]byte, bool, error) {
	size, err := binary.ReadUvarint(s.r)
	if err != nil {
		if errors.Is(err, io.EOF) {
			return nil, false, nil
		}
		if errors.Is(err, io.ErrUnexpectedEOF) {
			return nil, false, fmt.Errorf("stream truncated mid-frame header: %w", err)
		}
		return nil, false, err
	}
	if s.maxFrameSize > 0 && size > uint64(s.maxFrameSize) {
		return nil, false, ApiErr{DisplayErr: "Request frame too large", InternalErr: "request frame exceeds max size", Code: http.StatusRequestEntityTooLarge}
	}
	if size == 0 {
		return nil, true, nil
	}
	payload := make([]byte, size)
	if _, err := io.ReadFull(s.r, payload); err != nil {
		if errors.Is(err, io.EOF) || errors.Is(err, io.ErrUnexpectedEOF) {
			return nil, false, fmt.Errorf("stream truncated mid-frame body: %w", err)
		}
		return nil, false, err
	}
	return payload, true, nil
}

func WriteStreamFrame(w io.Writer, payload []byte) error {
	var header [binary.MaxVarintLen64]byte
	n := binary.PutUvarint(header[:], uint64(len(payload)))
	if _, err := w.Write(header[:n]); err != nil {
		return err
	}
	if len(payload) > 0 {
		if _, err := w.Write(payload); err != nil {
			return err
		}
	}
	return nil
}

// StreamWriter lazily commits a protobuf-stream response on the first frame.
type StreamWriter struct {
	w       http.ResponseWriter
	control *http.ResponseController
	started bool
}

func NewStreamWriter(w http.ResponseWriter) *StreamWriter {
	return &StreamWriter{w: w, control: http.NewResponseController(w)}
}

func (s *StreamWriter) Write(payload []byte) error {
	if !s.started {
		s.started = true
		SetStreamHeaders(s.w)
	}
	if err := WriteStreamFrame(s.w, payload); err != nil {
		return err
	}
	return s.control.Flush()
}

func (s *StreamWriter) Finish(ctx context.Context, err error) {
	if err != nil {
		if !s.started {
			// Streaming responses are protobuf-framed regardless of Accept, so
			// their failures report as protobuf too.
			handleReqErr(ctx, err, "", false, s.w)
			return
		}
		slog.ErrorContext(ctx, fmt.Sprintf("stream err: %v", err.Error()))
		return
	}
	if s.started {
		return
	}
	SetStreamHeaders(s.w)
	s.w.WriteHeader(http.StatusOK)
}

// SetStreamHeaders sets the response headers for a server-streaming RPC.
// In addition to the protobuf-stream content type, it disables intermediate
// buffering: nginx and similar reverse proxies respect "X-Accel-Buffering: no",
// and "Cache-Control: no-cache" prevents caching layers from holding onto the
// response. Caching also implies the proxy must not transform the body.
func SetStreamHeaders(w http.ResponseWriter) {
	h := w.Header()
	h.Set("Content-Type", "application/protobuf-stream")
	h.Set("Cache-Control", "no-cache, no-transform")
	h.Set("X-Accel-Buffering", "no")
}

func NewApiErr(displayErr string, internalErr string, code int32) ApiErr {
	return ApiErr{DisplayErr: displayErr, InternalErr: internalErr, Code: code}
}

func (e ApiErr) Error() string {
	if e.InternalErr != "" {
		return e.InternalErr
	}
	return e.DisplayErr
}

// ValidationError represents a buf.validate constraint failure on a request payload.
// The Path slice records the path to the offending field, joined with dots when
// rendered (e.g. "user.email" or "items[3].name").
type ValidationError struct {
	Path   []string
	Reason string
}

func (e *ValidationError) Error() string {
	return joinValidationPath(e.Path) + ": " + e.Reason
}

func joinValidationPath(parts []string) string {
	switch len(parts) {
	case 0:
		return ""
	case 1:
		return parts[0]
	}
	n := len(parts) - 1
	for _, p := range parts {
		n += len(p)
	}
	out := make([]byte, 0, n)
	for i, p := range parts {
		if i > 0 && len(p) > 0 && p[0] != '[' {
			out = append(out, '.')
		}
		out = append(out, p...)
	}
	return string(out)
}

func newValidationError(path []string, reason string) *ValidationError {
	return &ValidationError{Path: path, Reason: reason}
}

func wrapValidationError(err error, segment string) error {
	if err == nil {
		return nil
	}
	var ve *ValidationError
	if errors.As(err, &ve) {
		path := make([]string, 0, len(ve.Path)+1)
		path = append(path, segment)
		path = append(path, ve.Path...)
		ve.Path = path
		return ve
	}
	return err
}
