// Code generated by cleanproto. DO NOT EDIT.

package apigen

import (
	"errors"
	"github.com/google/uuid"
	"io"
	"math"
	"sort"
	"time"
	"unicode/utf8"
)

var errInvalidWireType = errors.New("invalid wire type")
var errInvalidUTF8 = errors.New("invalid UTF-8")

func ConsumeTag(b []byte) ([]byte, Number, Type, error) {
	num, typ, n := consumeTag(b)
	if err := ParseError(n); err != nil {
		return nil, 0, 0, err
	}
	return b[n:], num, typ, nil
}

func SkipFieldValue(b []byte, num Number, typ Type) ([]byte, error) {
	n := ConsumeFieldValue(num, typ, b)
	if err := ParseError(n); err != nil {
		return nil, err
	}
	return b[n:], nil
}

func ConsumeVarInt32(b []byte, typ Type) ([]byte, int32, error) {
	if typ != VarintType {
		return nil, 0, errInvalidWireType
	}
	v, n := ConsumeVarint(b)
	if err := ParseError(n); err != nil {
		return nil, 0, err
	}
	return b[n:], int32(v), nil
}

func ConsumeVarInt64(b []byte, typ Type) ([]byte, int64, error) {
	if typ != VarintType {
		return nil, 0, errInvalidWireType
	}
	v, n := ConsumeVarint(b)
	if err := ParseError(n); err != nil {
		return nil, 0, err
	}
	return b[n:], int64(v), nil
}

func ConsumeVarUint32(b []byte, typ Type) ([]byte, uint32, error) {
	if typ != VarintType {
		return nil, 0, errInvalidWireType
	}
	v, n := ConsumeVarint(b)
	if err := ParseError(n); err != nil {
		return nil, 0, err
	}
	return b[n:], uint32(v), nil
}

func ConsumeVarUint64(b []byte, typ Type) ([]byte, uint64, error) {
	if typ != VarintType {
		return nil, 0, errInvalidWireType
	}
	v, n := ConsumeVarint(b)
	if err := ParseError(n); err != nil {
		return nil, 0, err
	}
	return b[n:], v, nil
}

func ConsumeSint32(b []byte, typ Type) ([]byte, int32, error) {
	if typ != VarintType {
		return nil, 0, errInvalidWireType
	}
	v, n := ConsumeVarint(b)
	if err := ParseError(n); err != nil {
		return nil, 0, err
	}
	return b[n:], int32(DecodeZigZag(v)), nil
}

func ConsumeSint64(b []byte, typ Type) ([]byte, int64, error) {
	if typ != VarintType {
		return nil, 0, errInvalidWireType
	}
	v, n := ConsumeVarint(b)
	if err := ParseError(n); err != nil {
		return nil, 0, err
	}
	return b[n:], int64(DecodeZigZag(v)), nil
}

func ConsumeBool(b []byte, typ Type) ([]byte, bool, error) {
	if typ != VarintType {
		return nil, false, errInvalidWireType
	}
	v, n := ConsumeVarint(b)
	if err := ParseError(n); err != nil {
		return nil, false, err
	}
	return b[n:], v != 0, nil
}

func ConsumeEnum(b []byte, typ Type) ([]byte, int32, error) {
	return ConsumeVarInt32(b, typ)
}

func ConsumeFixedInt32(b []byte, typ Type) ([]byte, int32, error) {
	if typ != Fixed32Type {
		return nil, 0, errInvalidWireType
	}
	v, n := ConsumeFixed32(b)
	if err := ParseError(n); err != nil {
		return nil, 0, err
	}
	return b[n:], int32(v), nil
}

func ConsumeFixedUint32(b []byte, typ Type) ([]byte, uint32, error) {
	if typ != Fixed32Type {
		return nil, 0, errInvalidWireType
	}
	v, n := ConsumeFixed32(b)
	if err := ParseError(n); err != nil {
		return nil, 0, err
	}
	return b[n:], v, nil
}

func ConsumeFixedInt64(b []byte, typ Type) ([]byte, int64, error) {
	if typ != Fixed64Type {
		return nil, 0, errInvalidWireType
	}
	v, n := ConsumeFixed64(b)
	if err := ParseError(n); err != nil {
		return nil, 0, err
	}
	return b[n:], int64(v), nil
}

func ConsumeFixedUint64(b []byte, typ Type) ([]byte, uint64, error) {
	if typ != Fixed64Type {
		return nil, 0, errInvalidWireType
	}
	v, n := ConsumeFixed64(b)
	if err := ParseError(n); err != nil {
		return nil, 0, err
	}
	return b[n:], v, nil
}

func ConsumeSfixed32(b []byte, typ Type) ([]byte, int32, error) {
	return ConsumeFixedInt32(b, typ)
}

func ConsumeSfixed64(b []byte, typ Type) ([]byte, int64, error) {
	return ConsumeFixedInt64(b, typ)
}

func ConsumeFloat32(b []byte, typ Type) ([]byte, float32, error) {
	if typ != Fixed32Type {
		return nil, 0, errInvalidWireType
	}
	v, n := ConsumeFixed32(b)
	if err := ParseError(n); err != nil {
		return nil, 0, err
	}
	return b[n:], math.Float32frombits(v), nil
}

func ConsumeFloat64(b []byte, typ Type) ([]byte, float64, error) {
	if typ != Fixed64Type {
		return nil, 0, errInvalidWireType
	}
	v, n := ConsumeFixed64(b)
	if err := ParseError(n); err != nil {
		return nil, 0, err
	}
	return b[n:], math.Float64frombits(v), nil
}

func ConsumeBytes(b []byte, typ Type) ([]byte, []byte, error) {
	if typ != BytesType {
		return nil, nil, errInvalidWireType
	}
	v, n := consumeBytes(b)
	if err := ParseError(n); err != nil {
		return nil, nil, err
	}
	return b[n:], v, nil
}

func ConsumeString(b []byte, typ Type) ([]byte, string, error) {
	if typ != BytesType {
		return nil, "", errInvalidWireType
	}
	v, n := consumeBytes(b)
	if err := ParseError(n); err != nil {
		return nil, "", err
	}
	if !utf8.Valid(v) {
		return nil, "", errInvalidUTF8
	}
	return b[n:], string(v), nil
}

func ConsumeMessage(b []byte, typ Type) ([]byte, []byte, error) {
	return ConsumeBytes(b, typ)
}

// ---- Everything below is copied/adapted from the google.golang.org/protobuf/encoding/protowire package. ----
// Copyright 2018 The Go Authors. All rights reserved.
// Use of this source code is governed by a BSD-style license.

// Number represents the field number.
type Number int32

const (
	MinValidNumber        Number = 1
	MaxValidNumber        Number = 1<<29 - 1
	DefaultRecursionLimit        = 10000
)

// Type represents the wire type.
type Type int8

const (
	VarintType     Type = 0
	Fixed32Type    Type = 5
	Fixed64Type    Type = 1
	BytesType      Type = 2
	StartGroupType Type = 3
	EndGroupType   Type = 4
)

const (
	_ = -iota
	errCodeTruncated
	errCodeFieldNumber
	errCodeOverflow
	errCodeReserved
	errCodeEndGroup
	errCodeRecursionDepth
)

var (
	errFieldNumber = errors.New("invalid field number")
	errOverflow    = errors.New("variable length integer overflow")
	errReserved    = errors.New("cannot parse reserved wire type")
	errEndGroup    = errors.New("mismatching end group marker")
	errParse       = errors.New("parse error")
)

// ParseError converts an error code into an error value.
// This returns nil if n is a non-negative number.
func ParseError(n int) error {
	if n >= 0 {
		return nil
	}
	switch n {
	case errCodeTruncated:
		return io.ErrUnexpectedEOF
	case errCodeFieldNumber:
		return errFieldNumber
	case errCodeOverflow:
		return errOverflow
	case errCodeReserved:
		return errReserved
	case errCodeEndGroup:
		return errEndGroup
	default:
		return errParse
	}
}

// ConsumeFieldValue parses a field value and returns its length.
// This assumes that the field Number and wire Type have already been parsed.
// This returns a negative length upon an error (see ParseError).
func ConsumeFieldValue(num Number, typ Type, b []byte) (n int) {
	return consumeFieldValueD(num, typ, b, DefaultRecursionLimit)
}

func consumeFieldValueD(num Number, typ Type, b []byte, depth int) (n int) {
	switch typ {
	case VarintType:
		_, n = ConsumeVarint(b)
		return n
	case Fixed32Type:
		_, n = ConsumeFixed32(b)
		return n
	case Fixed64Type:
		_, n = ConsumeFixed64(b)
		return n
	case BytesType:
		_, n = consumeBytes(b)
		return n
	case StartGroupType:
		if depth < 0 {
			return errCodeRecursionDepth
		}
		n0 := len(b)
		for {
			num2, typ2, n := consumeTag(b)
			if n < 0 {
				return n
			}
			b = b[n:]
			if typ2 == EndGroupType {
				if num != num2 {
					return errCodeEndGroup
				}
				return n0 - len(b)
			}

			n = consumeFieldValueD(num2, typ2, b, depth-1)
			if n < 0 {
				return n
			}
			b = b[n:]
		}
	case EndGroupType:
		return errCodeEndGroup
	default:
		return errCodeReserved
	}
}

// AppendTag encodes num and typ as a varint-encoded tag and appends it to b.
func AppendTag(b []byte, num Number, typ Type) []byte {
	return AppendVarint(b, EncodeTag(num, typ))
}

func consumeTag(b []byte) (Number, Type, int) {
	v, n := ConsumeVarint(b)
	if n < 0 {
		return 0, 0, n
	}
	num, typ := DecodeTag(v)
	if num < MinValidNumber {
		return 0, 0, errCodeFieldNumber
	}
	return num, typ, n
}

// AppendVarint appends v to b as a varint-encoded uint64.
func AppendVarint(b []byte, v uint64) []byte {
	switch {
	case v < 1<<7:
		b = append(b, byte(v))
	case v < 1<<14:
		b = append(b,
			byte((v>>0)&0x7f|0x80),
			byte(v>>7))
	case v < 1<<21:
		b = append(b,
			byte((v>>0)&0x7f|0x80),
			byte((v>>7)&0x7f|0x80),
			byte(v>>14))
	case v < 1<<28:
		b = append(b,
			byte((v>>0)&0x7f|0x80),
			byte((v>>7)&0x7f|0x80),
			byte((v>>14)&0x7f|0x80),
			byte(v>>21))
	case v < 1<<35:
		b = append(b,
			byte((v>>0)&0x7f|0x80),
			byte((v>>7)&0x7f|0x80),
			byte((v>>14)&0x7f|0x80),
			byte((v>>21)&0x7f|0x80),
			byte(v>>28))
	case v < 1<<42:
		b = append(b,
			byte((v>>0)&0x7f|0x80),
			byte((v>>7)&0x7f|0x80),
			byte((v>>14)&0x7f|0x80),
			byte((v>>21)&0x7f|0x80),
			byte((v>>28)&0x7f|0x80),
			byte(v>>35))
	case v < 1<<49:
		b = append(b,
			byte((v>>0)&0x7f|0x80),
			byte((v>>7)&0x7f|0x80),
			byte((v>>14)&0x7f|0x80),
			byte((v>>21)&0x7f|0x80),
			byte((v>>28)&0x7f|0x80),
			byte((v>>35)&0x7f|0x80),
			byte(v>>42))
	case v < 1<<56:
		b = append(b,
			byte((v>>0)&0x7f|0x80),
			byte((v>>7)&0x7f|0x80),
			byte((v>>14)&0x7f|0x80),
			byte((v>>21)&0x7f|0x80),
			byte((v>>28)&0x7f|0x80),
			byte((v>>35)&0x7f|0x80),
			byte((v>>42)&0x7f|0x80),
			byte(v>>49))
	case v < 1<<63:
		b = append(b,
			byte((v>>0)&0x7f|0x80),
			byte((v>>7)&0x7f|0x80),
			byte((v>>14)&0x7f|0x80),
			byte((v>>21)&0x7f|0x80),
			byte((v>>28)&0x7f|0x80),
			byte((v>>35)&0x7f|0x80),
			byte((v>>42)&0x7f|0x80),
			byte((v>>49)&0x7f|0x80),
			byte(v>>56))
	default:
		b = append(b,
			byte((v>>0)&0x7f|0x80),
			byte((v>>7)&0x7f|0x80),
			byte((v>>14)&0x7f|0x80),
			byte((v>>21)&0x7f|0x80),
			byte((v>>28)&0x7f|0x80),
			byte((v>>35)&0x7f|0x80),
			byte((v>>42)&0x7f|0x80),
			byte((v>>49)&0x7f|0x80),
			byte((v>>56)&0x7f|0x80),
			1)
	}
	return b
}

// ConsumeVarint parses b as a varint-encoded uint64, reporting its length.
// This returns a negative length upon an error (see ParseError).
func ConsumeVarint(b []byte) (v uint64, n int) {
	var y uint64
	if len(b) <= 0 {
		return 0, errCodeTruncated
	}
	v = uint64(b[0])
	if v < 0x80 {
		return v, 1
	}
	v -= 0x80

	if len(b) <= 1 {
		return 0, errCodeTruncated
	}
	y = uint64(b[1])
	v += y << 7
	if y < 0x80 {
		return v, 2
	}
	v -= 0x80 << 7

	if len(b) <= 2 {
		return 0, errCodeTruncated
	}
	y = uint64(b[2])
	v += y << 14
	if y < 0x80 {
		return v, 3
	}
	v -= 0x80 << 14

	if len(b) <= 3 {
		return 0, errCodeTruncated
	}
	y = uint64(b[3])
	v += y << 21
	if y < 0x80 {
		return v, 4
	}
	v -= 0x80 << 21

	if len(b) <= 4 {
		return 0, errCodeTruncated
	}
	y = uint64(b[4])
	v += y << 28
	if y < 0x80 {
		return v, 5
	}
	v -= 0x80 << 28

	if len(b) <= 5 {
		return 0, errCodeTruncated
	}
	y = uint64(b[5])
	v += y << 35
	if y < 0x80 {
		return v, 6
	}
	v -= 0x80 << 35

	if len(b) <= 6 {
		return 0, errCodeTruncated
	}
	y = uint64(b[6])
	v += y << 42
	if y < 0x80 {
		return v, 7
	}
	v -= 0x80 << 42

	if len(b) <= 7 {
		return 0, errCodeTruncated
	}
	y = uint64(b[7])
	v += y << 49
	if y < 0x80 {
		return v, 8
	}
	v -= 0x80 << 49

	if len(b) <= 8 {
		return 0, errCodeTruncated
	}
	y = uint64(b[8])
	v += y << 56
	if y < 0x80 {
		return v, 9
	}
	v -= 0x80 << 56

	if len(b) <= 9 {
		return 0, errCodeTruncated
	}
	y = uint64(b[9])
	v += y << 63
	if y < 2 {
		return v, 10
	}
	return 0, errCodeOverflow
}

// AppendFixed32 appends v to b as a little-endian uint32.
func AppendFixed32(b []byte, v uint32) []byte {
	return append(b,
		byte(v>>0),
		byte(v>>8),
		byte(v>>16),
		byte(v>>24))
}

// ConsumeFixed32 parses b as a little-endian uint32, reporting its length.
// This returns a negative length upon an error (see ParseError).
func ConsumeFixed32(b []byte) (v uint32, n int) {
	if len(b) < 4 {
		return 0, errCodeTruncated
	}
	v = uint32(b[0])<<0 | uint32(b[1])<<8 | uint32(b[2])<<16 | uint32(b[3])<<24
	return v, 4
}

// AppendFixed64 appends v to b as a little-endian uint64.
func AppendFixed64(b []byte, v uint64) []byte {
	return append(b,
		byte(v>>0),
		byte(v>>8),
		byte(v>>16),
		byte(v>>24),
		byte(v>>32),
		byte(v>>40),
		byte(v>>48),
		byte(v>>56))
}

// ConsumeFixed64 parses b as a little-endian uint64, reporting its length.
// This returns a negative length upon an error (see ParseError).
func ConsumeFixed64(b []byte) (v uint64, n int) {
	if len(b) < 8 {
		return 0, errCodeTruncated
	}
	v = uint64(b[0])<<0 | uint64(b[1])<<8 | uint64(b[2])<<16 | uint64(b[3])<<24 | uint64(b[4])<<32 | uint64(b[5])<<40 | uint64(b[6])<<48 | uint64(b[7])<<56
	return v, 8
}

// AppendBytes appends v to b as a length-prefixed bytes value.
func AppendBytes(b []byte, v []byte) []byte {
	return append(AppendVarint(b, uint64(len(v))), v...)
}

func consumeBytes(b []byte) (v []byte, n int) {
	m, n := ConsumeVarint(b)
	if n < 0 {
		return nil, n
	}
	if m > uint64(len(b[n:])) {
		return nil, errCodeTruncated
	}
	return b[n:][:m], n + int(m)
}

// DecodeTag decodes the field Number and wire Type from its unified form.
// The Number is -1 if the decoded field number overflows int32.
func DecodeTag(x uint64) (Number, Type) {
	if x>>3 > uint64(math.MaxInt32) {
		return -1, 0
	}
	return Number(x >> 3), Type(x & 7)
}

// EncodeTag encodes the field Number and wire Type into its unified form.
func EncodeTag(num Number, typ Type) uint64 {
	return uint64(num)<<3 | uint64(typ&7)
}

// DecodeZigZag decodes a zig-zag-encoded uint64 as an int64.
func DecodeZigZag(x uint64) int64 {
	return int64(x>>1) ^ int64(x)<<63>>63
}

// EncodeZigZag encodes an int64 as a zig-zag-encoded uint64.
func EncodeZigZag(x int64) uint64 {
	return uint64(x<<1) ^ uint64(x>>63)
}

func EncodeTimestamp(t time.Time) []byte {
	if t.IsZero() {
		return nil
	}
	var b []byte
	seconds := t.Unix()
	nanos := int32(t.Nanosecond())
	b = AppendTag(b, 1, VarintType)
	b = AppendVarint(b, uint64(seconds))
	if nanos != 0 {
		b = AppendTag(b, 2, VarintType)
		b = AppendVarint(b, uint64(int64(nanos)))
	}
	return b
}

func DecodeTimestamp(b []byte) (time.Time, error) {
	var seconds int64
	var nanos int32
	for len(b) > 0 {
		var num Number
		var typ Type
		var err error
		b, num, typ, err = ConsumeTag(b)
		if err != nil {
			return time.Time{}, err
		}
		switch num {
		case 1:
			b, seconds, err = ConsumeVarInt64(b, typ)
			if err != nil {
				return time.Time{}, err
			}
		case 2:
			var n int32
			b, n, err = ConsumeVarInt32(b, typ)
			if err != nil {
				return time.Time{}, err
			}
			nanos = n
		default:
			b, err = SkipFieldValue(b, num, typ)
			if err != nil {
				return time.Time{}, err
			}
		}
	}
	return time.Unix(seconds, int64(nanos)), nil
}

func ConsumeTimestamp(b []byte, typ Type) ([]byte, time.Time, error) {
	var msgBytes []byte
	var err error
	b, msgBytes, err = ConsumeMessage(b, typ)
	if err != nil {
		return nil, time.Time{}, err
	}
	msg, err := DecodeTimestamp(msgBytes)
	if err != nil {
		return nil, time.Time{}, err
	}
	return b, msg, nil
}

func AppendTimestampFromTime(b []byte, v time.Time, num Number) []byte {
	if v.IsZero() {
		return b
	}
	return AppendBytesField(b, EncodeTimestamp(v), num)
}

func AppendInt32FromTime(b []byte, v time.Time, num Number) []byte {
	if v.IsZero() {
		return b
	}
	return AppendInt32Field(b, int32(v.Unix()), num)
}

func AppendInt64FromTime(b []byte, v time.Time, num Number) []byte {
	if v.IsZero() {
		return b
	}
	return AppendInt64Field(b, v.UnixMilli(), num)
}

func ConsumeTimeFromTimestamp(b []byte, typ Type) ([]byte, time.Time, error) {
	return ConsumeTimestamp(b, typ)
}

func ConsumeTimeFromTimestampOpt(b []byte, typ Type) ([]byte, *time.Time, error) {
	var v time.Time
	var err error
	b, v, err = ConsumeTimeFromTimestamp(b, typ)
	if err != nil {
		return nil, nil, err
	}
	return b, &v, nil
}

func ConsumeTimeFromInt32(b []byte, typ Type) ([]byte, time.Time, error) {
	var raw int32
	var err error
	b, raw, err = ConsumeVarInt32(b, typ)
	if err != nil {
		return nil, time.Time{}, err
	}
	return b, time.Unix(int64(raw), 0), nil
}

func ConsumeTimeFromInt32Opt(b []byte, typ Type) ([]byte, *time.Time, error) {
	var v time.Time
	var err error
	b, v, err = ConsumeTimeFromInt32(b, typ)
	if err != nil {
		return nil, nil, err
	}
	return b, &v, nil
}

func ConsumeTimeFromInt64(b []byte, typ Type) ([]byte, time.Time, error) {
	var raw int64
	var err error
	b, raw, err = ConsumeVarInt64(b, typ)
	if err != nil {
		return nil, time.Time{}, err
	}
	return b, time.UnixMilli(raw), nil
}

func ConsumeTimeFromInt64Opt(b []byte, typ Type) ([]byte, *time.Time, error) {
	var v time.Time
	var err error
	b, v, err = ConsumeTimeFromInt64(b, typ)
	if err != nil {
		return nil, nil, err
	}
	return b, &v, nil
}

func EncodeDuration(d time.Duration) []byte {
	if d == 0 {
		return nil
	}
	var b []byte
	seconds := int64(d / time.Second)
	nanos := int32(d % time.Second)
	b = AppendTag(b, 1, VarintType)
	b = AppendVarint(b, uint64(seconds))
	if nanos != 0 {
		b = AppendTag(b, 2, VarintType)
		b = AppendVarint(b, uint64(int64(nanos)))
	}
	return b
}

func DecodeDuration(b []byte) (time.Duration, error) {
	var seconds int64
	var nanos int32
	for len(b) > 0 {
		var num Number
		var typ Type
		var err error
		b, num, typ, err = ConsumeTag(b)
		if err != nil {
			return 0, err
		}
		switch num {
		case 1:
			b, seconds, err = ConsumeVarInt64(b, typ)
			if err != nil {
				return 0, err
			}
		case 2:
			var n int32
			b, n, err = ConsumeVarInt32(b, typ)
			if err != nil {
				return 0, err
			}
			nanos = n
		default:
			b, err = SkipFieldValue(b, num, typ)
			if err != nil {
				return 0, err
			}
		}
	}
	return time.Duration(seconds)*time.Second + time.Duration(nanos), nil
}

func ConsumeDuration(b []byte, typ Type) ([]byte, time.Duration, error) {
	var msgBytes []byte
	var err error
	b, msgBytes, err = ConsumeMessage(b, typ)
	if err != nil {
		return nil, 0, err
	}
	msg, err := DecodeDuration(msgBytes)
	if err != nil {
		return nil, 0, err
	}
	return b, msg, nil
}

func ConsumeDurationOpt(b []byte, typ Type) ([]byte, *time.Duration, error) {
	var v time.Duration
	var err error
	b, v, err = ConsumeDuration(b, typ)
	if err != nil {
		return nil, nil, err
	}
	return b, &v, nil
}

func AppendDurationFromDuration(b []byte, v time.Duration, num Number) []byte {
	if v == 0 {
		return b
	}
	return AppendBytesField(b, EncodeDuration(v), num)
}

func AppendInt32FromDuration(b []byte, v time.Duration, num Number) []byte {
	if v == 0 {
		return b
	}
	return AppendInt32Field(b, int32(v/time.Second), num)
}

func AppendInt64FromDuration(b []byte, v time.Duration, num Number) []byte {
	if v == 0 {
		return b
	}
	return AppendInt64Field(b, int64(v/time.Second), num)
}

func ConsumeDurationFromDuration(b []byte, typ Type) ([]byte, time.Duration, error) {
	return ConsumeDuration(b, typ)
}

func ConsumeDurationFromDurationOpt(b []byte, typ Type) ([]byte, *time.Duration, error) {
	var v time.Duration
	var err error
	b, v, err = ConsumeDurationFromDuration(b, typ)
	if err != nil {
		return nil, nil, err
	}
	return b, &v, nil
}

func ConsumeDurationFromInt32(b []byte, typ Type) ([]byte, time.Duration, error) {
	var raw int32
	var err error
	b, raw, err = ConsumeVarInt32(b, typ)
	if err != nil {
		return nil, 0, err
	}
	return b, time.Duration(raw) * time.Second, nil
}

func ConsumeDurationFromInt32Opt(b []byte, typ Type) ([]byte, *time.Duration, error) {
	var v time.Duration
	var err error
	b, v, err = ConsumeDurationFromInt32(b, typ)
	if err != nil {
		return nil, nil, err
	}
	return b, &v, nil
}

func ConsumeDurationFromInt64(b []byte, typ Type) ([]byte, time.Duration, error) {
	var raw int64
	var err error
	b, raw, err = ConsumeVarInt64(b, typ)
	if err != nil {
		return nil, 0, err
	}
	return b, time.Duration(raw) * time.Second, nil
}

func ConsumeDurationFromInt64Opt(b []byte, typ Type) ([]byte, *time.Duration, error) {
	var v time.Duration
	var err error
	b, v, err = ConsumeDurationFromInt64(b, typ)
	if err != nil {
		return nil, nil, err
	}
	return b, &v, nil
}

func AppendBytesFromUUID(b []byte, v uuid.UUID, num Number) []byte {
	if v == uuid.Nil {
		return b
	}
	return AppendBytesField(b, v[:], num)
}

func ConsumeUUIDFromBytes(b []byte, typ Type) ([]byte, uuid.UUID, error) {
	var raw []byte
	var err error
	b, raw, err = ConsumeBytes(b, typ)
	if err != nil {
		return nil, uuid.Nil, err
	}
	v, err := uuid.FromBytes(raw)
	if err != nil {
		return nil, uuid.Nil, err
	}
	return b, v, nil
}

// Elem variants for repeated fields: a zero value is emitted as the field's
// zero encoding rather than skipped, so later elements keep their positions.

func AppendTimestampFromTimeElem(b []byte, v time.Time, num Number) []byte {
	return AppendBytesElem(b, EncodeTimestamp(v), num)
}

func AppendInt32FromTimeElem(b []byte, v time.Time, num Number) []byte {
	if v.IsZero() {
		return AppendInt32Elem(b, 0, num)
	}
	return AppendInt32Elem(b, int32(v.Unix()), num)
}

func AppendInt64FromTimeElem(b []byte, v time.Time, num Number) []byte {
	if v.IsZero() {
		return AppendInt64Elem(b, 0, num)
	}
	return AppendInt64Elem(b, v.UnixMilli(), num)
}

func AppendDurationFromDurationElem(b []byte, v time.Duration, num Number) []byte {
	return AppendBytesElem(b, EncodeDuration(v), num)
}

func AppendInt32FromDurationElem(b []byte, v time.Duration, num Number) []byte {
	return AppendInt32Elem(b, int32(v/time.Second), num)
}

func AppendInt64FromDurationElem(b []byte, v time.Duration, num Number) []byte {
	return AppendInt64Elem(b, int64(v/time.Second), num)
}

func AppendBytesFromUUIDElem(b []byte, v uuid.UUID, num Number) []byte {
	return AppendBytesElem(b, v[:], num)
}

func ConsumeUUIDFromBytesOpt(b []byte, typ Type) ([]byte, *uuid.UUID, error) {
	var v uuid.UUID
	var err error
	b, v, err = ConsumeUUIDFromBytes(b, typ)
	if err != nil {
		return nil, nil, err
	}
	return b, &v, nil
}

func ConsumeMapEntry[K comparable, V any](b []byte, typ Type, m map[K]V, consumeK func([]byte, Type) ([]byte, K, error), consumeV func([]byte, Type) ([]byte, V, error)) ([]byte, error) {
	var key K
	var value V
	if typ != BytesType {
		return nil, errInvalidWireType
	}
	var entryBytes []byte
	var err error
	b, entryBytes, err = ConsumeMessage(b, typ)
	if err != nil {
		return nil, err
	}
	for len(entryBytes) > 0 {
		var num Number
		var t Type
		var err2 error
		entryBytes, num, t, err2 = ConsumeTag(entryBytes)
		if err2 != nil {
			return nil, err2
		}
		switch num {
		case 1:
			entryBytes, key, err2 = consumeK(entryBytes, t)
			if err2 != nil {
				return nil, err2
			}
		case 2:
			entryBytes, value, err2 = consumeV(entryBytes, t)
			if err2 != nil {
				return nil, err2
			}
		default:
			entryBytes, err2 = SkipFieldValue(entryBytes, num, t)
			if err2 != nil {
				return nil, err2
			}
		}
	}
	m[key] = value
	return b, nil
}

func ConsumeMessageDecorator[T any](decodeFunc func([]byte) (T, error)) func(b []byte, typ Type) ([]byte, T, error) {
	return func(b []byte, typ Type) ([]byte, T, error) {
		var zeroV T
		var msgBytes []byte
		var err error
		b, msgBytes, err = ConsumeMessage(b, typ)
		if err != nil {
			return nil, zeroV, err
		}
		msg, err := decodeFunc(msgBytes)
		if err != nil {
			return nil, zeroV, err
		}
		return b, msg, nil
	}
}

func ConsumeRepeatedElement[T any](b []byte, typ Type, consume func([]byte, Type) ([]byte, T, error)) ([]byte, T, error) {
	var item T
	var err error
	b, item, err = consume(b, typ)
	if err != nil {
		return nil, item, err
	}
	return b, item, nil
}

func ConsumeRepeatedCompact[T any](b []byte, typ Type, elemTyp Type, consume func([]byte, Type) ([]byte, T, error)) ([]byte, []T, error) {
	if typ != BytesType || elemTyp == BytesType {
		return nil, nil, errInvalidWireType
	}
	var packed []byte
	var err error
	b, packed, err = ConsumeBytes(b, typ)
	if err != nil {
		return nil, nil, err
	}
	var items []T
	for len(packed) > 0 {
		var v T
		packed, v, err = consume(packed, elemTyp)
		if err != nil {
			return nil, nil, err
		}
		items = append(items, v)
	}
	return b, items, nil
}

func ConsumeVarInt32Opt(b []byte, typ Type) ([]byte, *int32, error) {
	var v int32
	var err error
	b, v, err = ConsumeVarInt32(b, typ)
	if err != nil {
		return nil, nil, err
	}
	return b, &v, nil
}

func ConsumeVarInt64Opt(b []byte, typ Type) ([]byte, *int64, error) {
	var v int64
	var err error
	b, v, err = ConsumeVarInt64(b, typ)
	if err != nil {
		return nil, nil, err
	}
	return b, &v, nil
}

func ConsumeVarUint32Opt(b []byte, typ Type) ([]byte, *uint32, error) {
	var v uint32
	var err error
	b, v, err = ConsumeVarUint32(b, typ)
	if err != nil {
		return nil, nil, err
	}
	return b, &v, nil
}

func ConsumeVarUint64Opt(b []byte, typ Type) ([]byte, *uint64, error) {
	var v uint64
	var err error
	b, v, err = ConsumeVarUint64(b, typ)
	if err != nil {
		return nil, nil, err
	}
	return b, &v, nil
}

func ConsumeSint32Opt(b []byte, typ Type) ([]byte, *int32, error) {
	var v int32
	var err error
	b, v, err = ConsumeSint32(b, typ)
	if err != nil {
		return nil, nil, err
	}
	return b, &v, nil
}

func ConsumeSint64Opt(b []byte, typ Type) ([]byte, *int64, error) {
	var v int64
	var err error
	b, v, err = ConsumeSint64(b, typ)
	if err != nil {
		return nil, nil, err
	}
	return b, &v, nil
}

func ConsumeFixedUint32Opt(b []byte, typ Type) ([]byte, *uint32, error) {
	var v uint32
	var err error
	b, v, err = ConsumeFixedUint32(b, typ)
	if err != nil {
		return nil, nil, err
	}
	return b, &v, nil
}

func ConsumeFixedUint64Opt(b []byte, typ Type) ([]byte, *uint64, error) {
	var v uint64
	var err error
	b, v, err = ConsumeFixedUint64(b, typ)
	if err != nil {
		return nil, nil, err
	}
	return b, &v, nil
}

func ConsumeSfixed32Opt(b []byte, typ Type) ([]byte, *int32, error) {
	var v int32
	var err error
	b, v, err = ConsumeSfixed32(b, typ)
	if err != nil {
		return nil, nil, err
	}
	return b, &v, nil
}

func ConsumeSfixed64Opt(b []byte, typ Type) ([]byte, *int64, error) {
	var v int64
	var err error
	b, v, err = ConsumeSfixed64(b, typ)
	if err != nil {
		return nil, nil, err
	}
	return b, &v, nil
}

func ConsumeFloat32Opt(b []byte, typ Type) ([]byte, *float32, error) {
	var v float32
	var err error
	b, v, err = ConsumeFloat32(b, typ)
	if err != nil {
		return nil, nil, err
	}
	return b, &v, nil
}

func ConsumeFloat64Opt(b []byte, typ Type) ([]byte, *float64, error) {
	var v float64
	var err error
	b, v, err = ConsumeFloat64(b, typ)
	if err != nil {
		return nil, nil, err
	}
	return b, &v, nil
}

func ConsumeBoolOpt(b []byte, typ Type) ([]byte, *bool, error) {
	var v bool
	var err error
	b, v, err = ConsumeBool(b, typ)
	if err != nil {
		return nil, nil, err
	}
	return b, &v, nil
}

func ConsumeStringOpt(b []byte, typ Type) ([]byte, *string, error) {
	var v string
	var err error
	b, v, err = ConsumeString(b, typ)
	if err != nil {
		return nil, nil, err
	}
	return b, &v, nil
}

func ConsumeBytesOpt(b []byte, typ Type) ([]byte, *[]byte, error) {
	var v []byte
	var err error
	b, v, err = ConsumeBytes(b, typ)
	if err != nil {
		return nil, nil, err
	}
	copyBytes := append([]byte(nil), v...)
	return b, &copyBytes, nil
}

func ConsumeBytesCopy(b []byte, typ Type) ([]byte, []byte, error) {
	var v []byte
	var err error
	b, v, err = ConsumeBytes(b, typ)
	if err != nil {
		return nil, nil, err
	}
	return b, append([]byte(nil), v...), nil
}

func AppendVarIntField(b []byte, v uint64, num Number) []byte {
	if v == 0 {
		return b
	}
	b = AppendTag(b, num, VarintType)
	return AppendVarint(b, v)
}

func AppendVarIntFieldOpt(b []byte, v *uint64, num Number) []byte {
	if v == nil {
		return b
	}
	b = AppendTag(b, num, VarintType)
	return AppendVarint(b, *v)
}

func AppendStringField(b []byte, v string, num Number) []byte {
	if v == "" {
		return b
	}
	b = AppendTag(b, num, BytesType)
	return AppendBytes(b, []byte(v))
}

func AppendStringFieldOpt(b []byte, v *string, num Number) []byte {
	if v == nil {
		return b
	}
	b = AppendTag(b, num, BytesType)
	return AppendBytes(b, []byte(*v))
}

func AppendBytesField(b []byte, v []byte, num Number) []byte {
	if len(v) == 0 {
		return b
	}
	b = AppendTag(b, num, BytesType)
	return AppendBytes(b, v)
}

func AppendBoolField(b []byte, v bool, num Number) []byte {
	if !v {
		return b
	}
	b = AppendTag(b, num, VarintType)
	return AppendVarint(b, 1)
}

func AppendBoolFieldOpt(b []byte, v *bool, num Number) []byte {
	if v == nil {
		return b
	}
	return AppendBoolElem(b, *v, num)
}

func AppendFloat32Field(b []byte, v float32, num Number) []byte {
	if v == 0 {
		return b
	}
	b = AppendTag(b, num, Fixed32Type)
	return AppendFixed32(b, math.Float32bits(v))
}

func AppendFloat32FieldOpt(b []byte, v *float32, num Number) []byte {
	if v == nil {
		return b
	}
	b = AppendTag(b, num, Fixed32Type)
	return AppendFixed32(b, math.Float32bits(*v))
}

func AppendFloat64Field(b []byte, v float64, num Number) []byte {
	if v == 0 {
		return b
	}
	b = AppendTag(b, num, Fixed64Type)
	return AppendFixed64(b, math.Float64bits(v))
}

func AppendFloat64FieldOpt(b []byte, v *float64, num Number) []byte {
	if v == nil {
		return b
	}
	b = AppendTag(b, num, Fixed64Type)
	return AppendFixed64(b, math.Float64bits(*v))
}

func AppendInt32Field(b []byte, v int32, num Number) []byte {
	if v == 0 {
		return b
	}
	b = AppendTag(b, num, VarintType)
	return AppendVarint(b, uint64(uint32(v)))
}

func AppendInt32FieldOpt(b []byte, v *int32, num Number) []byte {
	if v == nil {
		return b
	}
	b = AppendTag(b, num, VarintType)
	return AppendVarint(b, uint64(uint32(*v)))
}

func AppendUint32Field(b []byte, v uint32, num Number) []byte {
	if v == 0 {
		return b
	}
	b = AppendTag(b, num, VarintType)
	return AppendVarint(b, uint64(v))
}

func AppendUint32FieldOpt(b []byte, v *uint32, num Number) []byte {
	if v == nil {
		return b
	}
	b = AppendTag(b, num, VarintType)
	return AppendVarint(b, uint64(*v))
}

func AppendSint32Field(b []byte, v int32, num Number) []byte {
	if v == 0 {
		return b
	}
	b = AppendTag(b, num, VarintType)
	return AppendVarint(b, EncodeZigZag(int64(v)))
}

func AppendSint32FieldOpt(b []byte, v *int32, num Number) []byte {
	if v == nil {
		return b
	}
	b = AppendTag(b, num, VarintType)
	return AppendVarint(b, EncodeZigZag(int64(*v)))
}

func AppendInt64Field(b []byte, v int64, num Number) []byte {
	if v == 0 {
		return b
	}
	b = AppendTag(b, num, VarintType)
	return AppendVarint(b, uint64(v))
}

func AppendInt64FieldOpt(b []byte, v *int64, num Number) []byte {
	if v == nil {
		return b
	}
	b = AppendTag(b, num, VarintType)
	return AppendVarint(b, uint64(*v))
}

func AppendUint64Field(b []byte, v uint64, num Number) []byte {
	if v == 0 {
		return b
	}
	b = AppendTag(b, num, VarintType)
	return AppendVarint(b, v)
}

func AppendUint64FieldOpt(b []byte, v *uint64, num Number) []byte {
	if v == nil {
		return b
	}
	b = AppendTag(b, num, VarintType)
	return AppendVarint(b, *v)
}

func AppendSint64Field(b []byte, v int64, num Number) []byte {
	if v == 0 {
		return b
	}
	b = AppendTag(b, num, VarintType)
	return AppendVarint(b, EncodeZigZag(v))
}

func AppendSint64FieldOpt(b []byte, v *int64, num Number) []byte {
	if v == nil {
		return b
	}
	b = AppendTag(b, num, VarintType)
	return AppendVarint(b, EncodeZigZag(*v))
}

func AppendFixed32Field(b []byte, v uint32, num Number) []byte {
	if v == 0 {
		return b
	}
	b = AppendTag(b, num, Fixed32Type)
	return AppendFixed32(b, v)
}

func AppendFixed32FieldOpt(b []byte, v *uint32, num Number) []byte {
	if v == nil {
		return b
	}
	b = AppendTag(b, num, Fixed32Type)
	return AppendFixed32(b, *v)
}

func AppendFixed64Field(b []byte, v uint64, num Number) []byte {
	if v == 0 {
		return b
	}
	b = AppendTag(b, num, Fixed64Type)
	return AppendFixed64(b, v)
}

func AppendFixed64FieldOpt(b []byte, v *uint64, num Number) []byte {
	if v == nil {
		return b
	}
	b = AppendTag(b, num, Fixed64Type)
	return AppendFixed64(b, *v)
}

func AppendSfixed32Field(b []byte, v int32, num Number) []byte {
	if v == 0 {
		return b
	}
	b = AppendTag(b, num, Fixed32Type)
	return AppendFixed32(b, uint32(v))
}

func AppendSfixed32FieldOpt(b []byte, v *int32, num Number) []byte {
	if v == nil {
		return b
	}
	b = AppendTag(b, num, Fixed32Type)
	return AppendFixed32(b, uint32(*v))
}

func AppendSfixed64Field(b []byte, v int64, num Number) []byte {
	if v == 0 {
		return b
	}
	b = AppendTag(b, num, Fixed64Type)
	return AppendFixed64(b, uint64(v))
}

func AppendSfixed64FieldOpt(b []byte, v *int64, num Number) []byte {
	if v == nil {
		return b
	}
	b = AppendTag(b, num, Fixed64Type)
	return AppendFixed64(b, uint64(*v))
}

// The Elem variants write one element of a non-packed repeated field. Unlike
// the Field helpers they never skip the zero value: every element occupies a
// position, and skipping one shifts all later elements against any parallel
// column.

func AppendStringElem(b []byte, v string, num Number) []byte {
	b = AppendTag(b, num, BytesType)
	return AppendBytes(b, []byte(v))
}

func AppendBytesElem(b []byte, v []byte, num Number) []byte {
	b = AppendTag(b, num, BytesType)
	return AppendBytes(b, v)
}

func AppendBoolElem(b []byte, v bool, num Number) []byte {
	b = AppendTag(b, num, VarintType)
	return AppendBoolCompact(b, v)
}

func AppendFloat32Elem(b []byte, v float32, num Number) []byte {
	b = AppendTag(b, num, Fixed32Type)
	return AppendFloat32Compact(b, v)
}

func AppendFloat64Elem(b []byte, v float64, num Number) []byte {
	b = AppendTag(b, num, Fixed64Type)
	return AppendFloat64Compact(b, v)
}

func AppendInt32Elem(b []byte, v int32, num Number) []byte {
	b = AppendTag(b, num, VarintType)
	return AppendInt32Compact(b, v)
}

func AppendUint32Elem(b []byte, v uint32, num Number) []byte {
	b = AppendTag(b, num, VarintType)
	return AppendUint32Compact(b, v)
}

func AppendSint32Elem(b []byte, v int32, num Number) []byte {
	b = AppendTag(b, num, VarintType)
	return AppendSint32Compact(b, v)
}

func AppendInt64Elem(b []byte, v int64, num Number) []byte {
	b = AppendTag(b, num, VarintType)
	return AppendInt64Compact(b, v)
}

func AppendUint64Elem(b []byte, v uint64, num Number) []byte {
	b = AppendTag(b, num, VarintType)
	return AppendUint64Compact(b, v)
}

func AppendSint64Elem(b []byte, v int64, num Number) []byte {
	b = AppendTag(b, num, VarintType)
	return AppendSint64Compact(b, v)
}

func AppendFixed32Elem(b []byte, v uint32, num Number) []byte {
	b = AppendTag(b, num, Fixed32Type)
	return AppendFixed32Compact(b, v)
}

func AppendSfixed32Elem(b []byte, v int32, num Number) []byte {
	b = AppendTag(b, num, Fixed32Type)
	return AppendSfixed32Compact(b, v)
}

func AppendFixed64Elem(b []byte, v uint64, num Number) []byte {
	b = AppendTag(b, num, Fixed64Type)
	return AppendFixed64Compact(b, v)
}

func AppendSfixed64Elem(b []byte, v int64, num Number) []byte {
	b = AppendTag(b, num, Fixed64Type)
	return AppendSfixed64Compact(b, v)
}

func AppendFieldDecorator[T any](appendField func([]byte, T, Number) []byte, num Number) func([]byte, T) []byte {
	return func(b []byte, value T) []byte {
		return appendField(b, value, num)
	}
}

func AppendCompactDecorator[T any](appendCompact func([]byte, T) []byte) func([]byte, T) []byte {
	return func(b []byte, value T) []byte {
		return appendCompact(b, value)
	}
}

func AppendBoolCompact(b []byte, v bool) []byte {
	if v {
		return AppendVarint(b, 1)
	}
	return AppendVarint(b, 0)
}

func AppendFloat32Compact(b []byte, v float32) []byte {
	return AppendFixed32(b, math.Float32bits(v))
}

func AppendFloat64Compact(b []byte, v float64) []byte {
	return AppendFixed64(b, math.Float64bits(v))
}

func AppendInt32Compact(b []byte, v int32) []byte {
	return AppendVarint(b, uint64(uint32(v)))
}

func AppendUint32Compact(b []byte, v uint32) []byte {
	return AppendVarint(b, uint64(v))
}

func AppendSint32Compact(b []byte, v int32) []byte {
	return AppendVarint(b, EncodeZigZag(int64(v)))
}

func AppendInt64Compact(b []byte, v int64) []byte {
	return AppendVarint(b, uint64(v))
}

func AppendUint64Compact(b []byte, v uint64) []byte {
	return AppendVarint(b, v)
}

func AppendSint64Compact(b []byte, v int64) []byte {
	return AppendVarint(b, EncodeZigZag(v))
}

func AppendFixed32Compact(b []byte, v uint32) []byte {
	return AppendFixed32(b, v)
}

func AppendSfixed32Compact(b []byte, v int32) []byte {
	return AppendFixed32(b, uint32(v))
}

func AppendFixed64Compact(b []byte, v uint64) []byte {
	return AppendFixed64(b, v)
}

func AppendSfixed64Compact(b []byte, v int64) []byte {
	return AppendFixed64(b, uint64(v))
}

type Encodable interface {
	Encode() []byte
}

func AppendMessageFieldDecorator[T Encodable](num Number) func([]byte, T) []byte {
	return func(b []byte, value T) []byte {
		return AppendBytesField(b, value.Encode(), num)
	}
}

func AppendRepeated[T any](b []byte, values []T, appendValue func([]byte, T) []byte) []byte {
	for _, value := range values {
		b = appendValue(b, value)
	}
	return b
}

func AppendRepeatedCompact[T any](b []byte, values []T, num Number, appendValue func([]byte, T) []byte) []byte {
	var packed []byte
	for _, value := range values {
		packed = appendValue(packed, value)
	}
	if len(packed) == 0 {
		return b
	}
	b = AppendTag(b, num, BytesType)
	return AppendBytes(b, packed)
}

func AppendMap[K comparable, V any](
	b []byte,
	m map[K]V,
	num Number,
	appendKey func([]byte, K) []byte,
	appendValue func([]byte, V) []byte,
) []byte {
	if len(m) == 0 {
		return b
	}
	keys := make([]K, 0, len(m))
	for key := range m {
		keys = append(keys, key)
	}
	sort.Slice(keys, func(i, j int) bool { return lessMapKey(keys[i], keys[j]) })
	for _, key := range keys {
		var entry []byte
		entry = appendKey(entry, key)
		entry = appendValue(entry, m[key])
		b = AppendTag(b, num, BytesType)
		b = AppendBytes(b, entry)
	}
	return b
}

func lessMapKey[K comparable](a, b K) bool {
	switch x := any(a).(type) {
	case string:
		return x < any(b).(string)
	case bool:
		return !x && any(b).(bool)
	case int32:
		return x < any(b).(int32)
	case int64:
		return x < any(b).(int64)
	case uint32:
		return x < any(b).(uint32)
	case uint64:
		return x < any(b).(uint64)
	default:
		return false
	}
}
