package main

import (
	"bytes"
	"compress/gzip"
	"crypto/tls"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/http/httputil"
	"net/url"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"
)

const (
	gitRoot      = "/srv/git"
	releaseRoot  = "/srv/releases"
	nixCacheRoot = "/srv/nix-cache"
	nixCacheHost = "cache.nixos.org"
)

var errNixCacheNotFound = errors.New("nix cache upstream not found")

func main() {
	if err := run(); err != nil {
		fmt.Fprintf(os.Stderr, "error: %v\n", err)
		os.Exit(1)
	}
}

func run() error {
	cmd := "serve"
	if len(os.Args) > 1 {
		cmd = os.Args[1]
	}
	switch cmd {
	case "prepare":
		return prepare()
	case "serve":
		return serve()
	case "help", "-h", "--help":
		fmt.Println("usage: repo-mirror [prepare|serve]")
		return nil
	default:
		return fmt.Errorf("unknown command %q", cmd)
	}
}

func prepare() error {
	for _, dir := range []string{gitRoot, releaseRoot, nixCacheRoot, "/srv/registry"} {
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
	}
	if err := mirrorRepo("jptrs93/opsagent", "https://github.com/jptrs93/opsagent.git"); err != nil {
		return err
	}
	if err := mirrorRepo("jptrs93/jnotes", "https://github.com/jptrs93/jnotes.git"); err != nil {
		return err
	}
	for _, version := range words(env("OPD_RELEASES", "")) {
		releaseDir := filepath.Join(releaseRoot, "jptrs93", "opsagent", version)
		if err := os.MkdirAll(releaseDir, 0o755); err != nil {
			return err
		}
		for _, arch := range words(env("OPD_ARCHES", "")) {
			if err := seedFile(
				fmt.Sprintf("https://github.com/jptrs93/opsagent/releases/download/%s/opendeploy-linux-%s", version, arch),
				filepath.Join(releaseDir, "opendeploy-linux-"+arch),
			); err != nil {
				return err
			}
		}
		if err := seedFile(
			fmt.Sprintf("https://github.com/jptrs93/opsagent/releases/download/%s/sha256sums.txt", version),
			filepath.Join(releaseDir, "sha256sums.txt"),
		); err != nil {
			return err
		}
	}
	latestDir := filepath.Join(releaseRoot, "jptrs93", "opsagent")
	if err := os.MkdirAll(latestDir, 0o755); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(latestDir, "latest"), []byte(env("OPD_LATEST_RELEASE", "")+"\n"), 0o644); err != nil {
		return err
	}
	containerdVersion := env("CONTAINERD_VERSION", "")
	runcVersion := env("RUNC_VERSION", "")
	for _, arch := range words(env("OPD_ARCHES", "")) {
		if err := seedFile(
			fmt.Sprintf("https://github.com/containerd/containerd/releases/download/v%s/containerd-%s-linux-%s.tar.gz", containerdVersion, containerdVersion, arch),
			filepath.Join(releaseRoot, "containerd", "containerd", "v"+containerdVersion, fmt.Sprintf("containerd-%s-linux-%s.tar.gz", containerdVersion, arch)),
		); err != nil {
			return err
		}
		if err := seedFile(
			fmt.Sprintf("https://github.com/opencontainers/runc/releases/download/v%s/runc.%s", runcVersion, arch),
			filepath.Join(releaseRoot, "opencontainers", "runc", "v"+runcVersion, "runc."+arch),
		); err != nil {
			return err
		}
	}
	return mirrorOCIImages()
}

func mirrorRepo(ownerRepo, remote string) error {
	dst := filepath.Join(gitRoot, filepath.FromSlash(ownerRepo)+".git")
	cached := filepath.Join(env("OPD_MOCK_ARTIFACT_DIR", ""), "git", filepath.FromSlash(ownerRepo)+".git")
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	if isDir(dst) {
		if refreshEnabled() {
			_ = runCmd(dst, "git", "remote", "update", "--prune")
		}
		return runCmd(dst, "git", "update-server-info")
	}
	if cached != "" && isDir(cached) {
		if err := runCmd("", "git", "clone", "--mirror", cached, dst); err != nil {
			return err
		}
		return runCmd(dst, "git", "update-server-info")
	}
	if !refreshEnabled() {
		fmt.Fprintf(os.Stderr, "creating placeholder %s; set OPD_REPO_MIRROR_REFRESH=true to clone %s\n", ownerRepo, remote)
		return createDummyRepo(ownerRepo, dst)
	}
	if err := runCmd("", "git", "clone", "--mirror", remote, dst); err == nil {
		return runCmd(dst, "git", "update-server-info")
	}
	fmt.Fprintf(os.Stderr, "warning: cloning %s failed; creating placeholder %s\n", remote, ownerRepo)
	_ = os.RemoveAll(dst)
	return createDummyRepo(ownerRepo, dst)
}

func createDummyRepo(ownerRepo, dst string) error {
	work, err := os.MkdirTemp("", "opd-repo-mirror-*")
	if err != nil {
		return err
	}
	defer os.RemoveAll(work)
	if err := runCmd("", "git", "init", work); err != nil {
		return err
	}
	_ = runCmd(work, "git", "config", "user.email", "repo-mirror@example.invalid")
	_ = runCmd(work, "git", "config", "user.name", "OpenDeploy Repo Mirror")
	flake := "{\n  description = \"OpenDeploy local placeholder flake\";\n  outputs = { self }: { };\n}\n"
	if err := os.WriteFile(filepath.Join(work, "README.md"), []byte("# "+ownerRepo+"\n\nLocal test placeholder repository generated by testing-vms/repo-mirror.\n"), 0o644); err != nil {
		return err
	}
	if err := os.WriteFile(filepath.Join(work, "flake.nix"), []byte(flake), 0o644); err != nil {
		return err
	}
	for _, sub := range []string{"nixdockerbuild1", "nixdockercrasher", "largeassetverify", "postgresclient"} {
		dir := filepath.Join(work, "testexamples", sub)
		if err := os.MkdirAll(dir, 0o755); err != nil {
			return err
		}
		if err := os.WriteFile(filepath.Join(dir, "flake.nix"), []byte(flake), 0o644); err != nil {
			return err
		}
	}
	if err := runCmd(work, "git", "add", "."); err != nil {
		return err
	}
	if err := runCmd(work, "git", "commit", "-m", "local placeholder"); err != nil {
		return err
	}
	if err := runCmd("", "git", "clone", "--mirror", work, dst); err != nil {
		return err
	}
	return runCmd(dst, "git", "update-server-info")
}

func seedFile(remoteURL, dst string) error {
	if fileNonEmpty(dst) {
		return nil
	}
	if err := os.MkdirAll(filepath.Dir(dst), 0o755); err != nil {
		return err
	}
	if root := env("OPD_MOCK_ARTIFACT_DIR", ""); root != "" {
		cached := filepath.Join(root, strings.TrimPrefix(dst, "/srv"))
		if fileNonEmpty(cached) {
			if err := copyFile(cached, dst); err != nil {
				return err
			}
			return os.Chmod(dst, 0o644)
		}
	}
	if !refreshEnabled() {
		return fmt.Errorf("missing mirrored artifact: %s", dst)
	}
	return runCmd("", "curl", "-fL", "--retry", "3", "--retry-delay", "2", remoteURL, "-o", dst)
}

func mirrorOCIImages() error {
	for _, spec := range words(env("OPD_OCI_IMAGES", "")) {
		src, dst, ok := strings.Cut(spec, "=")
		if !ok || src == "" || dst == "" || src == dst {
			return fmt.Errorf("bad OPD_OCI_IMAGES entry: %s", spec)
		}
		if runCmd("", "skopeo", "inspect", "docker://"+dst) == nil {
			fmt.Printf("OCI image already mirrored: %s\n", dst)
			continue
		}
		if root := env("OPD_MOCK_ARTIFACT_DIR", ""); root != "" {
			archive := filepath.Join(root, "oci", strings.NewReplacer("/", "_", ":", "_").Replace(src)+".tar")
			if fileNonEmpty(archive) {
				fmt.Printf("Importing OCI image %s -> %s\n", src, dst)
				if err := runCmd("", "skopeo", "copy", "--all", "oci-archive:"+archive, "docker://"+dst); err != nil {
					if err := runCmd("", "skopeo", "copy", "docker-archive:"+archive, "docker://"+dst); err != nil {
						return err
					}
				}
				continue
			}
		}
		if !refreshEnabled() {
			return fmt.Errorf("missing mirrored OCI image: %s", dst)
		}
		fmt.Printf("Mirroring OCI image %s -> %s\n", src, dst)
		if err := runCmd("", "skopeo", "copy", "--all", "docker://"+src, "docker://"+dst); err != nil {
			return err
		}
	}
	return nil
}

type handler struct{}

func serve() error {
	port := env("OPD_REPO_MIRROR_PORT", "443")
	server := &http.Server{Addr: ":" + port, Handler: handler{}, ReadHeaderTimeout: 30 * time.Second}
	cert, key := env("OPD_REPO_MIRROR_CERT", ""), env("OPD_REPO_MIRROR_KEY", "")
	if cert != "" && key != "" {
		server.TLSConfig = &tls.Config{MinVersion: tls.VersionTLS12}
		return server.ListenAndServeTLS(cert, key)
	}
	return server.ListenAndServe()
}

func (handler) ServeHTTP(w http.ResponseWriter, r *http.Request) {
	path := r.URL.Path
	if path == "/healthz" {
		writeBytes(w, http.StatusOK, []byte("ok\n"), "text/plain")
		return
	}
	if requestHost(r) == nixCacheHost || validNixCachePath(path) {
		handleNixCache(w, r)
		return
	}
	if strings.HasPrefix(path, "/repos/") {
		if !localReleaseAPIPath(path) {
			proxyUnknown(w, r)
			return
		}
		handleAPI(w, r)
		return
	}
	if strings.Contains(path, "/releases/download/") {
		if !localDownloadPath(path) {
			proxyUnknown(w, r)
			return
		}
		handleDownload(w, r)
		return
	}
	if strings.Contains(path, ".git") {
		if !localGitPath(path) {
			proxyUnknown(w, r)
			return
		}
		handleGit(w, r)
		return
	}
	proxyUnknown(w, r)
}

func localReleaseAPIPath(path string) bool {
	parts := splitPath(path)
	return len(parts) >= 4 && parts[0] == "repos" && parts[3] == "releases" && isDir(filepath.Join(releaseRoot, parts[1], parts[2]))
}

func localDownloadPath(path string) bool {
	parts := splitPath(path)
	idx := indexOf(parts, "releases")
	if idx < 2 || len(parts) < idx+4 || parts[idx+1] != "download" {
		return false
	}
	owner := strings.Join(parts[:idx-1], "/")
	repo := parts[idx-1]
	return isDir(filepath.Join(releaseRoot, filepath.FromSlash(owner), repo))
}

func localGitPath(path string) bool {
	prefix, _, _ := strings.Cut(strings.TrimPrefix(path, "/"), ".git")
	return prefix != "" && isDir(filepath.Join(gitRoot, filepath.FromSlash(prefix)+".git"))
}

func handleNixCache(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodGet && r.Method != http.MethodHead {
		http.Error(w, "method not allowed", http.StatusMethodNotAllowed)
		return
	}
	if !validNixCachePath(r.URL.Path) {
		http.NotFound(w, r)
		return
	}
	localPath := filepath.Join(nixCacheRoot, filepath.FromSlash(strings.TrimPrefix(r.URL.Path, "/")))
	if fileNonEmpty(localPath) {
		serveFile(w, r, localPath)
		return
	}
	mode := strings.ToLower(env("OPD_NIX_CACHE_MODE", "proxy-cache"))
	if mode == "" || mode == "off" || mode == "false" || mode == "0" || mode == "no" || mode == "strict" {
		fmt.Fprintf(os.Stderr, "warning: nix cache miss path=%s mode=%s\n", r.URL.Path, mode)
		http.NotFound(w, r)
		return
	}
	if mode != "proxy-cache" && mode != "proxy" && mode != "true" && mode != "1" && mode != "yes" {
		http.Error(w, "bad OPD_NIX_CACHE_MODE", http.StatusInternalServerError)
		return
	}
	if err := fetchAndCacheNixPath(r.URL.Path, localPath); err != nil {
		if errors.Is(err, errNixCacheNotFound) {
			fmt.Fprintf(os.Stderr, "warning: nix cache miss path=%s upstream=404\n", r.URL.Path)
			http.NotFound(w, r)
			return
		}
		fmt.Fprintf(os.Stderr, "warning: nix cache proxy failed path=%s err=%v\n", r.URL.Path, err)
		http.Error(w, "nix cache proxy failed: "+err.Error(), http.StatusBadGateway)
		return
	}
	serveFile(w, r, localPath)
}

func validNixCachePath(path string) bool {
	clean := strings.TrimPrefix(path, "/")
	if clean == "" || strings.Contains(clean, "..") || strings.HasPrefix(clean, "/") {
		return false
	}
	if clean == "nix-cache-info" || strings.HasSuffix(clean, ".narinfo") {
		return true
	}
	return strings.HasPrefix(clean, "nar/")
}

func fetchAndCacheNixPath(path string, localPath string) error {
	url := "https://" + nixCacheHost + path
	fmt.Fprintf(os.Stderr, "warning: nix cache miss path=%s upstream=%s\n", path, url)
	tmp := localPath + ".tmp"
	if err := os.MkdirAll(filepath.Dir(localPath), 0o755); err != nil {
		return err
	}
	req, err := http.NewRequest(http.MethodGet, url, nil)
	if err != nil {
		return err
	}
	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()
	if resp.StatusCode == http.StatusNotFound {
		return errNixCacheNotFound
	}
	if resp.StatusCode != http.StatusOK {
		return fmt.Errorf("upstream returned %s", resp.Status)
	}
	out, err := os.OpenFile(tmp, os.O_CREATE|os.O_WRONLY|os.O_TRUNC, 0o644)
	if err != nil {
		return err
	}
	_, copyErr := io.Copy(out, resp.Body)
	closeErr := out.Close()
	if copyErr != nil {
		_ = os.Remove(tmp)
		return copyErr
	}
	if closeErr != nil {
		_ = os.Remove(tmp)
		return closeErr
	}
	return os.Rename(tmp, localPath)
}

func requestHost(r *http.Request) string {
	return strings.Split(r.Host, ":")[0]
}

func proxyUnknown(w http.ResponseWriter, r *http.Request) {
	mode := strings.ToLower(env("OPD_REPO_MIRROR_PROXY_UNKNOWN", "false"))
	host := requestHost(r)
	if mode == "" || mode == "false" || mode == "0" || mode == "no" || mode == "none" || (host != "github.com" && host != "api.github.com") || (mode == "nixpkgs" && !isNixpkgsProxyPath(host, r.URL.Path)) {
		http.NotFound(w, r)
		return
	}
	target := &url.URL{Scheme: "https", Host: host}
	proxy := httputil.NewSingleHostReverseProxy(target)
	proxy.Director = func(req *http.Request) {
		req.URL.Scheme = "https"
		req.URL.Host = host
		req.Host = host
		req.Header = r.Header.Clone()
		req.Header.Del("Authorization")
	}
	proxy.ErrorHandler = func(w http.ResponseWriter, _ *http.Request, err error) {
		http.Error(w, "proxy failed: "+err.Error(), http.StatusBadGateway)
	}
	proxy.ServeHTTP(w, r)
}

func isNixpkgsProxyPath(host, path string) bool {
	clean := strings.TrimPrefix(path, "/")
	if host == "api.github.com" {
		return strings.HasPrefix(clean, "repos/NixOS/nixpkgs")
	}
	return strings.HasPrefix(clean, "NixOS/nixpkgs")
}

func handleAPI(w http.ResponseWriter, r *http.Request) {
	parts := splitPath(r.URL.Path)
	if len(parts) >= 6 && parts[0] == "repos" && parts[3] == "releases" && parts[4] == "assets" {
		owner, repo, tag, name, err := decodeAssetID(parts[5])
		if err != nil {
			http.NotFound(w, r)
			return
		}
		serveFile(w, r, filepath.Join(releaseRoot, owner, repo, tag, name))
		return
	}
	if len(parts) < 4 || parts[0] != "repos" || parts[3] != "releases" {
		http.NotFound(w, r)
		return
	}
	owner, repo := parts[1], parts[2]
	if len(parts) == 5 && parts[4] == "latest" {
		data, err := os.ReadFile(filepath.Join(releaseRoot, owner, repo, "latest"))
		if err != nil {
			http.NotFound(w, r)
			return
		}
		writeJSON(w, releaseJSON(r, owner, repo, strings.TrimSpace(string(data))))
		return
	}
	if len(parts) == 6 && parts[4] == "tags" {
		writeJSON(w, releaseJSON(r, owner, repo, parts[5]))
		return
	}
	if len(parts) == 4 || (len(parts) == 5 && parts[4] == "") {
		writeJSON(w, releaseList(r, owner, repo))
		return
	}
	http.NotFound(w, r)
}

func releaseList(r *http.Request, owner, repo string) []map[string]any {
	entries, err := os.ReadDir(filepath.Join(releaseRoot, owner, repo))
	if err != nil {
		return nil
	}
	var tags []string
	for _, entry := range entries {
		if entry.IsDir() {
			tags = append(tags, entry.Name())
		}
	}
	sort.Sort(sort.Reverse(sort.StringSlice(tags)))
	out := make([]map[string]any, 0, len(tags))
	for _, tag := range tags {
		out = append(out, releaseJSON(r, owner, repo, tag))
	}
	return out
}

func releaseJSON(r *http.Request, owner, repo, tag string) map[string]any {
	root := filepath.Join(releaseRoot, owner, repo, tag)
	entries, _ := os.ReadDir(root)
	host := r.Host
	scheme := "https"
	if env("OPD_REPO_MIRROR_TLS", "true") != "true" {
		scheme = "http"
	}
	assets := make([]map[string]any, 0, len(entries))
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}
		info, err := entry.Info()
		if err != nil {
			continue
		}
		assets = append(assets, map[string]any{"name": entry.Name(), "url": fmt.Sprintf("%s://%s/repos/%s/%s/releases/assets/%s", scheme, host, owner, repo, assetID(owner, repo, tag, entry.Name())), "size": info.Size()})
	}
	return map[string]any{"tag_name": tag, "name": tag, "published_at": "2026-01-01T00:00:00Z", "author": map[string]string{"login": "opendeploy-repo-mirror"}, "assets": assets}
}

func handleDownload(w http.ResponseWriter, r *http.Request) {
	parts := splitPath(r.URL.Path)
	idx := indexOf(parts, "releases")
	if idx < 2 || len(parts) < idx+4 || parts[idx+1] != "download" {
		http.NotFound(w, r)
		return
	}
	owner := strings.Join(parts[:idx-1], "/")
	repo := parts[idx-1]
	tag := parts[idx+2]
	name := strings.Join(parts[idx+3:], "/")
	if strings.Contains(owner, "..") || strings.Contains(repo, "/") || strings.Contains(tag, "/") || name == "" {
		http.NotFound(w, r)
		return
	}
	serveFile(w, r, filepath.Join(releaseRoot, filepath.FromSlash(owner), repo, tag, name))
}

func handleGit(w http.ResponseWriter, r *http.Request) {
	body, err := io.ReadAll(r.Body)
	if err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}
	if strings.EqualFold(r.Header.Get("Content-Encoding"), "gzip") {
		gz, err := gzip.NewReader(bytes.NewReader(body))
		if err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		body, err = io.ReadAll(gz)
		_ = gz.Close()
		if err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
	}
	remoteAddr, _, err := net.SplitHostPort(r.RemoteAddr)
	if err != nil {
		remoteAddr = r.RemoteAddr
	}
	envVars := os.Environ()
	envVars = append(envVars,
		"GIT_PROJECT_ROOT="+gitRoot,
		"GIT_HTTP_EXPORT_ALL=1",
		"REQUEST_METHOD="+r.Method,
		"PATH_INFO="+r.URL.Path,
		"QUERY_STRING="+r.URL.RawQuery,
		"REMOTE_ADDR="+remoteAddr,
		"REMOTE_USER=",
		"CONTENT_TYPE="+r.Header.Get("Content-Type"),
		"CONTENT_LENGTH="+strconv.Itoa(len(body)),
		"HTTP_GIT_PROTOCOL="+r.Header.Get("Git-Protocol"),
	)
	cmd := exec.Command("git", "http-backend")
	cmd.Env = envVars
	cmd.Stdin = bytes.NewReader(body)
	out, err := cmd.Output()
	if err != nil {
		var ee *exec.ExitError
		if errors.As(err, &ee) {
			_, _ = os.Stderr.Write(ee.Stderr)
		}
		http.Error(w, "git backend failed", http.StatusInternalServerError)
		return
	}
	headerBlob, responseBody, ok := bytes.Cut(out, []byte("\r\n\r\n"))
	if !ok {
		headerBlob, responseBody, _ = bytes.Cut(out, []byte("\n\n"))
	}
	status := http.StatusOK
	for _, raw := range bytes.Split(bytes.ReplaceAll(headerBlob, []byte("\r\n"), []byte("\n")), []byte("\n")) {
		if len(raw) == 0 {
			continue
		}
		key, value, _ := bytes.Cut(raw, []byte(":"))
		k := string(key)
		v := strings.TrimSpace(string(value))
		if strings.EqualFold(k, "Status") {
			fields := strings.Fields(v)
			if len(fields) > 0 {
				if n, err := strconv.Atoi(fields[0]); err == nil {
					status = n
				}
			}
			continue
		}
		if k != "" && v != "" {
			w.Header().Add(k, v)
		}
	}
	w.Header().Set("Content-Length", strconv.Itoa(len(responseBody)))
	w.WriteHeader(status)
	_, _ = w.Write(responseBody)
}

func serveFile(w http.ResponseWriter, r *http.Request, path string) {
	clean, err := filepath.Abs(path)
	if err != nil || !allowedServedFile(clean) || !fileNonEmpty(clean) {
		http.NotFound(w, r)
		return
	}
	http.ServeFile(w, r, clean)
}

func allowedServedFile(path string) bool {
	for _, root := range []string{releaseRoot, nixCacheRoot} {
		if path == root || strings.HasPrefix(path, root+string(os.PathSeparator)) {
			return true
		}
	}
	return false
}

func assetID(owner, repo, tag, name string) string {
	return strings.TrimRight(base64.URLEncoding.EncodeToString([]byte(owner+"/"+repo+"/"+tag+"/"+name)), "=")
}

func decodeAssetID(value string) (string, string, string, string, error) {
	raw, err := base64.URLEncoding.DecodeString(value + strings.Repeat("=", (4-len(value)%4)%4))
	if err != nil {
		return "", "", "", "", err
	}
	parts := strings.SplitN(string(raw), "/", 4)
	if len(parts) != 4 {
		return "", "", "", "", errors.New("bad asset id")
	}
	return parts[0], parts[1], parts[2], parts[3], nil
}

func writeJSON(w http.ResponseWriter, value any) {
	data, _ := json.Marshal(value)
	writeBytes(w, http.StatusOK, append(data, '\n'), "application/json")
}

func writeBytes(w http.ResponseWriter, status int, data []byte, contentType string) {
	w.Header().Set("Content-Type", contentType)
	w.Header().Set("Content-Length", strconv.Itoa(len(data)))
	w.WriteHeader(status)
	_, _ = w.Write(data)
}

func refreshEnabled() bool { return env("OPD_REPO_MIRROR_REFRESH", "false") == "true" }

func env(key, fallback string) string {
	if value := os.Getenv(key); value != "" {
		return value
	}
	return fallback
}

func words(value string) []string { return strings.Fields(value) }

func splitPath(path string) []string { return strings.Split(strings.Trim(path, "/"), "/") }

func indexOf(values []string, needle string) int {
	for i, value := range values {
		if value == needle {
			return i
		}
	}
	return -1
}

func isDir(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.IsDir()
}

func fileNonEmpty(path string) bool {
	info, err := os.Stat(path)
	return err == nil && info.Mode().IsRegular() && info.Size() > 0
}

func copyFile(src, dst string) error {
	in, err := os.Open(src)
	if err != nil {
		return err
	}
	defer in.Close()
	out, err := os.Create(dst)
	if err != nil {
		return err
	}
	_, copyErr := io.Copy(out, in)
	closeErr := out.Close()
	if copyErr != nil {
		return copyErr
	}
	return closeErr
}

func runCmd(dir, name string, args ...string) error {
	cmd := exec.Command(name, args...)
	cmd.Dir = dir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}
