#!/usr/bin/env bash
set -euo pipefail

mkdir -p /srv/git /srv/releases /srv/registry
MOCK_ARTIFACT_DIR=${OPD_MOCK_ARTIFACT_DIR:-}

refresh_enabled() {
  [[ "${OPD_REPO_MIRROR_REFRESH:-false}" == "true" ]]
}

create_dummy_repo() {
  local owner_repo=$1
  local work
  work=$(mktemp -d)
  git init "$work" >/dev/null
  git -C "$work" config user.email repo-mirror@example.invalid
  git -C "$work" config user.name "OpenDeploy Repo Mirror"
  mkdir -p "$work/testexamples/nixdockerbuild1" "$work/testexamples/nixdockercrasher" "$work/testexamples/largeassetverify" "$work/testexamples/postgresclient"
  cat >"$work/README.md" <<EOF
# ${owner_repo}

Local test placeholder repository generated by testing-vms/repo-mirror.
EOF
  cat >"$work/flake.nix" <<'EOF'
{
  description = "OpenDeploy local placeholder flake";
  outputs = { self }: { };
}
EOF
  cp "$work/flake.nix" "$work/testexamples/nixdockerbuild1/flake.nix"
  cp "$work/flake.nix" "$work/testexamples/nixdockercrasher/flake.nix"
  cp "$work/flake.nix" "$work/testexamples/largeassetverify/flake.nix"
  cp "$work/flake.nix" "$work/testexamples/postgresclient/flake.nix"
  git -C "$work" add .
  git -C "$work" commit -m "local placeholder" >/dev/null
  git clone --mirror "$work" "/srv/git/${owner_repo}.git" >/dev/null
  rm -rf "$work"
}

mirror_repo() {
  local owner_repo=$1
  local url=$2
  local dst="/srv/git/${owner_repo}.git"
  local cached="${MOCK_ARTIFACT_DIR}/git/${owner_repo}.git"
  mkdir -p "$(dirname "$dst")"
  if [[ -d "$dst" ]]; then
    if refresh_enabled; then
      git -C "$dst" remote update --prune || true
    fi
    git -C "$dst" update-server-info || true
    return
  fi
  if [[ -n "$MOCK_ARTIFACT_DIR" && -d "$cached" ]]; then
    git clone --mirror "$cached" "$dst" >/dev/null
    git -C "$dst" update-server-info
    return
  fi
  if ! refresh_enabled; then
    echo "creating placeholder ${owner_repo}; set OPD_REPO_MIRROR_REFRESH=true to clone ${url}" >&2
    create_dummy_repo "$owner_repo"
    git -C "$dst" update-server-info
    return
  fi
  if git clone --mirror "$url" "$dst"; then
    git -C "$dst" update-server-info
    return
  fi
  echo "warning: cloning ${url} failed; creating placeholder ${owner_repo}" >&2
  rm -rf "$dst"
  create_dummy_repo "$owner_repo"
  git -C "$dst" update-server-info
}

download_file() {
  local url=$1
  local dst=$2
  local cached=""
  if [[ -n "$MOCK_ARTIFACT_DIR" ]]; then
    cached="${MOCK_ARTIFACT_DIR}${dst#/srv}"
  fi
  mkdir -p "$(dirname "$dst")"
  if [[ -s "$dst" ]]; then
    return
  fi
  if [[ -n "$cached" && -s "$cached" ]]; then
    cp "$cached" "$dst"
    chmod a+r "$dst"
    return
  fi
  if ! refresh_enabled; then
    echo "missing mirrored artifact: ${dst}" >&2
    echo "seed /srv/releases manually or rerun with OPD_REPO_MIRROR_REFRESH=true" >&2
    exit 1
  fi
  curl -fL --retry 3 --retry-delay 2 "$url" -o "$dst"
}

mirror_oci_images() {
  if [[ -z "${OPD_OCI_IMAGES:-}" ]]; then
    return
  fi
  local spec src dst archive
  for spec in ${OPD_OCI_IMAGES}; do
    src=${spec%%=*}
    dst=${spec#*=}
    if [[ -z "$src" || -z "$dst" || "$src" == "$dst" ]]; then
      echo "bad OPD_OCI_IMAGES entry: ${spec}" >&2
      exit 1
    fi
    if skopeo inspect "docker://${dst}" >/dev/null 2>&1; then
      echo "OCI image already mirrored: ${dst}"
      continue
    fi
    if [[ -n "$MOCK_ARTIFACT_DIR" ]]; then
      archive="$MOCK_ARTIFACT_DIR/oci/${src//\//_}.tar"
      archive="${archive//:/_}"
      if [[ -s "$archive" ]]; then
        echo "Importing OCI image ${src} -> ${dst}"
        if ! skopeo copy --all "oci-archive:${archive}" "docker://${dst}"; then
          skopeo copy "docker-archive:${archive}" "docker://${dst}"
        fi
        continue
      fi
    fi
    if ! refresh_enabled; then
      echo "missing mirrored OCI image: ${dst}" >&2
      echo "seed /srv/registry manually or rerun with OPD_REPO_MIRROR_REFRESH=true" >&2
      exit 1
    fi
    echo "Mirroring OCI image ${src} -> ${dst}"
    skopeo copy --all "docker://${src}" "docker://${dst}"
  done
}

mirror_repo jptrs93/opsagent https://github.com/jptrs93/opsagent.git
mirror_repo jptrs93/jnotes https://github.com/jptrs93/jnotes.git

for version in ${OPD_RELEASES}; do
  release_dir="/srv/releases/jptrs93/opsagent/${version}"
  mkdir -p "$release_dir"
  for arch in ${OPD_ARCHES}; do
    download_file "https://github.com/jptrs93/opsagent/releases/download/${version}/opendeploy-linux-${arch}" \
      "${release_dir}/opendeploy-linux-${arch}"
  done
  download_file "https://github.com/jptrs93/opsagent/releases/download/${version}/sha256sums.txt" \
    "${release_dir}/sha256sums.txt"
done
mkdir -p /srv/releases/jptrs93/opsagent
printf '%s\n' "${OPD_LATEST_RELEASE}" > /srv/releases/jptrs93/opsagent/latest

for arch in ${OPD_ARCHES}; do
  download_file "https://github.com/containerd/containerd/releases/download/v${CONTAINERD_VERSION}/containerd-${CONTAINERD_VERSION}-linux-${arch}.tar.gz" \
    "/srv/releases/containerd/containerd/v${CONTAINERD_VERSION}/containerd-${CONTAINERD_VERSION}-linux-${arch}.tar.gz"
  download_file "https://github.com/opencontainers/runc/releases/download/v${RUNC_VERSION}/runc.${arch}" \
    "/srv/releases/opencontainers/runc/v${RUNC_VERSION}/runc.${arch}"
done

mirror_oci_images
