-- Primary-side startup migrations. Each statement should be idempotent —
-- this file is executed on every primary startup after the schema has been
-- applied. Remove entries from this file once the bad data they target has
-- been cleaned up in all deployments.
--
-- Every `?` placeholder in a statement is bound to the primary's machine
-- name (see applyPrimaryMigrations in backend/storage/sqlite/adapter.go).
